// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/assignHelper ../../../../core/maybe ../../../webgl ../../engine ../vectorTiles/shaders/ProgramCache ./BitBlitRenderer ./enums ./MaterialManager ./TextureManager ./effects/AnimationEffect ./effects/HighlightEffect ./effects/HittestEffect ./effects/blendEffects/BlendEffectMultiply ./effects/blendEffects/BlendEffectNormal ./effects/postProcessingEffects/PostProcessingEffectUnrealBloom ./painter/RenderPass".split(" "),function(g,l,A,k,f,d,n,p,h,q,r,t,
u,v,w,x,y,z){function m(c){var a=c.blendOption,b=c.postProcessingEffects;return 1!==c.opacity||k.isSome(a.mode)||void 0!==b}Object.defineProperty(l,"__esModule",{value:!0});g=function(){return function(){}}();l.PainterOptions=g;g=function(){function c(a,b){this.context=a;this._blitRenderer=new p.BitBlitRenderer;this._brushCache=new Map;this._vtlProgramCache=null;this.brushNameToCtor={marker:d.brushes.Marker,line:d.brushes.Line,fill:d.brushes.Fill,text:d.brushes.Text,label:d.brushes.Label,clip:d.brushes.Clip,
stencil:d.brushes.Stencil,bitmap:d.brushes.Bitmap,tileInfo:d.brushes.TileInfo,vtlBackground:d.brushes.VTLBackground,vtlFill:d.brushes.VTLFill,vtlLine:d.brushes.VTLLine,vtlCircle:d.brushes.VTLCircle,vtlSymbol:d.brushes.VTLSymbol};this.blendModeToBlendEffect={normal:new x.BlendEffectNormal,multiply:new w.BlendEffectMultiply,screen:null,overlay:null,darken:null,lighten:null,"color-dodge":null,"color-burn":null,"hard-light":null,"soft-light":null,difference:null,exclusion:null,hue:null,saturation:null,
color:null,luminosity:null};this._effectNameToLayerPostProcessingEffect={antialiasing:null,bloom:null,"edge-detect":null,"edge-enhance":null,emboss:null,"gaussian-blur":null,grayscale:null,"high-pass":null,"unreal-bloom":new y.PostProcessingEffectUnrealBloom,unsharpen:null};this.effects={highlight:new u.default,hittest:new v.HittestEffect,integrate:new t.AnimationEffect};this.materialManager=new q(a);this._vtlProgramCache=new n.default(a);this.textureManager=new r(b)}c.prototype.getFbos=function(a,
b){if(a!==this._lastWidth||b!==this._lastHeight){this._lastWidth=a;this._lastHeight=b;if(this._fbos)for(var e in this._fbos)this._fbos[e].dispose();e={target:3553,pixelFormat:6408,dataType:5121,samplingMode:9728,wrapMode:33071,width:a,height:b};var c={colorTarget:0,depthStencilTarget:3};a=new f.Renderbuffer(this.context,{width:a,height:b,internalFormat:34041});this._fbos={output:new f.FramebufferObject(this.context,c,e,a),blend:new f.FramebufferObject(this.context,c,e,a),effect0:new f.FramebufferObject(this.context,
c,e,a)}}return this._fbos};c.prototype.beforeRenderLayers=function(a){var b=a.getViewport(),b=this.getFbos(b.width,b.height);this._prevFBO=a.getBoundFramebufferObject();a.bindFramebuffer(b.output);a.setDepthWriteEnabled(!0);a.setClearColor(0,0,0,0);a.setClearDepth(1);a.clear(a.gl.COLOR_BUFFER_BIT|a.gl.DEPTH_BUFFER_BIT);a.setDepthWriteEnabled(!1)};c.prototype.beforeRenderLayer=function(a,b,e){m(e)?(a.bindFramebuffer(this._fbos.blend),a.setClearColor(0,0,0,0),a.clear(a.gl.COLOR_BUFFER_BIT)):a.bindFramebuffer(this._fbos.output);
a.setDepthWriteEnabled(!1);a.setDepthTestEnabled(!1);a.setStencilTestEnabled(!0);a.setClearStencil(b);a.setStencilWriteMask(255);a.clear(a.gl.STENCIL_BUFFER_BIT)};c.prototype.compositeLayer=function(a,b){var e=a.context,c=b.opacity;if(m(b)){var d=this.getPostProcessingEffects(b);if(k.isSome(d)&&d.length)for(var g=0;g<d.length;g++){var f=d[g],h=f.effect,f=f.options;e.bindFramebuffer(this._fbos.blend);h.draw(a,this._fbos.blend,f)}e.bindFramebuffer(this._fbos.output);e.setStencilTestEnabled(!1);e.setStencilWriteMask(0);
e.setBlendingEnabled(!0);e.setBlendFunctionSeparate(1,771,1,771);e.setColorMask(!0,!0,!0,!0);this.getBlendEffect(b).draw(a,this._fbos.blend.colorTexture,9728,c)}};c.prototype.renderLayers=function(a){a.bindFramebuffer(this._prevFBO);this._fbos&&(a.setStencilTestEnabled(!1),a.setStencilWriteMask(0),a.setBlendingEnabled(!0),a.setBlendFunctionSeparate(1,771,1,771),a.setColorMask(!0,!0,!0,!0),this._blitRenderer.render(a,this._fbos.output.colorTexture,9728,1))};c.prototype.getBlendEffect=function(a){a=
a.blendOption;return k.isSome(a.mode)?this.blendModeToBlendEffect[a.mode]:this.blendModeToBlendEffect.normal};c.prototype.getPostProcessingEffects=function(a){a=a.postProcessingEffects;if(k.isSome(a)&&0<a.length){for(var b=[],e=0;e<a.length;e++){var c=a[e],d=this._effectNameToLayerPostProcessingEffect[c.effect];d&&b.push({effect:d,options:c.options})}return b}return null};c.prototype.dispose=function(){this.materialManager.dispose();this.textureManager.dispose();this._blitRenderer&&(this._blitRenderer.dispose(),
this._blitRenderer=null);this._vtlProgramCache&&(this._vtlProgramCache.dispose(),this._vtlProgramCache=null);this._brushCache&&(this._brushCache.forEach(function(a){return a.dispose()}),this._brushCache.clear(),this._brushCache=null);if(this._fbos)for(var a in this._fbos)this._fbos[a]&&this._fbos[a].dispose();if(this.effects)for(var b in this.effects)this.effects[b]&&this.effects[b].dispose();this._prevFBO=null};c.prototype.getGeometryBrush=function(a){var b;a=(b={},b[h.WGLGeometryType.FILL]=d.brushes.Fill,
b[h.WGLGeometryType.LINE]=d.brushes.Line,b[h.WGLGeometryType.MARKER]=d.brushes.Marker,b[h.WGLGeometryType.TEXT]=d.brushes.Text,b)[a];b=this._brushCache.get(a);void 0===b&&(b=new a,this._brushCache.set(a,b));return this._brushCache.get(a)};c.prototype.renderObject=function(a,b,e,c){e=this.brushNameToCtor[e];if(!e)return null;var d=this._brushCache.get(e);void 0===d&&(d=new e,this._brushCache.set(e,d));d.prepareState(a,b,c);d.draw(a,b,c)};c.prototype.renderObjects=function(a,b,e,d){e=this.brushNameToCtor[e];
if(!e)return null;var c=this._brushCache.get(e);void 0===c&&(c=new e,this._brushCache.set(e,c));c.drawMany(a,b,d)};c.prototype.getVectorTileProgramCach=function(){return this._vtlProgramCache};c.prototype.registerRenderPass=function(a){var b=this,c=a.brushes.map(function(a){b._brushCache.has(a)||b._brushCache.set(a,new a);return b._brushCache.get(a)});return new z.default(c,a)};c.prototype.setHighlightOptions=function(a){this.effects.highlight.setHighlightOptions(a)};return c}();l.default=g});