// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define(["../../../../../Color","../GeometryUtils","../expression/expression","../expression/types"],function(k,n,h,f){class p{constructor(a,b){this.isDataDriven=!1;this.interpolator=null;switch(a.type){case "number":var d=!0;break;case "color":d=!0;break;case "array":d="number"===a.value;break;default:d=!1}null==b&&(b=a.default);if(Array.isArray(b)&&0<b.length&&h.ops[b[0]]){d={number:f.numberType,color:f.colorType,string:f.stringType,boolean:f.booleanType,enum:f.stringType};try{var e="array"===a.type?
f.arrayType(d[a.value]||f.valueType,a.length):d[a.type];const c=h.createExpression(b,null,e);this.getValue=this._buildExpression(c,a);this.isDataDriven=!0;c instanceof h.Interpolate&&c.input instanceof h.Zoom&&(this.interpolator=c)}catch(c){console.log(c.message),this.getValue=this._buildSimple(a.default)}}else{d&&"interval"===b.type&&(d=!1);if(e=b?.stops&&0<b.stops.length)for(const c of b.stops)c[1]=this._validate(c[1],a);if(this.isDataDriven=b?!!b.property:!1)if(void 0!==b.default&&(b.default=this._validate(b.default,
a)),e)switch(b.type){case "identity":this.getValue=this._buildIdentity(b,a);break;case "categorical":this.getValue=this._buildCategorical(b,a);break;default:this.getValue=d?this._buildInterpolate(b,a):this._buildInterval(b,a)}else this.getValue=this._buildIdentity(b,a);else e?this.getValue=d?this._buildZoomInterpolate(b):this._buildZoomInterval(b):(b=this._validate(b,a),this.getValue=this._buildSimple(b))}}_validate(a,b){if("number"===b.type){if(null!=b.minimum&&a<b.minimum)return b.minimum;if(null!=
b.maximum&&a>b.maximum)return b.maximum}else"color"===b.type?a=p._parseColor(a):"enum"===b.type?"string"===typeof a&&(a=b.values.indexOf(a)):"array"===b.type&&"enum"===b.value?a=a.map(d=>"string"===typeof d?b.values.indexOf(d):d):"string"===b.type&&(a=f.valueToString(a));return a}_buildSimple(a){return()=>a}_buildExpression(a,b){return(d,e)=>{try{const c=a.evaluate(e,d);return void 0===c?b.default:this._validate(c,b)}catch(c){return console.log(c.message),b.default}}}_buildIdentity(a,b){return(d,
e)=>{let c;e&&(c=e.values[a.property]);void 0!==c&&(c=this._validate(c,b));return null!=c?c:void 0!==a.default?a.default:b.default}}_buildCategorical(a,b){return(d,e)=>{let c;e&&(c=e.values[a.property]);c=this._categorical(c,a.stops);return void 0!==c?c:void 0!==a.default?a.default:b.default}}_buildInterval(a,b){return(d,e)=>{let c;e&&(c=e.values[a.property]);return"number"===typeof c?this._interval(c,a.stops):void 0!==a.default?a.default:b.default}}_buildInterpolate(a,b){return(d,e)=>{let c;e&&(c=
e.values[a.property]);return"number"===typeof c?this._interpolate(c,a.stops,a.base||1):void 0!==a.default?a.default:b.default}}_buildZoomInterpolate(a){return b=>this._interpolate(b,a.stops,a.base||1)}_buildZoomInterval(a){return b=>this._interval(b,a.stops)}_categorical(a,b){const d=b.length;for(let e=0;e<d;e++)if(b[e][0]===a)return b[e][1]}_interval(a,b){const d=b.length;let e=0;for(let c=0;c<d;c++)if(b[c][0]<=a)e=c;else break;return b[e][1]}_interpolate(a,b,d){const e=b.length;for(let l=0;l<e;l++){const m=
b[l];if(m[0]<=a)var c=m;else{var g=m;break}}if(c&&g){b=g[0]-c[0];a-=c[0];d=1===d?a/b:(d**a-1)/(d**b-1);if(Array.isArray(c[1])){c=c[1];g=g[1];a=[];for(b=0;b<c.length;b++)a.push(n.interpolate(c[b],g[b],d));return a}return n.interpolate(c[1],g[1],d)}if(c)return c[1];if(g)return g[1]}static _isEmpty(a){for(const b in a)if(a.hasOwnProperty(b))return!1;return!0}static _parseColor(a){if(Array.isArray(a))return a;"string"===typeof a&&(a=new k(a));if(a instanceof k&&!this._isEmpty(a))return k.toUnitRGBA(a)}}
return p});