// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/tslib.es6 ../../geometry ../../core/Logger ../../core/has ../../core/RandomLCG ../../core/Error ../../core/accessorSupport/decorators/subclass ./DrawAction ./input/DrawEvents ../input/InputManager ../interactive/keybindings ../support/screenUtils ../../geometry/Point".split(" "),function(g,m,r,t,u,v,w,n,p,e,c,d,h,q){const k=Symbol("view-handles"),l=Symbol("undo-redo-handles");g.MultipointDrawAction=class extends p{constructor(a){super(a);this._addVertexOnPointerUp=this._popVertexOnPointerMove=
!1}initialize(){this._addViewHandles();this._addUndoRedoHandles()}destroy(){this._removeViewHandles();this._removeUndoRedoHandles();this.emit("destroy")}undo(){super.undo();this.notifyChange("vertices")}redo(){super.redo();this.notifyChange("vertices")}complete(){this._completeDrawing()}_addViewHandles(){this._removeViewHandles();this.addHandles([this.view.on("click",a=>{a.stopPropagation()},c.ViewEventPriorities.TOOL),this.view.on("pointer-down",a=>{this._shouldHandlePointerEvent(a)&&(this._abortSnapping(),
this._activePointerId=a.pointerId,this._addVertexOnPointerUp=!0,this._cursorScreenPoint=h.createScreenPointFromEvent(a),"touch"===a.pointerType&&this._updateCursor())},c.ViewEventPriorities.TOOL),this.view.on("pointer-move",a=>{this._popVertexOnPointerMove&&(this.undo(),this._popVertexOnPointerMove=!1);this._abortSnapping();this._cursorScreenPoint=h.createScreenPointFromEvent(a);"touch"!==a.pointerType&&this._updateCursor()},c.ViewEventPriorities.TOOL),this.view.on("pointer-drag",a=>{this._shouldHandlePointerEvent(a)&&
(this._abortSnapping(),this._addVertexOnPointerUp=!1)},c.ViewEventPriorities.TOOL),this.view.on("pointer-up",a=>{this._shouldHandlePointerEvent(a)&&(this._abortSnapping(),this._activePointerId=null,this._addVertexOnPointerUp?this._vertexAddHandler(a):this._updateCursor("touch"===a.pointerType))},c.ViewEventPriorities.TOOL),this.view.on("drag",["Shift"],a=>{a.stopPropagation()},c.ViewEventPriorities.TOOL),this.view.on("double-click",a=>{a.stopPropagation();this._drawCompleteHandler(a)},c.ViewEventPriorities.TOOL),
this.view.on("double-click",["Control"],a=>{a.stopPropagation();this._drawCompleteHandler(a)},c.ViewEventPriorities.TOOL),this.view.on("key-down",a=>{const {key:b,repeat:f}=a;b===d.sketchKeys.vertexAdd&&!f&&this._cursorScreenPoint?(a.stopPropagation(),this._abortSnapping(),this._vertexAddHandler(a)):b!==d.sketchKeys.complete||f?b!==d.sketchKeys.undo||this.interactiveUndoDisabled||f?b!==d.sketchKeys.redo||this.interactiveUndoDisabled||f?b!==d.sketchKeys.pan||f||a.stopPropagation():(a.stopPropagation(),
this.redo()):(a.stopPropagation(),this.undo()):(a.stopPropagation(),this._drawCompleteHandler(a))},c.ViewEventPriorities.TOOL),this.view.on("key-up",a=>{a.key===d.sketchKeys.pan&&a.stopPropagation()},c.ViewEventPriorities.TOOL)],k)}_addUndoRedoHandles(){this._removeUndoRedoHandles();this.addHandles([this._editGeometryOperations.on("vertex-remove",a=>{this.notifyChange("vertices");if("undo"===a.operation){const b=[...this._committedVertices];null!=this._stagedVertex&&b.push(this._coordinateHelper.pointToArray(this._stagedVertex));
this.emit("undo",new e.VertexRemoveEvent(this.view,a.vertices[0].index,b))}}),this._editGeometryOperations.on("vertex-add",a=>{this.notifyChange("vertices");if("apply"===a.operation)a=new e.VertexAddEvent(this.view,this._committedVertices.length-1,this.vertices),this.emit("vertex-add",a),a.defaultPrevented&&(this._popVertexOnPointerMove=!0);else if("redo"===a.operation){const b=[...this._committedVertices];null!=this._stagedVertex&&b.push(this._coordinateHelper.pointToArray(this._stagedVertex));this.emit("redo",
new e.VertexAddEvent(this.view,a.vertices[0].index,b))}})],l)}_removeViewHandles(){this.removeHandles(k)}_removeUndoRedoHandles(){this.removeHandles(l)}_addVertex(a){a=this._coordinateHelper.arrayToVector(a);this._isDuplicateOfLastVertex(a)||this._editGeometryOperations.appendVertex(a)}_updateCursor(a=!1){this._popCursorVertex();if(this._cursorScreenPoint){var b=this.getCoordsAndPointFromScreenPoint(this._cursorScreenPoint);null==b||a||this._pushCursorVertex(b.vertex,()=>this.emit("cursor-update",
new e.CursorUpdateEvent(this.view,this._activeComponent.vertices.length,this.vertices,null!=this._stagedVertex?new q(this._stagedVertex):null)))}}_completeDrawing(){this._activePointerId=null;this._popCursorVertex();this._abortSnapping();null!=this._snappingManager&&this._snappingManager.doneSnapping();if(!(1>this.vertices.length)){var a=new e.DrawCompleteEvent(this.vertices);this.emit("draw-complete",a);a.defaultPrevented||this._removeViewHandles()}}};g.MultipointDrawAction=m.__decorate([n.subclass("esri.views.draw.MultipointDrawAction")],
g.MultipointDrawAction);Object.defineProperty(g,Symbol.toStringTag,{value:"Module"})});