// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("../../../chunks/tslib.es6 ../../../core/reactiveUtils ../../../core/accessorSupport/decorators/property ../../../core/has ../../../core/Logger ../../../core/RandomLCG ../../../core/accessorSupport/decorators/subclass ../../Widget ../../support/globalCss ../../support/widgetUtils ../../support/jsxFactory".split(" "),function(h,l,k,f,u,v,n,p,q,r,g){const t={nextPhase:"nextPhase",previousPhase:"previousPhase",currentPhase:"{{value}}"};f=class extends p{constructor(c,d){super(c,d);this._phasesContainer=
null;this._shouldScrollCurrentPhaseIntoView=!0;this._shouldFocusCurrentPhase=!1;this._onKeyDown=a=>{const {vm:b}=this;switch(a.key){case "ArrowDown":case "ArrowLeft":a.stopPropagation();a.preventDefault();b.previous();this._shouldFocusCurrentPhase=!0;break;case "ArrowUp":case "ArrowRight":a.stopPropagation(),a.preventDefault(),b.next(),this._shouldFocusCurrentPhase=!0}};this._onArrowLeftClick=()=>{this.vm.previous()};this._onArrowRightClick=()=>{this.vm.next()};this._onPhasesContainerAfterCreate=
a=>{this._phasesContainer=a;requestAnimationFrame(this._scrollOrFocusPhase)};this._scrollOrFocusPhase=()=>{const a=this._phasesContainer;if(!this.destroyed&&null!=a){var b=a.querySelector(".esri-building-phase-picker__phase--current");b&&(this._shouldScrollCurrentPhaseIntoView&&(a.scrollLeft=-(a.offsetWidth/2)+b.offsetLeft-b.offsetWidth/2,this._shouldScrollCurrentPhaseIntoView=!1),this._shouldFocusCurrentPhase&&(b.focus(),this._shouldFocusCurrentPhase=!1))}}}initialize(){this.addHandles(l.watch(()=>
[this._currentPhase,this._phasesContainer,this.container],()=>{this._shouldScrollCurrentPhaseIntoView=!0;requestAnimationFrame(this._scrollOrFocusPhase)},l.initial))}get _phases(){return this.vm.allowedValues}get _currentPhase(){const {vm:c}=this;return c.enabled?c.value:null}render(){if(2>this._phases.length)return g.tsx("div",{key:"no-phases"});const {vm:c,container:d,messages:a}=this,{previousPhase:b,nextPhase:e}=a??t,m=r.isRTL(d);return g.tsx("div",{class:this.classes(q.globalCss.widget,"esri-building-phase-picker"),
key:this,onkeydown:this._onKeyDown},g.tsx("button",{"aria-label":b,class:m?"esri-building-phase-picker__arrow-right":"esri-building-phase-picker__arrow-left",disabled:!c.hasPrevious,onclick:this._onArrowLeftClick,title:b,type:"button"}),g.tsx("div",{afterCreate:this._onPhasesContainerAfterCreate,class:"esri-building-phase-picker__phases-container"},this._renderPhaseButtons()),g.tsx("button",{"aria-label":e,class:m?"esri-building-phase-picker__arrow-left":"esri-building-phase-picker__arrow-right",
disabled:!c.hasNext,onclick:this._onArrowRightClick,title:e,type:"button"}))}_renderPhaseButtons(){const c=this._phases,d=this._currentPhase,a=[];for(let e=0;e<c.length;++e){var b=c[e];b={phase:b,active:null!=d?b<=d:!1,current:null!=d?b===d:!1};0<e&&a.push(this._renderDivider(b));a.push(this._renderPhaseButton(b))}return a}_renderPhaseButton({phase:c,active:d,current:a}){const {vm:b}=this,e=b.getValueLabel(c);return g.tsx("button",{"aria-label":e,class:this.classes("esri-building-phase-picker__phase",
{["esri-building-phase-picker__phase--active"]:d,["esri-building-phase-picker__phase--current"]:a}),key:`phase-${c}`,onclick:()=>b.select(c),title:e,type:"button"},c)}_renderDivider({phase:c,active:d}){return g.tsx("div",{class:this.classes("esri-building-phase-picker__divider",{["esri-building-phase-picker__divider--active"]:d}),key:`phase-divider-${c}`})}};h.__decorate([k.property({nonNullable:!0})],f.prototype,"vm",void 0);h.__decorate([k.property()],f.prototype,"messages",void 0);h.__decorate([k.property()],
f.prototype,"_phases",null);h.__decorate([k.property()],f.prototype,"_currentPhase",null);h.__decorate([k.property()],f.prototype,"_phasesContainer",void 0);return f=h.__decorate([n.subclass("esri.widgets.BuildingExplorer.BuildingPhasePicker.BuildingPhasePicker")],f)});