// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("../../chunks/tslib.es6 ../../core/Collection ../../core/handleUtils ../../core/Logger ../../core/LRUCache ../../core/MapUtils ../../core/MultiOriginJSONSupport ../../core/accessorSupport/decorators/property ../../core/has ../../core/RandomLCG ../../core/accessorSupport/decorators/subclass ../Layer ../mixins/BlendLayer ../mixins/ScaleRangeLayer ../support/commonProperties ../support/lazyLayerLoader ../support/OrderByInfo ../../portal/Portal ../../portal/PortalItem ../../statistics/utils".split(" "),
function(f,p,q,r,e,m,t,g,E,F,u,n,v,w,x,y,z,A,B,C){class D{constructor(a,d){this.objectId=a;this.itemSource=d;this.count=0;this.layer=null;this.sortValue=void 0}}const k=new e.LRUCache(20,a=>a.destroy());e=class extends w.ScaleRangeLayer(v.BlendLayer(t.MultiOriginJSONMixin(n))){constructor(a){super(a);this._oidToReference=new Map;this._layerToReference=new Map;this._portals=new Map;this.layers=new p;this.maximumVisibleSublayers=10;this.opacity=1;this.title="Layers In View";this.type="catalog-dynamic-group";
this.visible=!0}load(a){this.addResolvingPromise(this.parent.load());return Promise.resolve(this)}get _orderBy(){return this.parent.orderBy?.find(a=>!a.valueExpression&&a.field)??new z({field:this.parent.objectIdField})}get _referenceComparator(){const a=this._orderBy,d=this.parent.fieldsIndex.get(a.field),b=C.getAttributeComparator(d?.toJSON().type,"descending"===a.order);return(c,h)=>(h=b(c.sortValue,h.sortValue))?h:c.objectId-c.objectId}acquireLayer(a){const d=a.getObjectId(),b=m.getOrCreateMapValue(this._oidToReference,
d,()=>this._createLayerReference(a));b.count++;return q.makeHandle(()=>{b.count--;b.count||this._disposeLayerReference(b)})}_createLayerReference(a){const d=a.getObjectId(),b=a.getAttribute(this.parent.itemSourceField),c=new D(d,b);if(k.get(b))return this._addLayer(k.pop(b),c,a),c;let h;try{h=JSON.parse(b)}catch(l){return r.getLogger(this).error(l),c}this._createLayer(h).then(l=>{this.destroyed||0===c.count?(k.get(b)||k.put(c.itemSource,l),c.layer=null):this._addLayer(l,c,a)}).catch(()=>{});return c}_addLayer(a,
d,b){this._layerToReference.set(a,d);d.sortValue=b.getAttribute(this._orderBy.field);d.layer=a;a.parent=this;this.layers.add(a);this.layers.sort((c,h)=>this._referenceComparator(this._layerToReference.get(c),this._layerToReference.get(h)))}_disposeLayerReference(a){a.layer&&(this._layerToReference.delete(a.layer),this.layers.remove(a.layer),k.put(a.itemSource,a.layer));this._oidToReference.delete(a.objectId)}async _createLayer(a){if(!("object"===typeof a&&null!=a&&"itemId"in a&&"portalUrl"in a))return new (await y.layerLookupMap.UnsupportedLayer());
const {itemId:d,portalUrl:b}=a;a=m.getOrCreateMapValue(this._portals,b,()=>new A({url:b}));return n.fromPortalItem(new B({id:d,portal:a}))}};f.__decorate([g.property()],e.prototype,"_orderBy",null);f.__decorate([g.property()],e.prototype,"_referenceComparator",null);f.__decorate([g.property({readOnly:!0})],e.prototype,"layers",void 0);f.__decorate([g.property()],e.prototype,"maximumVisibleSublayers",void 0);f.__decorate([g.property(x.opacity)],e.prototype,"opacity",void 0);f.__decorate([g.property({type:String,
json:{name:"title",write:!0}})],e.prototype,"title",void 0);f.__decorate([g.property({json:{read:!1}})],e.prototype,"type",void 0);f.__decorate([g.property({type:Boolean,json:{name:"visibility",write:!0}})],e.prototype,"visible",void 0);return e=f.__decorate([u.subclass("esri.layers.catalog.CatalogDynamicGroupLayer")],e)});