// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.8/esri/copyright.txt for details.
//>>built
define("require ../core/promiseUtils dojo/on dojo/Deferred dojo/promise/all ../layers/support/layerUtils ../geometry/support/scaleUtils ../geometry/Extent ../tasks/support/Query ../layers/GroupLayer ../core/Accessor".split(" "),function(G,w,C,y,H,D,E,I,J,F,K){var z;return K.createSubclass({declaredClass:"esri.views.PopupManager",properties:{map:{dependsOn:["view.map"],readOnly:!0}},constructor:function(){this._featureLayersCache={}},destroy:function(){this._featureLayersCache={};this.view=null},_clickHandle:null,
_featureLayersCache:null,enabled:!1,_enabledSetter:function(b){this._clickHandle&&(b?this._clickHandle.resume():this._clickHandle.pause());this._set("enabled",b)},_mapGetter:function(){return this.get("view.map")||null},view:null,_viewSetter:function(b){this._clickHandle&&(this._clickHandle.remove(),this._clickHandle=null);b&&(this._clickHandle=C.pausable(b,"click",this._clickHandler.bind(this)),this.enabled||this._clickHandle.pause());this._set("view",b)},getMapLayer:function(b){var c;if(b&&(c=b.findLayerById())&&
(b=c.id,this._featureLayersCache[b])){var a=b.lastIndexOf("_");-1<a&&(b=b.substring(0,a),c=this.map.findLayerById(b))}return c},_closePopup:function(){var b=this.get("view.popup");b&&(b.clear(),b.close())},_showPopup:function(b,c,a){function g(t){return k.allLayerViews.find(function(a){return a.layer===t})}function n(a){if(null==a)return!1;var b=g(a);return null==b?!1:a.loaded&&!b.suspended&&(a.popupEnabled&&a.popupTemplate||"graphics"===a.type||"geo-rss"===a.type||"map-notes"===a.type||"kml"===a.type||
b.getPopupData)}function u(a){return(a=g(a))&&a.hasDraped}var k=this.view;b=k.popup;var q=this,h=[],d="3d"===k.type;this.map.layers.toArray().forEach(function(a){a.isInstanceOf(F)?a.layers.toArray().forEach(function(a){!n(a)||d&&!u(a)||h.push(a)}):!n(a)||d&&!u(a)||h.push(a)});0<k.graphics.length&&h.push(k.graphics);(a&&k.graphics.includes(a)?a.popupTemplate:!a||n(a.layer))||(a=null);if(h.length||a){var l=[],r=!!a,m=q._calculateClickTolerance(h);if(c){var x=1;"2d"===k.type&&(x=k.state.resolution);
var f=k.basemapTerrain;f&&f.overlayManager&&(x=f.overlayManager.overlayPixelSizeInMapUnits(c));m*=x;f&&!f.spatialReference.equals(k.spatialReference)&&(m*=E.getMetersPerUnitForSR(f.spatialReference)/E.getMetersPerUnitForSR(k.spatialReference));var f=c.clone().offset(-m,-m),m=c.clone().offset(m,m),v=new I(Math.min(f.x,m.x),Math.min(f.y,m.y),Math.max(f.x,m.x),Math.max(f.y,m.y),k.spatialReference),f=function(b){var h;if("imagery"===b.type){h=new J;h.geometry=c;var e=g(b),d={rasterAttributeTableFieldPrefix:"Raster.",
returnDomainValues:!0};d.layerView=e;h=b.queryVisibleRasters(h,d).then(function(a){r=r||0<a.length;return a})}else if("csv"===b.type||"scene"===b.type||!q._featureLayersCache[b.id]&&"function"!==typeof b.queryFeatures){if("map-image"===b.type||"wms"===b.type)return e=g(b),e.getPopupData(v);var d=[],f;"esri.core.Collection\x3cesri.Graphic\x3e"===b.declaredClass?(e=b,f=!0):"graphics"===b.type?(e=b.graphics,f=!0):(e=(e=g(b))&&e.loadedGraphics,f=!1);e&&(d=e.filter(function(a){return a&&(!f||a.popupTemplate)&&
a.visible&&v.intersects(a.geometry)}).toArray());0<d.length&&(r=!0,h="scene"===b.type?q._fetchSceneAttributes(b,d):w.resolve(d))}else e=b.createQuery(),e.geometry=v,h=b.queryFeatures(e).then(function(c){c=c.features;if(a&&a.layer===b&&b.objectIdField){var e=b.objectIdField,h=a.attributes[e];c=c.filter(function(a){return a.attributes[e]!==h})}if(!a&&"graphics3DGraphics"in g(b)){var d=[],q=g(b).graphics3DGraphics,f;for(f in q)d.push(q[f].graphic.attributes[b.objectIdField]);c=c.filter(function(a){return-1!==
d.indexOf(a.attributes[b.objectIdField])})}r=r||0<c.length;return c});return h};if(d&&!a||!d)var l=h.map(f).filter(function(a){return!!a}),p=function(a){return a.reduce(function(a,b){return a.concat(b.items?p(b.items):b)},[])},l=p(l);a&&(a.layer&&"scene"===a.layer.type?l.unshift(this._fetchSceneAttributes(a.layer,[a])):a.popupTemplate&&(f=new y,l.unshift(f.resolve([a]))));l.some(function(a){return!a.isFulfilled()})||r?l.length&&b.open({promises:l,location:c}):q._closePopup()}else q._closePopup()}else q._closePopup()},
_fetchSceneAttributes:function(b,c){return this.view.whenLayerView(b).then(function(a){var g=this._getOutFields(b.popupTemplate),n=c.map(function(b){return a.whenGraphicAttributes(b,g).catch(function(){return b})});return w.eachAlways(n)}.bind(this)).then(function(a){return a.map(function(a){return a.value})})},_getSubLayerFeatureLayers:function(b,c){var a=c||new y,g=[];c=b.length;var n=Math.floor(this.view.extent.width/this.view.width),u=this.view.scale,k=!1,q=this,h=0;a:for(;h<c;h++){var d=b[h],
l=d.dynamicLayerInfos||d.layerInfos;if(l){var r=null;d._params&&(d._params.layers||d._params.dynamicLayers)&&(r=d.visibleLayers);for(var r=D._getVisibleLayers(l,r),m=D._getLayersForScale(u,l),x=l.length,f=0;f<x;f++){var v=l[f],p=v.id,t=d.popupTemplates[p];if(!v.subLayerIds&&t&&t.popupTemplate&&-1<r.indexOf(p)&&-1<m.indexOf(p)){if(!z){k=!0;break a}var A=d.id+"_"+p,e=this._featureLayersCache[A];e&&e.loadError||(e||((e=t.layerUrl)||(e=v.source?this._getLayerUrl(d.url,"/dynamicLayer"):this._getLayerUrl(d.url,
p)),e=new z(e,{id:A,drawMode:!1,mode:z.MODE_SELECTION,outFields:this._getOutFields(t.popupTemplate),resourceInfo:t.resourceInfo,source:v.source}),this._featureLayersCache[A]=e),e.setDefinitionExpression(d.layerDefinitions&&d.layerDefinitions[p]),e.setGDBVersion(d.gdbVersion),e.popupTemplate=t.popupTemplate,e.setMaxAllowableOffset(n),e.setUseMapTime(!!d.useMapTime),d.layerDrawingOptions&&d.layerDrawingOptions[p]&&d.layerDrawingOptions[p].renderer&&e.setRenderer(d.layerDrawingOptions[p].renderer),g.push(e))}}}}if(k){var w=
new y;G(["../layers/FeatureLayer"],function(a){z=a;w.resolve()});w.then(function(){q._getSubLayerFeatureLayers(b,a)})}else{var B=[];g.forEach(function(a){if(!a.loaded){var b=new y;C.once(a,"load, error",function(){b.resolve()});B.push(b.promise)}});B.length?H(B).then(function(){g=g.filter(function(a){return!a.loadError&&a.isVisibleAtScale(u)});a.resolve(g)}):(g=g.filter(function(a){return a.isVisibleAtScale(u)}),a.resolve(g))}return a.promise},_getLayerUrl:function(b,c){var a=b.indexOf("?");return-1===
a?b+"/"+c:b.substring(0,a)+"/"+c+b.substring(a)},_getOutFields:function(b){var c=["*"];if("esri.PopupTemplate"===b.declaredClass){var a=null==b.content||Array.isArray(b.content)&&b.content.every(function(a){return"attachments"===a.type||"fields"===a.type&&null==a.fieldInfos||"text"===a.type&&-1===a.text.indexOf("{")});b.fieldInfos&&!b.expressionInfos&&a&&(c=[],b.fieldInfos.forEach(function(a){var b=a.fieldName&&a.fieldName.toLowerCase();b&&"shape"!==b&&0!==b.indexOf("relationships/")&&c.push(a.fieldName)}))}return c},
_calculateClickTolerance:function(b){var c=6;b.forEach(function(a){if(a=a.renderer)"simple"===a.type?((a=a.symbol)&&a.xoffset&&(c=Math.max(c,Math.abs(a.xoffset))),a&&a.yoffset&&(c=Math.max(c,Math.abs(a.yoffset)))):"unique-value"!==a.type&&"class-breaks"!==a.type||(a.uniqueValueInfos||a.classBreakInfos).forEach(function(a){(a=a.symbol)&&a.xoffset&&(c=Math.max(c,Math.abs(a.xoffset)));a&&a.yoffset&&(c=Math.max(c,Math.abs(a.yoffset)))})});return c},_clickHandler:function(b){function c(b){return a.allLayerViews.find(function(a){return a.layer===
b})}var a=this.view,g=b.screenPoint,n=this;if(0===b.button&&a.popup&&a.ready){var u="3d"===a.type,k=a.map.allLayers.some(function(a){if(a.isInstanceOf(F))return!1;var b;null==a?b=!1:(b=c(a),b=null==b?!1:a.loaded&&!b.suspended&&(a.popupEnabled&&a.popupTemplate||"graphics"===a.type||b.getPopupData));b&&!(b=!u)&&(b=(a=c(a))&&a.hasDraped);return b?!0:!1});null!=g?this.view.hitTest(g.x,g.y).then(function(a){k||0<a.results.length?0<a.results.length?(a=a.results[0],n._showPopup(b,a.mapPoint,a.graphic)):
n._showPopup(b,b.mapPoint,null):n._closePopup()}):n._showPopup(b,b.mapPoint)}}})});