// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("../chunks/tslib.es6 ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/cast ../core/RandomLCG ../core/has ../core/accessorSupport/decorators/subclass ./Widget ./BuildingExplorer/BuildingExplorerViewModel ./BuildingExplorer/css ./BuildingExplorer/BuildingDisciplinesTree/BuildingDisciplinesTree ./BuildingExplorer/BuildingLevelPicker/BuildingLevelPicker ./BuildingExplorer/BuildingPhasePicker/BuildingPhasePicker ./support/globalCss ./support/Heading ./support/legacyIcon ./support/widgetUtils ./support/decorators/messageBundle ./support/jsxFactory".split(" "),
function(e,g,r,c,z,t,u,n,f,v,w,x,l,m,y,h,p,d){const q={levels:!0,phases:!0,disciplines:!0};c=class extends u{constructor(a,b){super(a,b);this.viewModel=this._defaultViewModel=new n;this.visibleElements={...q};this.headingLevel=3;this.iconClass=f.css.widgetIcon;this.messagesCommon=this.messages=this.icon=null;this.toggleSiblingsVisibility=!1}destroy(){this.viewModel!==this._defaultViewModel&&this._defaultViewModel.destroy()}get view(){return this.viewModel.view}set view(a){this.viewModel.view=a}get layers(){return this.viewModel.layers}set layers(a){this.viewModel.layers=
a}_castVisibleElements(a){return{...q,...a}}get label(){return this.messages?.widgetLabel??""}set label(a){this._overrideIfSome("label",a)}render(){const a=this.viewModel;return d.tsx("div",{"aria-label":this.messages.widgetLabel,class:h.classes(l.globalCss.widget,f.css.base,l.globalCss.panel,{[l.globalCss.widgetDisabled]:"disabled"===a.state||!a.isSupported}),key:this},this._renderContent())}_renderContent(){const a=this.viewModel,b=this.messages;if(!a.isSupported)return d.tsx("p",{class:f.css.panelError},
b.unsupported);if(!a.layers.length)return d.tsx("p",{class:f.css.panelError},b.noData);switch(a.state){case "loading":return this._renderLoadingIndicator();case "ready":return d.tsx("div",{class:f.css.content,key:"content"},this._renderLevelPickerSection(),this._renderPhasePickerSection(),this._renderDisciplinesSection());case "failed":return d.tsx("p",{class:f.css.panelError},b.failed);default:return null}}_renderLoadingIndicator(){const a=this.messagesCommon.loading;return d.tsx("div",{"aria-label":a,
class:f.css.loadingContainer,key:"loading-container",role:"presentation",title:a},d.tsx("span",{"aria-hidden":"true",class:h.classes(y.legacyIcon.loadingIndicator,l.globalCss.rotating)}))}_renderLevelPickerSection(){const a=this.viewModel.level;var b="ready"===a.state;const k=1<a.allowedValues.length;if(!this.visibleElements.levels||!b||!k)return null;b=this.messages?.level;return d.tsx("div",{class:h.classes(f.css.section,f.css.levels),key:"levels"},d.tsx(m.Heading,{level:this.headingLevel},b?.title),
d.tsx(w,{messages:b,vm:a}))}_renderPhasePickerSection(){const a=this.viewModel.phase;var b="ready"===a.state;const k=1<a.allowedValues.length;if(!this.visibleElements.phases||!b||!k)return null;b=this.messages.phase;return d.tsx("div",{class:h.classes(f.css.section,f.css.phases),key:"phases"},d.tsx(m.Heading,{level:this.headingLevel},b.title),d.tsx(x,{messages:b,vm:a}))}_renderDisciplinesSection(){const a=this.viewModel.disciplines;var b="ready"===a.state;const k=a.root.hasChildren;if(!this.visibleElements.disciplines||
!b||!k)return null;b=this.messages?.disciplines;return d.tsx("div",{class:h.classes(f.css.section,f.css.disciplines),key:"disciplines"},d.tsx(m.Heading,{level:this.headingLevel},b.title),d.tsx(v,{messages:b,toggleSiblingsVisibility:this.toggleSiblingsVisibility,vm:a}))}};e.__decorate([g.property({type:n})],c.prototype,"viewModel",void 0);e.__decorate([g.property()],c.prototype,"view",null);e.__decorate([g.property()],c.prototype,"layers",null);e.__decorate([g.property()],c.prototype,"visibleElements",
void 0);e.__decorate([r.cast("visibleElements")],c.prototype,"_castVisibleElements",null);e.__decorate([g.property()],c.prototype,"headingLevel",void 0);e.__decorate([g.property()],c.prototype,"iconClass",void 0);e.__decorate([g.property()],c.prototype,"icon",void 0);e.__decorate([g.property()],c.prototype,"label",null);e.__decorate([g.property(),p.messageBundle("esri/widgets/BuildingExplorer/t9n/BuildingExplorer")],c.prototype,"messages",void 0);e.__decorate([g.property(),p.messageBundle("esri/t9n/common")],
c.prototype,"messagesCommon",void 0);e.__decorate([g.property({nonNullable:!0})],c.prototype,"toggleSiblingsVisibility",void 0);e.__decorate([g.property()],c.prototype,"uiStrings",void 0);return c=e.__decorate([t.subclass("esri.widgets.BuildingExplorer")],c)});