// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper dojo/i18n!./ScaleBar/nls/ScaleBar ../core/screenUtils ../core/watchUtils ../core/accessorSupport/decorators ./Widget ./ScaleBar/ScaleBarViewModel ./support/widget".split(" "),function(r,t,m,e,h,n,k,c,p,q,d){return function(l){function b(a){a=l.call(this,a)||this;a.label=h.widgetLabel;a.unit="non-metric";a.view=null;a.viewModel=new q;return a}m(b,l);b.prototype.postInitialize=function(){var a=this;this.own([k.whenTrue(this,
"view.stationary",function(){return a.scheduleRender()}),k.watch(this,["view.center","view.scale","view.zoom"],function(){a.view.stationary&&a.scheduleRender()})])};Object.defineProperty(b.prototype,"style",{set:function(a){this._set("style","dual"===this.unit?"line":a)},enumerable:!0,configurable:!0});b.prototype.castStyle=function(a){return"line"===a?a:"ruler"};b.prototype.castUnit=function(a){return"metric"===a||"dual"===a?a:"non-metric"};b.prototype.render=function(){var a,f="disabled"===this.get("viewModel.state"),
b=(a={},a["esri-disabled"]=f,a),c,e;if(!f){var g=this.unit;a=this.style;f="metric"===g||"dual"===g;("non-metric"===g||"dual"===g)&&(g=this.viewModel.getScaleBarProperties(50,"non-metric"))&&(e="ruler"===a?this._renderRuler(g):this._renderLine(g,"bottom"));f&&(f=this.viewModel.getScaleBarProperties(50,"metric"))&&(c="ruler"===a?this._renderRuler(f):this._renderLine(f,"top"))}return d.tsx("div",{afterCreate:this._handleRootCreateOrUpdate,afterUpdate:this._handleRootCreateOrUpdate,bind:this,class:this.classes("esri-scale-bar esri-widget",
b)},c,e)};b.prototype._renderRuler=function(a){var b=2*Math.round(a.length);a=2*a.value+" "+(h[a.unit]||h.unknownUnit);return d.tsx("div",{class:this.classes("esri-scale-bar__bar-container","esri-scale-bar__bar-container--ruler"),key:"esri-scale-bar__ruler"},d.tsx("div",{class:"esri-scale-bar__ruler",styles:{width:b+"px"}},d.tsx("div",{class:"esri-scale-bar__ruler-block"}),d.tsx("div",{class:"esri-scale-bar__ruler-block"}),d.tsx("div",{class:"esri-scale-bar__ruler-block"}),d.tsx("div",{class:"esri-scale-bar__ruler-block"})),
d.tsx("div",{class:this.classes("esri-scale-bar__label-container","esri-scale-bar__label-container--ruler")},d.tsx("div",{class:"esri-scale-bar__label"},"0"),d.tsx("div",{class:"esri-scale-bar__label"},a)))};b.prototype._renderLine=function(a,b){var c,e,f=2*a.value+" "+(h[a.unit]||h.unknownUnit),g=(c={},c["esri-scale-bar__label-container--top"]="top"===b,c["esri-scale-bar__label-container--bottom"]="bottom"===b,c);c=d.tsx("div",{class:this.classes("esri-scale-bar__label-container","esri-scale-bar__label-container--line",
g),key:"esri-scale-bar__label"},d.tsx("div",{class:"esri-scale-bar__label"},f));b=(e={},e["esri-scale-bar__line--top"]="top"===b,e["esri-scale-bar__line--bottom"]="bottom"===b,e);a=2*Math.round(a.length);a=d.tsx("div",{class:this.classes("esri-scale-bar__line",b),key:"esri-scale-bar__line",styles:{width:a+"px"}});return d.tsx("div",{class:this.classes("esri-scale-bar__bar-container","esri-scale-bar__bar-container--line"),key:"esri-scale-bar__line-container"},[a,c])};b.prototype._handleRootCreateOrUpdate=
function(a){var b=this.viewModel;b&&(a=a.getBoundingClientRect(),b.scaleComputedFrom=n.createScreenPoint(a.left+window.pageXOffset,a.top+window.pageYOffset))};e([c.property()],b.prototype,"label",void 0);e([c.property({dependsOn:["unit"]}),d.renderable()],b.prototype,"style",null);e([c.cast("style")],b.prototype,"castStyle",null);e([c.property(),d.renderable()],b.prototype,"unit",void 0);e([c.cast("unit")],b.prototype,"castUnit",null);e([c.aliasOf("viewModel.view"),d.renderable()],b.prototype,"view",
void 0);e([c.property(),d.renderable(["viewModel.state"])],b.prototype,"viewModel",void 0);return b=e([c.subclass("esri.widgets.ScaleBar")],b)}(c.declared(p))});