// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
var DracoDecoderModule=function(){var na="undefined"!==typeof document&&document.currentScript?document.currentScript.src:void 0;return function(T){function Ba(f){return a.locateFile?a.locateFile(f,F):F+f}function R(a,c){a||K("Assertion failed: "+c)}function da(a,c){var b;if(a){b=Y;var d=a+c;for(c=a;b[c]&&!(c>=d);)++c;if(16<c-a&&b.subarray&&oa)b=oa.decode(b.subarray(a,c));else{for(d="";a<c;){var f=b[a++];if(f&128){var e=b[a++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|e);else{var g=b[a++]&
63,f=224==(f&240)?(f&15)<<12|e<<6|g:(f&7)<<18|e<<12|g<<6|b[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}b=d}}else b="";return b}function ea(a,c){0<a%c&&(a+=c-a%c);return a}function pa(){a.HEAP8=S=new Int8Array(z);a.HEAP16=new Int16Array(z);a.HEAP32=fa=new Int32Array(z);a.HEAPU8=Y=new Uint8Array(z);a.HEAPU16=new Uint16Array(z);a.HEAPU32=new Uint32Array(z);a.HEAPF32=new Float32Array(z);a.HEAPF64=new Float64Array(z)}
function Z(f){for(;0<f.length;){var c=f.shift();if("function"==typeof c)c();else{var b=c.func;"number"===typeof b?void 0===c.arg?a.dynCall_v(b):a.dynCall_vi(b,c.arg):b(void 0===c.arg?null:c.arg)}}}function qa(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}function ra(){try{if(a.wasmBinary)return new Uint8Array(a.wasmBinary);if(a.readBinary)return a.readBinary(L);throw"both async and sync fetching of the wasm failed";
}catch(f){K(f)}}function Da(){return a.wasmBinary||!U&&!O||"function"!==typeof fetch?new Promise(function(a,c){a(ra())}):fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return ra()})}function Ea(f){function c(c,b){a.asm=c.exports;P--;a.monitorRunDependencies&&a.monitorRunDependencies(P);0==P&&(null!==ga&&(clearInterval(ga),ga=null),V&&(c=V,V=null,c()))}function b(a){c(a.instance)}function d(a){Da().then(function(a){return WebAssembly.instantiate(a,
e)}).then(a,function(a){Q("failed to asynchronously prepare wasm: "+a);K(a)})}var e={env:f,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:Fa};P++;a.monitorRunDependencies&&a.monitorRunDependencies(P);if(a.instantiateWasm)try{return a.instantiateWasm(e,c)}catch(Ca){return Q("Module.instantiateWasm callback failed with error: "+Ca),!1}a.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||qa(L)||"function"!==typeof fetch?d(b):WebAssembly.instantiateStreaming(fetch(L,{credentials:"same-origin"}),
e).then(b,function(a){Q("wasm streaming compile failed: "+a);Q("falling back to ArrayBuffer instantiation");d(b)});return{}}function aa(){return!!aa.uncaught_exception}function sa(){return S.length}function Ga(a){a=ea(a,65536);var c=z.byteLength;try{return-1!==W.grow((a-c)/65536)?(z=W.buffer,!0):!1}catch(b){return!1}}function ba(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function ha(f){function c(){if(!a.calledRun&&(a.calledRun=!0,!ia)){ja||(ja=!0,Z(Ha));
Z(ta);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;)ua.unshift(a.postRun.shift());Z(ua)}}if(!(0<P)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)va.unshift(a.preRun.shift());Z(va);0<P||a.calledRun||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);c()},1)):c())}}function K(f){if(a.onAbort)a.onAbort(f);void 0!==f?
(wa(f),Q(f),f=JSON.stringify(f)):f="";ia=!0;throw"abort("+f+"). Build with -s ASSERTIONS\x3d1 for more info.";}function h(){}function m(a){return(a||h).__cache__}function G(a,c){var b=m(c),d=b[a];if(d)return d;d=Object.create((c||h).prototype);d.ptr=a;return b[a]=d}function M(a){if("string"===typeof a){for(var c=0,b=0;b<a.length;++b){var d=a.charCodeAt(b);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++b)&1023);127>=d?++c:c=2047>=d?c+2:65535>=d?c+3:c+4}c=Array(c+1);b=0;d=c.length;if(0<
d){for(var d=b+d-1,f=0;f<a.length;++f){var e=a.charCodeAt(f);if(55296<=e&&57343>=e)var h=a.charCodeAt(++f),e=65536+((e&1023)<<10)|h&1023;if(127>=e){if(b>=d)break;c[b++]=e}else{if(2047>=e){if(b+1>=d)break;c[b++]=192|e>>6}else{if(65535>=e){if(b+2>=d)break;c[b++]=224|e>>12}else{if(b+3>=d)break;c[b++]=240|e>>18;c[b++]=128|e>>12&63}c[b++]=128|e>>6&63}c[b++]=128|e&63}}c[b]=0}a=g.alloc(c,S);g.copy(c,S,a)}return a}function p(){throw"cannot construct a Status, no constructor in IDL";}function q(){this.ptr=
Ia();m(q)[this.ptr]=this}function A(){this.ptr=Ja();m(A)[this.ptr]=this}function r(){this.ptr=Ka();m(r)[this.ptr]=this}function t(){this.ptr=La();m(t)[this.ptr]=this}function B(){this.ptr=Ma();m(B)[this.ptr]=this}function k(){this.ptr=Na();m(k)[this.ptr]=this}function C(){this.ptr=Oa();m(C)[this.ptr]=this}function n(){this.ptr=Pa();m(n)[this.ptr]=this}function u(){this.ptr=Qa();m(u)[this.ptr]=this}function l(){this.ptr=Ra();m(l)[this.ptr]=this}function v(){this.ptr=Sa();m(v)[this.ptr]=this}function w(){this.ptr=
Ta();m(w)[this.ptr]=this}function H(){this.ptr=Ua();m(H)[this.ptr]=this}function D(){this.ptr=Va();m(D)[this.ptr]=this}function e(){this.ptr=Wa();m(e)[this.ptr]=this}function x(){this.ptr=Xa();m(x)[this.ptr]=this}function I(){throw"cannot construct a VoidPtr, no constructor in IDL";}function y(){this.ptr=Ya();m(y)[this.ptr]=this}function E(){this.ptr=Za();m(E)[this.ptr]=this}T=T||{};var a="undefined"!==typeof T?T:{},xa=!1,ya=!1;a.onRuntimeInitialized=function(){xa=!0;if(ya&&"function"===typeof a.onModuleLoaded)a.onModuleLoaded(a)};
a.onModuleParsed=function(){ya=!0;if(xa&&"function"===typeof a.onModuleLoaded)a.onModuleLoaded(a)};a.isVersionSupported=function(a){if("string"!==typeof a)return!1;a=a.split(".");return 2>a.length||3<a.length?!1:1==a[0]&&0<=a[1]&&3>=a[1]?!0:0!=a[0]||10<a[1]?!1:!0};var X={},N;for(N in a)a.hasOwnProperty(N)&&(X[N]=a[N]);a.arguments=[];a.thisProgram="./this.program";a.quit=function(a,c){throw c;};a.preRun=[];a.postRun=[];var U=!1,O=!1,ka=!1,za=!1,U="object"===typeof window,O="function"===typeof importScripts,
ka="object"===typeof process&&"function"===typeof require&&!U&&!O,za=!U&&!ka&&!O,F="";if(ka){var F=__dirname+"/",la,ma;a.read=function(a,c){la||(la=require("fs"));ma||(ma=require("path"));a=ma.normalize(a);a=la.readFileSync(a);return c?a:a.toString()};a.readBinary=function(f){f=a.read(f,!0);f.buffer||(f=new Uint8Array(f));R(f.buffer);return f};1<process.argv.length&&(a.thisProgram=process.argv[1].replace(/\\/g,"/"));a.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof
ba))throw a;});process.on("unhandledRejection",K);a.quit=function(a){process.exit(a)};a.inspect=function(){return"[Emscripten Module object]"}}else if(za)"undefined"!=typeof read&&(a.read=function(a){return read(a)}),a.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");R("object"===typeof a);return a},"undefined"!=typeof scriptArgs?a.arguments=scriptArgs:"undefined"!=typeof arguments&&(a.arguments=arguments),"function"===typeof quit&&(a.quit=
function(a){quit(a)});else if(U||O)O?F=self.location.href:document.currentScript&&(F=document.currentScript.src),na&&(F=na),F=0!==F.indexOf("blob:")?F.substr(0,F.lastIndexOf("/")+1):"",a.read=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},O&&(a.readBinary=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),a.readAsync=function(a,c,b){var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?c(d.response):b()};d.onerror=b;d.send(null)},a.setWindowTitle=function(a){document.title=a};var wa=a.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),Q=a.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||wa);for(N in X)X.hasOwnProperty(N)&&(a[N]=X[N]);var X=void 0,Fa={"f64-rem":function(a,c){return a%
c},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&Q("no native wasm support detected");var W,ia=!1,oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var z,S,Y,fa,ca=a.TOTAL_MEMORY||16777216;5242880>ca&&Q("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+ca+"! (TOTAL_STACK\x3d5242880)");a.buffer?z=a.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(W=new WebAssembly.Memory({initial:ca/
65536}),z=W.buffer):z=new ArrayBuffer(ca);pa();fa[4088]=5259264;var va=[],Ha=[],ta=[],ua=[],ja=!1,P=0,ga=null,V=null;a.preloadedImages={};a.preloadedAudios={};var L="draco_decoder.wasm";qa(L)||(L=Ba(L));a.asm=function(a,c,b){c.memory=W;c.table=new WebAssembly.Table({initial:490,maximum:490,element:"anyfunc"});c.__memory_base=1024;c.__table_base=0;return Ea(c)};var J={last:0,caught:[],infos:{},deAdjust:function(a){if(!a||J.infos[a])return a;for(var c in J.infos)for(var b=+c,d=J.infos[b].adjusted,e=
d.length,f=0;f<e;f++)if(d[f]===a)return b;return a},addRef:function(a){a&&J.infos[a].refcount++},decRef:function(e){if(e){var c=J.infos[e];R(0<c.refcount);c.refcount--;if(0===c.refcount&&!c.rethrown){c.destructor&&a.dynCall_vi(c.destructor,e);delete J.infos[e];try{$a(e)}catch(b){}}}},clearRef:function(a){a&&(J.infos[a].refcount=0)}},Aa=a.asm({},{e:K,d:function(a){return ab(a)},k:function(){ia=!0;throw"Pure virtual function called!";},c:function(a,c,b){J.infos[a]={ptr:a,adjusted:[a],type:c,destructor:b,
refcount:0,caught:!1,rethrown:!1};J.last=a;"uncaught_exception"in aa?aa.uncaught_exception++:aa.uncaught_exception=1;throw a;},f:function(e){a.___errno_location&&(fa[a.___errno_location()>>2]=e);return e},b:function(){a.abort()},j:sa,i:function(a,c,b){Y.set(Y.subarray(c,c+b),a)},h:function(a){var c=sa();if(2147418112<a)return!1;for(c=Math.max(c,16777216);c<a;)c=536870912>=c?ea(2*c,65536):Math.min(ea((3*c+2147483648)/4,65536),2147418112);if(!Ga(c))return!1;pa();return!0},g:function(){K("trap!")},l:function(a){K("OOM")},
a:16352},z);a.asm=Aa;var Ma=a._emscripten_bind_AttributeOctahedronTransform_AttributeOctahedronTransform_0=function(){return a.asm.m.apply(null,arguments)},bb=a._emscripten_bind_AttributeOctahedronTransform_InitFromAttribute_1=function(){return a.asm.n.apply(null,arguments)},cb=a._emscripten_bind_AttributeOctahedronTransform___destroy___0=function(){return a.asm.o.apply(null,arguments)},db=a._emscripten_bind_AttributeOctahedronTransform_quantization_bits_0=function(){return a.asm.p.apply(null,arguments)},
Pa=a._emscripten_bind_AttributeQuantizationTransform_AttributeQuantizationTransform_0=function(){return a.asm.q.apply(null,arguments)},eb=a._emscripten_bind_AttributeQuantizationTransform_InitFromAttribute_1=function(){return a.asm.r.apply(null,arguments)},fb=a._emscripten_bind_AttributeQuantizationTransform___destroy___0=function(){return a.asm.s.apply(null,arguments)},gb=a._emscripten_bind_AttributeQuantizationTransform_min_value_1=function(){return a.asm.t.apply(null,arguments)},hb=a._emscripten_bind_AttributeQuantizationTransform_quantization_bits_0=
function(){return a.asm.u.apply(null,arguments)},ib=a._emscripten_bind_AttributeQuantizationTransform_range_0=function(){return a.asm.v.apply(null,arguments)},Oa=a._emscripten_bind_AttributeTransformData_AttributeTransformData_0=function(){return a.asm.w.apply(null,arguments)},jb=a._emscripten_bind_AttributeTransformData___destroy___0=function(){return a.asm.x.apply(null,arguments)},kb=a._emscripten_bind_AttributeTransformData_transform_type_0=function(){return a.asm.y.apply(null,arguments)},Va=a._emscripten_bind_DecoderBuffer_DecoderBuffer_0=
function(){return a.asm.z.apply(null,arguments)},lb=a._emscripten_bind_DecoderBuffer_Init_2=function(){return a.asm.A.apply(null,arguments)},mb=a._emscripten_bind_DecoderBuffer___destroy___0=function(){return a.asm.B.apply(null,arguments)},nb=a._emscripten_bind_Decoder_DecodeBufferToMesh_2=function(){return a.asm.C.apply(null,arguments)},ob=a._emscripten_bind_Decoder_DecodeBufferToPointCloud_2=function(){return a.asm.D.apply(null,arguments)},Wa=a._emscripten_bind_Decoder_Decoder_0=function(){return a.asm.E.apply(null,
arguments)},pb=a._emscripten_bind_Decoder_GetAttributeByUniqueId_2=function(){return a.asm.F.apply(null,arguments)},qb=a._emscripten_bind_Decoder_GetAttributeFloatArrayForAllPoints_4=function(){return a.asm.G.apply(null,arguments)},rb=a._emscripten_bind_Decoder_GetAttributeFloatForAllPoints_3=function(){return a.asm.H.apply(null,arguments)},sb=a._emscripten_bind_Decoder_GetAttributeFloat_3=function(){return a.asm.I.apply(null,arguments)},tb=a._emscripten_bind_Decoder_GetAttributeIdByMetadataEntry_3=
function(){return a.asm.J.apply(null,arguments)},ub=a._emscripten_bind_Decoder_GetAttributeIdByName_2=function(){return a.asm.K.apply(null,arguments)},vb=a._emscripten_bind_Decoder_GetAttributeId_2=function(){return a.asm.L.apply(null,arguments)},wb=a._emscripten_bind_Decoder_GetAttributeInt16ForAllPoints_3=function(){return a.asm.M.apply(null,arguments)},xb=a._emscripten_bind_Decoder_GetAttributeInt32ForAllPoints_3=function(){return a.asm.N.apply(null,arguments)},yb=a._emscripten_bind_Decoder_GetAttributeInt8ForAllPoints_3=
function(){return a.asm.O.apply(null,arguments)},zb=a._emscripten_bind_Decoder_GetAttributeIntForAllPoints_3=function(){return a.asm.P.apply(null,arguments)},Ab=a._emscripten_bind_Decoder_GetAttributeMetadata_2=function(){return a.asm.Q.apply(null,arguments)},Bb=a._emscripten_bind_Decoder_GetAttributeUInt16ArrayForAllPoints_4=function(){return a.asm.R.apply(null,arguments)},Cb=a._emscripten_bind_Decoder_GetAttributeUInt16ForAllPoints_3=function(){return a.asm.S.apply(null,arguments)},Db=a._emscripten_bind_Decoder_GetAttributeUInt32ArrayForAllPoints_4=
function(){return a.asm.T.apply(null,arguments)},Eb=a._emscripten_bind_Decoder_GetAttributeUInt32ForAllPoints_3=function(){return a.asm.U.apply(null,arguments)},Fb=a._emscripten_bind_Decoder_GetAttributeUInt8ArrayForAllPoints_4=function(){return a.asm.V.apply(null,arguments)},Gb=a._emscripten_bind_Decoder_GetAttributeUInt8ForAllPoints_3=function(){return a.asm.W.apply(null,arguments)},Hb=a._emscripten_bind_Decoder_GetAttribute_2=function(){return a.asm.X.apply(null,arguments)},Ib=a._emscripten_bind_Decoder_GetEncodedGeometryType_1=
function(){return a.asm.Y.apply(null,arguments)},Jb=a._emscripten_bind_Decoder_GetFaceFromMesh_3=function(){return a.asm.Z.apply(null,arguments)},Kb=a._emscripten_bind_Decoder_GetMetadata_1=function(){return a.asm._.apply(null,arguments)},Lb=a._emscripten_bind_Decoder_GetTriangleStripsFromMesh_2=function(){return a.asm.$.apply(null,arguments)},Mb=a._emscripten_bind_Decoder_GetTrianglesUInt16Array_3=function(){return a.asm.aa.apply(null,arguments)},Nb=a._emscripten_bind_Decoder_GetTrianglesUInt32Array_3=
function(){return a.asm.ba.apply(null,arguments)},Ob=a._emscripten_bind_Decoder_SkipAttributeTransform_1=function(){return a.asm.ca.apply(null,arguments)},Pb=a._emscripten_bind_Decoder___destroy___0=function(){return a.asm.da.apply(null,arguments)},Ta=a._emscripten_bind_DracoFloat32Array_DracoFloat32Array_0=function(){return a.asm.ea.apply(null,arguments)},Qb=a._emscripten_bind_DracoFloat32Array_GetArray_2=function(){return a.asm.fa.apply(null,arguments)},Rb=a._emscripten_bind_DracoFloat32Array_GetValue_1=
function(){return a.asm.ga.apply(null,arguments)},Sb=a._emscripten_bind_DracoFloat32Array___destroy___0=function(){return a.asm.ha.apply(null,arguments)},Tb=a._emscripten_bind_DracoFloat32Array_size_0=function(){return a.asm.ia.apply(null,arguments)},Sa=a._emscripten_bind_DracoInt16Array_DracoInt16Array_0=function(){return a.asm.ja.apply(null,arguments)},Ub=a._emscripten_bind_DracoInt16Array_GetArray_2=function(){return a.asm.ka.apply(null,arguments)},Vb=a._emscripten_bind_DracoInt16Array_GetValue_1=
function(){return a.asm.la.apply(null,arguments)},Wb=a._emscripten_bind_DracoInt16Array___destroy___0=function(){return a.asm.ma.apply(null,arguments)},Xb=a._emscripten_bind_DracoInt16Array_size_0=function(){return a.asm.na.apply(null,arguments)},Ya=a._emscripten_bind_DracoInt32Array_DracoInt32Array_0=function(){return a.asm.oa.apply(null,arguments)},Yb=a._emscripten_bind_DracoInt32Array_GetArray_2=function(){return a.asm.pa.apply(null,arguments)},Zb=a._emscripten_bind_DracoInt32Array_GetValue_1=
function(){return a.asm.qa.apply(null,arguments)},$b=a._emscripten_bind_DracoInt32Array___destroy___0=function(){return a.asm.ra.apply(null,arguments)},ac=a._emscripten_bind_DracoInt32Array_size_0=function(){return a.asm.sa.apply(null,arguments)},Qa=a._emscripten_bind_DracoInt8Array_DracoInt8Array_0=function(){return a.asm.ta.apply(null,arguments)},bc=a._emscripten_bind_DracoInt8Array_GetArray_2=function(){return a.asm.ua.apply(null,arguments)},cc=a._emscripten_bind_DracoInt8Array_GetValue_1=function(){return a.asm.va.apply(null,
arguments)},dc=a._emscripten_bind_DracoInt8Array___destroy___0=function(){return a.asm.wa.apply(null,arguments)},ec=a._emscripten_bind_DracoInt8Array_size_0=function(){return a.asm.xa.apply(null,arguments)},Ia=a._emscripten_bind_DracoUInt16Array_DracoUInt16Array_0=function(){return a.asm.ya.apply(null,arguments)},fc=a._emscripten_bind_DracoUInt16Array_GetArray_2=function(){return a.asm.za.apply(null,arguments)},gc=a._emscripten_bind_DracoUInt16Array_GetValue_1=function(){return a.asm.Aa.apply(null,
arguments)},hc=a._emscripten_bind_DracoUInt16Array___destroy___0=function(){return a.asm.Ba.apply(null,arguments)},ic=a._emscripten_bind_DracoUInt16Array_size_0=function(){return a.asm.Ca.apply(null,arguments)},La=a._emscripten_bind_DracoUInt32Array_DracoUInt32Array_0=function(){return a.asm.Da.apply(null,arguments)},jc=a._emscripten_bind_DracoUInt32Array_GetArray_2=function(){return a.asm.Ea.apply(null,arguments)},kc=a._emscripten_bind_DracoUInt32Array_GetValue_1=function(){return a.asm.Fa.apply(null,
arguments)},lc=a._emscripten_bind_DracoUInt32Array___destroy___0=function(){return a.asm.Ga.apply(null,arguments)},mc=a._emscripten_bind_DracoUInt32Array_size_0=function(){return a.asm.Ha.apply(null,arguments)},Ka=a._emscripten_bind_DracoUInt8Array_DracoUInt8Array_0=function(){return a.asm.Ia.apply(null,arguments)},nc=a._emscripten_bind_DracoUInt8Array_GetArray_2=function(){return a.asm.Ja.apply(null,arguments)},oc=a._emscripten_bind_DracoUInt8Array_GetValue_1=function(){return a.asm.Ka.apply(null,
arguments)},pc=a._emscripten_bind_DracoUInt8Array___destroy___0=function(){return a.asm.La.apply(null,arguments)},qc=a._emscripten_bind_DracoUInt8Array_size_0=function(){return a.asm.Ma.apply(null,arguments)},Ua=a._emscripten_bind_GeometryAttribute_GeometryAttribute_0=function(){return a.asm.Na.apply(null,arguments)},rc=a._emscripten_bind_GeometryAttribute___destroy___0=function(){return a.asm.Oa.apply(null,arguments)},Xa=a._emscripten_bind_Mesh_Mesh_0=function(){return a.asm.Pa.apply(null,arguments)},
sc=a._emscripten_bind_Mesh___destroy___0=function(){return a.asm.Qa.apply(null,arguments)},tc=a._emscripten_bind_Mesh_num_attributes_0=function(){return a.asm.Ra.apply(null,arguments)},uc=a._emscripten_bind_Mesh_num_faces_0=function(){return a.asm.Sa.apply(null,arguments)},vc=a._emscripten_bind_Mesh_num_points_0=function(){return a.asm.Ta.apply(null,arguments)},wc=a._emscripten_bind_MetadataQuerier_GetDoubleEntry_2=function(){return a.asm.Ua.apply(null,arguments)},xc=a._emscripten_bind_MetadataQuerier_GetEntryName_2=
function(){return a.asm.Va.apply(null,arguments)},yc=a._emscripten_bind_MetadataQuerier_GetIntEntryArray_3=function(){return a.asm.Wa.apply(null,arguments)},zc=a._emscripten_bind_MetadataQuerier_GetIntEntry_2=function(){return a.asm.Xa.apply(null,arguments)},Ac=a._emscripten_bind_MetadataQuerier_GetStringEntry_2=function(){return a.asm.Ya.apply(null,arguments)},Bc=a._emscripten_bind_MetadataQuerier_HasEntry_2=function(){return a.asm.Za.apply(null,arguments)},Ra=a._emscripten_bind_MetadataQuerier_MetadataQuerier_0=
function(){return a.asm._a.apply(null,arguments)},Cc=a._emscripten_bind_MetadataQuerier_NumEntries_1=function(){return a.asm.$a.apply(null,arguments)},Dc=a._emscripten_bind_MetadataQuerier___destroy___0=function(){return a.asm.ab.apply(null,arguments)},Za=a._emscripten_bind_Metadata_Metadata_0=function(){return a.asm.bb.apply(null,arguments)},Ec=a._emscripten_bind_Metadata___destroy___0=function(){return a.asm.cb.apply(null,arguments)},Fc=a._emscripten_bind_PointAttribute_GetAttributeTransformData_0=
function(){return a.asm.db.apply(null,arguments)},Na=a._emscripten_bind_PointAttribute_PointAttribute_0=function(){return a.asm.eb.apply(null,arguments)},Gc=a._emscripten_bind_PointAttribute___destroy___0=function(){return a.asm.fb.apply(null,arguments)},Hc=a._emscripten_bind_PointAttribute_attribute_type_0=function(){return a.asm.gb.apply(null,arguments)},Ic=a._emscripten_bind_PointAttribute_byte_offset_0=function(){return a.asm.hb.apply(null,arguments)},Jc=a._emscripten_bind_PointAttribute_byte_stride_0=
function(){return a.asm.ib.apply(null,arguments)},Kc=a._emscripten_bind_PointAttribute_data_type_0=function(){return a.asm.jb.apply(null,arguments)},Lc=a._emscripten_bind_PointAttribute_normalized_0=function(){return a.asm.kb.apply(null,arguments)},Mc=a._emscripten_bind_PointAttribute_num_components_0=function(){return a.asm.lb.apply(null,arguments)},Nc=a._emscripten_bind_PointAttribute_size_0=function(){return a.asm.mb.apply(null,arguments)},Oc=a._emscripten_bind_PointAttribute_unique_id_0=function(){return a.asm.nb.apply(null,
arguments)},Ja=a._emscripten_bind_PointCloud_PointCloud_0=function(){return a.asm.ob.apply(null,arguments)},Pc=a._emscripten_bind_PointCloud___destroy___0=function(){return a.asm.pb.apply(null,arguments)},Qc=a._emscripten_bind_PointCloud_num_attributes_0=function(){return a.asm.qb.apply(null,arguments)},Rc=a._emscripten_bind_PointCloud_num_points_0=function(){return a.asm.rb.apply(null,arguments)},Sc=a._emscripten_bind_Status___destroy___0=function(){return a.asm.sb.apply(null,arguments)},Tc=a._emscripten_bind_Status_code_0=
function(){return a.asm.tb.apply(null,arguments)},Uc=a._emscripten_bind_Status_error_msg_0=function(){return a.asm.ub.apply(null,arguments)},Vc=a._emscripten_bind_Status_ok_0=function(){return a.asm.vb.apply(null,arguments)},Wc=a._emscripten_bind_VoidPtr___destroy___0=function(){return a.asm.wb.apply(null,arguments)},Xc=a._emscripten_enum_draco_AttributeTransformType_ATTRIBUTE_INVALID_TRANSFORM=function(){return a.asm.xb.apply(null,arguments)},Yc=a._emscripten_enum_draco_AttributeTransformType_ATTRIBUTE_NO_TRANSFORM=
function(){return a.asm.yb.apply(null,arguments)},Zc=a._emscripten_enum_draco_AttributeTransformType_ATTRIBUTE_OCTAHEDRON_TRANSFORM=function(){return a.asm.zb.apply(null,arguments)},$c=a._emscripten_enum_draco_AttributeTransformType_ATTRIBUTE_QUANTIZATION_TRANSFORM=function(){return a.asm.Ab.apply(null,arguments)},ad=a._emscripten_enum_draco_EncodedGeometryType_INVALID_GEOMETRY_TYPE=function(){return a.asm.Bb.apply(null,arguments)},bd=a._emscripten_enum_draco_EncodedGeometryType_POINT_CLOUD=function(){return a.asm.Cb.apply(null,
arguments)},cd=a._emscripten_enum_draco_EncodedGeometryType_TRIANGULAR_MESH=function(){return a.asm.Db.apply(null,arguments)},dd=a._emscripten_enum_draco_GeometryAttribute_Type_COLOR=function(){return a.asm.Eb.apply(null,arguments)},ed=a._emscripten_enum_draco_GeometryAttribute_Type_GENERIC=function(){return a.asm.Fb.apply(null,arguments)},fd=a._emscripten_enum_draco_GeometryAttribute_Type_INVALID=function(){return a.asm.Gb.apply(null,arguments)},gd=a._emscripten_enum_draco_GeometryAttribute_Type_NORMAL=
function(){return a.asm.Hb.apply(null,arguments)},hd=a._emscripten_enum_draco_GeometryAttribute_Type_POSITION=function(){return a.asm.Ib.apply(null,arguments)},id=a._emscripten_enum_draco_GeometryAttribute_Type_TEX_COORD=function(){return a.asm.Jb.apply(null,arguments)},jd=a._emscripten_enum_draco_StatusCode_ERROR=function(){return a.asm.Kb.apply(null,arguments)},kd=a._emscripten_enum_draco_StatusCode_INVALID_PARAMETER=function(){return a.asm.Lb.apply(null,arguments)},ld=a._emscripten_enum_draco_StatusCode_IO_ERROR=
function(){return a.asm.Mb.apply(null,arguments)},md=a._emscripten_enum_draco_StatusCode_OK=function(){return a.asm.Nb.apply(null,arguments)},nd=a._emscripten_enum_draco_StatusCode_UNKNOWN_VERSION=function(){return a.asm.Ob.apply(null,arguments)},od=a._emscripten_enum_draco_StatusCode_UNSUPPORTED_VERSION=function(){return a.asm.Pb.apply(null,arguments)},$a=a._free=function(){return a.asm.Qb.apply(null,arguments)},ab=a._malloc=function(){return a.asm.Rb.apply(null,arguments)};a.dynCall_v=function(){return a.asm.Sb.apply(null,
arguments)};a.dynCall_vi=function(){return a.asm.Tb.apply(null,arguments)};a.asm=Aa;a.then=function(e){if(a.calledRun)e(a);else{var c=a.onRuntimeInitialized;a.onRuntimeInitialized=function(){c&&c();e(a)}}return a};ba.prototype=Error();ba.prototype.constructor=ba;V=function c(){a.calledRun||ha();a.calledRun||(V=c)};a.run=ha;a.abort=K;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();a.noExitRuntime=!0;ha();h.prototype=Object.create(h.prototype);
h.prototype.constructor=h;h.prototype.__class__=h;h.__cache__={};a.WrapperObject=h;a.getCache=m;a.wrapPointer=G;a.castObject=function(a,b){return G(a.ptr,b)};a.NULL=G(0);a.destroy=function(a){if(!a.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";a.__destroy__();delete m(a.__class__)[a.ptr]};a.compare=function(a,b){return a.ptr===b.ptr};a.getPointer=function(a){return a.ptr};a.getClass=function(a){return a.__class__};var g={buffer:0,size:0,pos:0,temps:[],needed:0,prepare:function(){if(g.needed){for(var c=
0;c<g.temps.length;c++)a._free(g.temps[c]);g.temps.length=0;a._free(g.buffer);g.buffer=0;g.size+=g.needed;g.needed=0}g.buffer||(g.size+=128,g.buffer=a._malloc(g.size),R(g.buffer));g.pos=0},alloc:function(c,b){R(g.buffer);c=c.length*b.BYTES_PER_ELEMENT;c=c+7&-8;g.pos+c>=g.size?(R(0<c),g.needed+=c,b=a._malloc(c),g.temps.push(b)):(b=g.buffer+g.pos,g.pos+=c);return b},copy:function(a,b,d){switch(b.BYTES_PER_ELEMENT){case 2:d>>=1;break;case 4:d>>=2;break;case 8:d>>=3}for(var c=0;c<a.length;c++)b[d+c]=
a[c]}};p.prototype=Object.create(h.prototype);p.prototype.constructor=p;p.prototype.__class__=p;p.__cache__={};a.Status=p;p.prototype.code=p.prototype.code=function(){return Tc(this.ptr)};p.prototype.ok=p.prototype.ok=function(){return!!Vc(this.ptr)};p.prototype.error_msg=p.prototype.error_msg=function(){return da(Uc(this.ptr))};p.prototype.__destroy__=p.prototype.__destroy__=function(){Sc(this.ptr)};q.prototype=Object.create(h.prototype);q.prototype.constructor=q;q.prototype.__class__=q;q.__cache__=
{};a.DracoUInt16Array=q;q.prototype.GetValue=q.prototype.GetValue=function(a){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);return gc(c,a)};q.prototype.size=q.prototype.size=function(){return ic(this.ptr)};q.prototype.GetArray=q.prototype.GetArray=function(a,b){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);return!!fc(c,a,b)};q.prototype.__destroy__=q.prototype.__destroy__=function(){hc(this.ptr)};A.prototype=Object.create(h.prototype);A.prototype.constructor=
A;A.prototype.__class__=A;A.__cache__={};a.PointCloud=A;A.prototype.num_attributes=A.prototype.num_attributes=function(){return Qc(this.ptr)};A.prototype.num_points=A.prototype.num_points=function(){return Rc(this.ptr)};A.prototype.__destroy__=A.prototype.__destroy__=function(){Pc(this.ptr)};r.prototype=Object.create(h.prototype);r.prototype.constructor=r;r.prototype.__class__=r;r.__cache__={};a.DracoUInt8Array=r;r.prototype.GetValue=r.prototype.GetValue=function(a){var c=this.ptr;a&&"object"===typeof a&&
(a=a.ptr);return oc(c,a)};r.prototype.size=r.prototype.size=function(){return qc(this.ptr)};r.prototype.GetArray=r.prototype.GetArray=function(a,b){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);return!!nc(c,a,b)};r.prototype.__destroy__=r.prototype.__destroy__=function(){pc(this.ptr)};t.prototype=Object.create(h.prototype);t.prototype.constructor=t;t.prototype.__class__=t;t.__cache__={};a.DracoUInt32Array=t;t.prototype.GetValue=t.prototype.GetValue=function(a){var c=
this.ptr;a&&"object"===typeof a&&(a=a.ptr);return kc(c,a)};t.prototype.size=t.prototype.size=function(){return mc(this.ptr)};t.prototype.GetArray=t.prototype.GetArray=function(a,b){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);return!!jc(c,a,b)};t.prototype.__destroy__=t.prototype.__destroy__=function(){lc(this.ptr)};B.prototype=Object.create(h.prototype);B.prototype.constructor=B;B.prototype.__class__=B;B.__cache__={};a.AttributeOctahedronTransform=B;B.prototype.InitFromAttribute=
B.prototype.InitFromAttribute=function(a){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);return!!bb(c,a)};B.prototype.quantization_bits=B.prototype.quantization_bits=function(){return db(this.ptr)};B.prototype.__destroy__=B.prototype.__destroy__=function(){cb(this.ptr)};k.prototype=Object.create(h.prototype);k.prototype.constructor=k;k.prototype.__class__=k;k.__cache__={};a.PointAttribute=k;k.prototype.size=k.prototype.size=function(){return Nc(this.ptr)};k.prototype.GetAttributeTransformData=k.prototype.GetAttributeTransformData=
function(){return G(Fc(this.ptr),C)};k.prototype.attribute_type=k.prototype.attribute_type=function(){return Hc(this.ptr)};k.prototype.data_type=k.prototype.data_type=function(){return Kc(this.ptr)};k.prototype.num_components=k.prototype.num_components=function(){return Mc(this.ptr)};k.prototype.normalized=k.prototype.normalized=function(){return!!Lc(this.ptr)};k.prototype.byte_stride=k.prototype.byte_stride=function(){return Jc(this.ptr)};k.prototype.byte_offset=k.prototype.byte_offset=function(){return Ic(this.ptr)};
k.prototype.unique_id=k.prototype.unique_id=function(){return Oc(this.ptr)};k.prototype.__destroy__=k.prototype.__destroy__=function(){Gc(this.ptr)};C.prototype=Object.create(h.prototype);C.prototype.constructor=C;C.prototype.__class__=C;C.__cache__={};a.AttributeTransformData=C;C.prototype.transform_type=C.prototype.transform_type=function(){return kb(this.ptr)};C.prototype.__destroy__=C.prototype.__destroy__=function(){jb(this.ptr)};n.prototype=Object.create(h.prototype);n.prototype.constructor=
n;n.prototype.__class__=n;n.__cache__={};a.AttributeQuantizationTransform=n;n.prototype.InitFromAttribute=n.prototype.InitFromAttribute=function(a){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);return!!eb(c,a)};n.prototype.quantization_bits=n.prototype.quantization_bits=function(){return hb(this.ptr)};n.prototype.min_value=n.prototype.min_value=function(a){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);return gb(c,a)};n.prototype.range=n.prototype.range=function(){return ib(this.ptr)};n.prototype.__destroy__=
n.prototype.__destroy__=function(){fb(this.ptr)};u.prototype=Object.create(h.prototype);u.prototype.constructor=u;u.prototype.__class__=u;u.__cache__={};a.DracoInt8Array=u;u.prototype.GetValue=u.prototype.GetValue=function(a){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);return cc(c,a)};u.prototype.size=u.prototype.size=function(){return ec(this.ptr)};u.prototype.GetArray=u.prototype.GetArray=function(a,b){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);return!!bc(c,
a,b)};u.prototype.__destroy__=u.prototype.__destroy__=function(){dc(this.ptr)};l.prototype=Object.create(h.prototype);l.prototype.constructor=l;l.prototype.__class__=l;l.__cache__={};a.MetadataQuerier=l;l.prototype.HasEntry=l.prototype.HasEntry=function(a,b){var c=this.ptr;g.prepare();a&&"object"===typeof a&&(a=a.ptr);b=b&&"object"===typeof b?b.ptr:M(b);return!!Bc(c,a,b)};l.prototype.GetIntEntry=l.prototype.GetIntEntry=function(a,b){var c=this.ptr;g.prepare();a&&"object"===typeof a&&(a=a.ptr);b=b&&
"object"===typeof b?b.ptr:M(b);return zc(c,a,b)};l.prototype.GetIntEntryArray=l.prototype.GetIntEntryArray=function(a,b,d){var c=this.ptr;g.prepare();a&&"object"===typeof a&&(a=a.ptr);b=b&&"object"===typeof b?b.ptr:M(b);d&&"object"===typeof d&&(d=d.ptr);yc(c,a,b,d)};l.prototype.GetDoubleEntry=l.prototype.GetDoubleEntry=function(a,b){var c=this.ptr;g.prepare();a&&"object"===typeof a&&(a=a.ptr);b=b&&"object"===typeof b?b.ptr:M(b);return wc(c,a,b)};l.prototype.GetStringEntry=l.prototype.GetStringEntry=
function(a,b){var c=this.ptr;g.prepare();a&&"object"===typeof a&&(a=a.ptr);b=b&&"object"===typeof b?b.ptr:M(b);return da(Ac(c,a,b))};l.prototype.NumEntries=l.prototype.NumEntries=function(a){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);return Cc(c,a)};l.prototype.GetEntryName=l.prototype.GetEntryName=function(a,b){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);return da(xc(c,a,b))};l.prototype.__destroy__=l.prototype.__destroy__=function(){Dc(this.ptr)};v.prototype=
Object.create(h.prototype);v.prototype.constructor=v;v.prototype.__class__=v;v.__cache__={};a.DracoInt16Array=v;v.prototype.GetValue=v.prototype.GetValue=function(a){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);return Vb(c,a)};v.prototype.size=v.prototype.size=function(){return Xb(this.ptr)};v.prototype.GetArray=v.prototype.GetArray=function(a,b){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);return!!Ub(c,a,b)};v.prototype.__destroy__=v.prototype.__destroy__=
function(){Wb(this.ptr)};w.prototype=Object.create(h.prototype);w.prototype.constructor=w;w.prototype.__class__=w;w.__cache__={};a.DracoFloat32Array=w;w.prototype.GetValue=w.prototype.GetValue=function(a){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);return Rb(c,a)};w.prototype.size=w.prototype.size=function(){return Tb(this.ptr)};w.prototype.GetArray=w.prototype.GetArray=function(a,b){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);return!!Qb(c,a,b)};w.prototype.__destroy__=
w.prototype.__destroy__=function(){Sb(this.ptr)};H.prototype=Object.create(h.prototype);H.prototype.constructor=H;H.prototype.__class__=H;H.__cache__={};a.GeometryAttribute=H;H.prototype.__destroy__=H.prototype.__destroy__=function(){rc(this.ptr)};D.prototype=Object.create(h.prototype);D.prototype.constructor=D;D.prototype.__class__=D;D.__cache__={};a.DecoderBuffer=D;D.prototype.Init=D.prototype.Init=function(a,b){var c=this.ptr;g.prepare();if("object"==typeof a&&"object"===typeof a){var e=g.alloc(a,
S);g.copy(a,S,e);a=e}b&&"object"===typeof b&&(b=b.ptr);lb(c,a,b)};D.prototype.__destroy__=D.prototype.__destroy__=function(){mb(this.ptr)};e.prototype=Object.create(h.prototype);e.prototype.constructor=e;e.prototype.__class__=e;e.__cache__={};a.Decoder=e;e.prototype.GetEncodedGeometryType=e.prototype.GetEncodedGeometryType=function(a){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);return Ib(c,a)};e.prototype.DecodeBufferToPointCloud=e.prototype.DecodeBufferToPointCloud=function(a,b){var c=this.ptr;
a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);return G(ob(c,a,b),p)};e.prototype.DecodeBufferToMesh=e.prototype.DecodeBufferToMesh=function(a,b){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);return G(nb(c,a,b),p)};e.prototype.GetAttributeId=e.prototype.GetAttributeId=function(a,b){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);return vb(c,a,b)};e.prototype.GetAttributeIdByName=e.prototype.GetAttributeIdByName=
function(a,b){var c=this.ptr;g.prepare();a&&"object"===typeof a&&(a=a.ptr);b=b&&"object"===typeof b?b.ptr:M(b);return ub(c,a,b)};e.prototype.GetAttributeIdByMetadataEntry=e.prototype.GetAttributeIdByMetadataEntry=function(a,b,d){var c=this.ptr;g.prepare();a&&"object"===typeof a&&(a=a.ptr);b=b&&"object"===typeof b?b.ptr:M(b);d=d&&"object"===typeof d?d.ptr:M(d);return tb(c,a,b,d)};e.prototype.GetAttribute=e.prototype.GetAttribute=function(a,b){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===
typeof b&&(b=b.ptr);return G(Hb(c,a,b),k)};e.prototype.GetAttributeByUniqueId=e.prototype.GetAttributeByUniqueId=function(a,b){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);return G(pb(c,a,b),k)};e.prototype.GetMetadata=e.prototype.GetMetadata=function(a){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);return G(Kb(c,a),E)};e.prototype.GetAttributeMetadata=e.prototype.GetAttributeMetadata=function(a,b){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===
typeof b&&(b=b.ptr);return G(Ab(c,a,b),E)};e.prototype.GetFaceFromMesh=e.prototype.GetFaceFromMesh=function(a,b,d){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Jb(c,a,b,d)};e.prototype.GetTriangleStripsFromMesh=e.prototype.GetTriangleStripsFromMesh=function(a,b){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);return Lb(c,a,b)};e.prototype.GetTrianglesUInt16Array=e.prototype.GetTrianglesUInt16Array=
function(a,b,d){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Mb(c,a,b,d)};e.prototype.GetTrianglesUInt32Array=e.prototype.GetTrianglesUInt32Array=function(a,b,d){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Nb(c,a,b,d)};e.prototype.GetAttributeFloat=e.prototype.GetAttributeFloat=function(a,b,d){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);
b&&"object"===typeof b&&(b=b.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!sb(c,a,b,d)};e.prototype.GetAttributeFloatForAllPoints=e.prototype.GetAttributeFloatForAllPoints=function(a,b,d){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!rb(c,a,b,d)};e.prototype.GetAttributeFloatArrayForAllPoints=e.prototype.GetAttributeFloatArrayForAllPoints=function(a,b,d,e){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===
typeof b&&(b=b.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);return!!qb(c,a,b,d,e)};e.prototype.GetAttributeIntForAllPoints=e.prototype.GetAttributeIntForAllPoints=function(a,b,d){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!zb(c,a,b,d)};e.prototype.GetAttributeInt8ForAllPoints=e.prototype.GetAttributeInt8ForAllPoints=function(a,b,d){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===
typeof b&&(b=b.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!yb(c,a,b,d)};e.prototype.GetAttributeUInt8ForAllPoints=e.prototype.GetAttributeUInt8ForAllPoints=function(a,b,d){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Gb(c,a,b,d)};e.prototype.GetAttributeUInt8ArrayForAllPoints=e.prototype.GetAttributeUInt8ArrayForAllPoints=function(a,b,d,e){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=
b.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);return!!Fb(c,a,b,d,e)};e.prototype.GetAttributeInt16ForAllPoints=e.prototype.GetAttributeInt16ForAllPoints=function(a,b,d){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!wb(c,a,b,d)};e.prototype.GetAttributeUInt16ForAllPoints=e.prototype.GetAttributeUInt16ForAllPoints=function(a,b,d){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===
typeof b&&(b=b.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Cb(c,a,b,d)};e.prototype.GetAttributeUInt16ArrayForAllPoints=e.prototype.GetAttributeUInt16ArrayForAllPoints=function(a,b,d,e){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);return!!Bb(c,a,b,d,e)};e.prototype.GetAttributeInt32ForAllPoints=e.prototype.GetAttributeInt32ForAllPoints=function(a,b,d){var c=this.ptr;a&&"object"===typeof a&&
(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!xb(c,a,b,d)};e.prototype.GetAttributeUInt32ForAllPoints=e.prototype.GetAttributeUInt32ForAllPoints=function(a,b,d){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);d&&"object"===typeof d&&(d=d.ptr);return!!Eb(c,a,b,d)};e.prototype.GetAttributeUInt32ArrayForAllPoints=e.prototype.GetAttributeUInt32ArrayForAllPoints=function(a,b,d,e){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);
b&&"object"===typeof b&&(b=b.ptr);d&&"object"===typeof d&&(d=d.ptr);e&&"object"===typeof e&&(e=e.ptr);return!!Db(c,a,b,d,e)};e.prototype.SkipAttributeTransform=e.prototype.SkipAttributeTransform=function(a){var b=this.ptr;a&&"object"===typeof a&&(a=a.ptr);Ob(b,a)};e.prototype.__destroy__=e.prototype.__destroy__=function(){Pb(this.ptr)};x.prototype=Object.create(h.prototype);x.prototype.constructor=x;x.prototype.__class__=x;x.__cache__={};a.Mesh=x;x.prototype.num_faces=x.prototype.num_faces=function(){return uc(this.ptr)};
x.prototype.num_attributes=x.prototype.num_attributes=function(){return tc(this.ptr)};x.prototype.num_points=x.prototype.num_points=function(){return vc(this.ptr)};x.prototype.__destroy__=x.prototype.__destroy__=function(){sc(this.ptr)};I.prototype=Object.create(h.prototype);I.prototype.constructor=I;I.prototype.__class__=I;I.__cache__={};a.VoidPtr=I;I.prototype.__destroy__=I.prototype.__destroy__=function(){Wc(this.ptr)};y.prototype=Object.create(h.prototype);y.prototype.constructor=y;y.prototype.__class__=
y;y.__cache__={};a.DracoInt32Array=y;y.prototype.GetValue=y.prototype.GetValue=function(a){var b=this.ptr;a&&"object"===typeof a&&(a=a.ptr);return Zb(b,a)};y.prototype.size=y.prototype.size=function(){return ac(this.ptr)};y.prototype.GetArray=y.prototype.GetArray=function(a,b){var c=this.ptr;a&&"object"===typeof a&&(a=a.ptr);b&&"object"===typeof b&&(b=b.ptr);return!!Yb(c,a,b)};y.prototype.__destroy__=y.prototype.__destroy__=function(){$b(this.ptr)};E.prototype=Object.create(h.prototype);E.prototype.constructor=
E;E.prototype.__class__=E;E.__cache__={};a.Metadata=E;E.prototype.__destroy__=E.prototype.__destroy__=function(){Ec(this.ptr)};(function(){function c(){a.OK=md();a.ERROR=jd();a.IO_ERROR=ld();a.INVALID_PARAMETER=kd();a.UNSUPPORTED_VERSION=od();a.UNKNOWN_VERSION=nd();a.INVALID_GEOMETRY_TYPE=ad();a.POINT_CLOUD=bd();a.TRIANGULAR_MESH=cd();a.ATTRIBUTE_INVALID_TRANSFORM=Xc();a.ATTRIBUTE_NO_TRANSFORM=Yc();a.ATTRIBUTE_QUANTIZATION_TRANSFORM=$c();a.ATTRIBUTE_OCTAHEDRON_TRANSFORM=Zc();a.INVALID=fd();a.POSITION=
hd();a.NORMAL=gd();a.COLOR=dd();a.TEX_COORD=id();a.GENERIC=ed()}ja?c():ta.unshift(c)})();if("function"===typeof a.onModuleParsed)a.onModuleParsed();return T}}();"object"===typeof exports&&"object"===typeof module?module.exports=DracoDecoderModule:"function"===typeof define&&define.amd?define([],function(){return DracoDecoderModule}):"object"===typeof exports&&(exports.DracoDecoderModule=DracoDecoderModule);