// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.8/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../geometry ../../Graphic ../../core/Accessor ../../core/Evented ../../core/Handles ../../core/watchUtils ../../core/accessorSupport/decorators ../../layers/GraphicsLayer ../../symbols/SimpleFillSymbol ../../symbols/SimpleLineSymbol ../../symbols/SimpleMarkerSymbol ../../views/2d/draw/Draw ../../views/2d/draw/VertexMover ./support/sketchUtils".split(" "),function(N,O,w,p,q,n,v,x,D,y,m,E,z,A,u,
F,B,h){var C=function(h){function d(){return null!==h&&h.apply(this,arguments)||this}w(d,h);p([m.property()],d.prototype,"reset",void 0);return d=p([m.subclass()],d)}(m.declared(v,x)),t=function(h){function d(){var a=null!==h&&h.apply(this,arguments)||this;a.type=null;return a}w(d,h);p([m.property()],d.prototype,"type",void 0);p([m.property()],d.prototype,"complete",void 0);p([m.property()],d.prototype,"cancel",void 0);return d=p([m.subclass()],d)}(m.declared(v,x)),G=function(){return function(h){this.tool=
h;this.type="draw-start"}}(),H=function(){return function(h){this.tool=h;this.type="draw-cancel"}}(),I=function(){return function(h,d){this.tool=h;this.geometry=d;this.type="draw-complete"}}(),J=function(){return function(h){this.geometry=h;this.type="update-start"}}(),K=function(){return function(h){this.geometry=h;this.type="update-cancel"}}(),L=function(){return function(h){this.geometry=h;this.type="update-complete"}}(),M=function(){return function(){this.type="reset"}}();return function(v){function d(a){a=
v.call(this,a)||this;a._activeLineGraphic=null;a._centerGraphic=null;a._centerSymbol=new u({type:"simple-marker",style:"circle",size:3,color:[255,255,255],outline:{color:[100,100,100]}});a._defaultGraphicsLayer=new E;a._defaultSegmentOffset=48;a._fillGraphic=null;a._graphics=null;a._handles=new D;a._lineGraphic=null;a._operationHandle=null;a._vertexGraphics=[];a.activeFillSymbol=new z({type:"simple-fill",style:"solid",color:[150,150,150,.2],outline:{color:[0,0,0,0]}});a.activeLineSymbol=new A({type:"simple-line",
color:[12,207,255,1],width:2,style:"dash"});a.activePointSymbol=new u({type:"simple-marker",style:"circle",size:6,color:[12,207,255],outline:{color:[50,50,50],width:1}});a.draw=null;a.graphic=null;a.hoverVertexSymbol=new u({type:"simple-marker",style:"circle",size:8,color:[33,205,255],outline:{color:[0,12,255],width:1}});a.layer=null;a.pointSymbol=new u({type:"simple-marker",style:"circle",size:6,color:[255,255,255],outline:{color:[50,50,50],width:1}});a.polygonSymbol=new z({type:"simple-fill",color:[150,
150,150,.2],outline:{color:[50,50,50],width:2}});a.polylineSymbol=new A({type:"simple-line",color:[130,130,130],width:2});a.selectedVertexSymbol=new u({type:"simple-marker",style:"circle",size:8,color:[255,255,255],outline:{color:[0,12,255],width:1}});a.updatePointSymbol=new u({type:"simple-marker",size:10,color:[0,200,255,.5],outline:{color:"black",width:1}});a.updatePolygonSymbol=new z({type:"simple-fill",color:[0,200,255,.5],outline:{join:"round",color:[0,12,255],width:2}});a.updatePolylineSymbol=
new A({type:"simple-line",color:[0,200,255,1],width:2});a.vertexSymbol=new u({type:"simple-marker",style:"circle",size:6,color:[33,205,255],outline:{color:[0,12,255],width:1}});a.view=null;return a}w(d,v);d.prototype.initialize=function(){var a=this;this._handles.add([y.whenOnce(this,"view.ready",function(){a._set("draw",new F({view:a.view}))}),y.when(this,"layer",function(){a.view&&a.view.map.remove(a._defaultGraphicsLayer);a._graphics=a.layer}),y.whenNot(this,"layer",function(){a.view&&a.view.map.add(a._defaultGraphicsLayer);
a._graphics=a._defaultGraphicsLayer})])};d.prototype.destroy=function(){this.reset();this._handles.removeAll();this._handles=null;this.view&&this.view.map.remove(this._defaultGraphicsLayer);this._defaultGraphicsLayer.destroy();this._graphics=this._defaultGraphicsLayer=null;this.draw&&this.draw.destroy();this._set("draw",null);this._set("view",null);this.emit("destroy")};Object.defineProperty(d.prototype,"state",{get:function(){var a=!!this.get("view.ready"),c=this._operationHandle;return a&&c?"create"===
c.type?"creating":"updating":a?"ready":"disabled"},enumerable:!0,configurable:!0});d.prototype.complete=function(){this._operationHandle&&this._operationHandle.complete();this.draw.reset()};d.prototype.create=function(a,c){var b=this;this._operationHandle&&this._operationHandle.cancel();this._operationHandle=null;var g;switch(a){case "point":g=this._createPointOperation(c);break;case "polygon":g=this._createPolygonOperation(c);break;case "polyline":g=this._createPolylineOperation(c);break;case "multipoint":g=
this._createMultipointOperation(c);break;case "rectangle":g=this._createRectangleOperation(c);break;case "circle":g=this._createCircleOperation(c);break;case "ellipse":g=this._createEllipseOperation(c);break;case "triangle":g=this._createTriangleOperation(c)}if(g)return g.on("complete",function(){g===b._operationHandle&&(b._operationHandle=null,b.emit("draw-complete",new I(a,b.graphic.geometry.clone())))}),g.on("cancel",function(){g===b._operationHandle&&(b._operationHandle=null,b.emit("draw-cancel",
new H(a)))}),this._operationHandle=g,this.emit("draw-start",new G(a)),g};d.prototype.reset=function(){this._clearGraphics();this._operationHandle&&this._operationHandle.cancel();this._operationHandle=null;this.view.container.style.cursor="default";this.graphic&&this._graphics.remove(this.graphic);this._set("graphic",null);this.draw.reset();this.emit("reset",new M)};d.prototype.update=function(a,c){var b=this;this._operationHandle&&this._operationHandle.cancel();this._operationHandle=null;if(a){var g;
switch(a.type){case "point":g=this._updatePointOperation(a,c);break;case "polyline":g=this._updatePolylineOperation(a,c);break;case "polygon":g=this._updatePolygonOperation(a,c)}if(g)return g.on("complete",function(){g===b._operationHandle&&(b._operationHandle=null,b.emit("update-complete",new L(b.graphic.geometry.clone())))}),g.on("cancel",function(){g===b._operationHandle&&(b._operationHandle=null,b.emit("update-cancel",new K(b.graphic.geometry.clone())))}),this._operationHandle=g,this.emit("update-start",
new J(a.clone())),g}};d.prototype._createPointOperation=function(a){var c=this;a=this.draw.create("point",a);var b=null,g=[a.on("cursor-update",function(a){b=c._displayCrosshairCursor()}),a.on("draw-complete",function(b){c._graphics.remove(c.graphic);b=b.coordinates;c._set("graphic",new n(new q.Point({x:b[0],y:b[1],spatialReference:c.view.spatialReference}),c.pointSymbol));f&&f.complete()})],f=new t({type:"create",complete:function(){c._graphics.remove(c.graphic);b&&b.reset();g.forEach(function(c){return c.remove()});
f.emit("complete")},cancel:function(){c._graphics.remove(c.graphic);b&&b.reset();g.forEach(function(c){return c.remove()});f.emit("cancel")}});return f};d.prototype._createPolygonOperation=function(a){var c=this,b=this.draw.create("polygon",a),g=new q.Point,f=null,e=null,k=!1,d=[b.on("vertex-add",function(b){var a=b.vertices;e=b;k&&c._snapLastVertexToAxis(a);c._showPolygonGraphic(a,!1)}),b.on("vertex-remove",function(b){var a=b.vertices;e=b;k&&c._snapLastVertexToAxis(a);c._showPolygonGraphic(a,!1)}),
b.on("vertex-update",function(b){var a=b.vertices;e=b;k&&c._snapLastVertexToAxis(a);c._showPolygonGraphic(a,!1)}),b.on("cursor-update",function(b){var a=b.vertices,l=b.native;e=b;c.view.toMap(l.x,l.y,g);k&&c._snapLastVertexToAxis(a);c._showPolygonGraphic(a,!0)}),b.on("draw-complete",function(b){c._graphics.remove(c.graphic);c._set("graphic",new n(h.createPolygon([b.vertices],c.view),c.polygonSymbol));l&&l.complete()}),b.on("undo",function(b){b=b.vertices;var a=e&&"cursor-update"===e.type;b.length?
(k&&c._snapLastVertexToAxis(b),c._showPolygonGraphic(b,a)):c._clearGraphics()}),b.on("redo",function(b){b=b.vertices;var a=e&&"cursor-update"===e.type;k&&c._snapLastVertexToAxis(b);c._showPolygonGraphic(b,a)}),this.view.on("key-down",function(a){var l=b.vertices.slice(0),f=e&&"cursor-update"===e.type;"Control"!==a.key||k?"z"===a.key?(a.stopPropagation(),b.canUndo()&&b.undo()):"r"===a.key&&(a.stopPropagation(),b.canRedo()&&b.redo()):(k=!0,f&&c._snapLastVertexToAxis(l),c._showPolygonGraphic(l,f))}),
this.view.on("key-up",function(a){var l=b.vertices.slice(0),f=e&&"cursor-update"===e.type;"Control"===a.key&&(k=!1,l.pop(),l.push([g.x,g.y]),c._showPolygonGraphic(l,f))}),this.view.on("pointer-down",function(b){c.view.hitTest(b).then(function(a){a=a.results;a.length&&a[0].graphic&&0===c._vertexGraphics.indexOf(a[0].graphic)&&b.stopPropagation()})}),this.view.on("click",function(a){c.view.hitTest(a).then(function(l){l=l.results;l.length&&l[0].graphic&&0===c._vertexGraphics.indexOf(l[0].graphic)&&2<
c._vertexGraphics.length&&(a.stopPropagation(),e&&"cursor-update"===e.type&&b.vertices.pop(),b.complete())})}),this.view.on("pointer-move",function(b){c.view.hitTest(b).then(function(b){f=c._displayCrosshairCursor()})})],l=new t({type:"create",complete:function(){c._clearGraphics();c._graphics.remove(c.graphic);f&&f.reset();d.forEach(function(c){return c.remove()});l.emit("complete")},cancel:function(){c._clearGraphics();c._graphics.remove(c.graphic);f&&f.reset();d.forEach(function(c){return c.remove()});
l.emit("cancel")}});return l};d.prototype._createPolylineOperation=function(a){var c=this,b=this.draw.create("polyline",a),g=new q.Point,f=null,e=null,k=!1,d=[b.on("vertex-add",function(b){var a=b.vertices;f=b;k&&c._snapLastVertexToAxis(a);c._showPolylineGraphic(a,!1)}),b.on("vertex-remove",function(b){var a=b.vertices;f=b;k&&c._snapLastVertexToAxis(a);c._showPolylineGraphic(a,!1)}),b.on("vertex-update",function(b){var a=b.vertices;f=b;k&&c._snapLastVertexToAxis(a);c._showPolylineGraphic(a,!1)}),
b.on("cursor-update",function(b){var a=b.vertices,l=b.native;f=b;c.view.toMap(l.x,l.y,g);k&&c._snapLastVertexToAxis(a);c._showPolylineGraphic(a,!0)}),b.on("draw-complete",function(b){c._graphics.remove(c.graphic);c._set("graphic",new n(h.createPolyline([b.vertices],c.view),c.polylineSymbol));l&&l.complete()}),b.on("undo",function(b){b=b.vertices;var a=f&&"cursor-update"===f.type;b.length?(k&&c._snapLastVertexToAxis(b),c._showPolylineGraphic(b,a)):c._clearGraphics()}),b.on("redo",function(b){b=b.vertices;
var a=f&&"cursor-update"===f.type;k&&c._snapLastVertexToAxis(b);c._showPolylineGraphic(b,a)}),this.view.on("key-down",function(a){var l=b.vertices.slice(0),e=f&&"cursor-update"===f.type;"Control"!==a.key||k?"z"===a.key?(a.stopPropagation(),b.canUndo()&&b.undo()):"r"===a.key&&(a.stopPropagation(),b.canRedo()&&b.redo()):(k=!0,e&&c._snapLastVertexToAxis(l),c._showPolylineGraphic(l,e))}),this.view.on("key-up",function(a){var l=b.vertices.slice(0),e=f&&"cursor-update"===f.type;"Control"===a.key&&(k=!1,
l.pop(),l.push([g.x,g.y]),c._showPolylineGraphic(l,e))}),this.view.on("pointer-move",function(b){c.view.hitTest(b).then(function(b){e=c._displayCrosshairCursor()})})],l=new t({type:"create",complete:function(){c._clearGraphics();c._graphics.remove(c.graphic);e&&e.reset();d.forEach(function(c){return c.remove()});l.emit("complete")},cancel:function(){c._clearGraphics();c._graphics.remove(c.graphic);e&&e.reset();d.forEach(function(c){return c.remove()});l.emit("cancel")}});return l};d.prototype._createRectangleOperation=
function(a){var c=this,b=this.draw.create("rectangle",a),g=null,f=!1,e=!1,k=[b.on("vertex-add",function(b){c._showRectangleGraphic(b.vertices,e,f)}),b.on("cursor-update",function(b){c._showRectangleGraphic(b.vertices,e,f)}),b.on("draw-complete",function(b){c._graphics.remove(c.graphic);b=b.vertices.slice(0);if(1===b.length){e=f=!1;var a=c.view.toScreen(b[0][0],b[0][1],null);b=c.view.toMap(a.x-c._defaultSegmentOffset,a.y+c._defaultSegmentOffset);a=c.view.toMap(a.x+c._defaultSegmentOffset,a.y-c._defaultSegmentOffset);
b=[[b.x,b.y],[a.x,a.y]]}b=f?h.createSquare(b,c.view,e):h.createRectangle(b,c.view,e);c._set("graphic",new n(b,c.polygonSymbol));d&&d.complete()}),this.view.on("key-down",function(a){"Control"!==a.key||f?"Alt"!==a.key||e||(e=!0,c._showRectangleGraphic(b.vertices,e,f)):(f=!0,c._showRectangleGraphic(b.vertices,e,f))}),this.view.on("key-up",function(a){"Control"===a.key?(f=!1,c._showRectangleGraphic(b.vertices,e,f)):"Alt"===a.key&&(e=!1,c._showRectangleGraphic(b.vertices,e,f))}),this.view.on("pointer-move",
function(b){c.view.hitTest(b).then(function(b){g=c._displayCrosshairCursor()})})],d=new t({type:"create",complete:function(){c._clearGraphics();c._graphics.remove(c.graphic);g&&g.reset();k.forEach(function(b){return b.remove()});d.emit("complete")},cancel:function(){c._clearGraphics();c._graphics.remove(c.graphic);g&&g.reset();k.forEach(function(b){return b.remove()});d.emit("cancel")}});return d};d.prototype._createMultipointOperation=function(a){var c=this;a=this.draw.create("multipoint",a);var b=
null,g=[a.on("vertex-add",function(b){c._showMultipointGraphic(b.vertices)}),a.on("vertex-remove",function(b){c._showMultipointGraphic(b.vertices)}),a.on("vertex-update",function(b){c._showMultipointGraphic(b.vertices)}),a.on("cursor-update",function(b){c._showMultipointGraphic(b.vertices)}),a.on("draw-complete",function(b){c._graphics.remove(c.graphic);c._set("graphic",new n(h.createMultipoint(b.vertices,c.view),c.pointSymbol));f&&f.complete()}),this.view.on("pointer-move",function(a){c.view.hitTest(a).then(function(a){b=
c._displayCrosshairCursor()})})],f=new t({type:"create",complete:function(){c._clearGraphics();c._graphics.remove(c.graphic);b&&b.reset();g.forEach(function(b){return b.remove()});f.emit("complete")},cancel:function(){c._clearGraphics();c._graphics.remove(c.graphic);b&&b.reset();g.forEach(function(b){return b.remove()});f.emit("cancel")}});return f};d.prototype._createCircleOperation=function(a){var c=this,b=this.draw.create("circle",a),g=null,f=!1,e=!1,k=[b.on("vertex-add",function(b){c._showCircleGraphic(b.vertices,
e,f)}),b.on("cursor-update",function(b){c._showCircleGraphic(b.vertices,e,f)}),b.on("draw-complete",function(a){c._graphics.remove(c.graphic);a=a.vertices.slice(0);if(1===a.length){f=!1;e=!0;var l=c.view.toScreen(a[0][0],a[0][1],null),l=new q.ScreenPoint({x:l.x+c._defaultSegmentOffset,y:l.y});a.push(b.getCoordsFromScreenPoint(l))}a=f?h.createEllipse(a,c.view,e):h.createCircle(a,c.view,e);c._set("graphic",new n(a,c.polygonSymbol));d&&d.complete()}),this.view.on("key-down",function(a){"Control"!==a.key||
f?"Alt"!==a.key||e||(e=!0,c._showCircleGraphic(b.vertices,e,f)):(f=!0,c._showCircleGraphic(b.vertices,e,f))}),this.view.on("key-up",function(a){"Control"===a.key?(f=!1,c._showCircleGraphic(b.vertices,e,f)):"Alt"===a.key&&(e=!1,c._showCircleGraphic(b.vertices,e,f))}),this.view.on("pointer-move",function(b){c.view.hitTest(b).then(function(b){g=c._displayCrosshairCursor()})})],d=new t({type:"create",complete:function(){c._clearGraphics();c._graphics.remove(c.graphic);g&&g.reset();k.forEach(function(b){return b.remove()});
d.emit("complete")},cancel:function(){c._clearGraphics();c._graphics.remove(c.graphic);g&&g.reset();k.forEach(function(b){return b.remove()});d.emit("cancel")}});return d};d.prototype._createEllipseOperation=function(a){var c=this,b=this.draw.create("ellipse",a),g=null,f=!1,e=!1,k=[b.on("vertex-add",function(b){c._showEllipseGraphic(b.vertices,e,f)}),b.on("cursor-update",function(b){c._showEllipseGraphic(b.vertices,e,f)}),b.on("draw-complete",function(a){c._graphics.remove(c.graphic);a=a.vertices.slice(0);
if(1===a.length){e=f=!0;var g=c.view.toScreen(a[0][0],a[0][1],null),g=new q.ScreenPoint({x:g.x+c._defaultSegmentOffset,y:g.y});a.push(b.getCoordsFromScreenPoint(g))}a=f?h.createCircle(a,c.view,e):h.createEllipse(a,c.view,e);c._set("graphic",new n(a,c.polygonSymbol));d&&d.complete()}),this.view.on("key-down",function(a){"Control"!==a.key||f?"Alt"!==a.key||e||(e=!0,c._showEllipseGraphic(b.vertices,e,f)):(f=!0,c._showEllipseGraphic(b.vertices,e,f))}),this.view.on("key-up",function(a){"Control"===a.key?
(f=!1,c._showEllipseGraphic(b.vertices,e,f)):"Alt"===a.key&&(e=!1,c._showEllipseGraphic(b.vertices,e,f))}),this.view.on("pointer-move",function(b){c.view.hitTest(b).then(function(b){g=c._displayCrosshairCursor()})})],d=new t({type:"create",complete:function(){c._clearGraphics();c._graphics.remove(c.graphic);g&&g.reset();k.forEach(function(b){return b.remove()});d.emit("complete")},cancel:function(){c._clearGraphics();c._graphics.remove(c.graphic);g&&g.reset();k.forEach(function(b){return b.remove()});
d.emit("cancel")}});return d};d.prototype._createTriangleOperation=function(a){var c=this,b=this.draw.create("triangle",a),g=null,f=!1,e=!1,k=[b.on("vertex-add",function(b){c._showTriangleGraphic(b.vertices,e,f)}),b.on("cursor-update",function(b){c._showTriangleGraphic(b.vertices,e,f)}),b.on("draw-complete",function(a){c._graphics.remove(c.graphic);a=a.vertices.slice(0);if(1===a.length){e=f=!0;var g=c.view.toScreen(a[0][0],a[0][1],null),g=new q.ScreenPoint({x:g.x+c._defaultSegmentOffset,y:g.y});a.push(b.getCoordsFromScreenPoint(g))}c._set("graphic",
new n(h.createTriangle(a,c.view,e,f),c.polygonSymbol));d&&d.complete()}),this.view.on("key-down",function(a){"Control"!==a.key||f?"Alt"!==a.key||e||(e=!0,c._showTriangleGraphic(b.vertices,e,f)):(f=!0,c._showTriangleGraphic(b.vertices,e,f))}),this.view.on("key-up",function(a){"Control"===a.key?(f=!1,c._showTriangleGraphic(b.vertices,e,f)):"Alt"===a.key&&(e=!1,c._showTriangleGraphic(b.vertices,e,f))}),this.view.on("pointer-move",function(b){c.view.hitTest(b).then(function(b){g=c._displayCrosshairCursor()})})],
d=new t({type:"create",complete:function(){c._clearGraphics();c._graphics.remove(c.graphic);g&&g.reset();k.forEach(function(b){return b.remove()});d.emit("complete")},cancel:function(){c._clearGraphics();c._graphics.remove(c.graphic);g&&g.reset();k.forEach(function(b){return b.remove()});d.emit("cancel")}});return d};d.prototype._updatePointOperation=function(a,c){var b=this,g=!1,f=!1,e=null,d=new n(a,this.updatePointSymbol);this._graphics.add(d);this._set("graphic",d.clone());var h=[this.view.on("click",
function(c){b.view.hitTest(c).then(function(b){b=b.results;b.length&&b[0].graphic&&b[0].graphic===d||(d.geometry!==a?l&&l.complete():l&&l.cancel())})}),this.view.on("pointer-down",function(a){f=!1;g=!0;b.view.hitTest(a).then(function(b){g=!(!b.results||!b.results[0]||b.results[0].graphic!==d)})}),this.view.on("pointer-move",function(a){f=!0;b.view.hitTest(a).then(function(a){a=a.results;a.length&&a[0].graphic?a[0].graphic===d?e=b._displayPointerCursor():(e&&e.reset(),e=null):(e&&e.reset(),e=null)})}),
this.view.on("pointer-up",function(a){g&&(a.stopPropagation(),g=!1,f&&(f=!1,a=b.view.toMap(a.x,a.y),d.set("geometry",a),b.graphic.set("geometry",a)))}),this.view.on("drag",function(a){g&&(a.stopPropagation(),d.set("geometry",b.view.toMap(a.x,a.y)))})],l=new t({type:"update",complete:function(){b._graphics.remove(d);h.forEach(function(b){return b.remove()});e&&e.reset();b.graphic.set("geometry",d.geometry);l.emit("complete")},cancel:function(){b._graphics.remove(d);h.forEach(function(b){return b.remove()});
e&&e.reset();b.graphic.set("geometry",d.geometry);l.emit("cancel")}});return l};d.prototype._updatePolygonOperation=function(a,c){var b=this;c=h.getVerticesForPolygon(a);var d=!1,f=!1,e=null,k=new n(a,this.updatePolygonSymbol);this._graphics.add(k);this._set("graphic",k.clone());var m=new B({pointSymbol:this.vertexSymbol,pointHoverSymbol:this.hoverVertexSymbol,selectedPointSymbol:this.selectedVertexSymbol,layer:this._graphics,view:this.view}),l=m.update({vertices:c,handles:{onMoveStart:function(a){k.set("geometry",
new q.Polygon({rings:a.vertices,spatialReference:b.view.spatialReference}))},onMove:function(a){k.set("geometry",new q.Polygon({rings:a.vertices,spatialReference:b.view.spatialReference}))},onMoveStop:function(a){a=new q.Polygon({rings:a.vertices,spatialReference:b.view.spatialReference});b.graphic.set("geometry",a);k.set("geometry",a)},onSelect:function(b){},onDeselect:function(b){}}}),p=[this.view.on("click",function(c){b.view.hitTest(c).then(function(b){if(b.results.length&&b.results[0].graphic&&
(b=b.results[0].graphic,b===k||-1<m.graphics.indexOf(b)))return;k.geometry!==a?r&&r.complete():r&&r.cancel()})}),this.view.on("pointer-down",function(a){d=f=!1;b.view.hitTest(a).then(function(b){b=b.results;d=!(!b.length||b[0].graphic!==k)})}),this.view.on("pointer-move",function(a){f=!0;b.view.hitTest(a).then(function(a){a=a.results;if(a.length&&a[0].graphic){a=a[0].graphic;var c=m.graphics;a===k||-1<c.indexOf(a)?e=b._displayPointerCursor():(e&&e.reset(),e=null)}else e&&e.reset(),e=null})}),this.view.on("pointer-up",
function(a){d&&f&&(a=h.getVerticesForPolygon(k.geometry),b.graphic.set("geometry",k.geometry),m.set("vertices",a),m.refresh())}),this.view.on("drag",function(a){d&&(a.stopPropagation(),a=h.movePolygon(b.graphic.geometry,b.view,a.x-a.origin.x,a.y-a.origin.y),k.set("geometry",a),m.reset())})],r=new t({type:"update",complete:function(){m.destroy();b._graphics.remove(k);l.remove();p.forEach(function(b){return b.remove()});e&&e.reset();var a=h.getVerticesForPolygon(k.geometry);b.graphic.set("geometry",
h.createPolygon(a,b.view));r.emit("complete")},cancel:function(){m.destroy();b._graphics.remove(k);l.remove();p.forEach(function(b){return b.remove()});e&&e.reset();var a=h.getVerticesForPolygon(k.geometry);b.graphic.set("geometry",h.createPolygon(a,b.view));r.emit("cancel")}});return r};d.prototype._updatePolylineOperation=function(a,c){var b=this;c=h.getVerticesForPolyline(a);var d=!1,f=!1,e=null,k=new n(a,this.updatePolylineSymbol);this._graphics.add(k);this._set("graphic",k.clone());var m=new B({pointSymbol:this.vertexSymbol,
pointHoverSymbol:this.hoverVertexSymbol,selectedPointSymbol:this.selectedVertexSymbol,layer:this._graphics,view:this.view}),l=m.update({vertices:c,handles:{onMoveStart:function(a){k.set("geometry",new q.Polyline({paths:a.vertices,spatialReference:b.view.spatialReference}))},onMove:function(a){k.set("geometry",new q.Polyline({paths:a.vertices,spatialReference:b.view.spatialReference}))},onMoveStop:function(a){a=new q.Polyline({paths:a.vertices,spatialReference:b.view.spatialReference});b.graphic.set("geometry",
a);k.set("geometry",a)},onSelect:function(a){},onDeselect:function(a){}}}),p=[this.view.on("click",function(c){b.view.hitTest(c).then(function(b){if(b.results.length&&b.results[0].graphic&&(b=b.results[0].graphic,b===k||-1<m.graphics.indexOf(b)))return;k.geometry!==a?r&&r.complete():r&&r.cancel()})}),this.view.on("pointer-down",function(a){d=f=!1;b.view.hitTest(a).then(function(a){a=a.results;d=!(!a.length||a[0].graphic!==k)})}),this.view.on("pointer-move",function(a){f=!0;b.view.hitTest(a).then(function(a){a=
a.results;if(a.length&&a[0].graphic){a=a[0].graphic;var c=m.graphics;a===k||-1<c.indexOf(a)?e=b._displayPointerCursor():(e&&e.reset(),e=null)}else e&&e.reset(),e=null})}),this.view.on("pointer-up",function(a){d&&f&&(a=h.getVerticesForPolyline(k.geometry),b.graphic.set("geometry",k.geometry),m.set("vertices",a),m.refresh())}),this.view.on("drag",function(a){d&&(a.stopPropagation(),a=h.movePolyline(b.graphic.geometry,b.view,a.x-a.origin.x,a.y-a.origin.y),k.set("geometry",a),m.reset())})],r=new t({type:"update",
complete:function(){m.destroy();b._graphics.remove(k);l.remove();p.forEach(function(a){return a.remove()});e&&e.reset();var a=h.getVerticesForPolyline(k.geometry);b.graphic.set("geometry",h.createPolyline(a,b.view));r.emit("complete")},cancel:function(){m.destroy();b._graphics.remove(k);l.remove();p.forEach(function(a){return a.remove()});e&&e.reset();var a=h.getVerticesForPolyline(k.geometry);b.graphic.set("geometry",h.createPolyline(a,b.view));r.emit("cancel")}});return r};d.prototype._showPolygonGraphic=
function(a,c){var b=this;this._graphics.remove(this.graphic);this._clearGraphics();var d=2<a.length?h.createPolygon([a],this.view):h.createPolyline([a],this.view);this._set("graphic",new n(d,this.polygonSymbol));if(c){var f=a.map(function(a){return Array.apply([],a)});c=f.pop();c=[f[f.length-1],c];2<a.length&&(this._fillGraphic=new n(h.createPolygon([a],this.view),this.activeFillSymbol),this._graphics.add(this._fillGraphic));1<a.length&&(this._lineGraphic=new n(h.createPolyline([f],this.view),this.polylineSymbol),
this._graphics.add(this._lineGraphic),this._activeLineGraphic=new n(h.createPolyline(c,this.view),this.activeLineSymbol),this._graphics.add(this._activeLineGraphic));f.forEach(function(a,c){c=c===f.length-1?b.activePointSymbol:b.pointSymbol;a=new n({geometry:new q.Point({x:a[0],y:a[1],spatialReference:b.view.spatialReference}),symbol:c});b._vertexGraphics.push(a);b._graphics.add(a)})}else 2<a.length&&(this._fillGraphic=new n(d,this.activeFillSymbol),this._graphics.add(this._fillGraphic)),this._lineGraphic=
new n(h.createPolyline([a],this.view),this.polylineSymbol),this._graphics.add(this._lineGraphic),a.forEach(function(c,f){f=f===a.length-1?b.activePointSymbol:b.pointSymbol;c=new n({geometry:new q.Point({x:c[0],y:c[1],spatialReference:b.view.spatialReference}),symbol:f});b._vertexGraphics.push(c);b._graphics.add(c)})};d.prototype._showPolylineGraphic=function(a,c){var b=this;this._graphics.remove(this.graphic);this._clearGraphics();this._set("graphic",new n(h.createPolyline([a],this.view),this.polylineSymbol));
if(c){var d=a.map(function(a){return Array.apply([],a)});c=d.pop();c=[d[d.length-1],c];1<a.length&&(this._lineGraphic=new n(h.createPolyline(d,this.view),this.polylineSymbol),this._graphics.add(this._lineGraphic),this._activeLineGraphic=new n(h.createPolyline(c,this.view),this.activeLineSymbol),this._graphics.add(this._activeLineGraphic));d.forEach(function(a,c){c=c===d.length-1?b.activePointSymbol:b.pointSymbol;a=new n({geometry:new q.Point({x:a[0],y:a[1],spatialReference:b.view.spatialReference}),
symbol:c});b._vertexGraphics.push(a);b._graphics.add(a)})}else this._lineGraphic=new n(h.createPolyline([a],this.view),this.polylineSymbol),this._graphics.add(this._lineGraphic),a.forEach(function(c,d){d=d===a.length-1?b.activePointSymbol:b.pointSymbol;c=new n({geometry:new q.Point({x:c[0],y:c[1],spatialReference:b.view.spatialReference}),symbol:d});b._vertexGraphics.push(c);b._graphics.add(c)})};d.prototype._showRectangleGraphic=function(a,c,b){this._graphics.remove(this.graphic);this._clearGraphics();
2>a.length||(a=b?h.createSquare(a,this.view,c):h.createRectangle(a,this.view,c),this._toggleCenterGraphic(a),this._set("graphic",new n(a,this.polygonSymbol)),this._graphics.add(this.graphic))};d.prototype._showMultipointGraphic=function(a){this._graphics.remove(this.graphic);this._set("graphic",new n(h.createMultipoint(a,this.view),this.pointSymbol));this._graphics.add(this.graphic)};d.prototype._showCircleGraphic=function(a,c,b){this._graphics.remove(this.graphic);this._clearGraphics();2>a.length||
(a=b?h.createEllipse(a,this.view,c):h.createCircle(a,this.view,c),this._toggleCenterGraphic(a),this._set("graphic",new n(a,this.polygonSymbol)),this._graphics.add(this.graphic))};d.prototype._showEllipseGraphic=function(a,c,b){this._graphics.remove(this.graphic);this._clearGraphics();2>a.length||(a=b?h.createCircle(a,this.view,c):h.createEllipse(a,this.view,c),this._toggleCenterGraphic(a),this._set("graphic",new n(a,this.polygonSymbol)),this._graphics.add(this.graphic))};d.prototype._showTriangleGraphic=
function(a,c,b){this._graphics.remove(this.graphic);this._clearGraphics();2>a.length||(a=h.createTriangle(a,this.view,c,b),this._toggleCenterGraphic(a),this._set("graphic",new n(a,this.polygonSymbol)),this._graphics.add(this.graphic))};d.prototype._toggleCenterGraphic=function(a){this._graphics.remove(this._centerGraphic);this._centerGraphic=null;a&&a.extent&&a.extent.center&&(this._centerGraphic=new n(a.extent.center,this._centerSymbol),this._graphics.add(this._centerGraphic))};d.prototype._clearGraphics=
function(){this._toggleCenterGraphic();this._graphics.remove(this._fillGraphic);this._fillGraphic=null;this._graphics.remove(this._lineGraphic);this._lineGraphic=null;this._graphics.remove(this._activeLineGraphic);this._activeLineGraphic=null;this._graphics.removeMany(this._vertexGraphics);this._vertexGraphics=[]};d.prototype._snapLastVertexToAxis=function(a){if(!(2>a.length)){var c=a.pop(),b=a[a.length-1],c=this.view.toScreen(c[0],c[1],null),b=this.view.toScreen(b[0],b[1],null),d=Math.abs(c.x-b.x),
f=Math.abs(c.y-b.y),c=this.view.toMap(d>f?c.x:b.x,d>f?b.y:c.y);a.push([c.x,c.y])}};d.prototype._displayCrosshairCursor=function(){var a=this;"crosshair"!==this.view.container.style.cursor&&(this.view.container.style.cursor="crosshair");return new C({reset:function(){"default"!==a.view.container.style.cursor&&(a.view.container.style.cursor="default")}})};d.prototype._displayPointerCursor=function(){var a=this;"pointer"!==this.view.container.style.cursor&&(this.view.container.style.cursor="pointer");
return new C({reset:function(){"default"!==a.view.container.style.cursor&&(a.view.container.style.cursor="default")}})};p([m.property()],d.prototype,"_operationHandle",void 0);p([m.property()],d.prototype,"activeFillSymbol",void 0);p([m.property()],d.prototype,"activeLineSymbol",void 0);p([m.property()],d.prototype,"activePointSymbol",void 0);p([m.property({readOnly:!0})],d.prototype,"draw",void 0);p([m.property({readOnly:!0})],d.prototype,"graphic",void 0);p([m.property()],d.prototype,"hoverVertexSymbol",
void 0);p([m.property()],d.prototype,"layer",void 0);p([m.property()],d.prototype,"pointSymbol",void 0);p([m.property()],d.prototype,"polygonSymbol",void 0);p([m.property()],d.prototype,"polylineSymbol",void 0);p([m.property()],d.prototype,"selectedVertexSymbol",void 0);p([m.property({dependsOn:["view.ready","_operationHandle"],readOnly:!0})],d.prototype,"state",null);p([m.property()],d.prototype,"view",void 0);return d=p([m.subclass("esri.widgets.Sketch.SketchViewModel")],d)}(m.declared(v,x))});