// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../../core/tsSupport/extendsHelper ../../../../../../core/Error ../../../../../../core/Logger ../../../../../../core/maybe ../../../../../../core/screenUtils ../../../../../../core/libs/gl-matrix-2/mat2d ../../../../../../core/libs/gl-matrix-2/mat2df32 ../../../../../../core/libs/gl-matrix-2/vec2 ../../../../../../core/libs/gl-matrix-2/vec2f32 ../../../../../../symbols/cim/enums ../../color ../../number ../../materialKey/MaterialKey ./util ./WGLBaseMarkerTemplate ./WGLDynamicMeshTemplate ../../util/Result".split(" "),
function(r,x,z,D,E,F,k,A,G,q,B,H,n,l,C,g,I,J,K){Object.defineProperty(x,"__esModule",{value:!0});var L=3.14159265359/180,b=B.vec2f32.create(),p=G.mat2df32.create(),M=E.getLogger("esri.views.2d.engine.webgl.WGLDynamicMarkerTemplate");r=function(r){function h(b,d){var c=r.call(this,d)||this;c._cimMarkerLayer=d;g.isFunction(d.color)?c._dynamicPropertyMap.set("_fillColor",function(c,a,b){return n.premultiplyAlphaRGBA(d.color(c,a,b))}):c._fillColor=n.premultiplyAlphaRGBA(d.color);g.isFunction(d.outlineColor)?
c._dynamicPropertyMap.set("_outlineColor",function(c,a,b){return n.premultiplyAlphaRGBA(d.outlineColor(c,a,b))}):c._outlineColor=n.premultiplyAlphaRGBA(d.outlineColor);g.isFunction(d.size)?c._dynamicPropertyMap.set("_size",function(c,a,b){return k.pt2px(d.size(c,a,b))}):c._size=k.pt2px(d.size);g.isFunction(d.scaleX)?c._dynamicPropertyMap.set("_scaleX",d.scaleX):c._scaleX=d.scaleX;g.isFunction(d.offsetX)?c._dynamicPropertyMap.set("xOffset",function(c,a,b){return k.pt2px(d.offsetX(c,a,b))}):c.xOffset=
k.pt2px(d.offsetX);g.isFunction(d.offsetY)?c._dynamicPropertyMap.set("yOffset",function(c,a,b){return k.pt2px(d.offsetY(c,a,b))}):c.yOffset=k.pt2px(d.offsetY);g.isFunction(d.outlineWidth)?c._dynamicPropertyMap.set("_outlineWidth",function(c,a,b){return k.pt2px(d.outlineWidth(c,a,b))}):c._outlineWidth=k.pt2px(d.outlineWidth);g.isFunction(d.rotation)?c._dynamicPropertyMap.set("_angle",d.rotation):c._angle=d.rotation;c._scaleFactor=F.unwrapOr(d.scaleFactor,1);c._bitSet=(d.alignment===H.Alignment.MAP?
1:0)|(d.colorLocked?1:0)<<1|(d.scaleSymbolsProportionally?1:0)<<3;c._materialKey=C.createMaterialKey(c.geometryType,b,!1);return c}z(h,r);h.fromCIMMarker=function(b,d){return new h(b,d)};h.prototype.bindFeature=function(g,d,c){var r=this;this._dynamicPropertyMap.forEach(function(a,b){r[b]=a(g,d,c)});var a=this._cimMarkerLayer.materialHash,a="function"===typeof a?a(g,d,c):a;if((a=this._materialCache.get(a))&&K.ok(a.spriteMosaicItem)&&a.spriteMosaicItem){var a=a.spriteMosaicItem,h=this._cimMarkerLayer.sizeRatio,
u=a.width/a.height*this._scaleX,v=this._cimMarkerLayer.rotateClockwise?this._angle:-this._angle,e=this._size,t=e*u,n=this.xOffset*this._scaleFactor,y=this.yOffset*this._scaleFactor,f=this._cimMarkerLayer.scaleSymbolsProportionally&&this._cimMarkerLayer.frameHeight?this._size/k.pt2px(this._cimMarkerLayer.frameHeight):1,x=this._outlineWidth*f,z=k.pt2px(this._cimMarkerLayer.referenceSize),m=0,f=0,w=this._cimMarkerLayer.anchorPoint;w&&(this._cimMarkerLayer.isAbsoluteAnchorPoint?this._size&&(m=-w.x/(this._size*
u),f=w.y/this._size):(m=w.x,f=w.y));this._sizeOutlineWidth=l.i8888to32(Math.round(Math.sqrt(256*t)),Math.round(Math.sqrt(256*e)),Math.round(Math.sqrt(256*x)),Math.round(Math.sqrt(256*z)));A.mat2d.identity(p);A.mat2d.translate(p,p,B.vec2f32.fromValues(n,-y));v&&A.mat2d.rotate(p,p,L*v);u=a.rect.x;v=a.rect.y;n=u+a.rect.width;y=v+a.rect.height;m=.5-((.5+m)*a.width+1)/a.rect.width;f=.5-((.5+f)*a.height+1)/a.rect.height;t=t*h*this._scaleFactor;e=e*h*this._scaleFactor;h=Math.round(64*h);t*=a.rect.width/
a.width;e*=a.rect.height/a.height;m=(m-.5)*t;f=(f-.5)*e;this._bitestAndDistRatio=l.i8888to32(0,0,this._bitSet,h);q.vec2.set(b,m,f);q.vec2.transformMat2d(b,b,p);this._offsetUpperLeft=l.i1616to32(16*b[0],16*b[1]);this._texUpperLeft=l.i1616to32(u,v);q.vec2.set(b,m+t,f);q.vec2.transformMat2d(b,b,p);this._offsetUpperRight=l.i1616to32(16*b[0],16*b[1]);this._texUpperRight=l.i1616to32(n,v);q.vec2.set(b,m,f+e);q.vec2.transformMat2d(b,b,p);this._offsetBottomLeft=l.i1616to32(16*b[0],16*b[1]);this._texBottomLeft=
l.i1616to32(u,y);q.vec2.set(b,m+t,f+e);q.vec2.transformMat2d(b,b,p);this._offsetBottomRight=l.i1616to32(16*b[0],16*b[1]);this._texBottomRight=l.i1616to32(n,y);e=C.MarkerMaterialKey.load(this._materialKey);e.sdf=a.sdf;e.pattern=!0;e.textureBinding=a.textureBinding;this._materialKey=e.data}else M.error(D("mapview-cim","Encountered an error when binding feature"))};return h}(I.default(J.default));x.default=r});