// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("require ../../chunks/tslib.es6 ../../core/arrayUtils ../../core/maybe ../../core/uid ../../core/accessorSupport/decorators/property ../../core/has ../../core/Logger ../../core/accessorSupport/decorators/subclass ../Widget ../../chunks/componentsUtils ./globalCss ./LabeledSwitch ./legacyIcon ./widgetUtils ./decorators/messageBundle ./jsxFactory ./SnappingControls/SnappingControlsViewModel ./SnappingControls/VisibleElements".split(" "),function(l,f,p,r,u,g,e,G,v,w,x,y,n,z,H,A,d,B,t){var C=z.legacyIcon.vertexGps;
e=class extends w{constructor(a,b){super(a,b);this._layerListFilter=this._defaultViewModel=null;this.iconClass=C;this.icon=null;this.layerListOpen=!0;this.messages=null;this.visibleElements=new t;this._enableSnappingSwitchChange=h=>{this.snappingOptions.enabled=h};this._featureEnabledSwitchChange=h=>{this.snappingOptions.featureEnabled=h};this._selfEnabledSwitchChange=h=>{this.snappingOptions.selfEnabled=h};this._onToggleLayersButtonClick=h=>{this.viewModel.toggleSnappingForAllLayers(!this.viewModel.allLayersEnabled);
requestAnimationFrame(()=>h.target.setFocus())};const {snappingOptions:c,view:m,viewModel:k}=a;this.viewModel=k??(this._defaultViewModel=new B({snappingOptions:c,view:m}))}normalizeCtorArgs(a){const {snappingOptions:b,view:c,viewModel:m,...k}=a;return k}destroy(){this.viewModel!==this._defaultViewModel&&(this._defaultViewModel=r.destroyMaybe(this._defaultViewModel))}loadDependencies(){return Promise.all([x.loadCalciteComponents({accordion:()=>new Promise((a,b)=>l(["../../chunks/calcite-accordion"],
a,b)),"accordion-item":()=>new Promise((a,b)=>l(["../../chunks/calcite-accordion-item"],a,b)),action:()=>new Promise((a,b)=>l(["../../chunks/calcite-action"],a,b)),block:()=>new Promise((a,b)=>l(["../../chunks/calcite-block"],a,b)),button:()=>new Promise((a,b)=>l(["../../chunks/calcite-button"],a,b)),icon:()=>new Promise((a,b)=>l(["../../chunks/calcite-icon"],a,b)),input:()=>new Promise((a,b)=>l(["../../chunks/calcite-input"],a,b)),list:()=>new Promise((a,b)=>l(["../../chunks/calcite-list"],a,b)),
"list-item":()=>new Promise((a,b)=>l(["../../chunks/calcite-list-item"],a,b))}),n.loadLabeledSwitchComponents()])}get label(){return this.messages?.widgetLabel??""}set label(a){this._overrideIfSome("label",a)}get snappingOptions(){return this.viewModel.snappingOptions}set snappingOptions(a){this.viewModel.snappingOptions=a}get view(){return this.viewModel.view}set view(a){this.viewModel.view=a}set viewModel(a){if(a!==this._get("viewModel")){if(null==this._defaultViewModel||this._defaultViewModel!==
a)this._defaultViewModel=r.destroyMaybe(this._defaultViewModel);this._set("viewModel",a)}}render(){const {label:a}=this;return d.tsx("div",{"aria-label":a,class:this.classes("esri-snapping-controls",y.globalCss.widget)},d.tsx("div",{class:"esri-snapping-controls__container"},this._renderContent()))}_renderContent(){return[this._renderToggles(),this._renderLayerList()]}_renderToggles(){const {visibleElements:a}=this;var b=[a.selfEnabledToggle?this._renderSelfEnabledToggle():null,a.featureEnabledToggle?
this._renderFeatureEnabledToggle():null].filter(p.isSome);b=[a.enabledToggle?this._renderEnabledToggle():null,0<b.length?d.tsx("div",{class:"esri-snapping-controls__nested-container"},b):null].filter(p.isSome);return 0===b.length?null:d.tsx("calcite-block",{class:"esri-snapping-controls__toggle-block",heading:a.header?this.label:"",key:"toggle-block",open:!0},b)}_renderEnabledToggle(){const {messages:a,viewModel:b}=this,{snappingOptions:c}=b;return d.tsx(n.LabeledSwitch,{checked:c.enabled,disabled:this._enabledToggleDisabled,
key:`${this.id}__enabled-toggle`,label:a.enableSnapping,onChange:this._enableSnappingSwitchChange})}_renderSelfEnabledToggle(){const {messages:a,viewModel:b}=this,{snappingOptions:c}=b;return d.tsx(n.LabeledSwitch,{checked:c.enabled&&c.selfEnabled,disabled:this._secondaryElementsDisabled,key:`${this.id}__self-enabled-toggle`,label:a.geometryGuides,onChange:this._selfEnabledSwitchChange})}_renderFeatureEnabledToggle(){const {messages:a,viewModel:b}=this,{snappingOptions:c}=b;return d.tsx(n.LabeledSwitch,
{checked:c.enabled&&c.featureEnabled,disabled:this._secondaryElementsDisabled,key:`${this.id}__feature-enabled-toggle`,label:a.featureToFeature,onChange:this._featureEnabledSwitchChange})}_renderLayerList(){if(!this.visibleElements.layerList)return null;const {messages:a,viewModel:b}=this;var c=({target:{value:k}})=>{this._layerListFilter=""===k?null:new RegExp(k,"i")};c=9<b.layerListViewModel.operationalItems.length?d.tsx("calcite-input",{class:"esri-snapping-controls__layer-list__filter",clearable:!0,
placeholder:a?.searchLayers,onCalciteInputInput:c}):null;const m=this._secondaryElementsDisabled;return d.tsx("calcite-block",{class:"esri-snapping-controls__layer-list-block",collapsible:!0,disabled:this._secondaryElementsDisabled,heading:a.snappingLayers,key:"list-block",open:this.layerListOpen&&!m,onCalciteBlockToggle:k=>this.layerListOpen=k.target.open},c,this._renderToggleLayersButton(),d.tsx("calcite-list",{class:"esri-snapping-controls__layer-list"},this._renderLayerListItemCollection(b.layerListViewModel.operationalItems,
this._layerListFilter)))}_renderLayerListItemCollection(a,b){return a.map(c=>{if(b?this._itemTitleMatchesFilter(c,b):1)return 0<c.children.length?this._renderLayerListItemGroup(c):this._renderLayerListItem(c);const m=c.children.filter(k=>this._itemTitleMatchesFilter(k,b));return 0<m.length?this._renderLayerListItemGroup(c,m):null}).toArray().filter(p.isSome)}_renderToggleLayersButton(){if(!this.visibleElements.layerListToggleLayersButton)return null;const {viewModel:{allLayersEnabled:a},messages:b}=
this,c=a?b.disableAllLayers:b.enableAllLayers;return d.tsx("calcite-button",{appearance:"transparent",class:"esri-snapping-controls__layer-list__button",label:c,name:"layer-toggle",onclick:this._onToggleLayersButtonClick,scale:"m"},c)}_renderLayerListItem(a){const {messages:{untitledLayer:b}}=this,c=a.enabled;return d.tsx("calcite-list-item",{class:"esri-snapping-controls__layer-list__item",key:`${this.id}-list-item-${a.uid}`,label:a.title||b,onCalciteListItemSelect:()=>{this._handleLayerListItemChange({checked:!c,
value:a.layer.id})}},d.tsx("calcite-icon",{icon:c?"check-square-f":"square",scale:"s",slot:"content-start"}))}_renderLayerListItemGroup(a,b){const {allChildrenEnabled:c,children:m,hasChildrenEnabled:k,title:h}=a,q=this.messages,D=h||q.untitledLayer,E=h&&""!==h?h:u.generateUID(),F=b??m;return d.tsx("calcite-list-item",{class:"esri-snapping-controls__layer-list__item",key:E},d.tsx("calcite-accordion",{appearance:"transparent",class:"esri-snapping-controls__layer-list__group"},d.tsx("calcite-accordion-item",
{expanded:!!b,heading:D,key:a.uid},d.tsx("calcite-action",{onclick:()=>{this.viewModel.toggleSnappingForLayers(a.childLayerIds,!c)},scale:"m",slot:"actions-start",text:c?q.disableAllLayers:q.enableAllLayers,textEnabled:!1},d.tsx("calcite-icon",{icon:c?"check-square-f":k?"minus-square":"square",scale:"s"})),d.tsx("calcite-list",null,this._renderLayerListItemCollection(F)))))}_itemTitleMatchesFilter(a,b){return null!=b&&b.test(a.title)}async _handleLayerListItemChange(a){a.checked?this.viewModel.enableSnappingForLayer(a.value):
this.viewModel.disableSnappingForLayer(a.value)}get _enabledToggleDisabled(){const a=this.snappingOptions;return a.enabledToggled||a.forceDisabled}get _secondaryElementsDisabled(){return this._enabledToggleDisabled||!this.snappingOptions.enabled}};f.__decorate([g.property()],e.prototype,"_defaultViewModel",void 0);f.__decorate([g.property()],e.prototype,"_layerListFilter",void 0);f.__decorate([g.property()],e.prototype,"iconClass",void 0);f.__decorate([g.property()],e.prototype,"icon",void 0);f.__decorate([g.property()],
e.prototype,"label",null);f.__decorate([g.property({type:Boolean,nonNullable:!0})],e.prototype,"layerListOpen",void 0);f.__decorate([g.property(),A.messageBundle("esri/widgets/support/SnappingControls/t9n/SnappingControls")],e.prototype,"messages",void 0);f.__decorate([g.property()],e.prototype,"snappingOptions",null);f.__decorate([g.property()],e.prototype,"view",null);f.__decorate([g.property()],e.prototype,"viewModel",null);f.__decorate([g.property({type:t,nonNullable:!0})],e.prototype,"visibleElements",
void 0);f.__decorate([g.property()],e.prototype,"_enabledToggleDisabled",null);f.__decorate([g.property()],e.prototype,"_secondaryElementsDisabled",null);return e=f.__decorate([v.subclass("esri.widgets.support.SnappingControls")],e)});