// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/assignHelper ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper dojo/i18n!./ColorSizeSlider/nls/ColorSizeSlider ../../core/maybe ../../core/accessorSupport/decorators ../../renderers/visualVariables/support/ColorSizeStop ../../renderers/visualVariables/support/ColorStop ../../renderers/visualVariables/support/SizeStop ./SmartMappingSliderBase ./ColorSizeSlider/ColorSizeSliderViewModel ./support/utils ./../support/widget".split(" "),
function(A,B,C,r,k,t,m,e,p,u,v,w,x,y,f){return function(q){function b(a){a=q.call(this,a)||this;a._bgFillId=null;a._backgroundFillColor="#e0e0e0";a._minRampFillWidth=.2;a._rampFillId=null;a._rampNode=null;a._maxRampFillWidth=1;a.label=t.widgetLabel;a.stops=null;a.viewModel=new x;a.zoomOptions=null;a._bgFillId=a.id+"-bg-fill";a._rampFillId=a.id+"-linear-gradient";return a}r(b,q);l=b;b.fromRendererResult=function(a,d){var g=a.color.visualVariable.stops,c=a.statistics,z=c.avg,c=c.stddev,h=a.renderer.authoringInfo.visualVariables[0],
b=h.minSliderValue,h=h.maxSliderValue,f=a.size.visualVariables[0];a=g.map(function(a,d){return new p({color:a.color,label:a.label,value:a.value,size:0===d?f.minSize:d===g.length-1?f.maxSize:null})});return new l({max:h,min:b,stops:a,histogramConfig:{average:z,standardDeviation:c,bins:d?d.bins:[]}})};b.prototype.updateFromRendererResult=function(a,d){var g=a.color.visualVariable.stops,c=a.statistics,b=c.avg,c=c.stddev,h=a.renderer.authoringInfo.visualVariables[0],f=h.minSliderValue,h=h.maxSliderValue,
e=a.size.visualVariables[0];a=g.map(function(a,d){return new p({color:a.color,label:a.label,value:a.value,size:0===d?e.minSize:d===g.length-1?e.maxSize:null})});this.set({max:h,min:f,stops:a,histogramConfig:{average:b,standardDeviation:c,bins:d?d.bins:[]}})};b.prototype.updateVisualVariables=function(a){var d=this;return a.map(function(a){var c=a.clone();if("size"===a.type)if(m.isSome(a.minSize)&&m.isSome(a.maxSize)){var b=d.stops;a=b[0];b=b[b.length-1];c.set({maxDataValue:b.value,minDataValue:a.value,
maxSize:b.size,minSize:a.size})}else a.stops&&c.set({stops:d.stops.map(function(a){return new v({label:a.label,size:a.size,value:a.value})})});else"color"===a.type&&c.set({stops:d.stops.map(function(a){return new u({color:a.color,label:a.label,value:a.value})})});return c})};b.prototype.render=function(){var a,d=this.label,b="disabled"===this.state,c=this.classes("esri-color-size-slider","esri-widget","esri-widget--panel",(a={},a["esri-disabled"]=b,a));return f.tsx("div",{"aria-label":d,class:c},
b?null:this.renderContent(this.renderRamp(),"esri-color-size-slider__slider-container","esri-color-size-slider__histogram-container"))};b.prototype.renderRamp=function(){var a=this._bgFillId,b=this._rampFillId,g=this.zoomOptions,c=this.viewModel.getColorStopInfo();return f.tsx("div",{afterCreate:f.storeNode,bind:this,class:"esri-color-size-slider__ramp","data-node-ref":"_rampNode"},f.tsx("svg",{xmlns:"http://www.w3.org/2000/svg"},f.tsx("defs",null,this.renderRampFillDefinition(b,c),this.renderBackgroundFillDefinition(a)),
f.tsx("rect",{x:"0",y:"0",fill:this._backgroundFillColor,height:"100%",width:"100%"}),this.renderPaths()),g?this.renderZoomCaps():null)};b.prototype.renderPaths=function(){if(this._rampNode){var a=this._rampNode,b=a.offsetHeight,b=void 0===b?0:b,a=a.offsetWidth,a=void 0===a?0:a;if(m.isSome(b)&&m.isSome(a)){var g=this.stops,c=this.values,e=this.viewModel,h=e.max,k=e.min,e=this._bgFillId,l=this._rampFillId,n=[this._maxRampFillWidth,this._minRampFillWidth];g[0].size<g[g.length-1].size&&n.reverse();b=
y.getPathForSizeStops({bottomValue:c[0],bottomWidth:n[0],max:h,min:k,pathHeight:b,pathWidth:a,topValue:c[1],topWidth:n[1]});return[f.tsx("path",{key:"background",d:b,fill:"url(#"+e+")"}),f.tsx("path",{key:"fill",d:b,fill:"url(#"+l+")"})]}}};var l;k([e.property()],b.prototype,"label",void 0);k([e.aliasOf("viewModel.stops")],b.prototype,"stops",void 0);k([e.property(),f.renderable("viewModel.hasTimeData viewModel.inputFormatFunction viewModel.inputParseFunction viewModel.labelFormatFunction viewModel.max viewModel.min viewModel.stops viewModel.values viewModel.zoomOptions".split(" "))],
b.prototype,"viewModel",void 0);k([e.aliasOf("viewModel.zoomOptions")],b.prototype,"zoomOptions",void 0);return b=l=k([e.subclass("esri.widgets.smartMapping.ColorSizeSlider")],b)}(e.declared(w.SmartMappingSliderBase))});