// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/assignHelper ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../Camera ../../../Viewpoint ../../../core/Accessor ../../../core/Error ../../../core/Handles ../../../core/Logger ../../../core/maybe ../../../core/promiseUtils ../../../core/scheduling ../../../core/screenUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators ../../../core/libs/gl-matrix-2/vec4 ../../../core/libs/gl-matrix-2/vec4f64 ../../../geometry/Extent ../../../geometry/Point ../../../geometry/support/webMercatorUtils ../camera/constraintUtils ../camera/intersectionUtils ./ConstraintsManager ./Frustum ./controllers/PointToPointAnimationController ./controllers/SurfaceCollisionCorrectionController ../support/cameraUtils ../support/PropertiesPool ../support/viewpointUtils ../webgl-engine/lib/Camera ../../animation/easing".split(" "),
function(r,C,D,L,h,t,u,w,z,M,x,N,O,q,p,P,Q,v,l,H,R,I,S,T,E,J,U,V,F,K,e,W,G,X,Y){Object.defineProperty(C,"__esModule",{value:!0});var k=O.getLogger("esri.views.3d.state.ViewStateManager");r=function(r){function b(a){a=r.call(this,a)||this;a.propertiesPool=new W.default({frustum:V.default},a);a.handles=new N;a.cameraSetByUser=!1;a.internalSetOrder=[];a.immediateGoToController=null;a.animatedGoToController=null;a.ready=!1;a.updateDevicePixelRatio=null;return a}L(b,r);Object.defineProperty(b.prototype,
"camera",{get:function(){if(!this.ready)return this._get("camera");var a=e.internalToExternal(this.view,this.view.state.camera),c=this._get("camera");return a&&c&&a.equals(c)?c:a},set:function(a){this.updatePropertyBeforeReady("camera",a)||this.setStateCamera(e.externalToInternal(this.view,a),{applyConstraints:!1})||k.error("#camera\x3d","Invalid camera",a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"center",{get:function(){return this.ready?this.view.pointsOfInterest.centerOnContent.location:
this._get("center")},set:function(a){this.updatePropertyBeforeReady("center",a)||(a?this.isCompatible(a)?this.setStateCamera(this.centerToCamera(a),{applyConstraints:!0})?this.view.pointsOfInterest.centerOnContent.update():k.error("#center\x3d","Invalid center",a):k.error("#center\x3d","Center has an incompatible spatial reference (center: "+(a.spatialReference?a.spatialReference.wkid:"none")+", view: "+this.view.spatialReference.wkid+")",a):k.error("#center\x3d","Center may not be null or undefined"))},
enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"extent",{get:function(){return this.ready?e.toExtent(this.view,this.view.state.camera,this.view.pointsOfInterest.centerOnContent.renderLocation):this._get("extent")},set:function(a){this.updatePropertyBeforeReady("extent",a)||(a?this.isCompatible(a)?this.setStateCamera(this.extentToCamera(a),{applyConstraints:!0})||k.error("#extent\x3d","Invalid extent",a):k.error("#extent\x3d","Extent has an incompatible spatial reference (extent: "+
(a.spatialReference?a.spatialReference.wkid:"none")+", view: "+this.view.spatialReference.wkid+")",a):k.error("#extent\x3d","Extent may not be null or undefined"))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"frustum",{get:function(){var a=this.propertiesPool.get("frustum");a.renderCoordsHelper=this.view.renderCoordsHelper;a.update(this.view.state.camera);return a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"hasInitialView",{get:function(){return!!this.view.get("map.initialViewProperties.viewpoint")},
enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"scale",{get:function(){if(!this.ready)return this._get("scale");var a=this.view.pointsOfInterest.centerOnContent;return e.distanceToScale(this.view,a.distance,a.location.latitude)},set:function(a){this.updatePropertyBeforeReady("scale",a)||this.setStateCamera(this.scaleToCamera(a),{applyConstraints:!0})||k.error("#scale\x3d","Invalid scale",a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"padding",{get:function(){if(!this.ready)return this._get("padding");
var a=this.view.state.camera,c=a.padding,d=a.pixelRatio,a=this._get("padding"),b=Math.round(c[0]/d),g=Math.round(c[1]/d),n=Math.round(c[2]/d),c=Math.round(c[3]/d);return null!=a&&a.top===b&&a.right===g&&a.bottom===n&&a.left===c?a:{top:b,right:g,bottom:n,left:c}},set:function(a){this.updatePropertyBeforeReady("padding",a)||(this.paddingToArray(a,this.view.state.camera.pixelRatio,A),this.view.state.updateCamera(function(a){return a.padding=A}))},enumerable:!0,configurable:!0});b.prototype.paddingToArray=
function(a,c,d){a?H.vec4.set(d,a.top||0,a.right||0,a.bottom||0,a.left||0):H.vec4.set(d,0,0,0,0);for(a=0;4>a;a++)d[a]=Math.round(d[a]*c)};Object.defineProperty(b.prototype,"screenCenter",{get:function(){var a=this.padding;return Q.createScreenPoint((this.view.width-(a.left+a.right))/2+a.left,(this.view.height-(a.top+a.bottom))/2+a.top)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"viewpoint",{get:function(){return this.ready?G.fromCamera(this.view,this.camera):this._get("viewpoint")},
set:function(a){if(!this.updatePropertyBeforeReady("viewpoint",a))if(a)if(this.isCompatible(a))this.setStateCamera(this.viewpointToCamera(a),{applyConstraints:!a.camera})||k.error("#viewpoint\x3d","Invalid viewpoint",a);else{var c=a.camera?a.camera.position:a.targetGeometry,c=c&&c.spatialReference;k.error("#viewpoint\x3d","Viewpoint has an incompatible spatial reference (viewpoint: "+(c?c.wkid:"none")+", view: "+this.view.spatialReference.wkid+")",a)}else k.error("#viewpoint\x3d","Viewpoint may not be null or undefined")},
enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"zoom",{get:function(){return this.ready?e.scaleToZoom(this.view,this.scale):this._get("zoom")},set:function(a){this.updatePropertyBeforeReady("zoom",a)||this.setStateCamera(this.zoomToCamera(a),{applyConstraints:!0})||k.error("#zoom\x3d","Invalid zoom",a)},enumerable:!0,configurable:!0});b.prototype.initialize=function(){var a=this;this.handles.add([this.view.watch("state.camera",function(c){return a.cameraChangedSync(c)},!0),v.on(this.view,
"state.events","before-camera-change",function(c){return a.updateElevation(c.camera)})]);v.once(this.view,"state.camera",function(c){return a.updateElevation(c)},!0);this.handles.add(P.addFrameTask({prepare:function(){return a.prepareFrame()}}));this.handles.add(this.view.watch("state.cameraController",function(){a.cameraSetByUser=!0;a.handles.remove(B);a.cancelImmediateGoTo()}));this.handles.add(v.on(this.view,"state.events","camera-projection-changed",function(){return a.notifyChange("scale")}))};
b.prototype.destroy=function(){this.deinit();this.handles&&(this.handles.destroy(),this.handles=null);this.propertiesPool&&(this.propertiesPool.destroy(),this.propertiesPool=null)};b.prototype.init=function(){var a=this;this.constraintsManager=new U.default({view:this.view});this.prepareFrame();var c=this.getInitialProperties();this.cameraSetByUser=!1;this._set("ready",!0);for(var d=0;d<c.length;d++){var b=c[d];this.set(b.name,b.value)}this.cameraSetByUser||((c=this.view.get("map.initialViewProperties.viewpoint")||
this.view.initialExtent)&&this.isCompatible(c)?this.setInitialView(c):"local"===this.view.state.mode&&this.handles.add(v.whenOnce(this.view.basemapTerrain,"ready",function(){a.handles.remove(B);a.setInitialView(a.view.groundExtent)}),B))};b.prototype.deinit=function(){this.ready&&(this._override("padding",this.padding),this.cancelImmediateGoTo(),this.cancelAnimatedGoTo(),this._set("ready",!1),this._clearOverride("hasInitialView"),this.internalSetOrder.length=0,this.cameraSetByUser=!1,this.handles.remove(B),
this.constraintsManager&&(this.constraintsManager.destroy(),this.constraintsManager=null))};b.prototype.goTo=function(a,c){return u(this,void 0,void 0,function(){var d;return t(this,function(b){d=D({animate:!0},c);return d.animate?[2,this.goToAnimated(a,d)]:[2,this.goToImmediate(a,d)]})})};b.prototype.debugSetCameraOnContent=function(){this.setStateCamera(J.cameraOnContentAlongViewDirection(this.view),{applyConstraints:!1})};b.prototype.step=function(a){var c=this.view.state,d=c&&this.view.state.cameraController;
d&&(c.updateCamera(function(c){d.stepController(a,c)}),d.steppingFinished&&d.finishController())};b.prototype.cancelImmediateGoTo=function(){var a=this.immediateGoToController;q.isSome(a)&&(this.immediateGoToController=null,a.abort())};b.prototype.cancelAnimatedGoTo=function(){var a=this.animatedGoToController;q.isSome(a)&&(this.animatedGoToController=null,a.abort())};b.prototype.getInitialProperties=function(){for(var a=new Set,c=[],d=0,b=Z;d<b.length;d++){var g=b[d],n=g.propertyName,g=g.overrides,
e=a.has(n),y=this._isOverridden(n);!e&&y&&c.push({name:n,value:this._get(n)});this._clearOverride(n);(e||y)&&g.forEach(function(c){return a.add(c)})}return c};b.prototype.setInitialView=function(a){if(a&&!this.cameraSetByUser)if(a instanceof w)this.setStateCamera(e.externalToInternal(this.view,a),{applyConstraints:!1});else if(a instanceof z)if(a.targetGeometry instanceof I){var c=e.fromExtent(this.view,a.targetGeometry,0,.5,0);this.setStateCamera(e.externalToInternal(this.view,c),{applyConstraints:!0})}else c=
{applyConstraints:!a.camera},a=this.viewpointToCamera(a),this.setStateCamera(a,c);else c=e.fromExtent(this.view,a,0,.5,0),this.setStateCamera(e.externalToInternal(this.view,c),{applyConstraints:!0})};b.prototype.updatePropertyBeforeReady=function(a,c){if(!this.ready){this._override(a,c);var d=this.internalSetOrder.indexOf(a);-1!==d&&(this.internalSetOrder=this.internalSetOrder.splice(d,1));c&&(this.internalSetOrder.push(a),-1!==aa.indexOf(a)&&this._override("hasInitialView",!0));return!0}return!1};
b.prototype.isCompatible=function(a){return a?a instanceof z?a.camera?this.isCompatible(a.camera):this.isCompatible(a.targetGeometry):a instanceof w?this.isCompatible(a.position):a.spatialReference&&T.canProject(a.spatialReference,this.view.spatialReference):!1};b.prototype.getPreservingHeadingTilt=function(a){void 0===a&&(a=ba);this.cameraSetByUser?(a.heading=this.camera.heading,a.tilt=this.camera.tilt):(a.heading=0,a.tilt=.5);return a};b.prototype.centerPointAtDistanceToCamera=function(a,c,d){void 0===
d&&(d=m);var b=this.getPreservingHeadingTilt();return(a=e.getObserverForPointAtDistance(this.view,b.heading,b.tilt,a,c,1))?(d.copyFrom(this.view.state.camera),d.eye=a.eye,d.center=a.center,d.up=a.up,d):null};b.prototype.centerToCamera=function(a){var c=this.view.pointsOfInterest.centerOnContent;c.update();return this.centerPointAtDistanceToCamera(a,c.distance)};b.prototype.extentToCamera=function(a){var c=this.getPreservingHeadingTilt();a=e.fromExtent(this.view,a,c.heading,c.tilt,1,ca);return e.externalToInternal(this.view,
a)};b.prototype.scaleToCamera=function(a){if(null==a)return null;var c=this.view.pointsOfInterest.centerOnContent;c.update();var d=c.renderLocation;a=e.scaleToDistance(this.view,a,c.location.latitude);return this.centerPointAtDistanceToCamera(d,a)};b.prototype.zoomToCamera=function(a){return this.scaleToCamera(e.zoomToScale(this.view,a))};b.prototype.viewpointToCamera=function(a){return(a=G.toCamera(this.view,a))?e.externalToInternal(this.view,a):null};b.prototype.setStateCamera=function(a,c){var d=
this;if(!a||!this.view.state.stopActiveCameraController())return!1;this.cameraSetByUser=!0;this.cancelImmediateGoTo();this.view.state.updateCamera(function(b){c.positionAndOrientationOnly?(b.eye=a.eye,b.center=a.center,b.up=a.up):b.copyFrom(a);c.applyConstraints&&E.applyAll(d.view,b)});c.applyConstraints||(this.view.state.cameraController=new K.SurfaceCollisionCorrectionController({view:this.view,desiredCamera:a}));return!0};b.prototype.prepareFrame=function(){var a=this.view,c=a.container,d=a.canvas;
if(c&&d){q.isSome(this.updateDevicePixelRatio)&&this.updateDevicePixelRatio();var a=this.view.pixelRatio,b=Math.round(c.clientWidth*a),c=Math.round(c.clientHeight*a);0!==b&&0!==c&&(d.width=b,d.height=c,this.view.state&&(d=this.view.state.camera,d.fullWidth!==b||d.fullHeight!==c||d.pixelRatio!==a))&&(m.copyFrom(d),m.pixelRatio!==a&&(this.paddingToArray(this.padding,a,A),m.padding=A),m.fullWidth=b,m.fullHeight=c,m.pixelRatio=a,this.view.state.camera=m)}};b.prototype.updateElevation=function(a){var c=
this.view.basemapTerrain&&this.view.basemapTerrain.spatialReference,b=this.view.renderCoordsHelper.getAltitude(a.eye),c=c?J.surfaceElevationBelowEye(this.view,a):0;a.relativeElevation=b-c};b.prototype.cameraChangedSync=function(a){a&&this.view._stage&&this.view._stage.setCamera(a)};b.prototype.createGoToCamera=function(a,c){return u(this,void 0,void 0,function(){var b,f,g,n,k,y,l,h;return t(this,function(d){switch(d.label){case 0:return[4,v.whenOnce(this,"ready",c.signal,!0)];case 1:return d.sent(),
p.throwIfAborted(c),[4,G.create(this.view,a,c.signal)];case 2:b=d.sent();f=!!(a instanceof z&&a.camera||a instanceof w);g=b.camera;if(!this.isCompatible(g))throw y=(k=(n=g.position)&&n.spatialReference)?k.wkid:"none",l=this.view.spatialReference.wkid,new x("goto:incompatible-spatialreference","Resulting camera has an incompatible spatial reference (camera: "+y+", view: "+l+")",{camera:g});h=e.externalToInternal(this.view,g);if(!h)throw new x("goto:invalid-camera","Resulting camera is invalid");return[2,
{viewpoint:b,camera:h,isFullySpecified:f}]}})})};b.prototype.cancellableGoTo=function(a,c){var b=this,f,g=function(){b.view.state.cameraController===a&&a.active&&a.asyncResult===f&&a.stopController()};return p.create(function(b,d){f={resolve:b,reject:d};a.asyncResult=f;p.onAbort(c,g)},g)};b.prototype.goToImmediate=function(a,c){return u(this,void 0,void 0,function(){var b,f,g,e=this;return t(this,function(d){this.cancelAnimatedGoTo();this.cancelImmediateGoTo();b=p.createAbortController();p.onAbort(c,
function(){return b.abort()});f=this.createGoToCamera(a,D({},c,{signal:b.signal}));g=function(){e.immediateGoToController===b&&(e.immediateGoToController=null)};this.immediateGoToController=b;return[2,f.then(function(a){g();e.setStateCamera(a.camera,{applyConstraints:!a.isFullySpecified,positionAndOrientationOnly:!0})}).catch(function(a){g();!p.isAbortError(a)&&a instanceof x&&a.message&&k.error("#goTo()","Failed to create camera from target, "+a.message[0].toLowerCase()+a.message.slice(1));throw a;
})]})})};b.prototype.goToAnimatedBeforeReady=function(a,c){return u(this,void 0,void 0,function(){var b;return t(this,function(d){switch(d.label){case 0:return this.cancelAnimatedGoTo(),b=p.createAbortController(),p.onAbort(c,function(){return b.abort()}),this.animatedGoToController=b,c=D({},c,{signal:b.signal}),[4,v.whenOnce(this.view,"ready",b.signal)];case 1:return d.sent(),this.animatedGoToController=null,[2,this.goToAnimated(a,c)]}})})};b.prototype.goToAnimated=function(a,c){return u(this,void 0,
void 0,function(){var b,f,g,e,h,l,m=this;return t(this,function(d){this.cancelAnimatedGoTo();if(!this.ready)return[2,this.goToAnimatedBeforeReady(a,c)];b=this.view.state.cameraController;b instanceof F.PointToPointAnimationController&&(b.updateStateFromViewAnimation(),b.active&&(f=b));null==f&&(f=new F.PointToPointAnimationController(this.view.state,this.view.sceneIntersectionHelper,"animation"));g=f.viewAnimation;if(q.isNone(g))return k.warn("Unreachable code in ViewStateManager"),[2];e=this.createGoToCamera(a,
c);g.update(e.then(function(a){return a.viewpoint}));if(f!==b&&!this.view.state.switchCameraController(f))return g.stop(),k.error("#goTo()","Cannot start an animation while interacting"),[2,p.reject(new x("view:goto-cannot-interrupt","Cannot start an animation while interacting"))];h=g.target;l=function(){return m.view.state.cameraController===f&&q.isSome(f.viewAnimation)&&f.viewAnimation.target===h&&f.active};e.then(function(a){var b=a.viewpoint,d=a.camera,e=a.isFullySpecified;return u(m,void 0,
void 0,function(){var a,k,m=this;return t(this,function(n){switch(n.label){case 0:if(!l())return[2];q.isSome(f.viewAnimation)&&(f.viewAnimation.update(b),h=f.viewAnimation.target);e?(a=new K.SurfaceCollisionCorrectionController({view:this.view,desiredCamera:d}),E.applySurfaceCollisionConstraint(this.view,d,1)):E.applyAll(this.view,d);f.begin(d,this.internalAnimateOptions(c));k=function(){var b=m.view.state.cameraController;a&&(b&&b.active?b instanceof F.PointToPointAnimationController&&q.isSome(b.viewAnimation)&&
b.viewAnimation.target===h&&(m.view.state.cameraController=a):q.isSome(f.viewAnimation)&&f.viewAnimation.target===h&&"finished"===f.state&&(m.view.state.cameraController=a))};return[4,g.when(k,k)];case 1:return n.sent(),[2]}})})}).catch(function(a){!p.isAbortError(a)&&a instanceof x&&a.message&&k.error("#goTo()","Failed to create camera from target, "+a.message[0].toLowerCase()+a.message.slice(1));if(l())throw m.view.state.cameraController.stopController(),a;});return[2,this.cancellableGoTo(f,c)]})})};
b.prototype.internalAnimateOptions=function(a){var b={};a&&(null!=a.speedFactor&&(b.speedFactor=a.speedFactor),null!=a.duration&&(b.duration=a.duration/1E3),null!=a.maxDuration&&(b.maxDuration=a.maxDuration/1E3),null!=a.easing&&(b.easing="string"===typeof a.easing?Y.named[a.easing]:a.easing));return b};h([l.property({type:w,dependsOn:["view.state.camera","ready"]})],b.prototype,"camera",null);h([l.property({type:S,dependsOn:["view.pointsOfInterest.centerOnContent.location","ready"]})],b.prototype,
"center",null);h([l.property({type:I,dependsOn:["view.state.camera","ready","view.pointsOfInterest.centerOnContent.location"]})],b.prototype,"extent",null);h([l.property({readOnly:!0,dependsOn:["view.state.camera","ready"]})],b.prototype,"frustum",null);h([l.property({readOnly:!0,dependsOn:["view.map.initialViewProperties?.viewpoint"]})],b.prototype,"hasInitialView",null);h([l.property({readOnly:!0,type:Boolean})],b.prototype,"ready",void 0);h([l.property({dependsOn:["view.pointsOfInterest.centerOnContent.distance",
"ready"],type:Number})],b.prototype,"scale",null);h([l.property({dependsOn:["view.state.camera","ready"]})],b.prototype,"padding",null);h([l.property({readOnly:!0,dependsOn:["view.width","view.height","padding"]})],b.prototype,"screenCenter",null);h([l.property({constructOnly:!0})],b.prototype,"view",void 0);h([l.property({type:z,dependsOn:["camera","ready"]})],b.prototype,"viewpoint",null);h([l.property({type:Number,dependsOn:["scale"]})],b.prototype,"zoom",null);h([l.property({constructOnly:!0})],
b.prototype,"updateDevicePixelRatio",void 0);return b=h([l.subclass("esri.views.3d.state.ViewStateManager")],b)}(l.declared(M));C.ViewStateManager=r;var aa="camera viewpoint extent scale center zoom".split(" "),Z=[{propertyName:"camera",overrides:["viewpoint"]},{propertyName:"viewpoint",overrides:["extent"]},{propertyName:"extent",overrides:["center","scale"]},{propertyName:"center",overrides:[]},{propertyName:"scale",overrides:["zoom"]},{propertyName:"zoom",overrides:[]},{propertyName:"padding",
overrides:[]}],ba={heading:0,tilt:0},ca=new w,m=new X.default,A=R.vec4f64.create(),B="pending-initial-view";C.default=r});