// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define({title:"Llum del dia",directShadow:"Mostra les ombres",notSupportedInHW:"Aquesta caracter\u00edstica no \u00e9s compatible en aquest navegador.",unsupported:"L'eina Llum del dia nom\u00e9s s'admet a l'SceneView.",datePattern:"d de MMMM de aaaa",playDay:"Anima el sol i les ombres durant un dia",playYear:"Anima el sol i les ombres durant un any",pause:"Atura temporalment",season:"Estaci\u00f3",spring:"Primavera",summer:"Estiu",winter:"Hivern",fall:"Tardor",timezoneHAST:"HAST",timezoneAKST:"AKST",
timezonePST:"PST",timezoneMST:"MST",timezoneCST:"CST",timezoneEST:"EST",timezoneCET:"CET",timezoneEET:"EET",timezoneMSK:"MSK",timezoneGST:"GST",timezoneICT:"ICT",timezoneCCT:"CCT",timezoneJST:"JST",timezoneAEST:"AEST",timezoneNZST:"NZST",timezoneDateline:"L\u00ednia internacional de canvi de data oest",timezoneHawaii:"Hawaii",timezoneAlaska:"Alaska",timezoneBaja:"Baixa Calif\u00f2rnia",timezoneMountain:"Hora de la Muntanya (EUA i Canad\u00e0)",timezoneLaPaz:"Chihuahua, La Paz, Mazatl\u00e1n",timezoneArizona:"Arizona",
timezoneSaskatchewan:"Saskatchewan",timezoneCentralAmerica:"Am\u00e8rica Central",timezoneCentralTime:"Hora Central (EUA i Canad\u00e0)",timezoneMexico:"Guadalajara, Ciutat de M\u00e8xic, Monterrey",timezoneEasternUS:"Hora de l'Est (EUA i Canad\u00e0)",timezoneLima:"Bogot\u00e0, Lima, Quito",timezoneIndiana:"Indiana (Est) ",timezoneAtlantic:"Hora de l'Atl\u00e0ntic (Canad\u00e0)",timezoneCuiaba:"Cuiab\u00e1",timezoneSantiago:"Santiago",timezoneManaus:"Georgetown, La Paz, Manaus, San Juan",timezoneAsuncion:"Asunci\u00f3n",
timezoneBrasilia:"Bras\u00edlia",timezoneGreenland:"Groenl\u00e0ndia",timezoneMontevideo:"Montevideo",timezoneCayenne:"Cayenne, Fortaleza",timezoneBuenosAires:"Buenos Aires",timezoneMidAtlantic:"Atl\u00e0ntic central",timezoneAzores:"A\u00e7ores",timezoneCaboVerde:"Illes Cap Verd",timezoneDublin:"Dubl\u00edn, Edimburg, Lisboa, Londres",timezoneReykjavik:"Monr\u00f2via, Reykjavik",timezoneCasablanca:"Casablanca",timezoneBelgrade:"Belgrad, Bratislava, Budapest, Ljubljana, Praga",timezoneSarajevo:"Sarajevo, Skopje, Vars\u00f2via, Zagreb",
timezoneBrussels:"Brussel\u00b7les, Copenhaguen, Madrid, Par\u00eds",timezoneWCAfrica:"\u00c0frica Central Occidental",timezoneAmsterdam:"Amsterdam, Berl\u00edn, Berna, Roma, Estocolm, Viena",timezoneWindhoek:"Windhoek",timezoneMinsk:"Minsk",timezoneCairo:"El Caire",timezoneHelsinki:"H\u00e8lsinki, K\u00edev, Riga, Sofia, Tallin, V\u00edlnius",timezoneAthens:"Atenes, Bucarest",timezoneJerusalem:"Jerusalem",timezoneAmman:"Amman",timezoneBeirut:"Beirut",timezoneHarare:"Harare, Pret\u00f2ria",timezoneDamascus:"Damasc",
timezoneIstanbul:"Istanbul",timezoneKuwait:"Kuwait, Riad",timezoneBaghdad:"Bagdad",timezoneNairobi:"Nairobi",timezoneKaliningrad:"Kaliningrad",timezoneMoscow:"Moscou, Sant Petersburg, Volgograd",timezoneMuscat:"Abu Dhabi, Muscat",timezoneBaku:"Bak\u00fa",timezoneYerevan:"Erevan",timezoneTbilisi:"Tbilissi",timezonePortLouis:"Port Louis",timezoneTashkent:"Taixkent",timezoneIslamabad:"Islamabad, Karachi",timezoneEkaterinburg:"Ekaterinburg",timezoneAstana:"Astan\u00e0",timezoneDhaka:"Dacca",timezoneNovosibirsk:"Novosibirsk",
timezoneBangkok:"Bangkok, Hanoi, Jakarta",timezoneKrasnoyarsk:"Krasnoyarsk",timezoneBeijing:"Beijing, Chongqing, Hong Kong, Urumqi",timezoneSingapore:"Kuala Lumpur, Singapur",timezoneTaipei:"Taipei",timezonePerth:"Perth",timezoneUlaanbaatar:"Ulan Bator",timezoneIrkutsk:"Irkutsk",timezoneSeoul:"Se\u00fcl",timezoneOsaka:"Osaka, Sapporo, T\u00f2quio",timezoneYakutsk:"Iakutsk",timezoneCanberra:"Canberra, Melbourne, Sydney",timezoneBrisbane:"Brisbane",timezoneHobart:"Hobart",timezoneGuam:"Guam, Port Moresby",
timezoneVladivostok:"Vladivostok",timezoneSolomon:"Illes Salom\u00f3, Nova Caled\u00f2nia",timezoneMagadan:"Magadan",timezoneFiji:"Fiji",timezoneAuckland:"Auckland, Wellington",timezoneNukualofa:"Nuku'alofa",timezoneSamoa:"Samoa",chooseTimezone:"Trieu la zona hor\u00e0ria"});