// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define(["exports","../../../../../../chunks/tslib.es6","./ShaderGraphNode"],function(b,q,e){function ba(a){switch(a.type){case "uint":return h;case "uvec2":return b.Vec2;case "uvec3":return b.Vec3;case "uvec4":return b.Vec4;default:throw Error("Found unexpected type");}}function ca(a){switch(a.type){case "float":return b.UInt;case "vec2":return b.UVec2;case "vec3":return b.UVec3;case "vec4":return b.UVec4;default:throw Error("Found unexpected type");}}function da(a){switch(a.type){case "int":return h;
case "ivec2":return b.Vec2;case "ivec3":return b.Vec3;case "ivec4":return b.Vec4;default:throw Error("Found unexpected type");}}function ea(a){switch(a.type){case "float":return r;case "vec2":return b.IVec2;case "vec3":return b.IVec3;case "vec4":return b.IVec4;default:throw Error("Found unexpected type");}}function x(a){switch(a.type){case "bool":case "float":case "int":case "uint":return p;case "bvec2":case "vec2":case "ivec2":case "uvec2":return b.BVec2;case "bvec3":case "vec3":case "ivec3":case "uvec3":return b.BVec3;
case "bvec4":case "vec4":case "ivec4":case "uvec4":return b.BVec4;default:throw Error("Unable to handle type");}}function fa(a){switch(a.type){case "float":case "int":case "uint":case "bool":case "sampler2D":return 1;case "vec2":case "ivec2":case "uvec2":case "bvec2":return 2;case "vec3":case "ivec3":case "uvec3":case "bvec3":return 3;case "vec4":case "ivec4":case "uvec4":case "bvec4":return 4;case "mat2":return 4;case "mat3":return 9;case "mat4":return 16;case "array":return a.size*fa(a.elementType)}}
function sa(a){const c=[["float","vec2","vec3","vec4"],["int","ivec2","ivec3","ivec4"],["uint","uvec2","uvec3","uvec4"],["bool","bvec2","bvec3","bvec4"]];for(const d of c)if(d.includes(a))return d.map(f=>ta[f]);throw Error("Unable to find type family");}function ha(a){return new Proxy(a,{get(c,d){if("constructor"===d)return new Proxy(c.constructor,{construct(f,k,v){f=new f(...k);return ha(f)}});if(d in c)return c[d];if("string"===typeof d)return c=sa(a.type),t(a,d,c[d.length-1])}})}function u(a){return new Proxy(a,
{construct(c,d,f){c=new c(...d);return ha(c)}})}function ua(a){return new Proxy(a,{get(c,d){if(d in c)return c[d];if("string"===typeof d&&(c=parseInt(d,10),!isNaN(c)))return t(a,`[${c}]`,a.elementType.constructor)}})}function l(a,c){return"number"===typeof a?new c(a):a}function t(a,c,d){a=new d(new e.ShaderPropertyAccessNode(c,a,d));a.isImplicit=!0;return a}function n(a,c,d,f=null){if(f){const k=new f;a=new f(new e.ShaderFunctionNode(a,[c,d],!0,!1,k));a.isImplicit=!0;return a}if("float"===c.type||
"int"===c.type||("mat2"===c.type||"mat3"===c.type||"mat4"===c.type)&&"float"!==d.type)return a=new d.constructor(new e.ShaderFunctionNode(a,[c,d],!0,!1,d.constructor)),a.isImplicit=!0,a;a=new c.constructor(new e.ShaderFunctionNode(a,[c,d],!0,!1,c.constructor));a.isImplicit=!0;return a}function g(a,c,d=c.constructor){a=new d(new e.ShaderFunctionNode(a,[c],!1,!1,d));a.isImplicit=!0;return a}function m(a,c,d,f=c.constructor){a=new f(new e.ShaderFunctionNode(a,[c,d],!1,!1,f));a.isImplicit=!0;return a}
function E(a,c,d,f,k=c.constructor){a=new k(new e.ShaderFunctionNode(a,[c,d,f],!1,!1,k));a.isImplicit=!0;return a}function ia(a){return w(a,ja(-1))}function J(a,c,d,f){return new c(new e.ShaderBlockNode(a,c,d,f))}function ka(a,c,d=0,f=a.size){d=(new r(d)).setMutable().setDebugName("FindIndexIterator");a=a.get(d);c=c(a).setDebugName("FindIndexPredicate");return J({iter:d},r,c,({out:k,iter:v,subgraph:B})=>`\n${k} = -1;\n\nfor (; ${v} < ${f}; ${v}++) {\n\n${B.body}\n\n  if (${B.varName}) {\n    ${k} = ${v};\n    break;\n  }\n\n}\n`).setDebugName("FindIndexBlock")}
function la(a,c,d=0,f=a.size){return J({array:a},r,null,({out:k,array:v})=>`\n${k} = -1;\nfor (int i = ${d}; i < ${f}; i++) {\n  bool condition;\n  ${c({array:v,i:"i",out:"condition"})}\n  if (condition) {\n    ${k} = i;\n    break;\n  }\n}\n`).setDebugName("GlslFindIndexBlock")}function ma(a,c,d){c="function"===typeof c?c():c;d="function"===typeof d?d():d;a=new c.constructor(new e.ShaderConditionNode(a,c,d));a.isImplicit=!0;return a}function w(a,c){return n("*",a,c)}function z(a,c){return n("/",
a,c)}function y(a,c){return n("+",a,c)}function A(a,c){return n("-",a,c)}function na(...a){return 1>=a.length?a[0]:a.slice(1).reduce((c,d)=>oa(c,d),a[0])}function oa(a,c){return n("||",a,c,p)}function pa(...a){return 1>=a.length?a[0]:a.slice(1).reduce((c,d)=>n("\x26\x26",c,d,p),a[0])}function G(a){return g("all",a,p)}function H(a){return g("any",a,p)}function qa(a){return g("cos",a)}function ra(a){return g("sin",a)}var F,K,L,M,N,O,P,Q,R,S,T,U,V,W;class X extends Error{}b.FixedArray=F=class extends e.ShaderPrimitiveNode{constructor(a,
c){super();this.elementType=a;this.size=c;this.children=[];this.type="array"}clone(){const a=new F(this.elementType,this.size);super.cloneInto(a);return a}get(a){return"number"===typeof a?(a=new r(a),a.isImplicit=!0,t(this,a,this.elementType.constructor)):t(this,a,this.elementType.constructor)}last(){return this.get(this.size-1)}first(){return this.get(0)}findIndex(a,c,d){return ka(this,a,c,d)}glslFindIndex(a,c,d){return la(this,a,c,d)}static ofType(a,c){return new Proxy(F,{construct(d,f){return new F(new a,
c)}})}};b.FixedArray.type="array";b.FixedArray=F=q.__decorate([function(a){return new Proxy(a,{construct(c,d,f){c=new c(...d);return ua(c)}})}],b.FixedArray);class Y extends e.ShaderPrimitiveNode{constructor(){super(...arguments);this.type="sampler2D";this.children=[]}clone(){const a=new Y;a.children=this.children.map(e.cloneShaderNode);super.cloneInto(a);return a}}Y.type="sampler2D";class h extends e.ShaderPrimitiveNode{constructor(a){super();this.type="float";this.children=[a]}clone(){const a=new h(e.cloneShaderNode(this.children[0]));
super.cloneInto(a);return a}multiply(a){return"number"===typeof a?w(this,l(a,h)):w(this,a)}divide(a){return"number"===typeof a?z(this,l(a,h)):z(this,a)}add(a){return"number"===typeof a?y(this,l(a,h)):y(this,a)}subtract(a){return"number"===typeof a?A(this,l(a,h)):A(this,a)}}h.type="float";b.Vec2=K=class extends e.ShaderPrimitiveNode{constructor(a,c){super();this.type="vec2";this.children=[a,c].filter(d=>null!=d)}clone(){const a=new K(e.cloneShaderNode(this.children[0]),e.cloneShaderNode(this.children[1]));
super.cloneInto(a);return a}get 0(){return t(this,"[0]",h)}get 1(){return t(this,"[1]",h)}get 2(){throw new X;}get 3(){throw new X;}multiply(a){return w(this,"number"===typeof a?l(a,h):a)}divide(a){return z(this,"number"===typeof a?l(a,h):a)}add(a){return y(this,"number"===typeof a?l(a,h):a)}subtract(a){return A(this,"number"===typeof a?l(a,h):a)}};b.Vec2.type="vec2";b.Vec2=K=q.__decorate([u],b.Vec2);b.Vec3=L=class extends e.ShaderPrimitiveNode{constructor(a,c,d){super();this.type="vec3";this.children=
[a,c,d].filter(f=>null!=f)}get 0(){return t(this,"[0]",h)}get 1(){return t(this,"[1]",h)}get 2(){return t(this,"[2]",h)}get 3(){throw new X;}clone(){const a=new L(e.cloneShaderNode(this.children[0]),e.cloneShaderNode(this.children[1]),e.cloneShaderNode(this.children[2]));super.cloneInto(a);return a}multiply(a){return w(this,"number"===typeof a?l(a,h):a)}divide(a){return z(this,"number"===typeof a?l(a,h):a)}add(a){return y(this,"number"===typeof a?l(a,h):a)}subtract(a){return A(this,"number"===typeof a?
l(a,h):a)}};b.Vec3.type="vec3";b.Vec3=L=q.__decorate([u],b.Vec3);b.Vec4=M=class extends e.ShaderPrimitiveNode{constructor(a,c,d,f){super();this.type="vec4";this.children=[a,c,d,f].filter(k=>null!=k)}clone(){const a=new M(e.cloneShaderNode(this.children[0]),e.cloneShaderNode(this.children[1]),e.cloneShaderNode(this.children[2]),e.cloneShaderNode(this.children[3]));super.cloneInto(a);return a}get 0(){return t(this,"[0]",h)}get 1(){return t(this,"[1]",h)}get 2(){return t(this,"[2]",h)}get 3(){return t(this,
"[3]",h)}multiply(a){return w(this,"number"===typeof a?l(a,h):a)}divide(a){return z(this,"number"===typeof a?l(a,h):a)}add(a){return y(this,"number"===typeof a?l(a,h):a)}subtract(a){return A(this,"number"===typeof a?l(a,h):a)}};b.Vec4.type="vec4";b.Vec4=M=q.__decorate([u],b.Vec4);b.UInt=N=class extends e.ShaderPrimitiveNode{constructor(a){super();this.type="uint";this.children=[a]}clone(){const a=new N(e.cloneShaderNode(this.children[0]));super.cloneInto(a);return a}};b.UInt.type="uint";b.UInt=N=
q.__decorate([u],b.UInt);b.UVec2=O=class extends e.ShaderPrimitiveNode{constructor(a,c){super();this.type="uvec2";this.children=[a,c].filter(d=>null!=d)}clone(){const a=new O(e.cloneShaderNode(this.children[0]),e.cloneShaderNode(this.children[1]));super.cloneInto(a);return a}};b.UVec2.type="uvec2";b.UVec2=O=q.__decorate([u],b.UVec2);b.UVec3=P=class extends e.ShaderPrimitiveNode{constructor(a,c,d){super();this.type="uvec3";this.children=[a,c,d].filter(f=>null!=f)}clone(){const a=new P(e.cloneShaderNode(this.children[0]),
e.cloneShaderNode(this.children[1]),e.cloneShaderNode(this.children[2]));super.cloneInto(a);return a}};b.UVec3.type="uvec3";b.UVec3=P=q.__decorate([u],b.UVec3);b.UVec4=Q=class extends e.ShaderPrimitiveNode{constructor(a,c,d,f){super();this.type="uvec4";this.children=[a,c,d,f].filter(k=>null!=k)}clone(){const a=new Q(e.cloneShaderNode(this.children[0]),e.cloneShaderNode(this.children[1]),e.cloneShaderNode(this.children[2]),e.cloneShaderNode(this.children[3]));super.cloneInto(a);return a}};b.UVec4.type=
"uvec4";b.UVec4=Q=q.__decorate([u],b.UVec4);class p extends e.ShaderPrimitiveNode{constructor(a){super();this.type="bool";this.children=[a]}and(a){return pa(this,a)}or(a){return na(this,a)}clone(){const a=new p(e.cloneShaderNode(this.children[0]));super.cloneInto(a);return a}}p.type="bool";b.BVec2=R=class extends e.ShaderPrimitiveNode{constructor(a,c){super();this.type="bvec2";this.children=[a,c].filter(d=>null!=d)}all(){return G(this)}any(){return H(this)}clone(){const a=new R(e.cloneShaderNode(this.children[0]),
e.cloneShaderNode(this.children[1]));super.cloneInto(a);return a}};b.BVec2.type="bvec2";b.BVec2=R=q.__decorate([u],b.BVec2);b.BVec3=S=class extends e.ShaderPrimitiveNode{constructor(a,c,d){super();this.type="bvec3";this.children=[a,c,d].filter(f=>null!=f)}all(){return G(this)}any(){return H(this)}clone(){const a=new S(e.cloneShaderNode(this.children[0]),e.cloneShaderNode(this.children[1]),e.cloneShaderNode(this.children[2]));super.cloneInto(a);return a}};b.BVec3.type="bvec3";b.BVec3=S=q.__decorate([u],
b.BVec3);b.BVec4=T=class extends e.ShaderPrimitiveNode{constructor(a,c,d,f){super();this.type="bvec4";this.children=[a,c,d,f].filter(k=>null!=k)}all(){return G(this)}any(){return H(this)}clone(){const a=new T(e.cloneShaderNode(this.children[0]),e.cloneShaderNode(this.children[1]),e.cloneShaderNode(this.children[2]),e.cloneShaderNode(this.children[3]));super.cloneInto(a);return a}};b.BVec4.type="bvec4";b.BVec4=T=q.__decorate([u],b.BVec4);class r extends e.ShaderPrimitiveNode{constructor(a){super();
this.type="int";this.children=[a]}multiply(a){return w(this,l(a,r))}add(a){return y(this,l(a,r))}subtract(a){return A(this,l(a,r))}divide(a){return z(this,l(a,r))}clone(){const a=new r(e.cloneShaderNode(this.children[0]));super.cloneInto(a);return a}}r.type="int";b.IVec2=U=class extends e.ShaderPrimitiveNode{constructor(a,c){super();this.type="ivec2";this.children=[a,c].filter(d=>null!=d)}clone(){const a=new U(e.cloneShaderNode(this.children[0]),e.cloneShaderNode(this.children[1]));super.cloneInto(a);
return a}};b.IVec2.type="ivec2";b.IVec2=U=q.__decorate([u],b.IVec2);b.IVec3=V=class extends e.ShaderPrimitiveNode{constructor(a,c,d){super();this.type="ivec3";this.children=[a,c,d].filter(f=>null!=f)}clone(){const a=new V(e.cloneShaderNode(this.children[0]),e.cloneShaderNode(this.children[1]),e.cloneShaderNode(this.children[2]));super.cloneInto(a);return a}};b.IVec3.type="ivec3";b.IVec3=V=q.__decorate([u],b.IVec3);b.IVec4=W=class extends e.ShaderPrimitiveNode{constructor(a,c,d,f){super();this.type=
"ivec4";this.children=[a,c,d,f].filter(k=>null!=k)}clone(){const a=new W(e.cloneShaderNode(this.children[0]),e.cloneShaderNode(this.children[1]),e.cloneShaderNode(this.children[2]),e.cloneShaderNode(this.children[3]));super.cloneInto(a);return a}};b.IVec4.type="ivec4";b.IVec4=W=q.__decorate([u],b.IVec4);class I extends e.ShaderPrimitiveNode{constructor(a,c,d,f){super();this.type="mat2";this.children=[a,c,d,f]}clone(){const a=new I(e.cloneShaderNode(this.children[0]),e.cloneShaderNode(this.children[1]),
e.cloneShaderNode(this.children[2]),e.cloneShaderNode(this.children[3]));super.cloneInto(a);return a}}I.type="mat2";class C extends e.ShaderPrimitiveNode{static identity(){return new C(1,0,0,0,1,0,0,0,1)}static fromRotation(a){const c=ra(a);a=qa(a);return new C(a,c,0,ia(c),a,0,0,0,1)}constructor(a,c,d,f,k,v,B,Z,aa){super();this.type="mat3";this.children=[a,c,d,f,k,v,B,Z,aa]}add(a){return y(this,a)}multiply(a){return w(this,a)}clone(){const a=new C(e.cloneShaderNode(this.children[0]),e.cloneShaderNode(this.children[1]),
e.cloneShaderNode(this.children[2]),e.cloneShaderNode(this.children[3]),e.cloneShaderNode(this.children[4]),e.cloneShaderNode(this.children[5]),e.cloneShaderNode(this.children[6]),e.cloneShaderNode(this.children[7]),e.cloneShaderNode(this.children[8]));super.cloneInto(a);return a}}C.type="mat3";class D extends e.ShaderPrimitiveNode{static identity(){return new D(1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1)}constructor(a,c,d,f,k,v,B,Z,aa,va,wa,xa,ya,za,Aa,Ba){super();this.type="mat4";this.children=[a,c,d,f,k,
v,B,Z,aa,va,wa,xa,ya,za,Aa,Ba]}static fromColumns(a,c,d,f){return new D(a.x,a.y,a.z,a.w,c.x,c.y,c.z,c.w,d.x,d.y,d.z,d.w,f.x,f.y,f.z,f.w)}multiply(a){return w(this,a)}clone(){const a=new D(e.cloneShaderNode(this.children[0]),e.cloneShaderNode(this.children[1]),e.cloneShaderNode(this.children[2]),e.cloneShaderNode(this.children[3]),e.cloneShaderNode(this.children[4]),e.cloneShaderNode(this.children[5]),e.cloneShaderNode(this.children[6]),e.cloneShaderNode(this.children[7]),e.cloneShaderNode(this.children[8]),
e.cloneShaderNode(this.children[9]),e.cloneShaderNode(this.children[10]),e.cloneShaderNode(this.children[11]),e.cloneShaderNode(this.children[12]),e.cloneShaderNode(this.children[13]),e.cloneShaderNode(this.children[14]),e.cloneShaderNode(this.children[15]));super.cloneInto(a);return a}}D.type="mat4";const ta={float:h,vec2:b.Vec2,vec3:b.Vec3,vec4:b.Vec4,int:r,ivec2:b.IVec2,ivec3:b.IVec3,ivec4:b.IVec4,uint:b.UInt,uvec2:b.UVec2,uvec3:b.UVec3,uvec4:b.UVec4,bool:p,bvec2:b.BVec2,bvec3:b.BVec3,bvec4:b.BVec4},
ja=(...a)=>new h(...a);b.Bool=p;b.Float=h;b.Int=r;b.Mat2=I;b.Mat3=C;b.Mat4=D;b.Sampler2D=Y;b._or=oa;b.abs=function(a){return g("abs",a)};b.acos=function(a){return g("acos",a)};b.acosh=function(a){return g("acosh",a)};b.add=y;b.all=G;b.and=pa;b.any=H;b.asin=function(a){return g("asin",a)};b.asinh=function(a){return g("asinh",a)};b.atan=function(a,c){return null==c?g("atan",a):m("atan",a,c,a.constructor)};b.atanh=function(a){return g("atanh",a)};b.bitAnd=function(a,c){return n("\x26",a,c)};b.bitOr=
function(a,c){return n("|",a,c)};b.bitRShift=function(a,c){return n("\x3e\x3e",a,c)};b.bitShift=function(a,c){return n("\x3c\x3c",a,c)};b.bitXor=function(a,c){return n("^",a,c)};b.block=J;b.ceil=function(a){return g("ceil",a)};b.clamp=function(a,c,d){return E("clamp",a,c,d,a.constructor)};b.cond=function(...a){var c=a.map(([f,k])=>"function"===typeof k?[f,k()]:[f,k]);a=c[0][1].constructor;const d=c.findIndex(f=>!0===f[0]);if(-1===d)throw Error("A cond must have a fallthrough case with `true`/; ");
c=c.slice(0,d).reduceRight((f,k)=>ma(k[0],k[1],f),c[d][1]);a=new a(c);a.isImplicit=!0;return a};b.cos=qa;b.cosh=function(a){return g("cosh",a)};b.cross=function(a,c){return m("cross",a,c,a.constructor)};b.dFdx=function(a){return g("dFdX",a)};b.dFdy=function(a){return g("dFdY",a)};b.definePropertyAccess=t;b.degrees=function(a){return g("degrees",a)};b.determinant=function(a){return g("determinant",a,h)};b.distance=function(a,c){return m("distance",a,c,h)};b.divide=z;b.dot=function(a,c){return m("dot",
a,c,h)};b.equal=function(a,c){return n("\x3d\x3d",a,c,p)};b.equalComponent=function(a,c){return m("equal",a,c,x(a))};b.exp=function(a){return g("exp",a)};b.exp2=function(a){return g("exp2",a)};b.faceforward=function(a,c,d){return E("faceforward",a,c,d)};b.findIndex=ka;b.float=ja;b.floatBitsToInt=function(a){return g("floatBitsToInt",a,ea(a))};b.floatBitsToUint=function(a){return g("floatBitsToUint",a,ca(a))};b.floor=function(a){return g("floor",a)};b.fract=function(a){return g("fract",a)};b.fwidth=
function(a){return g("fwidth",a)};b.getTypeElementLengthForType=fa;b.glslFindIndex=la;b.greaterThan=function(a,c){return n("\x3e",a,c,p)};b.greaterThanComponent=function(a,c){return m("greaterThan",a,c,x(a))};b.greaterThanEqual=function(a,c){return n("\x3e\x3d",a,c,p)};b.greaterThanEqualComponent=function(a,c){return m("greaterThanEqual",a,c,x(a))};b.ifElse=ma;b.int=(...a)=>new r(...a);b.intBitsToFloat=function(a){return g("intBitsToFloat",a,da(a))};b.inverse=function(a){return g("inverse",a,h)};
b.inversesqrt=function(a){return g("inversesqrt",a)};b.isinf=function(a){return g("isinf",a,x(a))};b.isnan=function(a){return g("isnan",a,x(a))};b.length=function(a){return g("length",a,h)};b.lessThan=function(a,c){return n("\x3c",a,c,p)};b.lessThanComponent=function(a,c){return m("lessThan",a,c,x(a))};b.lessThanEqual=function(a,c){return n("\x3c\x3d",a,c,p)};b.lessThanEqualComponent=function(a,c){return m("lessThanEqual",a,c,x(a))};b.log=function(a){return g("log",a)};b.log2=function(a){return g("log2",
a)};b.mat2=(...a)=>new I(...a);b.mat3=(...a)=>new C(...a);b.mat4=(...a)=>new D(...a);b.matrixCompMult=function(a,c){return m("matrixCompMult",a,c)};b.max=function(a,c){return m("max",a,c)};b.min=function(a,c){return m("min",a,c)};b.mix=function(a,c,d){return E("mix",a,c,d)};b.mod=function(a,c){return m("mod",a,c)};b.modf=function(a,c){throw Error("modf not implemented");};b.multiply=w;b.namedScope=function(a,c){a="function"===typeof a?a():a;c=new a.constructor((new e.ShaderScopeNode(a)).setDebugName(c));
c.isImplicit=!0;return c};b.negate=ia;b.normalize=function(a){return g("normalize",a)};b.not=function(a){return"bool"===a.type?g("!",a):g("not",a)};b.notEqual=function(a,c){return n("!\x3d",a,c,p)};b.notEqualComponent=function(a,c){return m("notEqual",a,c,x(a))};b.or=na;b.outerProduct=function(a,c){throw Error("Impl type?");};b.packHalf2x16=function(a){return g("packHalf2x16",a,b.UInt)};b.packSnorm2x16=function(a){return g("packSnorm2x16",a,b.UInt)};b.packUnorm2x16=function(a){return g("packUnorm2x16",
a,b.UInt)};b.pow=function(a,c){return m("pow",a,c)};b.radians=function(a){return g("radians",a)};b.reflect=function(a,c){return m("reflect",a,c)};b.refract=function(a,c,d){return E("refract",a,c,d)};b.round=function(a){return g("round",a)};b.roundEven=function(a){return g("roundEven",a)};b.sign=function(a){return g("sign",a)};b.sin=ra;b.sinh=function(a){return g("sinh",a)};b.smoothstep=function(a,c,d){return E("smoothstep",a,c,d)};b.sqrt=function(a){return g("sqrt",a)};b.step=function(a,c){return m("step",
a,c,c.constructor)};b.subtract=A;b.tan=function(a){return g("tan",a)};b.tanh=function(a){return g("tanh",a)};b.texelFetch=function(a,c,d){throw Error("Impl type");};b.texelFetchOffset=function(a,c,d,f){throw Error("Impl type");};b.texture=function(a,c,d){throw Error("Impl type");};b.texture2D=function(a,c){return m("texture2D",a,c,b.Vec4)};b.textureGrad=function(a,c,d,f){throw Error("Impl type");};b.textureGradOffset=function(a,c,d,f,k){throw Error("Impl type");};b.textureLod=function(a,c,d){throw Error("Impl type");
};b.textureLodOffset=function(a,c,d,f){throw Error("Impl type");};b.textureOffset=function(a,c,d,f){throw Error("Impl type");};b.textureProj=function(a,c,d){throw Error("Impl type");};b.textureProjGrad=function(a,c,d,f){throw Error("Impl type");};b.textureProjGradOffset=function(a,c,d,f,k){throw Error("Impl type");};b.textureProjLod=function(a,c,d){throw Error("Impl type");};b.textureProjLodOffset=function(a,c,d,f){throw Error("Impl type");};b.textureProjOffset=function(a,c,d,f){throw Error("Impl type");
};b.textureSize=function(a,c){throw Error("Impl type");};b.transformFloatToInt=ea;b.transformFloatToUInt=ca;b.transformIntToFloat=da;b.transformTypeToBooleanType=x;b.transformUIntToFloat=ba;b.transpose=function(a){return g("transpose",a)};b.trunc=function(a){return g("trunc",a)};b.uintBitsToFloat=function(a){return g("uintBitsToFloat",a,ba(a))};b.unpackHalf2x16=function(a){return g("unpackHalf2x16",a,b.Vec2)};b.unpackSnorm2x16=function(a){return g("unpackSnorm2x16",a,b.Vec2)};b.unpackUnorm2x16=function(a){return g("unpackUnorm2x16",
a,b.Vec2)};b.vec2=(...a)=>new b.Vec2(...a);b.vec3=(...a)=>new b.Vec3(...a);b.vec4=(...a)=>new b.Vec4(...a);b.when=function(a,c){a=new c.constructor(new e.ShaderConditionNode(a,c,null));a.isImplicit=!0;return a};Object.defineProperty(b,Symbol.toStringTag,{value:"Module"})});