// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("../../chunks/tslib.es6 ../../Graphic ../../core/deprecate ../../core/Evented ../../core/Logger ../../core/maybe ../../core/Promise ../../core/reactiveUtils ../../core/string ../../core/accessorSupport/decorators/property ../../core/has ../../core/RandomLCG ../../core/accessorSupport/decorators/subclass ../../core/support/UpdatingHandles ../../form/FormTemplate ../../layers/support/ContingentValue ../../layers/support/editableLayers ../../layers/support/LayerContingentValuesCache ../../time/timeZoneUtils ./featureFormUtils ./FieldInput ./FormExpressionArcadeExecutor ./FormExpressionsManager ./GroupInput ./RelationshipInput".split(" "),
function(n,m,B,H,v,C,I,x,D,p,V,W,J,K,L,E,M,N,w,r,F,O,P,Q,R){function G(a){if("field"===a.type||"group"===a.type||"relationship"===a.type)return!0;const b=r.isInteractiveElement(a)?" "+a.label:"";v.getLogger("esri.widgets.FeatureForm.FeatureFormViewModel").warn("form-info::unsupported-element-type","Only element types 'field', 'group' and 'relationship' are supported",`Element${b} has unsupported type '${a.type}'`);return!1}const y=new m({attributes:{}}),S=["editableExpression","requiredExpression",
"valueExpression","visibilityExpression"],T=["visibilityExpression"],U=["editableExpression","visibilityExpression"];m=class extends I.EsriPromiseMixin(H.EventedAccessor){constructor(a){super(a);this._expressionExecutorsInUse=new Set;this._expressionExecutorLookup=new Map;this._contingentValuesCache=this._expressionsManager=null;this._featureClone=y.clone();this._initialFeature=y.clone();this._timeZone=null;this._updatingHandles=new K.UpdatingHandles;this.arcadeEditType="NA";this.contingencyConstraintViolations=
new Map;this.disabled=!1;this.highlightHelper=null;this.inputs=[];this.relatedRecordCallbacks=this.map=null;this.strict=!1}initialize(){const a=x.watch(()=>[this.layer,!!this.layer?.loaded,this.formTemplate,this.feature,this.timeZone,this.arcadeEditType],async([c,e])=>{null!=c&&(e?this._updatingHandles.addPromise(this._updateInputs()):c.load().catch(()=>{}))},{equals:([c,e,f,g,h,k],[l,q,t,u,z,A])=>c===l&&e===q&&f===t&&g===u&&h===z&&k===A,initial:!0}),b=x.watch(()=>this._arcadeContextInfo,c=>{null!=
this._expressionsManager&&(this._expressionsManager.arcadeContextInfo=c,this._updatingHandles.addPromise(this._expressionsManager.evaluateAll().finally(()=>this._afterExpressionsEvaluated())))}),d=x.watch(()=>this.layer,c=>{(c="subtype-sublayer"===c?.type?c.parent:"feature"===c?.type?c:null)&&this.addResolvingPromise(N.createLoadedLayerContingentValuesCache(c).then(e=>{this._contingentValuesCache=e;this.notifyChange("fieldsWithContingentValues")}))},{initial:!0});this.addHandles([a,b,d])}destroy(){this.layer=
this.feature=null;this._contingentValuesCache=C.destroyMaybe(this._contingentValuesCache);this.highlightHelper?.removeAll();this._updatingHandles.destroy()}get _expressionInfosLookup(){return new Map(this.formTemplate?.expressionInfos?.map(a=>[a.name,a]))}get activeRelationshipInput(){return this.allRelationshipInputs.find(a=>a.relationshipId===this.relationshipId)}get _arcadeContextInfo(){const {_initialFeature:a,arcadeEditType:b,layer:d,map:c,spatialReference:e,timeZone:f}=this;return{layer:M.isEditableLayer(d)?
d:null,originalFeature:a,editType:b,map:c,spatialReference:e,timeZone:f}}get allFieldInputs(){return r.flattenFieldInputs(this.inputs)}get allGroupInputs(){return this.inputs.filter(r.isGroupInput)}get allRelationshipInputs(){return r.flattenRelationshipInputs(this.inputs)}get _layerFieldsByName(){return new Map(this.layer?.fields.map(a=>[a.name,a]))}get feature(){return this._get("feature")}set feature(a){this._featureClone=a?a.clone():y.clone();this._initialFeature=this._featureClone.clone();this._expressionsManager&&
(this._expressionsManager.feature=this._featureClone);a?(this._resetFieldInputValues(this._featureClone),this.allRelationshipInputs.forEach(b=>b.feature=a)):(this.inputs.forEach(b=>b.destroy()),this.inputs.length=0);this.contingencyConstraintViolations.clear();this._set("feature",a)}get fieldsWithContingentValues(){if(null==this._contingentValuesCache)return new Set;const a=this._contingentValuesCache.fieldGroups.flatMap(b=>b.fields);return new Set(a)}get fieldsWithInvalidCodedValue(){return new Set(this.allFieldInputs.filter(a=>
{const {name:b,domain:d,value:c}=a;return"coded-value"===d?.type?(a=this.getFieldValueOptionsForField(b),null!=c&&""!==c&&!a.flat().some(e=>e.value===c)):!1}))}get formTemplate(){return this.layer&&"formTemplate"in this.layer?this.layer.formTemplate:null}set formTemplate(a){void 0===a?this._clearOverride("formTemplate"):this._override("formTemplate",a)}get formDescription(){const {formTemplate:a,layer:b}=this;return a?.description&&b?r.parseFormTemplateString({label:a.description,attributes:this.getValues(),
fieldsIndex:b.fieldsIndex,timeZone:this.timeZone}):null}get formTitle(){const {formTemplate:a,layer:b}=this;return a?.title&&b?r.parseFormTemplateString({label:a.title,attributes:this.getValues(),fieldsIndex:b.fieldsIndex,timeZone:this.timeZone}):null}get formHeaderVisible(){const {activeRelationshipInput:a,formDescription:b,formTitle:d}=this;return!(a||!b&&!d)}get joinedContingentValues(){return this._joinContingentValues()}get layer(){return this.feature?.sourceLayer&&"applyEdits"in this.feature.sourceLayer?
this.feature.sourceLayer:null}set layer(a){this._override("layer",a)}get relationshipId(){return this._get("relationshipId")}set relationshipId(a){var b=this.allRelationshipInputs;null!=a&&a===this.relationshipId||b.forEach(d=>d.showAllEnabled=!1);null!=a&&(b=b.find(d=>d.relationshipId===a))&&(b.showAllEnabled=!0);this._set("relationshipId",a)}get spatialReference(){return this.layer?.spatialReference??null}set spatialReference(a){this._override("spatialReference",a)}get state(){return this.layer?.loaded?
"ready":"disabled"}get submittable(){return this.valid?!0:this.allFieldInputs.filter(a=>!a.valid).every(({submittable:a})=>a)}get timeZone(){var {layer:a}=this;if(a&&"datesInUnknownTimezone"in a&&a.datesInUnknownTimezone)return w.utc;a=a&&"preferredTimeZone"in a&&a.preferredTimeZone;return this._timeZone===w.unknown?a||w.utc:this._timeZone||w.system}set timeZone(a){this._timeZone=a}get updating(){return this._updatingHandles.updating}get valid(){const a=this.allFieldInputs;return 0<a.length&&a.every(({valid:b})=>
b)}get view(){B.deprecatedProperty(v.getLogger("esri.widgets.FeatureForm.FeatureFormViewModel"),"view",{replacement:"FeatureForm.map",version:"4.27"});return this._get("view")}set view(a){B.deprecatedProperty(v.getLogger("esri.widgets.FeatureForm.FeatureFormViewModel"),"view",{replacement:"FeatureForm.map",version:"4.27"});this._set("view",a);a?.map&&(this.map=a.map)}findField(a){return this.allFieldInputs.find(b=>b.name===a)}getFieldValueOptionsForField(a,b){var d=this.findField(a);if(!d)return[[],
[]];d="coded-value"===d.domain?.type?d.domain.codedValues.map(({name:c,code:e})=>({name:c,value:e})):[];a=this.fieldsWithContingentValues.has(a)?this._getContingentValueOptionsForField(a,b):[];if(0<a.length){const c=new Set(a.map(e=>e.value));b=d.filter(e=>!c.has(e.value));return[a,b]}return[d,[]]}getValue(a){const {_featureClone:b,layer:d}=this,c=!!d?.getField(a);return b.getAttribute(a)??(c?null:void 0)}setValue(a,b){const {_featureClone:d,strict:c}=this,e=this.findField(a);b=""===b?null:b;e&&d.getAttribute(a)!==
b&&(e.value=b,!c||e.valid)&&(this._afterValueChange(e),null!=this._expressionsManager&&this._updatingHandles.addPromise(this._expressionsManager.evaluateInvalidated([e.name]).finally(()=>this._afterExpressionsEvaluated())))}getValues(){return{...this._featureClone.attributes}}overrideInitialFeature(a){this._initialFeature=a}submit(){var a=this.allFieldInputs;const b=new Set(a.filter(c=>c.valid).map(({name:c})=>c));a=a.filter(c=>!c.valid).map(({name:c})=>c);const d=this.getValues();if(0<this.validateContingencyConstraints(d,
{includeIncompleteViolations:!0}).length)for(const [c,e]of this.contingencyConstraintViolations.entries())"error"===e.type&&(b.delete(c),a.push(c));this.emit("submit",{valid:[...b],invalid:a,values:d})}validateContingencyConstraints(a,b){const {_contingentValuesCache:d}=this,c=new Map;this.contingencyConstraintViolations=c;if(null==d)return[];const {invalid:e,incomplete:f}=d.validateContingencyConstraints(a);a=[...e,...(b?.includeIncompleteViolations?f:[])];for(const g of a)for(const h of g.fieldGroup.fields)c.set(h,
g);return a}notifyFeatureGeometryChanged(){const {_expressionsManager:a,feature:b,_featureClone:d}=this;d.geometry=b.geometry;null!=a&&this._updatingHandles.addPromise(a.evaluateInvalidatedByGeometry().finally(()=>this._afterExpressionsEvaluated()))}_emitChangeEvent({name:a,valid:b,value:d}){this.emit("value-change",{layer:this.layer,feature:this.feature,fieldName:a,value:d,valid:b})}async _updateInputs(){this._stopExpressions();const {_featureClone:a,_initialFeature:b,arcadeEditType:d,formTemplate:c,
inputs:e,layer:f,timeZone:g}=this;if(f){var h={arcadeEditType:d,feature:a,initialFeature:b,layer:f,timeZone:g},k=e.slice();this.inputs=c?.elements&&0<c.elements.length?await this._updateInputsUsingFormElements(k,c.elements,h):this._updateInputsUsingLayerFields(k,f?.fields,h);await this._startExpressions()}}async _updateInputsUsingFormElements(a,b,d){const c=new Map;for(const e of a)if(r.isGroupInput(e)){c.set(e.element,e);for(const f of e.inputs)f.element&&c.set(f.element,f)}else e.element&&c.set(e.element,
e);a=new Map;b=this._updateInputsUsingFormElementsRecursive({existingInputsByElement:c,updatedElements:b.filter(G),sharedInitializationProperties:d,group:null,newExpressionExecutorPromises:a});for(const [e,f]of c.entries())c.delete(e),f.destroy();await Promise.all(Array.from(a.values()));return b}_updateInputsUsingFormElementsRecursive(a){const {existingInputsByElement:b,updatedElements:d,sharedInitializationProperties:c,group:e,newExpressionExecutorPromises:f}=a;a=[];for(const h of d){var g=b.has(h);
const k=g?b.get(h):r.isGroupElement(h)?this._makeGroupInputFromElement(h,c):r.isFieldElement(h)?this._makeFieldInputFromElement(h,c,e):r.isRelationshipElement(h)?this._makeRelationshipInputFromElement(h,c,e):null;if(k){a.push(k);this._assignExpressionExecutors(k,h,f);if(g)if(b.delete(h),r.isGroupInput(k)){const {feature:l,timeZone:q}=c;k.set({feature:l,timeZone:q})}else r.isRelationshipInput(k)?(g=this.relationshipId===h.relationshipId,k.set(c),k.set({map:this.map,showAllEnabled:g})):k.set(c);r.isGroupElement(h)&&
(g=h.elements.filter(l=>G(l)),k.inputs=this._updateInputsUsingFormElementsRecursive({existingInputsByElement:b,updatedElements:g,sharedInitializationProperties:c,group:k,newExpressionExecutorPromises:f}))}}return a}_updateInputsUsingLayerFields(a,b,d){if(!Array.isArray(b))return v.getLogger("esri.widgets.FeatureForm.FeatureFormViewModel").warn(this.declaredClass,"No attribute fields found."),[];const c=new Map;for(const l of a)if(r.isGroupInput(l)){for(const q of l.inputs)q.destroy();l.inputs.length=
0;l.destroy()}else r.isRelationshipInput(l)?l.destroy():r.isFieldInput(l)&&(null!==l.element?l.destroy():c.set(l.field,l));a=[];const {arcadeEditType:e,feature:f,initialFeature:g,layer:h,timeZone:k}=d;for(const l of b)b=c.get(l)??new F({arcadeEditType:e,field:l,feature:f,initialFeature:g,layer:h,value:f?.getAttribute(l.name)??null,preservesValueWhenHidden:this.formTemplate?.preserveFieldValuesWhenHidden,timeZone:k}),a.push(b),c.delete(l);for(const [l,q]of c.entries())c.delete(l),q.destroy();return a}_resetFieldInputValues(a){for(const b of this.allFieldInputs)b.value=
a.getAttribute(b.name)}_makeFieldInputFromElement(a,b,d){const {arcadeEditType:c,feature:e,initialFeature:f,layer:g,timeZone:h}=b;({fieldName:b}=a);return(b=b&&this._layerFieldsByName.get(b))?new F({arcadeEditType:c,element:a,field:b,value:e?.getAttribute(a.fieldName)??null,feature:e,initialFeature:f,layer:g,group:d,preservesValueWhenHidden:this.formTemplate?.preserveFieldValuesWhenHidden,timeZone:h}):null}_makeGroupInputFromElement(a,b){const {feature:d,layer:c}=b;return new Q({element:a,inputs:[],
feature:d,layer:c})}_makeRelationshipInputFromElement(a,b,d=null){const {map:c}=this,{feature:e,layer:f,timeZone:g}=b;return new R({element:a,feature:e,group:d,layer:f,map:c,timeZone:g})}_assignExpressionExecutors(a,b,d){var c=r.isGroupElement(b)?T:r.isRelationshipElement(b)?U:S;for(const e of c){const f=`${e}Executor`;if(a[f]){this._useExecutor(a[f]);continue}c=b[e];const {_expressionExecutorLookup:g}=this;if(null!=c&&""!==c){const h=this._expressionInfosLookup.get(c)?.expression??c;g.has(h)?a[f]=
this._useExecutor(g.get(h)):d.has(h)?(c=d.get(h).then(k=>a[f]=k),d.set(h,c)):(c=O.createFormExpressionArcadeExecutor(h,this.layer).then(k=>{a[f]=this._useExecutor(k);g.set(h,k);return k}),d.set(h,c))}}return[]}_createExpressionsManager(a){const {_arcadeContextInfo:b,_featureClone:d,allFieldInputs:c,formTemplate:e}=this;this._expressionsManager=new P.FormExpressionsManager({executors:a,feature:d,arcadeContextInfo:b,fieldInputs:c,preserveFieldValuesWhenHidden:!0===e?.preserveFieldValuesWhenHidden})}async _startExpressions(){if(0!==
this._expressionExecutorsInUse.size){var a=Array.from(this._expressionExecutorsInUse);this._createExpressionsManager(a);await this._expressionsManager.evaluateAll().finally(()=>this._afterExpressionsEvaluated())}}_stopExpressions(){this._expressionsManager=C.destroyMaybe(this._expressionsManager);this._expressionExecutorsInUse.clear()}_useExecutor(a){this._expressionExecutorsInUse.add(a);return a}_afterValueChange(a){const {name:b,value:d}=a,{_featureClone:c,formTemplate:e,layer:f}=this;if(f){var g=
c.getAttribute(b);c.setAttribute(b,d);var {typeFieldName:h,types:k}=r.getNormalizedFeatureTypeInfo(f);if(b===h&&d!==g){"subtype-sublayer"===f.type&&(g=f.parent?.findSublayerForFeature(c),c.sourceLayer=this.feature.sourceLayer=g);g=new Set;for(var l of k)if(l.domains&&"object"===typeof l.domains)for(const q of Object.keys(l.domains))g.add(q);for(const q of g)(l=this.findField(q))&&l.notifyChange("domain")}if(null!=e){const {description:q,title:t}=e;t&&D.templateHasKey(t,b)&&this.notifyChange("formTitle");
q&&D.templateHasKey(q,b)&&this.notifyChange("formDescription")}this._emitChangeEvent(a)}}_afterExpressionsEvaluated(){const {_featureClone:a}=this;for(const b of this.allFieldInputs)b.value!==a.getAttribute(b.name)&&this._afterValueChange(b)}_joinContingentValues(){var a=this._contingentValuesCache;if(null==a)return[];var {typeFieldName:b}=r.getNormalizedFeatureTypeInfo(this.layer);b=b?this.getValue(b):null;const d=[];for(var c of a.fieldGroups){const {contingencies:h,fields:k,name:l}=c;a=[];for(var e of h)e.isRetired||
(null==e.subtype||e.subtype.code===b)&&a.push({values:e.values});0<a.length&&d.push({name:l,fields:k,contingencies:a})}const [f,g]=this._generateJoinPlan(d);c=f.flatMap(h=>this._joinFieldGroupContingencies(h));e=g.flatMap(h=>h.contingencies);return[...c,...e]}_generateJoinPlan(a){var b=new Map,d=[],c=new Set;for(var e of a)for(const k of e.fields)if(b.has(k)){const l=b.get(k),q=e,t=[l.name,q.name].sort().join("|");c.has(t)||(d.push([l,q]),c.add(t),b.set(k,q))}else b.set(k,e);b=new Set(d.flat());a=
new Set(a);for(var f of b)a.delete(f);f=new Map;b=new Map;for(var g of new Set(d.flat()))c=Symbol(g.name),f.set(c,new Set([g])),b.set(g,c);for(const [k,l]of d)if(d=b.get(k),g=b.get(l),d!==g){c=f.get(d);e=f.get(g);for(var h of e)c.add(h),b.set(h,d);f.delete(g)}h=[...f.values()].map(k=>[...k]);d=[...a];return[h,d]}_joinFieldGroupContingencies(a){const b=a.slice();var d=b.shift(),c=b.shift();a=this._generateJoinKey(d.fields,c.fields);let e=new Set([...d.fields,...c.fields]),f=new Map;for(var g of d.contingencies)[d]=
this._hashContingency(g,a.codedValueFields,!0),f.has(d)?f.get(d)?.push(g):f.set(d,[g]);for(;0<b.length;){g=new Map;d=b.shift();const l=this._generateJoinKey(e,d.fields);for(var h of c.contingencies){const [q,t]=this._hashContingency(h,a.codedValueFields);c=t?this._findMatchingContingenciesWithAnyHashMask(f,q):f.get(q);f.has("#JSAPI_CONTINGENT_VALUE_ANY_HASH")&&c?.push(...this._findMatchingContingenciesContainingAny(h,f.get("#JSAPI_CONTINGENT_VALUE_ANY_HASH"),a.codedValueFields));if(null!=c)for(var k of c){c=
0<a.rangeFields.length?this._joinContingenciesWithRangeDomains(k,h,a.rangeFields):this._joinContingencies(k,h);if(null==c)break;const [u]=this._hashContingency(c,l.codedValueFields,!0);g.has(u)?g.get(u)?.push(c):g.set(u,[c])}}f=g;c=d;a=l;e=new Set([...e,...c.fields])}h=[];for(const l of c.contingencies){const [q,t]=this._hashContingency(l,a.codedValueFields);k=t?this._findMatchingContingenciesWithAnyHashMask(f,q):f.get(q);f.has("#JSAPI_CONTINGENT_VALUE_ANY_HASH")&&k.push(...this._findMatchingContingenciesContainingAny(l,
f.get("#JSAPI_CONTINGENT_VALUE_ANY_HASH"),a.codedValueFields));if(null!=k)for(const u of k)k=0<a.rangeFields.length?this._joinContingenciesWithRangeDomains(u,l,a.rangeFields):this._joinContingencies(u,l),null!=k&&h.push(k)}return h}_joinContingencies(a,b){b={values:{...a.values,...b.values}};for(const [d,c]of Object.entries(b.values))"any"===c.objectType&&null!=a.values[d]&&(b.values[d]=a.values[d]);return b}_joinContingenciesWithRangeDomains(a,b,d){const c=this._joinContingencies(a,b);for(const f of d){var e=
a.values[f];const g=b.values[f],{leftIsNull:h,rightIsNull:k,bothAreNull:l,leftIsAny:q,rightIsAny:t,bothAreAny:u,leftIsRange:z,rightIsRange:A}=this._compareObjectTypes(e.objectType,g.objectType);if(!l&&!u)if(h&&t||k&&q)c.values[f]=new E({objectType:"null"});else{if(h&&A||k&&z)return null;q?(e.minValue=-Infinity,e.maxValue=Infinity):t&&(g.minValue=-Infinity,g.maxValue=Infinity);d=Math.max(e.minValue,g.minValue);e=Math.min(e.maxValue,g.maxValue);if(d>e)return null;c.values[f]=new E({objectType:"range",
minValue:d,maxValue:e})}}return c}_findMatchingContingenciesContainingAny(a,b,d){return b.filter(c=>d.every(e=>{const f=c.values[e];e=a.values[e];return"any"===f.objectType||"any"===e.objectType||f.codedValue?.code===e.codedValue?.code}))}_findMatchingContingenciesWithAnyHashMask(a,b){b=RegExp(`${b}$`);const d=[];for(const [c,e]of a){if("#JSAPI_CONTINGENT_VALUE_ANY_HASH"===c)break;b.test(c)&&d.push(...e)}return d}_generateJoinKey(a,b){a=Array.isArray(a)?new Set(a):a;var d=Array.isArray(b)?new Set(b):
b;b=a.size<d.size?a:d;a=b===a?d:a;d=new Set;const c=new Set;for(const e of b)if(a.has(e)&&(b=this.layer?.getFieldDomain(e,{feature:this.feature}),null!=b))switch(b.type){case "coded-value":d.add(e);break;case "range":c.add(e)}return{codedValueFields:[...d],rangeFields:[...c]}}_contingencyIsValid(a,b){const d={};for(const {name:c,value:e}of this.allFieldInputs)this.fieldsWithContingentValues.has(c)&&null!=e&&c!==a&&(d[c]=e);return Object.entries(d).every(([c,e])=>!b.values.hasOwnProperty(c)||r.valueIsValidContingentValue(e,
b.values[c]))}_getContingentValueOptionsForField(a,b){var d=this.joinedContingentValues.slice();const c=new Map;b={code:"",name:b??"No value"};for(const e of d)if(d=e.values[a],"code"===d?.objectType||"null"===d?.objectType){const {code:f,name:g}=d.codedValue&&"null"!==d.objectType?d.codedValue:b;!c.has(f)&&this._contingencyIsValid(a,e)&&c.set(f,{name:g,value:f})}return[...c.values()]}_hashContingency(a,b,d=!1){if(1>b.length)return["#JSAPI_CONTINGENT_VALUE_EMPTY_HASH",!1];const c=[];let e=!1;for(const f of b)if(b=
a.values[f],"any"===b.objectType){if(d)return["#JSAPI_CONTINGENT_VALUE_ANY_HASH",!0];e=!0;c.push(`${f}:.*`)}else"null"===b.objectType?c.push(`${f}:${"#JSAPI_CONTINGENT_VALUE_NULL_HASH"}`):c.push(`${f}:${b.codedValue?.code}`);return[c.sort().join("\x26"),e]}_compareObjectTypes(a,b){return{leftIsNull:"null"===a,rightIsNull:"null"===b,bothAreNull:"null"===a&&"null"===b,leftIsAny:"any"===a,rightIsAny:"any"===b,bothAreAny:"any"===a&&"any"===b,leftIsRange:"range"===a,rightIsRange:"range"===b}}};n.__decorate([p.property()],
m.prototype,"_expressionInfosLookup",null);n.__decorate([p.property()],m.prototype,"_featureClone",void 0);n.__decorate([p.property()],m.prototype,"_timeZone",void 0);n.__decorate([p.property()],m.prototype,"activeRelationshipInput",null);n.__decorate([p.property()],m.prototype,"_arcadeContextInfo",null);n.__decorate([p.property()],m.prototype,"allFieldInputs",null);n.__decorate([p.property()],m.prototype,"allGroupInputs",null);n.__decorate([p.property()],m.prototype,"allRelationshipInputs",null);
n.__decorate([p.property()],m.prototype,"_layerFieldsByName",null);n.__decorate([p.property()],m.prototype,"arcadeEditType",void 0);n.__decorate([p.property()],m.prototype,"contingencyConstraintViolations",void 0);n.__decorate([p.property()],m.prototype,"disabled",void 0);n.__decorate([p.property()],m.prototype,"feature",null);n.__decorate([p.property()],m.prototype,"fieldsWithContingentValues",null);n.__decorate([p.property()],m.prototype,"fieldsWithInvalidCodedValue",null);n.__decorate([p.property({type:L})],
m.prototype,"formTemplate",null);n.__decorate([p.property()],m.prototype,"formDescription",null);n.__decorate([p.property()],m.prototype,"formTitle",null);n.__decorate([p.property()],m.prototype,"formHeaderVisible",null);n.__decorate([p.property()],m.prototype,"highlightHelper",void 0);n.__decorate([p.property()],m.prototype,"inputs",void 0);n.__decorate([p.property()],m.prototype,"joinedContingentValues",null);n.__decorate([p.property()],m.prototype,"layer",null);n.__decorate([p.property()],m.prototype,
"map",void 0);n.__decorate([p.property()],m.prototype,"relatedRecordCallbacks",void 0);n.__decorate([p.property()],m.prototype,"relationshipId",null);n.__decorate([p.property()],m.prototype,"spatialReference",null);n.__decorate([p.property()],m.prototype,"state",null);n.__decorate([p.property()],m.prototype,"strict",void 0);n.__decorate([p.property()],m.prototype,"submittable",null);n.__decorate([p.property()],m.prototype,"timeZone",null);n.__decorate([p.property()],m.prototype,"updating",null);n.__decorate([p.property()],
m.prototype,"valid",null);n.__decorate([p.property()],m.prototype,"view",null);n.__decorate([p.property()],m.prototype,"getValues",null);n.__decorate([p.property()],m.prototype,"submit",null);return m=n.__decorate([J.subclass("esri.widgets.FeatureForm.FeatureFormViewModel")],m)});