// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("../../chunks/tslib.es6 ../../core/Collection ../../core/Evented ../../core/reactiveUtils ../../core/accessorSupport/decorators/property ../../core/has ../../core/Logger ../../core/RandomLCG ../../core/accessorSupport/decorators/subclass ../LayerList/ListItem ../LayerList/support/layerListUtils".split(" "),function(h,f,x,e,k,z,A,B,y,r,t){const p=f.ofType(r);f=class extends x.EventedAccessor{constructor(a){super(a);this.baseItems=new p;this.baseListItemCreatedFunction=null;this.checkPublishStatusEnabled=
!1;this.referenceListItemCreatedFunction=null;this.referenceItems=new p;this.view=null;this._compileBaseList=this._compileBaseList.bind(this);this._compileReferenceList=this._compileReferenceList.bind(this)}initialize(){this.addHandles([e.watch(()=>[this.view?.map?.basemap,!0===this.view?.ready,this.view?.basemapView],()=>this._watchBasemapLayers(),e.initial),e.watch(()=>[this.baseListItemCreatedFunction,this.checkPublishStatusEnabled],()=>this._baseListItemCreatedFunctionChanged()),e.watch(()=>[this.referenceListItemCreatedFunction,
this.checkPublishStatusEnabled],()=>this._referenceListItemCreatedFunctionChanged())],"view")}destroy(){this.view=null;this.baseItems.removeAll();this.referenceItems.removeAll()}get basemapTitle(){return this.view?.map?.basemap?.title??null}set basemapTitle(a){this._override("basemapTitle",a)}get state(){return this.view?.ready?"ready":this.view?"loading":"disabled"}triggerAction(a,b){a&&!a.disabled&&this.emit("trigger-action",{action:a,item:b})}moveListItem({targetItem:a,fromParentItem:b,toParentItem:c,
from:d,to:g,newIndex:m}){const q=a?.layer;if(q){var n=this.view?.map?.basemap,l=n?.baseLayers,u=n?.referenceLayers;n=b?t.getItemLayers(b):"base"===d?l:u;l=c?t.getItemLayers(c):"base"===g?l:u;if(n&&l){var {baseItems:v,referenceItems:w}=this;g=c?.children||("base"===g?v:w);m=l.length-m;a.parent=c||null;(b?.children||("base"===d?v:w)).remove(a);n.remove(q);g.includes(a)||g.add(a,m);l.includes(q)||l.add(q,m);this._compileLists()}}}_createItemChangeHandles({items:a,key:b,callback:c}){this.removeHandles(b);
c();a&&this.addHandles(a.on("change",()=>c()),b)}_createListItem({layer:a,type:b}){const {view:c,baseListItemCreatedFunction:d,referenceListItemCreatedFunction:g,checkPublishStatusEnabled:m}=this;return new r({layer:a,checkPublishStatusEnabled:m,listItemCreatedFunction:"base"===b?d:g,view:c})}_watchLayersListMode({layers:a,key:b,callback:c}){this.removeHandles(b);a&&a.forEach(d=>{this.addHandles(e.watch(()=>d.listMode,()=>c()),b)})}_compileListItems({layers:a,items:b,key:c,type:d,callback:g}){this._watchLayersListMode({layers:a,
key:c,callback:g});this._createNewItems({type:d,items:b,layers:a});this._removeItems({items:b,layers:a});this._sortItems(b,a)}_compileReferenceList(){const {referenceItems:a}=this;this._compileListItems({type:"reference",layers:this.view?.map?.basemap?.referenceLayers,items:a,key:"base-layers-list-mode",callback:this._compileReferenceList})}_compileBaseList(){const {baseItems:a}=this;this._compileListItems({type:"base",layers:this.view?.map?.basemap?.baseLayers,items:a,key:"reference-layers-list-mode",
callback:this._compileBaseList})}_compileLists(){this._compileReferenceList();this._compileBaseList()}_createNewItems({items:a,layers:b,type:c}){b?.forEach(d=>{a.some(g=>g.layer===d)||a.add(this._createListItem({type:c,layer:d}))})}_removeItems({items:a,layers:b}){a&&a.forEach(c=>{c&&!b?.some(d=>c.layer===d)&&(this.removeHandles(`${"children"}-${c.uid}`),a.remove(c))})}_sortItems(a,b){a&&b&&a.sort((c,d)=>{c=b.indexOf(c.layer);d=b.indexOf(d.layer);return c>d?-1:c<d?1:0})}_removeAllBaseItems(){const {baseItems:a}=
this;a.forEach(b=>{this.removeHandles(`${"children"}-${b.uid}`)});a.removeAll()}_removeAllReferenceItems(){const {referenceItems:a}=this;a.forEach(b=>{this.removeHandles(`${"children"}-${b.uid}`)});a.removeAll()}_baseListItemCreatedFunctionChanged(){this._removeAllBaseItems();this._compileLists()}_referenceListItemCreatedFunctionChanged(){this._removeAllReferenceItems();this._compileLists()}_watchBasemapLayers(){const {view:a}=this;this.removeHandles(["base-layers","reference-layers","basemap","base-layer-views",
"reference-layer-views"]);a?.ready?(this._compileLists(),this.addHandles([e.watch(()=>this.view?.map?.basemap?.baseLayers,b=>this._createItemChangeHandles({items:b,key:"base-layers",callback:this._compileBaseList}),e.initial),e.watch(()=>this.view?.map?.basemap?.referenceLayers,b=>this._createItemChangeHandles({items:b,key:"reference-layers",callback:this._compileReferenceList}),e.initial),e.watch(()=>this.view?.basemapView?.baseLayerViews,b=>this._createItemChangeHandles({items:b,key:"base-layer-views",
callback:this._compileBaseList}),e.initial),e.watch(()=>this.view?.basemapView?.referenceLayerViews,b=>this._createItemChangeHandles({items:b,key:"reference-layer-views",callback:this._compileReferenceList}),e.initial)],"basemap")):(this._removeAllBaseItems(),this._removeAllReferenceItems())}};h.__decorate([k.property({type:p,readOnly:!0})],f.prototype,"baseItems",void 0);h.__decorate([k.property()],f.prototype,"basemapTitle",null);h.__decorate([k.property()],f.prototype,"baseListItemCreatedFunction",
void 0);h.__decorate([k.property()],f.prototype,"checkPublishStatusEnabled",void 0);h.__decorate([k.property()],f.prototype,"referenceListItemCreatedFunction",void 0);h.__decorate([k.property({type:p,readOnly:!0})],f.prototype,"referenceItems",void 0);h.__decorate([k.property({readOnly:!0})],f.prototype,"state",null);h.__decorate([k.property()],f.prototype,"view",void 0);return f=h.__decorate([y.subclass("esri.widgets.BasemapLayerList.BasemapLayerListViewModel")],f)});