// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/tslib.es6 ../../core/Error ../../core/handleUtils ../../core/maybe ../../core/reactiveUtils ../../core/accessorSupport/decorators/property ../../core/has ../../core/Logger ../../core/RandomLCG ../../core/accessorSupport/decorators/subclass ../../layers/GraphicsLayer ../../views/support/layerViewUtils ./UpdateFeatureWorkflowData ./UpdateRecordWorkflow ./workflowUtils ../Sketch/SketchViewModel".split(" "),function(f,r,y,z,A,B,t,K,L,M,C,D,E,F,x,h,G){var u;const c={...x.handleKeys,
highlights:Symbol(),sketchGraphics:Symbol(),sketchViewModel:Symbol()};f.UpdateFeatureWorkflow=u=class extends x.UpdateRecordWorkflow{constructor(a){super(a);this.type="update-feature";this._sketchViewModel=this._sketchGraphicClone=this._layerViewEditSession=null;this._webStyleCache=new Map}initialize(){const {edits:{feature:a},layerView:b}=this.data;h.canCreateInteractiveEditSession(b)&&(this._layerViewEditSession=b.createInteractiveEditSession(a))}destroy(){this._layerViewEditSession?.rollback()}async commit(){this.removeHandles(c.sketchGraphics);
try{const a=this.data.edits.stagedForDelete;await super.commit();const b=this._layerViewEditSession;a?b?.rollback():b?.commit()}catch(a){throw await this._configureSketchViewModel(),new y("editor-workflow:failed-to-commit","An error occurred when sending the updates to the service",{error:a});}}async start(){await super.start();return await this._initializeSketchViewModel()}_initializeFeatureFormViewModel(){super._initializeFeatureFormViewModel();this.addHandles(this._featureFormViewModel.on("value-change",
a=>{this._layerViewEditSession?.setAttribute(a.fieldName,a.value)}))}_configureHighlight(){const {edits:a,layerView:b}=this.data;E.highlightsSupported(b)&&this.addHandles(b.highlight(a.feature),c.highlights)}async _configureSketchViewModel(){var a=this._sketchViewModel;if(a){var {data:b,_featureFormViewModel:m,_sketchGraphicClone:v}=this,{edits:n,viewModel:g}=b,k=n.feature,{view:w}=g,l=h.getVisualVariableAttributes(k);a=await h.setUpGeometryUpdate({feature:k,featureClone:v,visualVariableAttributes:l,
sketchViewModel:a,view:w,onUpdate:({geometry:d,attributes:p},e)=>{n.updateAttributes(p);n.updateGeometry(d);m.feature.geometry=d;null!=l.rotation&&({field:d}=l.rotation,m.setValue(d,p[d]));null!=l.size&&({field:d}=l.size,m.setValue(d,p[d]));("undo"===e.type||"redo"===e.type||"update"===e.type&&null!=e.toolEventInfo&&h.isTerminalUpdateEventType(e.toolEventInfo.type))&&m.notifyFeatureGeometryChanged()},webStyleCache:this._webStyleCache});this.addHandles(a,c.sketchGraphics)}}async _initializeSketchViewModel(){const {data:a,
_sketchGraphicClone:b}=this,m=a.edits.feature,{geometryUpdatesEnabled:v,layer:n}=a.editableItem,{view:g}=a.viewModel;this.removeHandles([c.highlights,c.sketchGraphics,c.sketchViewModel]);if(!v)return{enter:async()=>{this.hasHandles(c.highlights)||this._configureHighlight()},exit:()=>this.removeHandles([c.highlights])};const {viewModel:k}=a,{labelOptions:w,snappingOptions:l,tooltipOptions:d,valueOptions:p}=k,e=new D({elevationInfo:n.elevationInfo,internal:!0,listMode:"hide"}),q=new G({allowDeleteKey:!1,
labelOptions:w,layer:e,snappingOptions:l,tooltipOptions:d,valueOptions:p,updateOnGraphicClick:!1,view:g});this._sketchViewModel=q;this.addHandles([B.watch(()=>[k.labelOptions,k.snappingOptions,k.tooltipOptions],([H,I,J])=>q.set({labelOptions:H,snappingOptions:I,tooltipOptions:J}))]);g?.map.add(e);this.addHandles(z.makeHandle(()=>{g?.destroyed||g?.map.remove(e);e.destroy();this._sketchViewModel=A.destroyMaybe(q)}),c.sketchViewModel);await h.updateGraphicSymbolWhenRequired(b,this._webStyleCache,"2d"===
g?.type?g.scale:null);this.addHandles([await h.swapForEditingSession(q,m,b)]);return{enter:async()=>{this.hasHandles(c.sketchGraphics)||await this._configureSketchViewModel()},exit:()=>this.removeHandles([c.sketchGraphics]),viewModel:q}}_onFullFeatureLoaded(a){super._onFullFeatureLoaded(a);this._sketchGraphicClone=h.cloneGraphicExceptMesh(a);const {edits:b}=this.data;b.updateGeometry(a.geometry);b.trackChanges()}static async create(a){a=new u({data:await F.create(a),onCommit:this._onCommitFactory(a.applyEdits)});
a._set("steps",this._createWorkflowSteps(a));return a}get test(){return{graphicClone:this._sketchGraphicClone}}};r.__decorate([t.property()],f.UpdateFeatureWorkflow.prototype,"_layerViewEditSession",void 0);r.__decorate([t.property()],f.UpdateFeatureWorkflow.prototype,"_sketchGraphicClone",void 0);r.__decorate([t.property()],f.UpdateFeatureWorkflow.prototype,"_sketchViewModel",void 0);f.UpdateFeatureWorkflow=u=r.__decorate([C.subclass("esri.widgets.Editor.UpdateFeatureWorkflow")],f.UpdateFeatureWorkflow);
f.handleKeys=c;Object.defineProperty(f,Symbol.toStringTag,{value:"Module"})});