// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("require exports ../../../../chunks/tslib.es6 ../core/shaderLibrary/ShaderOutput ../core/shaderTechnique/ReloadableShaderModule ../core/shaderTechnique/ShaderTechnique ../core/shaderTechnique/ShaderTechniqueConfiguration ../lib/basicInterfaces ../lib/OrderIndependentTransparency ../lib/Program ../lib/StencilUtils ../lib/TransparencyPassType ../lib/VertexAttribute ../materials/DefaultTechniqueConfiguration ../materials/PatternStyle ../../../../chunks/Pattern.glsl ../../../webgl/renderState".split(" "),
function(v,h,b,k,w,x,c,t,f,y,n,l,g,z,A,B,m){class p extends x.ShaderTechnique{initializeProgram(d){return new y.Program(d.rctx,p.shader.get().build(this.configuration),u)}_setPipelineState(d,q){const e=this.configuration,r=d===l.TransparencyPassType.NONE,C=d===l.TransparencyPassType.FrontFace;return m.makePipelineState({blending:e.output===k.ShaderOutput.Color||e.output===k.ShaderOutput.Alpha?r?f.blendingDefault:f.oitBlending(d):null,culling:m.cullingParams(e.cullFace),depthTest:e.draped?null:{func:f.oitDepthTest(d)},
depthWrite:e.draped?null:r?m.defaultDepthWriteParams:f.oitDepthWrite(d),colorWrite:m.defaultColorWriteParams,stencilWrite:e.hasOccludees?n.stencilWriteMaskOn:null,stencilTest:e.hasOccludees?q?n.stencilToolMaskBaseParams:n.stencilBaseAllZerosParams:null,polygonOffset:r||C?e.polygonOffset?D:null:f.getOITPolygonOffset(e.enableOffset)})}initializePipeline(){this._occludeePipelineState=this._setPipelineState(this.configuration.transparencyPassType,!0);return this._setPipelineState(this.configuration.transparencyPassType,
!1)}getPipeline(d){return d?this._occludeePipelineState:super.getPipeline()}}p.shader=new w.ReloadableShaderModule(B.Pattern,()=>new Promise((d,q)=>v(["./Pattern.glsl"],d,q)));const D={factor:1,units:1};class a extends z.DefaultTechniqueConfiguration{constructor(){super(...arguments);this.output=k.ShaderOutput.Color;this.cullFace=t.CullFaceOptions.None;this.transparencyPassType=l.TransparencyPassType.NONE;this.hasOccludees=this.polygonOffset=this.hasVertexColors=this.hasSlicePlane=!1;this.enableOffset=
!0;this.vvColor=this.cullAboveGround=this.multipassEnabled=!1}}b.__decorate([c.parameter({count:k.ShaderOutput.COUNT})],a.prototype,"output",void 0);b.__decorate([c.parameter({count:t.CullFaceOptions.COUNT})],a.prototype,"cullFace",void 0);b.__decorate([c.parameter({count:A.Style.COUNT})],a.prototype,"style",void 0);b.__decorate([c.parameter({count:l.TransparencyPassType.COUNT})],a.prototype,"transparencyPassType",void 0);b.__decorate([c.parameter()],a.prototype,"hasSlicePlane",void 0);b.__decorate([c.parameter()],
a.prototype,"hasVertexColors",void 0);b.__decorate([c.parameter()],a.prototype,"polygonOffset",void 0);b.__decorate([c.parameter()],a.prototype,"hasOccludees",void 0);b.__decorate([c.parameter()],a.prototype,"patternSpacing",void 0);b.__decorate([c.parameter()],a.prototype,"lineWidth",void 0);b.__decorate([c.parameter()],a.prototype,"enableOffset",void 0);b.__decorate([c.parameter()],a.prototype,"draped",void 0);b.__decorate([c.parameter()],a.prototype,"multipassEnabled",void 0);b.__decorate([c.parameter()],
a.prototype,"cullAboveGround",void 0);b.__decorate([c.parameter()],a.prototype,"vvColor",void 0);b.__decorate([c.parameter({constValue:!0})],a.prototype,"writeDepth",void 0);b.__decorate([c.parameter({constValue:!1})],a.prototype,"occlusionPass",void 0);b.__decorate([c.parameter({constValue:!1})],a.prototype,"hasVvInstancing",void 0);b.__decorate([c.parameter({constValue:!1})],a.prototype,"vvSize",void 0);b.__decorate([c.parameter({constValue:!1})],a.prototype,"vvOpacity",void 0);const u=new Map([[g.VertexAttribute.POSITION,
0],[g.VertexAttribute.COLOR,3],[g.VertexAttribute.UVMAPSPACE,4],[g.VertexAttribute.COLORFEATUREATTRIBUTE,5],[g.VertexAttribute.BOUNDINGRECT,6]]);h.PatternTechnique=p;h.PatternTechniqueConfiguration=a;h.vertexAttributeLocations=u;Object.defineProperty(h,Symbol.toStringTag,{value:"Module"})});