// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/maybe ../../../../core/screenUtils ../../../../core/libs/gl-matrix-2/mat2d ../../../../core/libs/gl-matrix-2/mat2df32 ../../../../core/libs/gl-matrix-2/vec2 ../../../../core/libs/gl-matrix-2/vec2f32 ../../../../geometry/SpatialReference ../../../../geometry/support/aaBoundingRect ../../../../geometry/support/boundsUtils ../../../../geometry/support/intersects ../../../../geometry/support/jsonUtils ../../../../geometry/support/normalizeUtils ../../../../geometry/support/spatialReferenceUtils ../../../../geometry/support/spatialReferenceUtils ../../engine".split(" "),
function(ja,q,Y,p,n,Z,g,w,A,aa,K,L,t,M,ba,ca,m){function N(a,d,c,b,e){var f,l,u=p.pt2px(c.xoffset),k=p.pt2px(c.yoffset),r=v*c.angle;e*=v;switch(c.type){case "simple-marker":f=l=p.pt2px(c.size);break;case "picture-marker":f=p.pt2px(c.width),l=p.pt2px(c.height)}c=n.mat2d.identity(E);n.mat2d.translate(c,c,g.vec2.set(h,a,d));n.mat2d.rotate(c,c,e-r);n.mat2d.scale(c,c,g.vec2.set(h,b,-b));n.mat2d.translate(c,c,g.vec2.set(h,u,-k));a=[0,0];g.vec2.transformMat2d(a,g.vec2.set(h,-.5*f,-.5*l),c);d=[0,0];g.vec2.transformMat2d(d,
g.vec2.set(h,-.5*f,.5*l),c);b=[0,0];g.vec2.transformMat2d(b,g.vec2.set(h,.5*f,-.5*l),c);u=[0,0];g.vec2.transformMat2d(u,g.vec2.set(h,.5*f,.5*l),c);return{rings:[[a,b,u,d,a]]}}function O(a,d,c,b,e){var f=m.CIMSymbolHelper.getEnvelope(c.data);if(!f)return null;c=p.pt2px(f.width);var l=p.pt2px(f.height),u=p.pt2px(f.x),f=p.pt2px(f.y),k=0*v,r=v*e;e=n.mat2d.identity(E);n.mat2d.translate(e,e,g.vec2.set(h,a,d));n.mat2d.rotate(e,e,r-k);n.mat2d.scale(e,e,g.vec2.set(h,b,b));a=[0,0];g.vec2.transformMat2d(a,g.vec2.set(h,
u,f+l),e);d=[0,0];g.vec2.transformMat2d(d,g.vec2.set(h,u,f),e);b=[0,0];g.vec2.transformMat2d(b,g.vec2.set(h,u+c,f+l),e);l=[0,0];g.vec2.transformMat2d(l,g.vec2.set(h,u+c,f),e);return{rings:[[a,b,l,d,a]]}}function P(a,d,c,b,e,f){var l=m.alignmentUtils.getYAnchorDirection(c.verticalAlignment||"baseline"),u="baseline"===(c.verticalAlignment||"baseline"),k=p.pt2px(c.xoffset),r=p.pt2px(c.yoffset),Q=p.pt2px(c.font.size)/24,R=4*Q,l=u?25*Q:b[1]+(1+l)*b[3]*.5;c=v*c.angle;u=v*f;f=n.mat2d.identity(E);n.mat2d.translate(f,
f,g.vec2.set(h,a,d));n.mat2d.rotate(f,f,u-c);n.mat2d.scale(f,f,g.vec2.set(h,e,-e));n.mat2d.translate(f,f,g.vec2.set(h,k,-r));n.mat2d.translate(f,f,g.vec2.set(h,-R,-R-l));a=[0,0];g.vec2.transformMat2d(a,g.vec2.set(h,b[0],b[1]),f);d=[0,0];g.vec2.transformMat2d(d,g.vec2.set(h,b[0],b[1]+b[3]),f);e=[0,0];g.vec2.transformMat2d(e,g.vec2.set(h,b[0]+b[2],b[1]),f);k=[0,0];g.vec2.transformMat2d(k,g.vec2.set(h,b[0]+b[2],b[1]+b[3]),f);return{rings:[[a,e,k,d,a]]}}function F(a,d,c){if(!c||0===c.glyphMosaicItems.length)return a;
var b=m.bidiText(d.text),e=b[0],b=b[1],f=m.alignmentUtils.getJustification(d.horizontalAlignment||"center"),l=m.alignmentUtils.getXAnchorDirection(d.horizontalAlignment||"center");c=(new m.TextShapingNew([c.glyphMosaicItems],m.definitions.TEXT_MAX_WIDTH,m.definitions.TEXT_LINE_HEIGHT,m.definitions.TEXT_SPACING,[0,.5*-G],.5*(1-l),0,f)).getShaping(e,b);e=m.fontUtils.getFontDecorationTop(d.font.decoration);isNaN(e)||m.TextShapingNew.addDecoration(c,e);c=m.TextShapingNew.getBox(c);d=p.pt2px(d.font.size)/
S;a[0]=d*c.x;a[1]=d*c.y;a[2]=d*c.width;a[3]=d*c.height;return a}function x(a,d){return Math.ceil((a-d)/(2*d))}function da(a,d){var c;c=t.isPolygon(a)?a.rings:a.paths;for(var b=0;b<c.length;b++)for(var e=0,f=c[b];e<f.length;e++)f[e][0]+=d;return a}function ea(a,d){if(!d)return a;var c=fa(a,d).map(function(b){return b.extent});return 2>c.length?c[0]||a:2<c.length?(a.xmin=d.valid[0],a.xmax=d.valid[1],a):{rings:c.map(function(b){return[[b.xmin,b.ymin],[b.xmin,b.ymax],[b.xmax,b.ymax],[b.xmax,b.ymin],[b.xmin,
b.ymin]]})}}function fa(a,d){var c=[],b=a.ymin,e=a.ymax,f=a.xmax-a.xmin,l=a.xmin,g=a.xmax,k,r=d.valid,m=r[0],h=r[1];k=T(a.xmin,d);var n=k.x,r=k.frameId;k=T(a.xmax,d);d=k.x;a=k.frameId;k=n===d&&0<f;if(f>2*h){f={xmin:l<g?n:d,ymin:b,xmax:h,ymax:e};l={xmin:m,ymin:b,xmax:l<g?d:n,ymax:e};g={xmin:0,ymin:b,xmax:h,ymax:e};b={xmin:m,ymin:b,xmax:0,ymax:e};e=[];m=[];B(f,g)&&e.push(r);B(f,b)&&m.push(r);B(l,g)&&e.push(a);B(l,b)&&m.push(a);for(h=r+1;h<a;h++)e.push(h),m.push(h);c.push({extent:f,frameIds:[r]},{extent:l,
frameIds:[a]},{extent:g,frameIds:e},{extent:b,frameIds:m})}else n>d||k?c.push({extent:{xmin:n,ymin:b,xmax:h,ymax:e},frameIds:[r]},{extent:{xmin:m,ymin:b,xmax:d,ymax:e},frameIds:[a]}):c.push({extent:{xmin:n,ymin:b,xmax:d,ymax:e},frameIds:[r]});return c}function T(a,d){var c=d.valid;d=c[0];var b=c[1],c=2*b,e=0;a>b?(d=Math.ceil(Math.abs(a-b)/c),a-=d*c,e=d):a<d&&(d=Math.ceil(Math.abs(a-d)/c),a+=d*c,e=-d);return{x:a,frameId:e}}function B(a,d){var c=d.xmin,b=d.ymin,e=d.xmax;d=d.ymax;return C(a,c,b)&&C(a,
c,d)&&C(a,e,d)&&C(a,e,b)}function C(a,d,c){return d>=a.xmin&&d<=a.xmax&&c>=a.ymin&&c<=a.ymax?!0:!1}function U(a,d,c){if(Array.isArray(a)){var b=a[0];if(b>d){var e=x(b,d);a[0]=b+-2*e*d}else b<c&&(e=x(b,c),a[0]=b+-2*e*c)}else b=a.x,b>d?(e=x(b,d),a.x+=-2*e*d):b<c&&(e=x(b,c),a.x+=-2*e*c);return a}Object.defineProperty(q,"__esModule",{value:!0});var v=Math.PI/180,ga=m.definitions.TEXT_MAX_WIDTH,G=m.definitions.TEXT_LINE_HEIGHT,ha=m.definitions.TEXT_SPACING,E=Z.mat2df32.create(),h=w.vec2f32.create(),y=
aa.create();q.getBounds=function(a,d,c,b,e,f){if(!b||!c.symbol)return a[0]=a[1]=a[2]=a[3]=0,d[0]=d[1]=d[2]=d[3]=0,a;if(t.isPoint(b)){var l=b.x;b=b.y;"text"===c.symbol.type&&0===d[2]&&0===d[3]&&F(d,c.symbol,c.mosaicItem);c=c.symbol;var g;switch(c.type){case "simple-marker":case "picture-marker":g=N(l,b,c,e,0);break;case "text":g=P(l,b,c,d,e,0);break;case "cim":case "expanded-cim":g=O(l,b,c,e,0)}for(e=d=0;e<g.rings[0].length-1;e++)c=g.rings[0][e],c=(l-c[0])*(l-c[0])+(b-c[1])*(b-c[1]),d=Math.max(d,c);
d=Math.sqrt(d);e=M.normalizeMapX(l-d,f);l=M.normalizeMapX(l+d,f);e>l&&(f=ca.getInfo(f))&&(e=f.valid,f=e[1],e=e[0],l=f);a[0]=e;a[1]=b-d;a[2]=l;a[3]=b+d}else{K.getBoundsXY(a,b);b=d[0];if(0===b){a:switch(b=0,c.symbol.type){case "simple-fill":case "picture-fill":b=c.symbol.outline;if(!b){b=0;break a}b=b.width;break;case "simple-line":b=c.symbol.width;break;case "simple-marker":b=c.symbol.size;break;case "picture-marker":b=Math.max(c.symbol.width,c.symbol.height);break;case "text":b=[0,0,0,0];F(b,c.symbol,
c.mosaicItem);b=Math.max(b[0],b[1]);break;case "cim":case "expanded-cim":b=m.CIMSymbolHelper.getEnvelope(c.symbol.data),b=Math.sqrt(b.width*b.width+b.height*b.height)}d[0]=b}b=e*b/2;a[0]-=b;a[1]-=b;a[2]+=b;a[3]+=b}return a};q.isMarkerSymbol=function(a){return"simple-marker"===a||"picture-marker"===a||"text"===a};q.graphicGeometryToNumber=function(a){switch(Y.expect(a.geometry).type){case "polyline":return 1;case "polygon":case "extent":return 2}return 0};var H=w.vec2f32.create(),V=w.vec2f32.create(),
W=w.vec2f32.create(),z=w.vec2f32.create(),I=w.vec2f32.create(),X=w.vec2f32.create(),J=w.vec2f32.create();q.isPointOnPolyline=function(a,d,c,b){g.vec2.set(W,d,c);a=a.paths;for(var e,f,l,h,k,m,n,p,q=Infinity,w=0;w<a.length;w++){var t=a[w];if(!(2>t.length))for(var v=1;v<t.length;v++)e=t[v-1][0],l=t[v-1][1],f=t[v][0],h=t[v][1],k=Math.min(e,f)-b,m=Math.min(l,h)-b,n=Math.max(e,f)+b,p=Math.max(l,h)+b,d<k||d>n||c<m||c>p||(g.vec2.set(H,e,l),g.vec2.set(V,f,h),g.vec2.subtract(z,V,H),g.vec2.subtract(I,H,W),g.vec2.scale(X,
z,g.vec2.dot(z,I)/g.vec2.dot(z,z)),g.vec2.subtract(J,I,X),e=g.vec2.dot(J,J),q>e&&(q=e))}return Math.sqrt(q)<=b};q.getMarkerSymbolBounds=N;q.getCIMMarkerBounds=O;q.getTextSymbolBounds=P;q.normalizeCentralMeridian=function(a){var d,c,b,e,f,g=null;if(!a)return null;d=a.spatialReference;c=ba.getInfo(d);f=d.isWebMercator?102100:4326;b=D[f].maxX;e=D[f].minX;d=D[f].plus180Line;f=D[f].minus180Line;var h,k=a.toJSON();if(!c)return k;"mesh"===a.type?h=k:t.isPoint(k)?h=U(k,b,e):t.isMultipoint(k)?(k.points=k.points.map(function(a){return U(a,
b,e)}),h=k):t.isExtent(k)?h=ea(k,c):t.isPolygon(k)||t.isPolyline(k)?(K.getBoundsXY(y,k),a={xmin:y[0],ymin:y[1],xmax:y[2],ymax:y[3]},c=2*x(a.xmin,e)*b,k=0===c?k:da(k,c),a.xmin+=c,a.xmax+=c,L.extentIntersectsPolyline(a,d)&&a.xmax!==b?g=k:L.extentIntersectsPolyline(a,f)&&a.xmin!==e?g=k:h=k):h=a.clone();return null!==g?(new ia).cut(g,b):h};var S=24;q.getTextSymbolSize=F;q.getTextSymbolEstimatedSize=function(a,d,c){var b=m.bidiText(d.text),e=b[0],b=b[1],f=m.alignmentUtils.getJustification(d.horizontalAlignment||
"center"),g=m.alignmentUtils.getXAnchorDirection(d.horizontalAlignment||"center");c=(new m.TextShapingNew([],ga,G,ha,[0,.5*-G],.5*(1-g),0,f)).getEstimatedShaping(e,b,c);c=m.TextShapingNew.getBox(c);d=p.pt2px(d.font.size)/S;a[0]=d*c.x;a[1]=d*c.y;a[2]=d*c.width;a[3]=d*c.height;return a};var D={102100:{maxX:2.0037508342788905E7,minX:-2.0037508342788905E7,plus180Line:{paths:[[[2.0037508342788905E7,-2.0037508342788905E7],[2.0037508342788905E7,2.0037508342788905E7]]],spatialReference:A.WebMercator},minus180Line:{paths:[[[-2.0037508342788905E7,
-2.0037508342788905E7],[-2.0037508342788905E7,2.0037508342788905E7]]],spatialReference:A.WebMercator}},4326:{maxX:180,minX:-180,plus180Line:{paths:[[[180,-180],[180,180]]],spatialReference:A.WGS84},minus180Line:{paths:[[[-180,-180],[-180,180]]],spatialReference:A.WGS84}}},ia=function(){function a(){}a.prototype.cut=function(a,c){var b;if(a.rings)this.closed=!0,b=a.rings,this.minPts=4;else if(a.paths)this.closed=!1,b=a.paths,this.minPts=2;else return null;var d=b.length;c*=-2;for(var f=0;f<d;f++){var g=
b[f];if(g&&g.length>=this.minPts){for(var h=[],k=0;k<g.length;k++){var m=g[k];h.push([m[0]+c,m[1]])}b.push(h)}}this.closed?a.rings=b:a.paths=b;return a};return a}()});