// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("exports ../../Color ../../core/arrayUtils ./support/colors ./support/symbologyUtils ./support/utils".split(" "),function(g,d,w,x,p,r){function t(a){const b=p.getRawSchemes({basemap:a.basemap,geometryType:a.geometryType,basemapTheme:a.basemapTheme,theme:u.get(a.theme||"default")});if(b){var {schemesInfo:c,basemapId:e,basemapTheme:f}=b,h=c.common;return{primaryScheme:v(a,c.primary,h),secondarySchemes:c.secondary.map(y=>v(a,y,h)).filter(w.isSome),basemapId:e,basemapTheme:f}}}function v(a,b,c){const e=
a.theme||"default";if(b=x[b]){var f=b.stops,h="mesh"!==a.geometryType&&a.worldScale?a.view:null;switch(a.geometryType){case "point":case "multipoint":return"point-cloud-class"===e?z({theme:e,name:b.name,tags:b.tags,colors:f}):A({name:b.name,tags:b.tags,theme:e,colors:f,noDataColor:c.noDataColor,opacity:1,outline:c.outline,size:c.size},h);case "polyline":return B({name:b.name,tags:b.tags,theme:e,colors:f,noDataColor:c.noDataColor,opacity:1,width:c.width},h);case "polygon":return C({name:b.name,tags:b.tags,
theme:e,colors:f,noDataColor:c.noDataColor,opacity:c.fillOpacity||1,outline:c.outline,size:"12px"},h);case "mesh":return D({name:b.name,tags:b.tags,theme:e,colors:f,noDataColor:c.noDataColor,opacity:c.fillOpacity||1})}}}function z(a){return{name:a.name,tags:[...a.tags],theme:a.theme,colors:a.colors.map(b=>new d(b))}}function A(a,b){return{name:a.name,tags:[...a.tags],theme:a.theme,colors:a.colors.map(c=>new d(c)),noDataColor:new d(a.noDataColor),outline:{color:new d(a.outline.color),width:a.outline.width},
size:b?r.toWorldScale(a.size,b):a.size,opacity:a.opacity}}function B(a,b){return{name:a.name,tags:[...a.tags],theme:a.theme,colors:a.colors.map(c=>new d(c)),noDataColor:new d(a.noDataColor),width:b?r.toWorldScale(a.width,b):a.width,opacity:a.opacity}}function C(a,b){return{name:a.name,tags:[...a.tags],theme:a.theme,colors:a.colors.map(c=>new d(c)),noDataColor:new d(a.noDataColor),outline:{color:new d(a.outline.color),width:a.outline.width},opacity:a.opacity,size:b?r.toWorldScale(a.size,b):a.size}}
function D(a){return{name:a.name,tags:[...a.tags],theme:a.theme,colors:a.colors.map(b=>new d(b)),noDataColor:new d(a.noDataColor),opacity:a.opacity}}var q={color:[153,153,153,.25],width:"1px"};const k="tropical-bliss desert-blooms under-the-sea vibrant-rainbow ocean-bay prairie-summer pastel-chalk".split(" "),l="predominant-v1 predominant-v2 predominant-v3 predominant-v4 predominant-v5 predominance-race predominance-money predominance-race-ethnic predominance-rainbow predominance-sequence".split(" "),
m="cat-symbols-strong cat-symbols-autumnal cat-symbols-bright cat-symbols-midrange cat-symbols-subdued cat-symbols-pastel cat-symbols-red cat-symbols-blue cat-symbols-green cat-symbols-gray".split(" "),n=["cat-popup-olympic-sunset"],E={light:{common:{noDataColor:"#aaaaaa",outline:q,size:"8px"},primary:"cat-dark",secondary:["cat-light"].concat(m).concat(k).concat(l).concat(n)},dark:{common:{noDataColor:"#aaaaaa",outline:{color:[26,26,26,.25],width:"1px"},size:"8px"},primary:"cat-light",secondary:["cat-dark"].concat(m).concat(k).concat(l).concat(n)}},
F={light:{common:{noDataColor:"#aaaaaa",width:"2px"},primary:"cat-dark",secondary:["cat-light"].concat(m).concat(k).concat(l).concat(n)},dark:{common:{noDataColor:"#aaaaaa",width:"2px"},primary:"cat-light",secondary:["cat-dark"].concat(m).concat(k).concat(l).concat(n)}};q={light:{common:{noDataColor:"#aaaaaa",outline:q,fillOpacity:.8},primary:"cat-dark",secondary:["cat-light"].concat(m).concat(k).concat(l).concat(n)},dark:{common:{noDataColor:"#aaaaaa",outline:{color:[153,153,153,.25],width:"1px"},
fillOpacity:.8},primary:"cat-light",secondary:["cat-dark"].concat(m).concat(k).concat(l).concat(n)}};const u=p.createThemes({themeDictionary:{default:{name:"default",label:"Default",description:"Default theme for visualizing features by their type.",schemes:{point:E,polyline:F,polygon:q}},"point-cloud-class":{name:"point-cloud-class",label:"Point Cloud Class",description:"Default theme for visualizing point cloud data based on classification.",schemes:{point:{light:{primary:"point-cloud-class-scheme",
secondary:[]},dark:{primary:"point-cloud-class-scheme",secondary:[]}}}}}});g.cloneScheme=function(a){if(a)return a={...a},a.colors=a.colors.map(b=>new d(b)),a.tags=[...a.tags],"noDataColor"in a&&a.noDataColor&&(a.noDataColor=new d(a.noDataColor)),"outline"in a&&a.outline&&(a.outline={color:a.outline.color&&new d(a.outline.color),width:a.outline.width}),a};g.getSchemeByName=function(a){return p.filterSchemesByName(a.name,t(a))};g.getSchemes=t;g.getSchemesByTag=function(a){return p.filterSchemesByTag(a.includedTags,
a.excludedTags,t(a))};g.getThemes=function(a){return p.getThemesforBasemap(u,a)};Object.defineProperty(g,Symbol.toStringTag,{value:"Module"})});