// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/assignHelper ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/awaiterHelper ../../../core/maybe ../../../core/promiseUtils ../../../core/scheduling ../../../core/urlUtils ../webgl-engine/lib/Texture".split(" "),function(f,g,m,n,p,q,k,r,t,u){Object.defineProperty(g,"__esModule",{value:!0});f=function(){function d(a,c,b,d){void 0===d&&(d=r.schedule);this._streamDataRequester=a;this._stage=c;this._textureOptions=b;this._schedule=d;this._textureRequests=
new Map}d.prototype.destroy=function(){var a=this;this._textureRequests.forEach(function(c){return a.releaseTextureRequest(c)});this._textureRequests=null};d.prototype.fromUrl=function(a,c,b){return p(this,void 0,void 0,function(){var d,h,e,f,g,l=this;return n(this,function(m){k.throwIfAborted(b);d=q.isSome(b)&&b.signal;h=this.makeUid(a,c);e=this._textureRequests.get(h);e||(f=k.createAbortController(),g=this._streamDataRequester.request(a,"image",{uid:h,signal:f.signal}),e={referenceCount:0,texture:null,
textureAsync:null,abortController:f},this._textureRequests.set(h,e),e.textureAsync=g.then(function(b){b=l.createTexture(a,b,c);e.texture=b;e.abortController=null;l.addToStage(b);return{uid:h,texture:b}},function(a){e.abortController=null;throw a;}));e.referenceCount++;return[2,k.create(function(a,b){k.onAbort(d,function(){b(k.createAbortError())});e.textureAsync.then(a,b)}).catch(function(a){l.release(h);throw a;})]})})};d.prototype.fromData=function(a,c){a=this.makeUid(a);var b=this._textureRequests.get(a);
b||(b={referenceCount:0,texture:c(),textureAsync:null,abortController:null},this.addToStage(b.texture),this._textureRequests.set(a,b));b.referenceCount++;return{uid:a,texture:b.texture}};d.prototype.release=function(a){var c=this;if(this._textureRequests){var b=this._textureRequests.get(a);b?(1>b.referenceCount&&console.warn("TextureCollection: reference count is \x3c 1 for "+a),b.referenceCount--,1>b.referenceCount&&this._schedule(function(){return c.releaseNow(a)})):console.warn("TextureCollection: texture doesn't exist: '"+
a+"'")}};Object.defineProperty(d.prototype,"test",{get:function(){return{textureRequests:this._textureRequests}},enumerable:!0,configurable:!0});d.prototype.releaseNow=function(a){if(this._textureRequests){var c=this._textureRequests.get(a);!c||0<c.referenceCount||(this.releaseTextureRequest(c),this._textureRequests.delete(a))}};d.prototype.releaseTextureRequest=function(a){a.texture?this.removeFromStage(a.texture):a.abortController&&(a.abortController.abort(),a.abortController=null)};d.prototype.createTexture=
function(a,c,b){t.isSVG(a)&&(b||0===c.width&&0===c.height)&&(a=c.width?c.height/c.width:1,b=b||64,1<a?(c.width=Math.round(b/a),c.height=b):(c.width=b,c.height=Math.round(b*a)));b=m({},this._textureOptions,{width:c.width,height:c.height,powerOfTwoResizeMode:2});return new u(c,"symbol",b)};d.prototype.addToStage=function(a){this._stage.add(4,a)};d.prototype.removeFromStage=function(a){this._stage.remove(4,a.id)};d.prototype.makeUid=function(a,c){return null!=c?a+"."+c+"px":a};return d}();g.TextureCollection=
f;g.default=f});