// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/tsSupport/generatorHelper ../../core/tsSupport/awaiterHelper ../../core/Accessor ../../core/arrayUtils ../../core/Handles ../../core/Logger ../../core/promiseUtils ../../core/watchUtils ../../core/accessorSupport/decorators ../../geometry/support/heightModelInfoUtils ../../geometry/support/webMercatorUtils @dojo/framework/shim/Promise".split(" "),function(u,D,v,g,w,x,y,k,z,A,B,p,e,q,r){function l(e){return e?
JSON.stringify(e.toJSON()):"undefined"}function t(e){switch(e){case 0:return"Waiting";case 1:return"Found";case 2:return"Exhausted"}return"Unknown: "+e}var C=A.getLogger("esri.views.support.DefaultsFromMap");return function(m){function c(){var a=null!==m&&m.apply(this,arguments)||this;a._handles=new z;a._waitTask=null;a._extentProjectController=null;a._spatialReferenceCandidates=null;a._extentCandidates=null;a.logDebugInformation=!1;a.isSpatialReferenceDone=!1;a.isTileInfoDone=!1;a.isHeightModelInfoSearching=
!1;a.spatialReference=null;a.extent=null;a.heightModelInfo=null;a.vcsWkid=null;a.latestVcsWkid=null;a.mapCollectionPaths=n.DefaultMapCollectionPaths.slice();a.tileInfo=null;return a}v(c,m);n=c;c.prototype.initialize=function(){var a=this;this.watch("mapCollectionPaths",function(){a._running&&(a.reset(),a.start())})};c.prototype.destroy=function(){this._set("view",null);this._handles&&(this._handles.destroy(),this._handles=null);this._cancelLoading()};Object.defineProperty(c.prototype,"_running",{get:function(){return!!(this._handles&&
0<this._handles.size)},enumerable:!0,configurable:!0});c.prototype.reset=function(){this._handles.removeAll();this._set("isSpatialReferenceDone",!1);this._set("isTileInfoDone",!1);this._set("isHeightModelInfoSearching",!1);this._set("spatialReference",null);this._set("extent",null);this._set("heightModelInfo",null);this._set("vcsWkid",null);this._set("latestVcsWkid",null);this._set("tileInfo",null);this._extentCandidates=this._spatialReferenceCandidates=null};c.prototype.start=function(){var a=this;
this._handles.removeAll();for(var b=this._updateLayerChange.bind(this),d=0,f=this.mapCollectionPaths;d<f.length;d++)this._handles.add(p.on(this.view,"map."+f[d],"change",b,b,b,!0));this._handles.add(p.when(this,"isSpatialReferenceDone",function(){return a._updateTileInfo()},!0))};c.prototype._ownerNameFromCollectionName=function(a){var b=a.lastIndexOf(".");return-1===b?"view":"view."+a.slice(0,b)};c.prototype._ensureLoadedOwnersFromCollectionName=function(a){for(var b=this._ownerNameFromCollectionName(a).split("."),
d,f=0;f<b.length;f++){d=this.get(b.slice(0,f+1).join("."));if(!d)break;if(d.load&&!d.isFulfilled())return{collectionName:a,owner:null,loading:d.load().catch(function(){})}}return{collectionName:a,owner:d}};c.prototype._cancelLoading=function(){this._waitTask=null;this._extentProjectController&&(this._extentProjectController.abort(),this._extentProjectController=null)};c.prototype._updateWhen=function(a){var b=this,d=!0,f=!1,c=a.catch(function(){}).then(function(){d?f=!0:c===b._waitTask&&b._update()}),
d=!1;f||(this._waitTask=c);return f};c.prototype._updateLayerChange=function(){this.isSpatialReferenceDone&&!this.spatialReference&&this._set("isSpatialReferenceDone",!1);this._update()};c.prototype._update=function(){var a=this;this._cancelLoading();if(this.view){if(!this.isSpatialReferenceDone){this._debugLog("Starting search for spatial reference...");var b=this._processMapCollections(function(b){return a._processSpatialReferenceSource(b)});this._debugLog("Search ended with status '"+t(b)+"'");
if(0!==b){var d=null,b=this._spatialReferenceCandidates;!b||1>b.length?(d=this.defaultSpatialReference,this._debugLog("No spatial reference found, locking to default ("+l(d)+")")):(this.defaultSpatialReference&&1<b.length&&-1<k.findIndex(b,function(b){return b.equals(a.defaultSpatialReference)})&&(b=[this.defaultSpatialReference]),d=b[0],this._debugLog("Locking to "+l(d)));this._set("spatialReference",d);d?this.extent?this._set("isSpatialReferenceDone",!0):(b=this.logDebugInformation,this.logDebugInformation=
!1,this._processMapCollections(function(b){return a._findExtent(b,d)}),this.logDebugInformation=b,this._projectExtentCandidate().catch().then(function(){return a._set("isSpatialReferenceDone",!0)})):this._set("isSpatialReferenceDone",!0)}}null==this.heightModelInfo&&this.view.isHeightModelInfoRequired&&(this._debugLog("Starting search for height model info..."),b=this._processMapCollections(function(b){return a._processHeightModelInfoSource(b)},function(a){return q.mayHaveHeightModelInfo(a)}),this._debugLog("Search ended with status "+
t(b)),this._set("isHeightModelInfoSearching",0===b));this._updateTileInfo()}};c.prototype._processMapCollections=function(a,b){var d=this;this._preloadMapCollections(b);var c=2;this._forAllMapCollectionSources(function(a){if(2!==c)return!1;d._debugLog("Processing collection "+a.collectionName+"...");return a.loading&&!d._updateWhen(a.loading)?(d._debugLog("Collection "+a.collectionName+" owner is loading -\x3e wait"),c=0,!1):!0},function(f){return 2!==c?!1:null==b||b(f)?!f.load||f.isFulfilled()||
d._updateWhen(f.load())?f.load&&!f.isResolved()||!a(f)?!0:(c=1,!1):(d._debugLog("Source "+f.id+" is loading -\x3e wait"),c=0,!1):(d._debugLog("Source "+f.id+" is skipped due to predicate"),!1)});return c};c.prototype._preloadMapCollections=function(a){var b=this,d=10,c=this.logDebugInformation;this.logDebugInformation=!1;this._forAllMapCollectionSources(function(){return!0},function(f){if(0===d||null!=a&&!a(f))return!1;f.load&&!f.isFulfilled()&&(b.logDebugInformation=c,b._debugLog("Pre-loading source "+
f.id),b.logDebugInformation=!1,f.load().catch(function(){}),d--);return!0});this.logDebugInformation=c};c.prototype._forAllMapCollectionSources=function(a,b){for(var d=0,c=this.mapCollectionPaths;d<c.length;d++){var e="map."+c[d],h=this._ensureLoadedOwnersFromCollectionName(e);!1!==a(h)&&(h=h.owner,!h||h.isRejected&&h.isRejected()?this._debugLog("Collection "+e+" owner is invalid or rejected -\x3e skip"):(h=this.view.get(e))?this._forEachSource(h,b):this._debugLog("Collection "+e+" does not exist -\x3e skip"))}};
c.prototype._forEachSource=function(a,b){var d=0;for(a=a.items;d<a.length;d++){var c=a[d];!1!==b(c)&&"layers"in c&&c.layers&&this._forEachSource(c.layers,b)}};c.prototype._processSpatialReferenceSource=function(a){var b=this._getSupportedSpatialReferences(a);if(0===b.length)return!1;this._spatialReferenceCandidates?(b=k.intersect(b,this._spatialReferenceCandidates,function(a,b){return a.equals(b)}),0<b.length?this._spatialReferenceCandidates=b:this._debugLog("Layer "+a.id+" is ignored because its supported spatial\n          references are not compatible with the previous candidates")):
this._spatialReferenceCandidates=b;return 1===this._spatialReferenceCandidates.length};c.prototype._findExtent=function(a,b){var d="fullExtents"in a&&a.fullExtents||(a.fullExtent?[a.fullExtent]:[]),c=k.find(d,function(a){return a.spatialReference.equals(b)});if(c)return this._set("extent",c),!0;0<this._getSupportedSpatialReferences(a).length&&(d=d.map(function(b){return{extent:b,layer:a}}),this._extentCandidates=(this._extentCandidates||[]).concat(d));return!1};c.prototype._projectExtentCandidate=
function(){return x(this,void 0,void 0,function(){var a,b,c,f,e;return w(this,function(d){switch(d.label){case 0:if(!this._extentCandidates||!this._extentCandidates.length)return[2];a=this.spatialReference;b=k.find(this._extentCandidates,function(b){return r.canProject(b.extent.spatialReference,a)});if(!b)return[3,1];this._set("extent",r.project(b.extent,a));return[3,7];case 1:return c=this._extentCandidates[0],this._extentProjectController=B.createAbortController(),[4,new Promise(function(a,b){u(["../../portal/support/geometryServiceUtils"],
a,b)})];case 2:f=d.sent(),d.label=3;case 3:return d.trys.push([3,5,,6]),[4,f.projectGeometry(c.extent,a,c.layer.portalItem,this._extentProjectController.signal)];case 4:return e=d.sent(),this._set("extent",e),[3,6];case 5:return d.sent(),[3,6];case 6:this._extentProjectController=null,d.label=7;case 7:return[2]}})})};c.prototype._getSupportedSpatialReferences=function(a){var b=this,c="supportedSpatialReferences"in a&&a.supportedSpatialReferences||(a.spatialReference?[a.spatialReference]:[]);if(0===
c.length)return this._debugLog("Layer "+a.id+" is ignored because it does not have any spatial references"),[];c=c.filter(function(c){return b.view.isSpatialReferenceSupported(c,a,function(a){return b._debugLog(a)})});0===c.length?this._debugLog("Layer "+a.id+" has spatial references but none of them are supported (or layer doesn't require locking)"):this._debugLog("Layer "+a.id+" has spatial references. Resulting candidate set: "+c.map(l).join(", "));return c};c.prototype._processHeightModelInfoSource=
function(a){var b=q.deriveHeightModelInfoFromLayer(a);return b?(this._set("heightModelInfo",b),this._set("isHeightModelInfoSearching",!1),a.spatialReference&&(this._set("vcsWkid",a.spatialReference.vcsWkid),this._set("latestVcsWkid",a.spatialReference.latestVcsWkid)),!0):!1};c.prototype._updateTileInfo=function(){if(null==this.tileInfo)if(!this.view.isTileInfoRequired())this._set("isTileInfoDone",!0);else if(this.isSpatialReferenceDone){var a=this.get("view.map");if(a){var b=a.basemap,a=a.get("layers.0"),
c=null;if(b&&"failed"!==b.loadStatus){if(!b.loaded){this._updateWhen(b.load());this._debugLog("updateTileInfo: basemap still loading");return}if((b=b&&b.get("baseLayers.0"))&&"failed"!==b.loadStatus)if(b.loaded)c="tileInfo"in b&&b.tileInfo;else{this._updateWhen(b.load());this._debugLog("updateTileInfo: first basemap layer still loading");return}else if(a&&"failed"!==a.loadStatus)if(a.loaded)c="tileInfo"in a&&a.tileInfo;else{this._updateWhen(a.load());this._debugLog("updateTileInfo: first operational layer still loading");
return}else return}else if(a&&"failed"!==a.loadStatus)if(a.loaded)c="tileInfo"in a&&a.tileInfo;else{this._updateWhen(a.load());this._debugLog("updateTileInfo: first operational layer still loading");return}c&&!c.spatialReference.equals(this.spatialReference)&&(c=null);this._debugLog("updateTileInfo: setting "+c);this._set("tileInfo",c);this._set("isTileInfoDone",!0)}else this._debugLog("updateTileInfo: no map")}};c.prototype._debugLog=function(a){this.logDebugInformation&&C.info(a)};var n;c.DefaultMapCollectionPaths=
["basemap.baseLayers","layers","ground.layers","basemap.referenceLayers"];g([e.property()],c.prototype,"logDebugInformation",void 0);g([e.property({readOnly:!0})],c.prototype,"isSpatialReferenceDone",void 0);g([e.property({readOnly:!0})],c.prototype,"isTileInfoDone",void 0);g([e.property({readOnly:!0})],c.prototype,"isHeightModelInfoSearching",void 0);g([e.property({constructOnly:!0})],c.prototype,"view",void 0);g([e.property({readOnly:!0})],c.prototype,"spatialReference",void 0);g([e.property({readOnly:!0})],
c.prototype,"extent",void 0);g([e.property({readOnly:!0})],c.prototype,"heightModelInfo",void 0);g([e.property({readOnly:!0})],c.prototype,"vcsWkid",void 0);g([e.property({readOnly:!0})],c.prototype,"latestVcsWkid",void 0);g([e.property()],c.prototype,"mapCollectionPaths",void 0);g([e.property()],c.prototype,"defaultSpatialReference",void 0);g([e.property({readOnly:!0})],c.prototype,"tileInfo",void 0);return c=n=g([e.subclass("esri.views.support.DefaultsFromMap")],c)}(e.declared(y))});