// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("./deprecate ./Handles ./Logger ./maybe ./accessorSupport/beforeDestroy ./accessorSupport/get ./accessorSupport/interfaces ./accessorSupport/metadata ./accessorSupport/Properties ./accessorSupport/set ./accessorSupport/testSupport ./accessorSupport/watch ./accessorSupport/decorators/property ./accessorSupport/decorators/subclass".split(" "),function(v,w,x,y,z,l,A,B,C,D,m,n,E,F){function G(a){if(null==a)return{value:a};if(Array.isArray(a))return{type:[a[0]],value:null};switch(typeof a){case "object":return a.constructor?.__accessorMetadata__||
a instanceof Date?{type:a.constructor,value:a}:a;case "boolean":return{type:Boolean,value:a};case "string":return{type:String,value:a};case "number":return{type:Number,value:a};case "function":return{type:a,value:null}}}const e=Symbol("Accessor-Handles"),g=Symbol("Accessor-Initialized");class p{static createSubclass(a={}){if(Array.isArray(a))throw Error("Multi-inheritance unsupported since 4.16");const {properties:b,declaredClass:d,constructor:q}=a;delete a.declaredClass;delete a.properties;delete a.constructor;
const h=this;class f extends h{constructor(...c){super(...c);this.inherited=null;q&&q.apply(this,c)}}B.getPropertiesMetadata(f.prototype);for(const c in a){const r=a[c];f.prototype[c]="function"===typeof r?function(...H){const t=this.inherited;this.inherited=function(...k){if(h.prototype[c])return h.prototype[c].apply(this,k)};let u=void 0;try{u=r.apply(this,H)}catch(k){throw this.inherited=t,k;}this.inherited=t;return u}:a[c]}for(const c in b)a=G(b[c]),E.property(a)(f.prototype,c);return F.subclass(d)(f)}constructor(...a){this[I]=
null;this[J]=!1;if(this.constructor===p)throw Error("[accessor] cannot instantiate Accessor. This can be fixed by creating a subclass of Accessor");const b=new C(this);Object.defineProperty(this,"__accessor__",{enumerable:!1,value:b});0<a.length&&this.normalizeCtorArgs&&(b.ctorArgs=this.normalizeCtorArgs.apply(this,a));m.getAccessorInterceptor()?.onInstanceConstruct(this)}postscript(a){const b=this.__accessor__;a=b.ctorArgs||a;b.initialize();a&&(this.set(a),b.ctorArgs=null);b.constructed();this.initialize();
this[g]=!0}initialize(){}[z.beforeDestroySymbol](){this[e]=y.destroyMaybe(this[e])}destroy(){this.destroyed||(n.removeTarget(this),this.__accessor__.destroy(),m.getAccessorInterceptor()?.onInstanceDestroy(this))}[Symbol.dispose](){this.destroy()}get constructed(){return this.__accessor__&&this.__accessor__.initialized||!1}get initialized(){return this[g]}get destroyed(){return this.__accessor__?.lifecycle===A.Lifecycle.DESTROYED||!1}commitProperty(a){l.get(this,a)}get(a){v.deprecatedFunction(x.getLogger(this),
"`Accessor.get` is deprecated in favor of using optional chaining",{version:"4.28",see:"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining"});return l.get(this,a)}hasOwnProperty(a){return this.__accessor__?this.__accessor__.has(a):Object.prototype.hasOwnProperty.call(this,a)}keys(){return this.__accessor__?this.__accessor__.keys():[]}set(a,b){D.set(this,a,b);return this}watch(a,b,d){return n.watch(this,a,b,d)}addHandles(a,b){if(this.destroyed){a=Array.isArray(a)?
a:[a];for(var d of a)d.remove()}else d=this[e],null==d&&(d=this[e]=new w),d.add(a,b)}removeHandles(a){const b=this[e];null!=b&&b.remove(a)}removeAllHandles(){const a=this[e];null!=a&&a.removeAll()}hasHandles(a){const b=this[e];return null!=b?b.has(a):!1}_override(a,b){void 0===b?this.__accessor__.clearOverride(a):this.__accessor__.override(a,b)}_clearOverride(a){return this.__accessor__.clearOverride(a)}_overrideIfSome(a,b){null==b?this.__accessor__.clearOverride(a):this.__accessor__.override(a,b)}_isOverridden(a){return this.__accessor__.isOverridden(a)}notifyChange(a){this.__accessor__.notifyChange(a)}_get(a){return this.__accessor__.internalGet(a)}_set(a,
b){this.__accessor__.internalSet(a,b);return this}}var I=e;var J=g;return p});