// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("exports ../config ./arrayUtils ./Error ./JSONSupport ./Logger ../portal/support/urlUtils ../support/base64Utils".split(" "),function(e,M,ha,ia,N,ja,A,O){function l(a){if(!a)return null;const b={path:null,query:null},c=new m(a),d=a.indexOf("?");null===c.query?b.path=a:(b.path=a.substring(0,d),b.query=I(c.query));c.fragment&&(b.hash=c.fragment,null===c.query&&(b.path=b.path.substring(0,b.path.length-(c.fragment.length+1))));return b}function I(a){var b=a.split("\x26");a={};for(const d of b){if(!d)continue;
var c=d.indexOf("\x3d");0>c?(b=decodeURIComponent(d),c=""):(b=decodeURIComponent(d.slice(0,c)),c=decodeURIComponent(d.slice(c+1)));let f=a[b];"string"===typeof f&&(f=a[b]=[f]);Array.isArray(f)?f.push(c):a[b]=c}return a}function t(a,b){return a?b&&"function"===typeof b?Object.keys(a).map(c=>encodeURIComponent(c)+"\x3d"+encodeURIComponent(b(c,a[c]))).join("\x26"):Object.keys(a).map(c=>{const d=a[c];if(null==d)return"";const f=encodeURIComponent(c)+"\x3d";return(c=b?.[c])?f+encodeURIComponent(c(d)):
Array.isArray(d)?d.map(h=>N.isSerializable(h)?f+encodeURIComponent(JSON.stringify(h)):f+encodeURIComponent(h)).join("\x26"):N.isSerializable(d)?f+encodeURIComponent(JSON.stringify(d)):f+encodeURIComponent(d)}).filter(c=>c).join("\x26"):""}function J(a){const b=a.indexOf("?");-1!==b?(u.path=a.slice(0,b),u.query=a.slice(b+1)):(u.path=a,u.query=null);return u}function P(a){a=J(a).path;a=Q(a);a=B(a,!0);return a=a.toLowerCase()}function C(a){const b=n.proxyRules;a=P(a);for(let c=0;c<b.length;c++)if(0===
a.indexOf(b[c].urlPrefix))return b[c]}function p(a){a=v(a);const b=a.indexOf("/sharing");return 0<b?a.substring(0,b):a.replace(/\/+$/,"")}function D(a,b,c=!1){if(!a||!b)return!1;a=K(a);b=K(b);return!c&&a.scheme!==b.scheme||null==a.host||null==b.host?!1:a.host.toLowerCase()===b.host.toLowerCase()&&a.port===b.port}function E(a,b=w,c){if(k(a))return c&&c.preserveProtocolRelative?a:"http"===g.scheme&&g.authority===R(a).slice(2)?`http:${a}`:`https:${a}`;if(!F(a)){c=S;if("/"===a[0]){var d=b.indexOf("//");
d=b.indexOf("/",d+2);b=-1===d?b:b.slice(0,d)}return c(b,a)}return a}function v(a){a=a.trim();a=E(a);if(/^https?:\/\//i.test(a)){const b=J(a);a=b.path.replaceAll(/\/{2,}/g,"/");a=a.replace("/","//");b.query&&(a+=`?${b.query}`)}a=a.replace(/^(https?:\/\/)(arcgis\.com)/i,"$1www.$2");return a=ka(a)}function S(...a){var b=a.filter(ha.isSome);if(b?.length){a=[];if(q(b[0])){var c=b[0],d=c.indexOf("//");-1!==d&&(a.push(c.slice(0,d+1)),la(b[0])&&(a[0]+="/"),b[0]=c.slice(d+2))}else"/"===b[0][0]&&a.push("");
b=b.reduce((f,h)=>h?f.concat(h.split("/")):f,[]);for(c=0;c<b.length;c++)d=b[c],".."===d&&0<a.length&&".."!==a[a.length-1]?a.pop():(!d&&c===b.length-1||d&&("."!==d||0===a.length))&&a.push(d);return a.join("/")}}function R(a,b=!1){if(null==a||T(a)||U(a))return null;var c=a.indexOf("://");if(-1===c&&k(a))c=2;else if(-1!==c)c+=3;else return null;c=a.indexOf("/",c);-1!==c&&(a=a.slice(0,c));b&&(a=B(a,!0));return a}function q(a){return k(a)||F(a)}function T(a){return null!=a&&"blob:"===a.slice(0,5)}function U(a){return null!=
a&&"data:"===a.slice(0,5)}function V(a){return(a=x(a))&&a.isBase64?O.base64ToArrayBuffer(a.data):null}function x(a){a=a.match(ma);if(!a)return null;const [,b,c,d]=a;return{mediaType:b,isBase64:!!c,data:d}}function W(a){const b=V(a);if(!b)return null;a=x(a);return new Blob([b],{type:a.mediaType})}function X(a,b){if(!a)return!1;const c=document.createElement("a");if(!("download"in c))return!1;a=URL.createObjectURL(a);c.download=b;c.href=a;c.style.display="none";document.body.appendChild(c);c.click();
document.body.removeChild(c);URL.revokeObjectURL(a);return!0}function k(a){return null!=a&&"/"===a[0]&&"/"===a[1]}function F(a){return null!=a&&Y.test(a)}function Z(a){return null!=a&&aa.test(a)||"https"===g.scheme&&k(a)}function na(a){return null!=a&&ba.test(a)||"http"===g.scheme&&k(a)}function la(a){return null!=a&&oa.test(a)}function L(a){return k(a)?`https:${a}`:a.replace(ba,"https:")}function G(){return"https"===g.scheme}function B(a,b=!1){if(k(a))return a.slice(2);a=a.replace(Y,"");b&&1<a.length&&
"/"===a[0]&&"/"===a[1]&&(a=a.slice(2));return a}function Q(a){return a.endsWith("/")?a:`${a}/`}function ka(a){const b=n.httpsDomains;if(!na(a))return a;const c=a.indexOf("/",7);let d;d=-1===c?a:a.slice(0,c);d=d.toLowerCase().slice(7);if(pa.test(d))if(d.endsWith(":80"))d=d.slice(0,-3),a=a.replace(":80","");else return a;if("http"===g.scheme&&d===g.authority&&!qa.test(a))return a;if(G()&&d===g.authority||b&&b.some(f=>d===f||d.endsWith(`.${f}`))||G()&&!C(a))a=L(a);return a}function K(a){if("string"===
typeof a)return new m(E(a));a.scheme||(a.scheme=g.scheme);return a}const n=M.request,Y=/^\s*[a-z][a-z0-9-+.]*:(?![0-9])/i,ba=/^\s*http:/i,aa=/^\s*https:/i,oa=/^\s*file:/i,pa=/:\d+$/,qa=/^https?:\/\/[^/]+\.arcgis.com\/sharing(\/|$)/i,ra=RegExp("^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\\?([^#]*))?(#(.*))?$"),sa=RegExp("^((([^\\[:]+):)?([^@]+)@)?(\\[([^\\]]+)\\]|([^\\[:]*))(:([0-9]+))?$");class m{constructor(a=""){this.uri=a;this.port=this.host=this.password=this.user=this.fragment=this.query=this.path=
this.authority=this.scheme=null;a=this.uri.match(ra);this.scheme=a[2]||(a[1]?"":null);this.authority=a[4]||(a[3]?"":null);this.path=a[5];this.query=a[7]||(a[6]?"":null);this.fragment=a[9]||(a[8]?"":null);null!=this.authority&&(a=this.authority.match(sa),this.user=a[3]||null,this.password=a[4]||null,this.host=a[6]||a[7],this.port=a[9]||null)}toString(){return this.uri}}const y={},ca=new m(M.applicationUrl);let g=ca;const da=function(){var a=g.path;a=a.substring(0,a.lastIndexOf(a.split("/")[a.split("/").length-
1]));return`${`${g.scheme}://${g.host}${null!=g.port?`:${g.port}`:""}`}${a}`}();let w=da;const u={path:"",query:""},ma=/^data:(.*?)(;base64)?,(.*)$/,ea=/([^.]*)\.([^\/]*)$/,ta=/(^data:image\/svg|\.svg$)/i;e.Url=m;e.addProxy=function(a){var b=C(a),c=void 0;if(b){var d=J(b.proxyUrl);c=d.path;d=d.query?I(d.query):null}c&&(b=l(a),a=c+"?"+b.path,(c=t({...d,...b.query}))&&(a=`${a}?${c}`));return a};e.addProxyRule=function(a){a={proxyUrl:a.proxyUrl,urlPrefix:P(a.urlPrefix)};const b=n.proxyRules,c=a.urlPrefix;
let d=b.length;for(let f=0;f<b.length;f++){const h=b[f].urlPrefix;if(0===c.indexOf(h)){if(c.length===h.length)return-1;d=f;break}0===h.indexOf(c)&&(d=f+1)}b.splice(d,0,a);return d};e.addQueryParameter=function(a,b,c){a=l(a);const d=a.query||{};d[b]=String(c);return`${a.path}?${t(d)}`};e.addQueryParameters=function(a,b){if(!b)return a;a=l(a);const c=a.query||{};for(const [d,f]of Object.entries(b))null!=f&&(c[d]=f);return(b=t(c))?`${a.path}?${b}`:a.path};e.base64UrlEncode=function(a){return O.arrayBufferToBase64(a).replaceAll("+",
"-").replaceAll("/","_").replace(/=+$/,"")};e.blobUrlToBlob=async function(a){return(await fetch(a)).blob()};e.changeDomain=function(a,b,c){if(!(b&&c&&a&&q(a)))return a;const d=a.indexOf("//");var f=a.indexOf("/",d+2);const h=a.indexOf(":",d+2);f=Math.min(0>f?a.length:f,0>h?a.length:h);if(a.slice(d+2,f).toLowerCase()!==b.toLowerCase())return a;b=a.slice(0,d+2);a=a.slice(f);return`${b}${c}${a}`};e.dataComponents=x;e.dataToArrayBuffer=V;e.dataToBlob=W;e.downloadBlobAsFile=function(a,b){X(a,b)};e.downloadDataAsFile=
function(a,b){(a=W(a))&&X(a,b)};e.ensureTrailingSlash=Q;e.getAppBaseUrl=()=>w;e.getAppUrl=()=>g;e.getFilename=function(a,b){if(!a)return"";a=l(a).path.replace(/\/+$/,"");a=a.substring(a.lastIndexOf("/")+1);if(!b?.length)return a;b=new RegExp(`.(${b.join("|")})$`,"ig");return a.replace(b,"")};e.getInterceptor=function(a){const b=d=>null==d||d instanceof RegExp&&d.test(a)||"string"===typeof d&&a.startsWith(d),c=n.interceptors;if(c)for(const d of c)if(Array.isArray(d.urls)){if(d.urls.some(b))return d}else if(b(d.urls))return d;
return null};e.getOrigin=R;e.getPathExtension=function(a){return null==a?null:(a=a.match(ea))?a[2]:null};e.getProxyRule=C;e.getProxyUrl=function(a=!1){let b,c=n.proxyUrl;if("string"===typeof a){if(b=Z(a),a=C(a))c=a.proxyUrl}else b=!!a;if(!c)throw ja.getLogger("esri.core.urlUtils").warn("esri/config: esriConfig.request.proxyUrl is not set."),new ia("urlUtils:proxy-not-set","esri/config: esriConfig.request.proxyUrl is not set.");b&&G()&&(c=L(c));return l(c)};e.hasProtocol=F;e.hasSameCanonicalArcGISOnlinePortal=
function(a,b){if(!a||!b)return!1;a=p(a);b=p(b);a=A.parseKnownArcGISOnlineDomain(a);b=A.parseKnownArcGISOnlineDomain(b);return null!=a&&null!=b?a.portalHostname===b.portalHostname:!1};e.hasSameCanonicalPortal=function(a,b){if(!a||!b)return!1;a=p(a);b=p(b);const c=A.parseKnownArcGISOnlineDomain(a),d=A.parseKnownArcGISOnlineDomain(b);return null!=c&&null!=d?c.portalHostname===d.portalHostname:null!=c||null!=d?!1:D(a,b,!0)};e.hasSameOrigin=D;e.hasSamePortal=function(a,b){a=p(a);b=p(b);return B(a)===B(b)};
e.isAbsolute=q;e.isAppHTTPS=G;e.isBlobProtocol=T;e.isDataProtocol=U;e.isHTTPSProtocol=Z;e.isProtocolRelative=k;e.isSVG=function(a){return ta.test(a)};e.isTrustedServer=function(a){if("string"===typeof a)if(q(a))a=K(a);else return!0;if(D(a,g))return!0;const b=n.trustedServers||[];for(let d=0;d<b.length;d++){var c=b[d];y[c]||(F(c)||k(c)?y[c]=[new m(E(c))]:y[c]=[new m(`http://${c}`),new m(`https://${c}`)]);c=y[c];for(let f=0;f<c.length;f++)if(D(a,c[f]))return!0}return!1};e.join=S;e.makeAbsolute=E;e.makeData=
function(a){return a.isBase64?`data:${a.mediaType};base64,${a.data}`:`data:${a.mediaType},${a.data}`};e.makeRelative=function(a,b=w,c){if(null==a||!q(a))return a;var d=v(a),f=d.toLowerCase();b=v(b).toLowerCase().replace(/\/+$/,"");if((c=c?v(c).toLowerCase().replace(/\/+$/,""):null)&&0!==b.indexOf(c))return a;const h=(fa,ua,H)=>{H=fa.indexOf(ua,H);return-1===H?fa.length:H};let r=h(f,"/",f.indexOf("//")+2),z=-1;for(;f.slice(0,r+1)===b.slice(0,r)+"/";){z=r+1;if(r===f.length)break;r=h(f,"/",r+1)}if(-1===
z||c&&z<c.length)return a;a=d.slice(z);d=b.slice(z-1).replaceAll(/[^/]+/g,"").length;if(0<d)for(f=0;f<d;f++)a=`../${a}`;else a=`./${a}`;return a};e.normalize=v;e.objectToQuery=t;e.parseData=async function(a){return"string"===typeof a?x(a)??{data:a}:new Promise((b,c)=>{const d=new FileReader;d.readAsDataURL(a);d.onload=()=>b(x(d.result));d.onerror=f=>c(f)})};e.queryToObject=I;e.removeFile=function(a){let b=0;if(q(a)){var c=a.indexOf("//");-1!==c&&(b=c+2)}c=a.lastIndexOf("/");return c<b?a:a.slice(0,
c+1)};e.removeQueryParameter=function(a,b){const {path:c,query:d}=l(a);if(!d)return a;delete d[b];return(a=t(d))?`${c}?${a}`:c};e.removeQueryParameters=function(a,b){a=l(a);const c=Object.keys(a.query||{});0<c.length&&b&&b.warn("removeQueryParameters()",`Url query parameters are not supported, the following parameters have been removed: ${c.join(", ")}.`);return a.path};e.removeTrailingSlash=function(a){return a.replace(/\/+$/,"")};e.splitPathExtension=function(a){if(null==a)return null;const b=a.match(ea);
return b?{path:b[1],extension:b[2]}:{path:a,extension:null}};e.test={setAppUrl:a=>g=a,setAppBaseUrl:a=>w=a,restoreUrls:()=>{g=ca;w=da}};e.toHTTP=function(a){return k(a)?`http:${a}`:a.replace(aa,"http:")};e.toHTTPS=L;e.trustedServersUrlCache=y;e.urlToObject=l;Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})});