// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.8/esri/copyright.txt for details.
//>>built
require({cache:{"esri/widgets/LayerList/ListItem":function(){define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/Accessor ../../core/Collection ../../core/Handles ../../core/Identifiable ../../core/watchUtils ../../core/accessorSupport/decorators ../../layers/support/Sublayer ../../support/Action ./ListItemPanel ./support/layerListUtils".split(" "),function(u,f,n,a,q,d,r,m,k,h,l,g,t,p){var v=d.ofType(d.ofType(g));return function(e){function b(b){b=
e.call(this)||this;b._handles=new r;b.actionsSections=new v;b.actionsOpen=!1;b.children=new (d.ofType(g));b.error=null;b.layer=null;b.open=!1;b.panel=null;b.parent=null;b.view=null;b.visible=null;return b}n(b,e);g=b;b.prototype.initialize=function(){var b=this;this._handles.add([k.init(this,"layer",function(a){return b._watchLayerProperties(a)}),k.init(this,"view",function(a){return b._updateChildren(a)}),k.init(this,"panel",function(a){return b._setListItemOnPanel(a)})])};b.prototype.destroy=function(){this._handles.destroy();
this.view=this._handles=null};Object.defineProperty(b.prototype,"layerView",{get:function(){return this._findLayerView(this.layer)||null},enumerable:!0,configurable:!0});b.prototype.castPanel=function(b){this.get("panel.open")&&!b.hasOwnProperty("open")&&(b.open=!0);return b?new t(b):null};Object.defineProperty(b.prototype,"title",{get:function(){var b=this.get("layer.layer");return(!b||b&&this.get("layer.layer.loaded"))&&this.get("layer.title")||""},set:function(b){void 0===b?this._clearOverride("title"):
this._override("title",b)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"updating",{get:function(){var b=this.layerView;return b?b.updating:this._isLayerUpdating(this.layer)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"visibleAtCurrentScale",{get:function(){return!p.isLayerOutsideScaleRange(this.layer,this.get("view.scale"))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"visibilityMode",{get:function(){return p.findLayerVisibilityMode(this.layer)||
"independent"},enumerable:!0,configurable:!0});b.prototype.clone=function(){return new g({actionsSections:this.actionsSections.clone(),actionsOpen:this.actionsOpen,children:this.children.clone(),layer:this.layer,open:this.open,panel:this.panel,title:this.title,view:this.view,visible:this.visible})};b.prototype._setListItemOnPanel=function(b){b&&(b.listItem=this)};b.prototype._updateChildren=function(b){var a=this.children;a&&a.forEach(function(a){return a.view=b})};b.prototype._addChildren=function(b){var a=
this;this.children.removeAll();if(b){var e=[];b.forEach(function(b){p.canDisplayLayer(b)&&(b=new g({layer:b,parent:a,view:a.view}),e.unshift(b))});this.children.addMany(e)}};b.prototype._watchSublayerChanges=function(b){var a=this;b&&this._handles.add(b.on("change",function(){a._addChildren(b)}),"layer")};b.prototype._initializeChildLayers=function(b){this._addChildren(b);this._watchSublayerChanges(b)};b.prototype._watchLayerProperties=function(b){var a=this;if(this._handles&&(this._handles.remove("layer"),
b)){var e=p.getNormalizedChildLayerProperty(b);e&&this._handles.add(k.init(b,e,function(){b.hasOwnProperty(e)&&a._initializeChildLayers(b[e])}),"layer")}};b.prototype._findLayerView=function(b){if(b){var a=this.get("view.allLayerViews");if(a)return a.find(function(a){return a.layer===b})}};b.prototype._isLayerUpdating=function(b){return b instanceof l?!1:"loading"===b.loadStatus};a([h.property({type:v})],b.prototype,"actionsSections",void 0);a([h.property()],b.prototype,"actionsOpen",void 0);a([h.property({type:d})],
b.prototype,"children",void 0);a([h.aliasOf("layer.loadError")],b.prototype,"error",void 0);a([h.property()],b.prototype,"layer",void 0);a([h.property({dependsOn:["layer","view"],readOnly:!0})],b.prototype,"layerView",null);a([h.property()],b.prototype,"open",void 0);a([h.property({type:t})],b.prototype,"panel",void 0);a([h.cast("panel")],b.prototype,"castPanel",null);a([h.property()],b.prototype,"parent",void 0);a([h.property({dependsOn:["layer.layer.loaded","layer.title"]})],b.prototype,"title",
null);a([h.property({dependsOn:["layer.loadStatus","layerView.updating"],readOnly:!0})],b.prototype,"updating",null);a([h.property({value:null})],b.prototype,"view",void 0);a([h.aliasOf("layer.visible")],b.prototype,"visible",void 0);a([h.property({dependsOn:["layer.minScale","layer.maxScale","view.scale"],readOnly:!0})],b.prototype,"visibleAtCurrentScale",null);a([h.property({dependsOn:["layer.visibilityMode"],readOnly:!0})],b.prototype,"visibilityMode",null);return b=g=a([h.subclass("esri.widgets.LayerList.ListItem")],
b);var g}(h.declared(q,m))})},"esri/layers/support/Sublayer":function(){define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/tsSupport/paramHelper dojo/io-query ../../PopupTemplate ../../core/Collection ../../core/JSONSupport ../../core/lang ../../core/Logger ../../core/accessorSupport/decorators ../../core/accessorSupport/ensureType ../../core/accessorSupport/write ../FeatureLayer ./LabelClass ./layerSourceUtils ../../renderers/support/jsonUtils ../../renderers/support/typeUtils ../../symbols/Symbol3D ../../tasks/QueryTask ../../tasks/support/Query".split(" "),
function(u,f,n,a,q,d,r,m,k,h,l,g,t,p,v,e,b,z,y,A,B,w){var x=l.getLogger("esri.layers.support.Sublayer"),C=0;return function(k){function c(){var b=null!==k&&k.apply(this,arguments)||this;b._sublayersHandles=null;b.popupEnabled=!0;return b}n(c,k);f=c;Object.defineProperty(c.prototype,"definitionExpression",{get:function(){return this._get("definitionExpression")},set:function(b){this._setAndNotifyLayer("definitionExpression",b)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"id",
{get:function(){var b=this._get("id");return null==b?C++:b},set:function(b){this._set("id",b)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"labelingInfo",{get:function(){return this._get("labelingInfo")},set:function(b){this._setAndNotifyLayer("labelingInfo",b)},enumerable:!0,configurable:!0});c.prototype.writeLabelingInfo=function(b,a,e,c){(!c||c.writeAsDynamic)&&b&&b.length&&(a.layerDefinition={drawingInfo:{labelingInfo:b.map(function(b){return b.write({},c)})}})};Object.defineProperty(c.prototype,
"labelsVisible",{get:function(){return this._get("labelsVisible")},set:function(b){this._setAndNotifyLayer("labelsVisible",b)},enumerable:!0,configurable:!0});c.prototype.writeLabelsVisible=function(b,a,e,c){if(!c||c.writeAsDynamic)a.showLabels=b};Object.defineProperty(c.prototype,"legendEnabled",{get:function(){return this._get("legendEnabled")},set:function(b){this._set("legendEnabled",b)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"layer",{set:function(b){this._set("layer",
b);this.sublayers&&this.sublayers.forEach(function(D){return D.layer=b})},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"minScale",{get:function(){return this._get("minScale")},set:function(b){this._set("minScale",b)},enumerable:!0,configurable:!0});c.prototype.readMinScale=function(b,a){return a.minScale||a.layerDefinition&&a.layerDefinition.minScale||0};c.prototype.writeMinScale=function(b,a,c,e){if(e&&e.writeOverridesOnly&&(c=e&&e.serviceSublayer)&&c.minScale===b&&c.maxScale===
this.maxScale)return;a.minScale=b};Object.defineProperty(c.prototype,"maxScale",{get:function(){return this._get("maxScale")},set:function(b){this._set("maxScale",b)},enumerable:!0,configurable:!0});c.prototype.readMaxScale=function(b,a){return a.maxScale||a.layerDefinition&&a.layerDefinition.maxScale||0};c.prototype.writeMaxScale=function(b,a,e,c){if(c&&c.writeOverridesOnly&&(e=c&&c.serviceSublayer)&&e.maxScale===b&&e.minScale===this.minScale)return;a.maxScale=b};Object.defineProperty(c.prototype,
"opacity",{get:function(){return this._get("opacity")},set:function(b){this._setAndNotifyLayer("opacity",b)},enumerable:!0,configurable:!0});c.prototype.readOpacity=function(b,a){b=a.layerDefinition;return 1-.01*(null!=b.transparency?b.transparency:b.drawingInfo.transparency)};c.prototype.writeOpacity=function(b,a,c,e){if(!e||e.writeAsDynamic)a.layerDefinition={drawingInfo:{transparency:100-100*b}}};c.prototype.writeParent=function(b,a,e,c){c&&c.writeOverridesOnly||(a.parentLayerId=this.parent&&this.parent!==
this.layer?this.parent.id:-1)};Object.defineProperty(c.prototype,"popupTemplate",{get:function(){return this._get("popupTemplate")},set:function(b){this._set("popupTemplate",b)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"renderer",{get:function(){return this._get("renderer")},set:function(b){if(b)for(var a=0,c=b.getSymbols();a<c.length;a++)if(c[a].isInstanceOf(A)){x.warn("Sublayer renderer should use 2D symbols");break}this._setAndNotifyLayer("renderer",b)},enumerable:!0,configurable:!0});
c.prototype.readRenderer=function(b,a,c){if(b=a.layerDefinition.drawingInfo.renderer||void 0)(b=z.read(b,a,c)||void 0)||x.error("Failed to create renderer",{rendererDefinition:a.drawingInfo.renderer,layer:this,context:c});return b};c.prototype.writeRenderer=function(b,a,c,e){if(!e||e.writeAsDynamic)a.layerDefinition={drawingInfo:{renderer:b.toJSON()}}};Object.defineProperty(c.prototype,"source",{get:function(){return this._get("source")||{mapLayerId:this.id,type:b.MAPLAYER}},set:function(b){this._setAndNotifyLayer("source",
b)},enumerable:!0,configurable:!0});c.prototype.writeSource=function(a,c,e,p){p&&!p.writeAsDynamic&&p.writeOverridesOnly||(c.layerDefinition={source:b.sourceToJSON(a)})};Object.defineProperty(c.prototype,"sublayers",{set:function(b){var a=this,c=this._get("sublayers");c&&(c.forEach(function(b){b.parent=null;b.layer=null}),this._sublayersHandles.forEach(function(b){return b.remove()}),this._sublayersHandles=null);b&&(b.forEach(function(b){b.parent=a;b.layer=a.layer}),this._sublayersHandles=[b.on("after-add",
function(b){b=b.item;b.parent=a;b.layer=a.layer}),b.on("after-remove",function(b){b=b.item;b.parent=null;b.layer=null})]);this._set("sublayers",b)},enumerable:!0,configurable:!0});c.prototype.castSublayers=function(b){return t.default(m.ofType(f),b)};c.prototype.writeSublayers=function(b,a,c,e){e&&e.writeOverridesOnly||(a[c]=this.get("sublayers.length")?this.sublayers.map(function(b){return b.id}).toArray().reverse():null)};Object.defineProperty(c.prototype,"title",{get:function(){return this._get("title")},
set:function(b){this._set("title",b)},enumerable:!0,configurable:!0});c.prototype.writeTitle=function(b,a,c,e){if(e&&e.writeOverridesOnly&&(e=e&&e.serviceSublayer)&&e.title===b)return;a[c]=b};Object.defineProperty(c.prototype,"url",{get:function(){var a=this.layer,c=this.source;if(!a)return null;if(b.isMapLayerSource(c))return a.parsedUrl.path+"/"+c.mapLayerId;c={layer:JSON.stringify({source:b.sourceToJSON(this.source)})};return a.parsedUrl.path+"/dynamicLayer?"+d.objectToQuery(c)},enumerable:!0,
configurable:!0});Object.defineProperty(c.prototype,"visible",{get:function(){return this._get("visible")},set:function(b){this._setAndNotifyLayer("visible",b)},enumerable:!0,configurable:!0});c.prototype.writeVisible=function(b,a,c,e){if(e&&e.writeOverridesOnly&&(e=e&&e.serviceSublayer)&&e.visible===b)return;a[c]=b};c.prototype.clone=function(){var b=new f;this.hasOwnProperty("definitionExpression")&&(b.definitionExpression=this.definitionExpression);this.hasOwnProperty("id")&&(b.id=this.id);this.hasOwnProperty("labelingInfo")&&
(b.labelingInfo=h.clone(this.labelingInfo));this.hasOwnProperty("labelsVisible")&&(b.labelsVisible=this.labelsVisible);this.hasOwnProperty("legendEnabled")&&(b.legendEnabled=this.legendEnabled);this.hasOwnProperty("visible")&&(b.visible=this.visible);this.hasOwnProperty("layer")&&(b.layer=this.layer);this.hasOwnProperty("minScale")&&(b.minScale=this.minScale);this.hasOwnProperty("maxScale")&&(b.maxScale=this.maxScale);this.hasOwnProperty("opacity")&&(b.opacity=this.opacity);this.hasOwnProperty("parent")&&
(b.parent=this.parent);this.hasOwnProperty("popupEnabled")&&(b.popupEnabled=this.popupEnabled);this.hasOwnProperty("popupTemplate")&&(b.popupTemplate=this.popupTemplate.clone());this.hasOwnProperty("renderer")&&(b.renderer=this.renderer.clone());this.hasOwnProperty("source")&&(b.source=h.clone(this.source));this.hasOwnProperty("sublayers")&&(b.sublayers=this.sublayers.clone());this.hasOwnProperty("title")&&(b.title=this.title);return b};c.prototype.createQuery=function(){return new w({returnGeometry:!0,
where:this.definitionExpression||"1\x3d1"})};c.prototype.createFeatureLayer=function(){if(this.hasOwnProperty("sublayers"))return null;var a=this.layer&&this.layer.parsedUrl,c=this.source,e=null;a&&(e=b.isMapLayerSource(c)?a.path+"/"+c.mapLayerId:a.path+"/dynamicLayer");a=new v({url:e});this.hasOwnProperty("definitionExpression")&&(a.definitionExpression=this.definitionExpression);this.hasOwnProperty("labelingInfo")&&(a.labelingInfo=h.clone(this.labelingInfo));this.hasOwnProperty("labelsVisible")&&
(a.labelsVisible=this.labelsVisible);this.hasOwnProperty("legendEnabled")&&(a.legendEnabled=this.legendEnabled);this.hasOwnProperty("visible")&&(a.visible=this.visible);this.hasOwnProperty("minScale")&&(a.minScale=this.minScale);this.hasOwnProperty("maxScale")&&(a.maxScale=this.maxScale);this.hasOwnProperty("opacity")&&(a.opacity=this.opacity);this.hasOwnProperty("popupTemplate")&&(a.popupTemplate=this.popupTemplate.clone());this.hasOwnProperty("renderer")&&(a.renderer=this.renderer.clone());this.hasOwnProperty("source")&&
b.isDataLayerSource(this.source)&&(a.dynamicDataSource=h.clone(this.source));this.hasOwnProperty("title")&&(a.title=this.title);return a};c.prototype.queryFeatures=function(b){var a=this;void 0===b&&(b=this.createQuery());return(new B({url:this.url})).execute(b).then(function(b){b&&b.features&&b.features.forEach(function(b){b.popupTemplate=a.popupTemplate;b.sourceLayer=a});return b})};c.prototype.toExportImageJSON=function(){var a={id:this.id,source:b.sourceToJSON(this.source)};this.definitionExpression&&
(a.definitionExpression=this.definitionExpression);if(this.renderer||this.labelingInfo||null!=this.opacity||null!=this.labelsVisible){var c=a.drawingInfo={};this.renderer&&(c.renderer=this.renderer.toJSON());null!=this.labelsVisible&&(c.showLabels=this.labelsVisible);!1!==this.labelsVisible&&this.labelingInfo&&(c.labelingInfo=this.labelingInfo.map(function(b){return b.write({},{origin:"service"})}));null!=this.opacity&&(c.transparency=100-100*this.opacity)}return a};c.prototype._setAndNotifyLayer=
function(b,a){var c=this.layer;this._get(b)!==a&&(this._set(b,a),c&&c.emit("sublayer-update",{propertyName:b}))};a([g.property({type:String,value:null,json:{read:{source:"layerDefinition.definitionExpression"},write:{target:"layerDefinition.definitionExpression"}}})],c.prototype,"definitionExpression",null);a([g.property({type:Number,json:{write:{ignoreOrigin:!0}}})],c.prototype,"id",null);a([g.property({value:null,type:[e],json:{read:{source:"layerDefinition.drawingInfo.labelingInfo"}}})],c.prototype,
"labelingInfo",null);a([g.writer("labelingInfo")],c.prototype,"writeLabelingInfo",null);a([g.property({type:Boolean,json:{read:{source:"showLabels"}}})],c.prototype,"labelsVisible",null);a([g.writer("labelsVisible")],c.prototype,"writeLabelsVisible",null);a([g.property({type:Boolean,value:!0,json:{read:{source:"showLegend"},write:{target:"showLegend"}}})],c.prototype,"legendEnabled",null);a([g.property({value:null})],c.prototype,"layer",null);a([g.property({type:Number,value:0,json:{write:{overridePolicy:function(b,
a,c){if(p.willPropertyWrite(this,"maxScale",{},c))return{ignoreOrigin:!0}}}}})],c.prototype,"minScale",null);a([g.reader("portal-item","minScale",["minScale","layerDefinition.minScale"])],c.prototype,"readMinScale",null);a([g.writer("minScale")],c.prototype,"writeMinScale",null);a([g.property({type:Number,value:0,json:{write:{overridePolicy:function(b,a,c){if(p.willPropertyWrite(this,"minScale",{},c))return{ignoreOrigin:!0}}}}})],c.prototype,"maxScale",null);a([g.reader("portal-item","maxScale",["maxScale",
"layerDefinition.maxScale"])],c.prototype,"readMaxScale",null);a([g.writer("maxScale")],c.prototype,"writeMaxScale",null);a([g.property({type:Number})],c.prototype,"opacity",null);a([g.reader("opacity",["layerDefinition.drawingInfo.transparency","layerDefinition.transparency"])],c.prototype,"readOpacity",null);a([g.writer("opacity")],c.prototype,"writeOpacity",null);a([g.property({json:{type:Number,write:{target:"parentLayerId",allowNull:!0}}})],c.prototype,"parent",void 0);a([g.writer("parent")],
c.prototype,"writeParent",null);a([g.property({type:Boolean})],c.prototype,"popupEnabled",void 0);a([g.property({value:null,type:r,json:{read:{source:"popupInfo"},write:{target:"popupInfo"}}})],c.prototype,"popupTemplate",null);a([g.property({types:y.types,value:null,json:{write:{target:"layerDefinition.drawingInfo.renderer"}}})],c.prototype,"renderer",null);a([g.reader("renderer",["layerDefinition.drawingInfo.renderer"])],c.prototype,"readRenderer",null);a([g.writer("renderer")],c.prototype,"writeRenderer",
null);a([g.property({cast:b.castSource,json:{read:{source:"layerDefinition.source",reader:b.sourceFromJSON},write:{target:"layerDefinition.source"}}})],c.prototype,"source",null);a([g.writer("source")],c.prototype,"writeSource",null);a([g.property({value:null,json:{type:[Number],write:{target:"subLayerIds",allowNull:!0}}})],c.prototype,"sublayers",null);a([g.cast("sublayers")],c.prototype,"castSublayers",null);a([g.writer("sublayers")],c.prototype,"writeSublayers",null);a([g.property({type:String,
value:null,json:{read:{source:"name"},write:{target:"name",allowNull:!0,ignoreOrigin:!0}}})],c.prototype,"title",null);a([g.writer("title")],c.prototype,"writeTitle",null);a([g.property({readOnly:!0,dependsOn:["layer","source"]})],c.prototype,"url",null);a([g.property({type:Boolean,value:!0,json:{read:{source:"defaultVisibility"},write:{target:"defaultVisibility"}}})],c.prototype,"visible",null);a([g.writer("visible")],c.prototype,"writeVisible",null);a([q(0,g.cast(w))],c.prototype,"queryFeatures",
null);return c=f=a([g.subclass("esri.layers.support.Sublayer")],c);var f}(g.declared(k))})},"esri/widgets/LayerList/ListItemPanel":function(){define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/Handles ../../core/Identifiable ../../core/requireUtils ../../core/watchUtils ../../core/accessorSupport/decorators ../../widgets/Widget ../support/widget".split(" "),function(u,f,n,a,q,d,r,m,k,h,l){return function(g){function d(a){a=g.call(this)||
this;a._legend=null;a._handles=new q;a.content=null;a.image=null;a.listItem=null;a.open=!1;a.visible=!0;return a}n(d,g);d.prototype.postInitialize=function(){var a=this;this.own([m.init(this,"content",function(d){return a._createLegend(d)})])};d.prototype.destroy=function(){var a=this._legend;a&&a.destroy();this._legend=null};Object.defineProperty(d.prototype,"className",{get:function(){var a=this.image,d=this._getFirstWidget();return this._get("className")||!a&&d?d.iconClass:""},set:function(a){void 0===
a?this._clearOverride("className"):this._override("className",a)},enumerable:!0,configurable:!0});Object.defineProperty(d.prototype,"title",{get:function(){var a=this._getFirstWidget();return this._get("title")||a?a.label:""},set:function(a){void 0===a?this._clearOverride("title"):this._override("title",a)},enumerable:!0,configurable:!0});d.prototype.render=function(){return l.tsx("div",{class:"esri-layer-list-panel"},this._renderContents())};d.prototype._renderContent=function(a,d){d=this._legend;
var e=this.listItem;return a?"legend"===a&&e&&e.view&&e.layer?l.tsx("div",{class:this.classes("esri-layer-list-panel__content","esri-layer-list-panel__content--legend"),key:a},d&&d.render()):"string"===typeof a?l.tsx("div",{class:this.classes("esri-layer-list-panel__content","esri-layer-list-panel__content--string"),key:a,innerHTML:a}):l.isWidget(a)?l.tsx("div",{class:this.classes("esri-layer-list-panel__content","esri-layer-list-panel__content--widget"),key:a},a.render()):a instanceof HTMLElement?
l.tsx("div",{class:this.classes("esri-layer-list-panel__content","esri-layer-list-panel__content--html-element"),key:a,bind:a,afterCreate:this._attachToNode}):null:null};d.prototype._renderContents=function(){var a=this,d=this.content;return Array.isArray(d)?d.map(function(e,b){return a._renderContent(e,b)}):this._renderContent(d,0)};d.prototype._getLegendOptions=function(a){if(a){var d=a.layer;a=a.view;if(d&&a)return{view:a,layerInfos:[{layer:d,title:""}]}}};d.prototype._createLegend=function(a){var d=
this;this._hasLegend(a)&&!this._legend&&r.when(u,"../Legend").then(function(a){var b=d._handles,e=new a(d._getLegendOptions(d.listItem));d._legend=e;d.notifyChange("className");d.notifyChange("title");a=m.init(d,["listItem.view","listItem.layer"],function(){return d._updateLegend(e)});b.add(a,"legends");d.scheduleRender()})};d.prototype._hasLegend=function(a){return"legend"===a?!0:Array.isArray(a)?a.some(function(a){return"legend"===a}):!1};d.prototype._attachToNode=function(a){a.appendChild(this)};
d.prototype._updateLegend=function(a){var d=this.listItem;if(d){var e=d.layer;a.view=d.view;a.layerInfos=[{layer:e,title:null}]}};d.prototype._getWidget=function(a){return"legend"===a?this._legend:l.isWidget(a)?a:null};d.prototype._getFirstWidget=function(){var a=this,d=this.content;if(Array.isArray(d)){var e=null;d.some(function(b){(b=a._getWidget(b))&&(e=b);return!!b});return e}return this._getWidget(d)};a([k.property({dependsOn:["content","image"]})],d.prototype,"className",null);a([k.property(),
l.renderable()],d.prototype,"content",void 0);a([k.property()],d.prototype,"image",void 0);a([k.property()],d.prototype,"listItem",void 0);a([k.property({dependsOn:["content"]})],d.prototype,"title",null);a([k.property(),l.renderable()],d.prototype,"open",void 0);a([k.property()],d.prototype,"visible",void 0);return d=a([k.subclass("esri.widgets.LayerList.ListItemPanel")],d)}(k.declared(h,d))})},"esri/core/requireUtils":function(){define(["require","exports","dojo/Deferred"],function(u,f,n){function a(f,
d){if(Array.isArray(d)){var r=new n;f(d,function(){for(var a=[],d=0;d<arguments.length;d++)a[d]=arguments[d];r.resolve(a)});return r.promise}return a(f,[d]).then(function(a){return a[0]})}Object.defineProperty(f,"__esModule",{value:!0});f.when=a;f.getAbsMid=function(a,d,f){return d.toAbsMid?d.toAbsMid(a):f.id.replace(/\/[^\/]*$/gi,"/")+a}})},"esri/widgets/LayerList/support/layerListUtils":function(){define(["require","exports"],function(u,f){function n(a){if(a)return a.hasOwnProperty("listMode")?
a.listMode:void 0}function a(a){if(a)return a.hasOwnProperty("minScale")?a.minScale:void 0}function q(a){if(a)return a.hasOwnProperty("maxScale")?a.maxScale:void 0}Object.defineProperty(f,"__esModule",{value:!0});f.findLayerListMode=n;f.findLayerMinScale=a;f.findLayerMaxScale=q;f.findLayerVisibilityMode=function(a){if(a){var d=a.get("layer.capabilities");return d&&-1===d.indexOf("supportsSublayerVisibility")?"inherited":a.hasOwnProperty("visibilityMode")?a.visibilityMode:void 0}};f.getNormalizedChildLayerProperty=
function(a){if(a&&"hide-children"!==a.listMode&&"wmts"!==a.type)return"group"===a.type?"layers":"sublayers"};f.canDisplayLayer=function(a){return"hide"!==n(a)};f.isLayerOutsideScaleRange=function(d,f){if(!d||isNaN(f))return!1;var m=a(d);d=q(d);m=!isNaN(m)&&0<m&&f>=m;f=!isNaN(d)&&0<d&&f<=d;return m||f}})},"*noref":1}});
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/Accessor ../../core/Collection ../../core/Evented ../../core/Handles ../../core/watchUtils ../../core/accessorSupport/decorators ./ListItem ./support/layerListUtils".split(" "),function(u,f,n,a,q,d,r,m,k,h,l,g){var t=d.ofType(l);return function(d){function f(a){a=d.call(this)||this;a._handles=new m;a.listItemCreatedFunction=null;a.operationalItems=new t;a.view=null;return a}n(f,d);f.prototype.initialize=
function(){var a=this;this._handles.add(k.init(this,"view",function(){return a._viewHandles()}),"view")};f.prototype.destroy=function(){this._handles.destroy();this.view=this._handles=null;this.operationalItems.removeAll()};Object.defineProperty(f.prototype,"state",{get:function(){var a=this.get("view");return this.get("view.ready")?"ready":a?"loading":"disabled"},enumerable:!0,configurable:!0});f.prototype.triggerAction=function(a,b){a&&this.emit("trigger-action",{action:a,item:b})};f.prototype._createMapHandles=
function(a){var b=this,e=this._handles;e.remove("map");var d=a&&a.get("map.layers");d&&(d=d.on("change",function(){return b._compileList(a)}),e.add(d,"map"))};f.prototype._resetMapItems=function(a){this._createMapHandles(a);this._compileList(a)};f.prototype._watchItemProperties=function(a){var b=this;this._handles.add([a.children.on("change",function(){b._modifyListItemChildren(a.children)})],"children-change-"+a.uid)};f.prototype._modifyListItemChildren=function(a){var b=this;a.forEach(function(a){return b._modifyListItem(a)})};
f.prototype._modifyListItem=function(a){"function"===typeof this.listItemCreatedFunction&&this.listItemCreatedFunction.call(null,{item:a});this._modifyListItemChildren(a.children)};f.prototype._createListItem=function(a){a=new l({layer:a,view:this.view});this._watchItemProperties(a);return a};f.prototype._removeAllItems=function(){var a=this._handles,b=this.operationalItems;b.forEach(function(b){a.remove("children-change-"+b.uid)});b.removeAll()};f.prototype._compileList=function(a){var b=this;if(!this.destroyed){var d=
this._handles,e=this.operationalItems,f=a&&a.get("map.layers");if(f){var h=f.filter(function(a){return"hide"!==g.findLayerListMode(a)});d.remove("layer-list-mode");f.forEach(function(e){d.add(k.watch(e,"listMode",function(){return b._compileList(a)}),"layer-list-mode")});this._createNewItems(e,h);this._modifyItems(e,h);this._sortItems(e,h)}else this._removeAllItems()}};f.prototype._createNewItems=function(a,b){var d=this;b.forEach(function(b){a.find(function(a){return a.layer===b})||a.add(d._createListItem(b))})};
f.prototype._modifyItems=function(a,b){var d=this,e=this._handles;a.forEach(function(f){f&&(b.find(function(a){return f.layer===a})?d._modifyListItem(f):(e.remove("children-change-"+f.uid),a.remove(f)))})};f.prototype._sortItems=function(a,b){a.sort(function(a,d){a=b.indexOf(a.layer);d=b.indexOf(d.layer);return a>d?-1:a<d?1:0})};f.prototype._viewHandles=function(){var a=this,b=this._handles,d=this.view;b.remove("layers");b.remove("layer-list-mode");this._resetMapItems(d);d&&d.when(function(){b.add([k.init(d,
"map",function(){return a._resetMapItems(d)}),d.layerViews.on("change",function(){return a._compileList(d)}),k.init(a,"listItemCreatedFunction",function(){return a._compileList(d)})],"layers")})};a([h.property()],f.prototype,"listItemCreatedFunction",void 0);a([h.property({type:t})],f.prototype,"operationalItems",void 0);a([h.property({dependsOn:["view.ready"],readOnly:!0})],f.prototype,"state",null);a([h.property()],f.prototype,"view",void 0);a([h.property()],f.prototype,"triggerAction",null);return f=
a([h.subclass("esri.widgets.LayerList.LayerListViewModel")],f)}(h.declared(q,r))});