// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define({"esri/widgets/Editor/nls/Editor":{widgetLabel:"Edytor",multipleFeaturesTemplate:"Wiele obiekt\u00f3w ({total})",untitledFeatureTemplate:"Obiekt bez nazwy {id}",editFeatures:"Edytuj obiekty",editFeature:"Edytuj obiekt",addFeature:"Dodaj obiekt",featureAttachments:"\u0142_Feature attachments____________________\u0105",attachmentsButtonLabel:"\u0142_Attachments____________\u0105",attachments:"\u0142_Attachments____________\u0105",addAttachment:"\u0142_Add attachment_______________\u0105",editAttachment:"\u0142_Manage attachment__________________\u0105",
selectTemplate:"Wybierz typ obiektu",selectFeatureToEdit:"Wybierz obiekt, aby go edytowa\u0107.",selectFeature:"Wybierz obiekt",placeFeature:"Rozmie\u015b\u0107 obiekt",placeFeatureOnMap:"Rozmie\u015b\u0107 obiekt na mapie.",add:"Dodaj",discardEdits:"Odrzu\u0107 zmiany",discardFeature:"Odrzu\u0107 obiekt",edit:"Edycja",keepAttachment:"\u0142_Keep attachment________________\u0105",keepFeature:"Zachowaj obiekt",continueAdding:"Kontynuuj dodawanie",continueEditing:"Kontynuuj edycj\u0119",editing:"Edycja",
warning:"Uwaga",retry:"Pon\u00f3w pr\u00f3b\u0119",ignore:"Ignoruj",deleteWarningTitle:"Czy usun\u0105\u0107 ten obiekt?",deleteAttachmentWarningTitle:"\u0142_Delete this attachment________________________\u0105?",deleteWarningMessage:"Ten obiekt zostanie trwale usuni\u0119ty.",deleteAttachmentWarningMessage:"\u0142_This attachment will be permanently removed_______________________\u0105.",cancelEditTitle:"Odrzuci\u0107 zmiany?",cancelAddTitle:"Czy odrzuci\u0107 obiekt?",cancelAddWarningMessage:"Ten obiekt zostanie utracony.",
cancelEditWarningMessage:"Aktualizacje tego obiektu zostan\u0105 utracone.",cancelRequestTitle:"Anulowa\u0107 procedur\u0119 wykonywania zada\u0144?",cancelRequestWarningMessage:"Za\u017c\u0105dano anulowania tej procedury wykonywania zada\u0144.",errorWarningTitle:"Przepraszamy, wyst\u0105pi\u0142y problemy",errorWarningMessageTemplate:"Nie mo\u017cna zapisa\u0107 zmian: {errorMessage}",clickToFinishTemplate:"Kliknij przycisk {button}, aby zako\u0144czy\u0107.",tips:{clickToStart:"Kliknij, aby rozpocz\u0105\u0107 rysowanie.",
clickToContinue:"Kliknij, aby kontynuowa\u0107 rysowanie.",clickToAddPoint:"Kliknij, aby doda\u0107 punkt.",clickToContinueThenDoubleClickToEnd:"Kliknij, aby kontynuowa\u0107 rysowanie, a nast\u0119pnie kliknij dwukrotnie, aby zako\u0144czy\u0107 prac\u0119.",clickToAddFeature:"Kliknij, aby doda\u0107 obiekt."},_localized:{}},"esri/widgets/FeatureTemplates/nls/FeatureTemplates":{widgetLabel:"Szablony obiekt\u00f3w",filterPlaceholder:"Typy filtr\u00f3w",noMatches:"Nie znaleziono \u017cadnych element\u00f3w",
noItems:"Brak szablon\u00f3w do wy\u015bwietlenia",_localized:{}},"esri/widgets/FeatureForm/nls/FeatureForm":{widgetLabel:"Formularz obiektu",empty:"- puste -",validationErrors:{cannotBeNull:"Wprowad\u017a warto\u015b\u0107",outsideRange:"Warto\u015b\u0107 powinna mie\u015bci\u0107 si\u0119 w granicach {min} i {max}",invalidCodedValue:"Warto\u015b\u0107 powinna by\u0107 r\u00f3wna jednej z wyszczeg\u00f3lnionych warto\u015bci.",invalidType:"Nieprawid\u0142owa warto\u015b\u0107"},_localized:{}},"dojo/cldr/nls/gregorian":{"dateFormatItem-Ehm":"E, h:mm a",
"days-standAlone-short":"niedz. pon. wt. \u015br. czw. pt. sob.".split(" "),"months-format-narrow":"slmkmclswplg".split(""),"field-second-relative+0":"teraz","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"dzie\u0144 tygodnia","dateFormatItem-yQQQ":"QQQ y","dateFormatItem-yMEd":"E, d.MM.y","field-wed-relative+0":"w t\u0119 \u015brod\u0119","field-wed-relative+1":"w przysz\u0142\u0105 \u015brod\u0119","dateFormatItem-GyMMMEd":"E, d.MM.y G","dateFormatItem-MMMEd":"E, d.MM",eraNarrow:["p.n.e.",
"BCE","n.e.","CE"],"field-tue-relative+-1":"w zesz\u0142y wtorek","days-format-short":"niedz. pon. wt. \u015br. czw. pt. sob.".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d MMMM y","field-fri-relative+-1":"w zesz\u0142y pi\u0105tek","field-wed-relative+-1":"w zesz\u0142\u0105 \u015brod\u0119","months-format-wide":"stycznia lutego marca kwietnia maja czerwca lipca sierpnia wrze\u015bnia pa\u017adziernika listopada grudnia".split(" "),"dateTimeFormat-medium":"{1}, {0}",
"dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE, d MMMM y","field-thu-relative+-1":"w zesz\u0142y czwartek","dateFormatItem-Md":"d.MM","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"w po\u0142udnie","dateFormatItem-yMd":"d.MM.y","field-era":"era","dateFormatItem-yM":"MM.y","months-standAlone-wide":"stycze\u0144 luty marzec kwiecie\u0144 maj czerwiec lipiec sierpie\u0144 wrzesie\u0144 pa\u017adziernik listopad grudzie\u0144".split(" "),
"timeFormat-short":"HH:mm","quarters-format-wide":["I kwarta\u0142","II kwarta\u0142","III kwarta\u0142","IV kwarta\u0142"],"dateFormatItem-yQQQQ":"QQQQ y","timeFormat-long":"HH:mm:ss z","field-year":"rok","dateFormatItem-yMMM":"MM.y","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"godzina","months-format-abbr":"sty lut mar kwi maj cze lip sie wrz pa\u017a lis gru".split(" "),"field-sat-relative+0":"w t\u0119 sobot\u0119","field-sat-relative+1":"w przysz\u0142\u0105 sobot\u0119","timeFormat-full":"HH:mm:ss zzzz",
"dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"dzisiaj","field-thu-relative+0":"w ten czwartek","field-day-relative+1":"jutro","field-thu-relative+1":"w przysz\u0142y czwartek","dateFormatItem-GyMMMd":"d.MM.y G","dateFormatItem-H":"HH","months-standAlone-abbr":"sty lut mar kwi maj cze lip sie wrz pa\u017a lis gru".split(" "),"quarters-format-abbr":["K1","K2","K3","K4"],"quarters-standAlone-wide":["I kwarta\u0142","II kwarta\u0142","III kwarta\u0142","IV kwarta\u0142"],
"dateFormatItem-Gy":"y G","dateFormatItem-M":"L","days-standAlone-wide":"niedziela poniedzia\u0142ek wtorek \u015broda czwartek pi\u0105tek sobota".split(" "),"dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"w t\u0119 niedziel\u0119","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"w przysz\u0142\u0105 niedziel\u0119","quarters-standAlone-abbr":["1 kw.","2 kw.","3 kw.","4 kw."],eraAbbr:["p.n.e.","BCE","n.e.","CE"],"field-minute":"minuta","field-dayperiod":"rano / po po\u0142udniu / wieczorem",
"days-standAlone-abbr":"niedz. pon. wt. \u015br. czw. pt. sob.".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"wczoraj","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"d.MM","dateFormatItem-MEd":"E, d.MM","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"w ten pi\u0105tek","field-fri-relative+1":"w przysz\u0142y pi\u0105tek","field-day":"dzie\u0144",
"days-format-wide":"niedziela poniedzia\u0142ek wtorek \u015broda czwartek pi\u0105tek sobota".split(" "),"field-zone":"strefa czasowa","months-standAlone-narrow":"slmkmclswplg".split(""),"dateFormatItem-y":"y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"w zesz\u0142ym roku","field-month-relative+-1":"w zesz\u0142ym miesi\u0105cu","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM",
"days-format-abbr":"niedz. pon. wt. \u015br. czw. pt. sob.".split(" "),eraNames:["p.n.e.","BCE","n.e.","CE"],"dateFormatItem-yMMMd":"d.MM.y","days-format-narrow":"NPW\u015aCPS".split(""),"field-month":"miesi\u0105c","days-standAlone-narrow":"NPW\u015aCPS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"w ten wtorek","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","field-tue-relative+1":"w przysz\u0142y wtorek","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})",
"dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E, HH:mm","field-mon-relative+0":"w ten poniedzia\u0142ek","field-mon-relative+1":"w przysz\u0142y poniedzia\u0142ek","dateFormat-short":"dd.MM.y","dateFormatItem-EHms":"E, HH:mm:ss","dateFormatItem-Ehms":"E, h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"sekunda","field-sat-relative+-1":"w zesz\u0142\u0105 sobot\u0119","dateFormatItem-yMMMEd":"E, d.MM.y","field-sun-relative+-1":"w zesz\u0142\u0105 niedziel\u0119",
"field-month-relative+0":"w tym miesi\u0105cu","field-month-relative+1":"w przysz\u0142ym miesi\u0105cu","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E, d","field-week":"tydzie\u0144","dateFormat-medium":"dd.MM.y","field-week-relative+-1":"w zesz\u0142ym tygodniu","field-year-relative+0":"w tym roku","field-year-relative+1":"w przysz\u0142ym roku","dayPeriods-format-narrow-pm":"p","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a",
"dateFormatItem-GyMMM":"MM.y G","field-mon-relative+-1":"w zesz\u0142y poniedzia\u0142ek","field-week-relative+0":"w tym tygodniu","field-week-relative+1":"w przysz\u0142ym tygodniu","dateFormatItem-yMM":"MM.y","dayPeriods-format-wide-earlyMorning":"nad ranem","dayPeriods-format-wide-morning":"rano","dayPeriods-format-wide-evening":"wieczorem","dateFormatItem-MMdd":"d.MM","field-day-relative+2":"pojutrze","dateFormatItem-MMMMd":"d MMMM","dayPeriods-format-wide-night":"w nocy","field-day-relative+-2":"przedwczoraj",
"dayPeriods-format-wide-lateMorning":"przed po\u0142udniem","dateFormatItem-yMMMM":"LLLL y","dayPeriods-format-wide-afternoon":"po po\u0142udniu",_localized:{}}});