// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define({"esri/widgets/Editor/nls/Editor":{widgetLabel:"Editor",multipleFeaturesTemplate:"Caracteristici multiple ({total})",untitledFeatureTemplate:"Obiect spa\u021bial {id} f\u0103r\u0103 titlu",editFeatures:"s\u0103 editeze obiecte spa\u021biale;",editFeature:"Editare obiect spa\u0163ial",addFeature:"Ad\u0103ugare obiect spa\u021bial",featureAttachments:"\u0102_Feature attachments____________________\u0219",attachmentsButtonLabel:"\u0102_Attachments____________\u0219",attachments:"\u0102_Attachments____________\u0219",
addAttachment:"\u0102_Add attachment_______________\u0219",editAttachment:"\u0102_Manage attachment__________________\u0219",selectTemplate:"Selectare tip de obiect spa\u021bial",selectFeatureToEdit:"Selecta\u021bi obiectul spa\u021bial pentru editare.",selectFeature:"Selectare obiect spa\u021bial",placeFeature:"Plasare obiect spa\u021bial",placeFeatureOnMap:"Plasa\u021bi obiectul spa\u021bial pe hart\u0103.",add:"Ad\u0103uga\u021bi",discardEdits:"Eliminare edit\u0103ri",discardFeature:"Eliminare obiect spa\u0163ial",
edit:"Editare",keepAttachment:"\u0102_Keep attachment________________\u0219",keepFeature:"P\u0103stra\u021bi obiectul spa\u021bial",continueAdding:"Continua\u021bi ad\u0103ugarea",continueEditing:"Continua\u021bi editarea",editing:"Editare",warning:"Notificare",retry:"Re\u00eencercare",ignore:"Ignorare",deleteWarningTitle:"\u0218terge\u021bi acest obiect spa\u021bial?",deleteAttachmentWarningTitle:"\u0102_Delete this attachment________________________\u0219?",deleteWarningMessage:"Acest obiect spa\u021bial va fi eliminat definitiv.",
deleteAttachmentWarningMessage:"\u0102_This attachment will be permanently removed_______________________\u0219.",cancelEditTitle:"Elimina\u0163i edit\u0103ri?",cancelAddTitle:"Elimina\u021bi obiect spa\u0163ial?",cancelAddWarningMessage:"Acest obiect spa\u0163ial va fi pierdut.",cancelEditWarningMessage:"Actualiz\u0103rile acestui obiect spa\u021bial vor fi pierdute.",cancelRequestTitle:"Anula\u021bi fluxul de lucru?",cancelRequestWarningMessage:"S-a solicitat anularea acestui flux de lucru.",errorWarningTitle:"Ne pare r\u0103u, ceva nu a mers bine",
errorWarningMessageTemplate:"Modific\u0103rile nu au putut fi salvate: {errorMessage}",clickToFinishTemplate:"Face\u021bi clic pe {button} pentru a finaliza.",tips:{clickToStart:"Face\u021bi clic pentru a \u00eencepe trasarea.",clickToContinue:"Face\u021bi clic pentru a continua trasarea.",clickToAddPoint:"Face\u021bi clic pentru a ad\u0103uga un punct.",clickToContinueThenDoubleClickToEnd:"Face\u021bi clic pentru a continua trasarea, apoi da\u021bi dublu clic pentru a finaliza.",clickToAddFeature:"Face\u021bi clic pentru a ad\u0103uga obiectul spa\u021bial."},
_localized:{}},"esri/widgets/FeatureTemplates/nls/FeatureTemplates":{widgetLabel:"\u0218abloane de obiecte spa\u021biale",filterPlaceholder:"Tipuri de filtru",noMatches:"Nu a fost g\u0103sit niciun element",noItems:"Niciun \u0219ablon de afi\u0219at",_localized:{}},"esri/widgets/FeatureForm/nls/FeatureForm":{widgetLabel:"Forma obiectului spa\u021bial",empty:"- gol -",validationErrors:{cannotBeNull:"Introduce\u0163i o valoare",outsideRange:"Valoarea trebuie s\u0103 fie \u00eentre {min} \u0219i {max}",
invalidCodedValue:"Valoarea trebuie s\u0103 fie una dintre valorile listate.",invalidType:"Nu este o valoare valabil\u0103"},_localized:{}},"dojo/cldr/nls/gregorian":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"Du Lu Ma Mi Jo Vi S\u00e2".split(" "),"months-format-narrow":"IFMAMIIASOND".split(""),"field-second-relative+0":"acum","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Zi a s\u0103pt\u0103m\u00e2nii","dateFormatItem-yQQQ":"QQQ y","dateFormatItem-yMEd":"E, dd.MM.y",
"field-wed-relative+0":"miercurea aceasta","field-wed-relative+1":"miercurea viitoare","dateFormatItem-GyMMMEd":"E, d MMM y G","dateFormatItem-MMMEd":"E, d MMM",eraNarrow:["\u00ee.Hr.","d.Hr."],"field-tue-relative+-1":"mar\u021bea trecut\u0103","days-format-short":"Du Lu Ma Mi Jo Vi S\u00e2".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d MMMM y","field-fri-relative+-1":"vinerea trecut\u0103","field-wed-relative+-1":"miercurea trecut\u0103","months-format-wide":"ianuarie februarie martie aprilie mai iunie iulie august septembrie octombrie noiembrie decembrie".split(" "),
"dateTimeFormat-medium":"{1}, {0}","dayPeriods-format-wide-pm":"p.m.","dateFormat-full":"EEEE, d MMMM y","field-thu-relative+-1":"joia trecut\u0103","dateFormatItem-Md":"dd.MM","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","dateFormatItem-yMd":"dd.MM.y","field-era":"Er\u0103","dateFormatItem-yM":"MM.y","months-standAlone-wide":"Ianuarie Februarie Martie Aprilie Mai Iunie Iulie August Septembrie Octombrie Noiembrie Decembrie".split(" "),
"timeFormat-short":"HH:mm","quarters-format-wide":["trimestrul I","trimestrul al II-lea","trimestrul al III-lea","trimestrul al IV-lea"],"dateFormatItem-yQQQQ":"QQQQ y","timeFormat-long":"HH:mm:ss z","field-year":"An","dateFormatItem-yMMM":"MMM y","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Or\u0103","months-format-abbr":"ian. feb. mar. apr. mai iun. iul. aug. sept. oct. nov. dec.".split(" "),"field-sat-relative+0":"s\u00e2mb\u0103ta aceasta","field-sat-relative+1":"s\u00e2mb\u0103ta viitoare",
"timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"azi","field-thu-relative+0":"joia aceasta","field-day-relative+1":"m\u00e2ine","field-thu-relative+1":"joia viitoare","dateFormatItem-GyMMMd":"d MMM y G","dateFormatItem-H":"HH","months-standAlone-abbr":"ian. feb. mar. apr. mai iun. iul. aug. sept. oct. nov. dec.".split(" "),"quarters-format-abbr":["trim. I","trim. II","trim. III","trim. IV"],"quarters-standAlone-wide":["Trimestrul I","Trimestrul al II-lea",
"Trimestrul al III-lea","Trimestrul al IV-lea"],"dateFormatItem-Gy":"y G","dateFormatItem-M":"L","days-standAlone-wide":"Duminic\u0103 Luni Mar\u021bi Miercuri Joi Vineri S\u00e2mb\u0103t\u0103".split(" "),"dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"duminica aceasta","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"duminica viitoare","quarters-standAlone-abbr":["Trim. I","Trim. II","Trim. III","Trim. IV"],eraAbbr:["\u00ee.Hr.","d.Hr."],"field-minute":"Minut",
"field-dayperiod":"a.m/p.m.","days-standAlone-abbr":"Dum Lun Mar Mie Joi Vin S\u00e2m".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"ieri","dateTimeFormat-long":"{1}, {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E, dd.MM","dateTimeFormat-full":"{1}, {0}","field-fri-relative+0":"vinerea aceasta","field-fri-relative+1":"vinerea viitoare","field-day":"Zi",
"days-format-wide":"duminic\u0103 luni mar\u021bi miercuri joi vineri s\u00e2mb\u0103t\u0103".split(" "),"field-zone":"Fus orar","months-standAlone-narrow":"IFMAMIIASOND".split(""),"dateFormatItem-y":"y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"anul trecut","field-month-relative+-1":"luna trecut\u0103","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"Dum Lun Mar Mie Joi Vin S\u00e2m".split(" "),
eraNames:["\u00eenainte de Hristos","dup\u0103 Hristos"],"dateFormatItem-yMMMd":"d MMM y","days-format-narrow":"DLMMJVS".split(""),"field-month":"Lun\u0103","days-standAlone-narrow":"DLMMJVS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"mar\u021bea aceasta","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","field-tue-relative+1":"mar\u021bea viitoare","dayPeriods-format-wide-am":"a.m.","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})",
"dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"lunea aceasta","field-mon-relative+1":"lunea viitoare","dateFormat-short":"dd.MM.y","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Secund\u0103","field-sat-relative+-1":"s\u00e2mb\u0103ta trecut\u0103","dateFormatItem-yMMMEd":"E, d MMM y","field-sun-relative+-1":"duminica trecut\u0103","field-month-relative+0":"luna aceasta","field-month-relative+1":"luna viitoare","dateTimeFormats-appendItem-Timezone":"{0} {1}",
"dateFormatItem-Ed":"E d","field-week":"S\u0103pt\u0103m\u00e2n\u0103","dateFormat-medium":"d MMM y","field-week-relative+-1":"s\u0103pt\u0103m\u00e2na trecut\u0103","field-year-relative+0":"anul acesta","field-year-relative+1":"anul viitor","dayPeriods-format-narrow-pm":"p","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"lunea trecut\u0103","field-week-relative+0":"s\u0103pt\u0103m\u00e2na aceasta",
"field-week-relative+1":"s\u0103pt\u0103m\u00e2na viitoare","dateFormatItem-yMM":"MM.y","dateFormatItem-MMdd":"dd.MM","field-day-relative+2":"poim\u00e2ine","dateFormatItem-MMMMd":"d MMMM","field-day-relative+-2":"alalt\u0103ieri","dateFormatItem-yMMMM":"MMMM y","dateFormatItem-MMMMEd":"E, d MMMM",_localized:{}}});