// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define({other:"Altres",classBreaks:"\u00f3_Class Breaks_____________\u00e0",classBreaksNormFieldAsPercent:"\u00f3_Class Breaks with normalizationField as percent_________________________\u00e0",heatmap:"\u00f3_Heatmap_______________\u00e0",simple:"\u00f3_Simple_____________\u00e0",simpleNormFieldAsPercent:"\u00f3_Simple with normalizationField as percent______________________\u00e0",uniqueValues:"\u00f3_Unique Values______________\u00e0",uniqueValuesNormFieldAsPercent:"\u00f3_Unique Values with normalizationField as percent_________________________\u00e0",
normFieldLabel:"\u00f3_{expression1} divided by {expression2}____________________\u00e0",normFieldLabelAsPercent:"\u00f3_Percentage of {expression1} and {expression2}________________________\u00e0",competingFields:"categories rivals",mostCommon:"{expression} m\u00e9s habitual",basicSummary:"Resum b\u00e0sic",orderedListOfValues:"Llista ordenada de valors",sumOfCategories:"Suma de categories",listOfCategories:"Llista de categories",predominantCategoryWithTotal:"Categoria predominant amb total",predominantCategoryWithTotalAndStrength:"Categoria predominant amb total i intensitat",
predominantCategoryWithChart:"Categoria predominant amb gr\u00e0fic",predominantCategory:"Categoria predominant",strengthOfPredominance:"Intensitat del predomini",marginOfVictory:"Marge de vict\u00f2ria",predominantCategoryValue:"Valor de categoria predominant",predominantCategoryContent:"La categoria m\u00e9s habitual d'aquesta \u00e0rea \u00e9s {expression}.",predominantCategoryValueContent:"La categoria m\u00e9s habitual d'aquesta \u00e0rea \u00e9s {expression1}, que t\u00e9 el valor {expression2}.",
predominantCategoryValueMarginContent:"{expression1} t\u00e9 el valor {expression2}, que guanya totes les altres \x3cb\x3ecategories\x3c/b\x3e amb un marge de {expression3} punts de percentatge.",predominantCategoryStrengthContent:"Amb el valor {expression1}, {expression2} \u00e9s la categoria m\u00e9s habitual de {title} en aquesta \u00e0rea, que \u00e9s {expression3} de totes les categories combinades.",predominantCategoryTotalContent:"Amb el valor {expression1}, {expression2} \u00e9s la categoria m\u00e9s habitual de tots els {expression3} {title} d'aquesta \u00e0rea.",
predominantCategoryTotalStrengthContent:"Amb el valor {expression1}, {expression2} \u00e9s la categoria m\u00e9s habitual d'aquesta \u00e0rea, que compr\u00e8n {expression3} de tots els {expression4} {title}.",ageInfo_years:"Antiguitat, en anys, de {startTime} a {endTime}",ageInfo_months:"Antiguitat, en mesos, de {startTime} a {endTime}",ageInfo_days:"Antiguitat, en dies, de {startTime} a {endTime}",ageInfo_hours:"Antiguitat, en hores, de {startTime} a {endTime}",ageInfo_minutes:"Antiguitat, en minuts, de {startTime} a {endTime}",
ageInfo_seconds:"Antiguitat, en segons, de {startTime} a {endTime}",relationship:{legendTitle:"Relaci\u00f3",HL:"Alt - Baix",HH:"Alt - Alt",LL:"Baix - Baix",LH:"Baix - Alt",HM:"Alt - Mitj\u00e0",ML:"Mitj\u00e0 - Baix",MM:"Mitj\u00e0 - Mitj\u00e0",MH:"Mitj\u00e0 - Alt",LM:"Baix - Mitj\u00e0",HM1:"High - Mild",HM2:"High - Medium",M2L:"Medium - Low",M2M1:"Mitj\u00e0 - Suau",M2M2:"Mitj\u00e0 - Mitj\u00e0",M2H:"Medium - High",M1L:"Mild - Low",M1M1:"Suau - Suau",M1M2:"Suau - Mitj\u00e0",M1H:"Mild - High",
LM1:"Low - Mild",LM2:"Low - Medium"}});