// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("exports ../../../../../geometry ../../../../../arcade/ArcadeDate ../../../../../core/has ../../../../../core/maybe ../../../../../core/sql/DateOnly ../../../../../core/sql/TimeOnly ../../../../../geometry/GeometryCursor ../../../../../geometry/support/aaBoundingBox ../../../../../geometry/support/labelPoint ../../../../../layers/graphics/featureConversionUtils ../../../../../layers/graphics/OptimizedFeature ../../../../../layers/graphics/OptimizedGeometry ../../../../../time/timeZoneUtils ./StaticBitSet ../../../../../geometry/support/jsonUtils".split(" "),
function(q,e,g,h,y,r,t,z,u,A,f,B,p,v,C,D){function E(a,b,c){if(!(a.length>b))for(;a.length<=b;)a.push(c)}e=h("featurelayer-simplify-thresholds")??[.5,.5,.5,.5];const F=e[0],G=e[1],H=e[2],I=e[3];e=h("featurelayer-simplify-payload-size-factors")??[1,2,4];const J=e[0],K=e[1],L=e[2],M=h("featurelayer-simplify-mobile-factor")??2,N=h("esri-mobile");class O{constructor(a){this.metadata=a;this.type="FeatureSetReader";this._deleted=null;this._joined=[];this._objectIdToIndex=null;this._boundsBuffer=[];this.arcadeDeclaredClass=
"esri.arcade.Feature";this._contextTimeZone=null}get isEmpty(){return null!=this._deleted&&this._deleted.countSet()===this.getSize()}getAreaSimplificationThreshold(a,b){let c=1;const d=N?M:1;4E6<b?c=L*d:1E6<b?c=K*d:5E5<b?c=J*d:1E5<b&&(c=d);b=0;4E3<a?b=I*c:2E3<a?b=H*c:100<a?b=G:15<a&&(b=F);return b}parseTimestampOffset(a){return a}getBounds(a){E(this._boundsBuffer,4*this.getIndex()+4,0);if(4294967295===this.getBoundsXMin())return!1;if(0===this.getBoundsXMin()){var b=this.readGeometryWorldSpace();if(!b)return this.setBoundsXMin(4294967295),
!1;let k=Infinity,l=Infinity,m=-Infinity,n=-Infinity;b.forEachVertex((w,x)=>{k=Math.min(k,w);l=Math.min(l,x);m=Math.max(m,w);n=Math.max(n,x)});this.setBoundsXMin(k);this.setBoundsYMin(l);this.setBoundsXMax(m);this.setBoundsYMax(n);u.fromRectValues(a,k,l,m,n);return!0}b=this.getBoundsXMin();const c=this.getBoundsYMin(),d=this.getBoundsXMax(),P=this.getBoundsYMax();u.fromRectValues(a,b,c,d,P);return!0}getBoundsXMin(){return this._boundsBuffer[4*this.getIndex()]}setBoundsXMin(a){this._boundsBuffer[4*
this.getIndex()]=a}getBoundsYMin(){return this._boundsBuffer[4*this.getIndex()+1]}setBoundsYMin(a){this._boundsBuffer[4*this.getIndex()+1]=a}getBoundsXMax(){return this._boundsBuffer[4*this.getIndex()+2]}setBoundsXMax(a){this._boundsBuffer[4*this.getIndex()+2]=a}getBoundsYMax(){return this._boundsBuffer[4*this.getIndex()+3]}setBoundsYMax(a){this._boundsBuffer[4*this.getIndex()+3]=a}readAttributeAsTimestamp(a){a=this.readAttribute(a);return"string"===typeof a?(new Date(a)).getTime():"number"===typeof a||
null==a?a:null}readAttribute(a,b=!1){var c=this._readAttribute(a,b);if(void 0!==c)return c;for(const d of this._joined)if(d.setIndex(this.getIndex()),c=d._readAttribute(a,b),void 0!==c)return c}readAttributes(){const a=this._readAttributes();for(const b of this._joined){b.setIndex(this.getIndex());const c=b._readAttributes();for(const d of Object.keys(c))a[d]=c[d]}return a}joinAttributes(a){this._joined.push(a)}removeIds(a){if(null==this._objectIdToIndex){var b=new Map;const c=this.getCursor();for(;c.next();){const d=
c.getObjectId();y.assertIsSome(d);b.set(d,c.getIndex())}this._objectIdToIndex=b}b=this._objectIdToIndex;for(const c of a.values())b.has(c)&&this._removeAtIndex(b.get(c))}readOptimizedFeatureWorldSpace(){var a=this.readGeometryWorldSpace();const b=this.readAttributes(),c=this.readCentroidWorldSpace();a=new B.OptimizedFeature(a,b,c);a.objectId=this.getObjectId();a.displayId=this.getDisplayId();return a}readLegacyFeatureForDisplay(){const a=this.readCentroidForDisplay();return{attributes:this.readAttributes(),
geometry:this.readLegacyGeometryForDisplay(),centroid:(a&&{x:a.coords[0],y:a.coords[1]})??null}}readLegacyFeatureWorldSpace(){const a=this.readCentroidWorldSpace();return{attributes:this.readAttributes(),geometry:this._readLegacyGeometryWorldSpace(),centroid:(a&&{x:a.coords[0],y:a.coords[1]})??null}}readLegacyGeometryForDisplay(){const a=this.readGeometryForDisplay();return f.convertToGeometry(a,this.geometryType,!1,!1)}readXForDisplay(){return this._readX()}readYForDisplay(){return this._readY()}readXWorldSpace(){const a=
this._readX(),b=this.getInTransform();return null==b?a:a*b.scale[0]+b.translate[0]}readYWorldSpace(){const a=this._readY(),b=this.getInTransform();return null==b?a:b.translate[1]-a*b.scale[1]}readGeometryForDisplay(){var a=this._readGeometryDeltaDecoded(!0);return a?a:(a=this._createGeometryFromServerCentroid())?a.deltaDecode():null}readGeometryWorldSpace(){var a=this._readGeometry();a||=this._createGeometryFromServerCentroid();if(!a)return null;a=a.clone();const b=this.getInTransform();null!=b&&
f.unquantizeOptimizedGeometry(a,a,this.hasZ,this.hasM,b);return a}readCentroidForDisplay(){const a=this.readGeometryForDisplay();return a?this._computeDisplayCentroid(a):this._readServerCentroid()}readCentroidWorldSpace(){var a=this.readGeometryForDisplay();a=a?this._computeDisplayCentroid(a):this._readServerCentroid();if(!a)return null;a=a.clone();const b=this.getInTransform();null!=b&&f.unquantizeOptimizedGeometry(a,a,this.hasZ,this.hasM,b);return a}_readGeometryDeltaDecoded(a){a=this._readGeometry(a);
return"esriGeometryPoint"!==this.geometryType&&a&&this.getInTransform()?a.deltaDecode():a}get contextTimeZone(){return this._contextTimeZone}set contextTimeZone(a){this._contextTimeZone=a}readArcadeFeature(){return this}hasField(a){return this.fields.has(a)}geometry(){var a=this.readGeometryWorldSpace();a=f.convertToGeometry(a,this.geometryType,this.hasZ,this.hasM);if(a=D.fromJSON(a)){if(!this.metadata.spatialReference)throw Error("InternalError: Expected spatial reference to be defined");a.spatialReference=
this.metadata.spatialReference}return a}autocastArcadeDate(a,b){return b&&b instanceof Date?this.isUnknownDateTimeField(a)?g.ArcadeDate.unknownDateJSToArcadeDate(b):g.ArcadeDate.dateJSAndZoneToArcadeDate(b,this.contextTimeZone??v.system):b}isUnknownDateTimeField(a){return this.metadata.fieldsIndex.getTimeZone(a)===v.unknown}field(a){let b=this.fields.get(a);if(b)switch(b.type){case "date-only":case "esriFieldTypeDateOnly":return r.DateOnly.fromReader(this.readAttribute(a,!1));case "time-only":case "esriFieldTypeTimeOnly":return t.TimeOnly.fromReader(this.readAttribute(a,
!1));case "esriFieldTypeTimestampOffset":case "timestamp-offset":return g.ArcadeDate.fromReaderAsTimeStampOffset(this.readAttribute(a,!1));case "date":case "esriFieldTypeDate":return this.autocastArcadeDate(a,this.readAttribute(a,!0));default:return this.readAttribute(a,!1)}for(const c of this._joined)if(c.setIndex(this.getIndex()),b=c.fields.get(a))switch(b.type){case "date-only":case "esriFieldTypeDateOnly":return r.DateOnly.fromReader(c._readAttribute(a,!1));case "time-only":case "esriFieldTypeTimeOnly":return t.TimeOnly.fromReader(c._readAttribute(a,
!1));case "esriFieldTypeTimestampOffset":case "timestamp-offset":return g.ArcadeDate.fromReaderAsTimeStampOffset(c._readAttribute(a,!1));case "date":case "esriFieldTypeDate":return this.autocastArcadeDate(a,c._readAttribute(a,!0));default:return this.readAttribute(a,!1)}throw Error(`Field ${a} does not exist`);}setField(a,b){throw Error("Unable to update feature attribute values, feature is readonly");}keys(){return this.fields.fields.map(a=>a.name)}castToText(a=!1){if(!a)return JSON.stringify(this.readLegacyFeatureForDisplay());
a=this.readLegacyFeatureForDisplay();if(!a)return JSON.stringify(null);a={geometry:a.geometry,attributes:{...(a.attributes??{})}};for(const b in a.attributes){const c=a.attributes[b];c instanceof Date&&(a.attributes[b]=c.getTime())}return JSON.stringify(a)}gdbVersion(){return null}fullSchema(){return this.metadata.arcadeSchema}castAsJson(a=null){return{attributes:this._readAttributes(),geometry:!0===a?.keepGeometryType?this.geometry():this.geometry()?.toJSON()??null}}castAsJsonAsync(a,b=null){return Promise.resolve(this.castAsJson(b))}_getExists(){return null==
this._deleted||!this._deleted.has(this.getIndex())}_computeDisplayCentroid(a){a=z.GeometryCursor.fromOptimized(a,this.geometryType);a.yFactor*=-1;return(a=A.getLabelPoint(a))?(a[1]*=-1,new p([],a)):null}copyInto(a){a._joined=this._joined;a._deleted=this._deleted;a._objectIdToIndex=this._objectIdToIndex;a._boundsBuffer=this._boundsBuffer}_readLegacyGeometryWorldSpace(){const a=this.readGeometryWorldSpace();return f.convertToGeometry(a,this.geometryType,!1,!1)}_createGeometryFromServerCentroid(){const a=
this._readServerCentroid();if(!a)return null;const [b,c]=a.coords;return this._createQuantizedExtrudedGeometry(b,c)}_createQuantizedExtrudedGeometry(a,b){return"esriGeometryPolyline"===this.geometryType?this._createQuantizedExtrudedLine(a,b):this._createQuantizedExtrudedQuad(a,b)}_createQuantizedExtrudedQuad(a,b){return new p([5],[a-1,b,1,-1,1,1,-1,1,-1,-1])}_createQuantizedExtrudedLine(a,b){return new p([2],[a-1,b+1,1,-1])}_removeAtIndex(a){null==this._deleted&&(this._deleted=C.StaticBitSet.create(this.getSize()));
this._deleted.set(a)}}q.FeatureSetReader=O;Object.defineProperty(q,Symbol.toStringTag,{value:"Module"})});