// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define({title:"Dagslys",directShadow:"Vi skygger",notSupportedInHW:"Denne funktion underst\u00f8ttes ikke af denne browser.",unsupported:"V\u00e6rkt\u00f8jet Dagslys underst\u00f8ttes kun i SceneView.",datePattern:"MMMM d, \u00e5\u00e5\u00e5\u00e5",playDay:"Anim\u00e9r sol og skygge i l\u00f8bet af en dag",playYear:"Anim\u00e9r sol og skygge i l\u00f8bet af et \u00e5r",pause:"Pause",season:"\u00c5rstid",spring:"For\u00e5r",summer:"Sommer",winter:"Vinter",fall:"Efter\u00e5r",timezoneHAST:"HAST",timezoneAKST:"AKST",
timezonePST:"PST",timezoneMST:"MST",timezoneCST:"CST",timezoneEST:"EST",timezoneCET:"CET",timezoneEET:"EET",timezoneMSK:"MSK",timezoneGST:"GST",timezoneICT:"ICT",timezoneCCT:"CCT",timezoneJST:"JST",timezoneAEST:"AEST",timezoneNZST:"NZST",timezoneDateline:"International vestlig datolinje",timezoneHawaii:"Hawaii",timezoneAlaska:"Alaska",timezoneBaja:"Baja California",timezoneMountain:"Mountain Time (USA og Canada)",timezoneLaPaz:"Chihuahua, La Paz, Mazatl\u00e1n",timezoneArizona:"Arizona",timezoneSaskatchewan:"Saskatchewan",
timezoneCentralAmerica:"Centralamerika",timezoneCentralTime:"Central Time (USA og Canada)",timezoneMexico:"Guadalajara, Mexico City, Monterrey",timezoneEasternUS:"Eastern Time (USA og Canada)",timezoneLima:"Bogota, Lima, Quito",timezoneIndiana:"Indiana (\u00d8st) ",timezoneAtlantic:"Atlantic Time (Canada)",timezoneCuiaba:"Cuiab\u00e1",timezoneSantiago:"Santiago",timezoneManaus:"Georgetown, La Paz, Manaus, San Juan",timezoneAsuncion:"Asunci\u00f3n",timezoneBrasilia:"Brasilia",timezoneGreenland:"Gr\u00f8nland",
timezoneMontevideo:"Montevideo",timezoneCayenne:"Cayenne, Fortaleza",timezoneBuenosAires:"Buenos Aires",timezoneMidAtlantic:"Mid-Atlantic",timezoneAzores:"Azorerne",timezoneCaboVerde:"Kap Verde",timezoneDublin:"Dublin, Edinburgh, Lissabon, London",timezoneReykjavik:"Monrovia, Reykjavik",timezoneCasablanca:"Casablanca",timezoneBelgrade:"Beograd, Bratislava, Budapest, Ljubljana, Prag",timezoneSarajevo:"Sarajevo, Skopje, Warsawa, Zagreb",timezoneBrussels:"Bruxelles, K\u00f8benhavn, Madrid, Paris",timezoneWCAfrica:"Vestlige centralafrika",
timezoneAmsterdam:"Amsterdam, Berlin, Bern, Rom, Stockholm, Wien",timezoneWindhoek:"Windhoek",timezoneMinsk:"Minsk",timezoneCairo:"Cairo",timezoneHelsinki:"Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",timezoneAthens:"Athen, Bukarest",timezoneJerusalem:"Jerusalem",timezoneAmman:"Amman",timezoneBeirut:"Beirut",timezoneHarare:"Harare, Pretoria",timezoneDamascus:"Damaskus",timezoneIstanbul:"Istanbul",timezoneKuwait:"Kuwait, Riyadh",timezoneBaghdad:"Baghdad",timezoneNairobi:"Nairobi",timezoneKaliningrad:"Kaliningrad",
timezoneMoscow:"Moskva, St. Petersborg, Volgograd",timezoneMuscat:"Abu Dhabi, Muscat",timezoneBaku:"Baku",timezoneYerevan:"Jerevan",timezoneTbilisi:"Tbilisi",timezonePortLouis:"Port Louis",timezoneTashkent:"Tasjkent",timezoneIslamabad:"Islamabad, Karachi",timezoneEkaterinburg:"Jekaterinburg",timezoneAstana:"Astana",timezoneDhaka:"Dhaka",timezoneNovosibirsk:"Novosibirsk",timezoneBangkok:"Bangkok, Hanoi, Jakarta",timezoneKrasnoyarsk:"Krasnojarsk",timezoneBeijing:"Beijing, Chongqing, Hongkong, \u00dcr\u00fcmqi",
timezoneSingapore:"Kuala Lumpur, Singapore",timezoneTaipei:"Taipei",timezonePerth:"Perth",timezoneUlaanbaatar:"Ulan Bator",timezoneIrkutsk:"Irkutsk",timezoneSeoul:"Seoul",timezoneOsaka:"Osaka, Sapporo, Tokyo",timezoneYakutsk:"Jakutsk",timezoneCanberra:"Canberra, Melbourne, Sydney",timezoneBrisbane:"Brisbane",timezoneHobart:"Hobart",timezoneGuam:"Guam, Port Moresby",timezoneVladivostok:"Vladivostok",timezoneSolomon:"Salomon\u00f8erne, Ny Kaledonien",timezoneMagadan:"Magadan",timezoneFiji:"Fiji",timezoneAuckland:"Auckland, Wellington",
timezoneNukualofa:"Nuku'alofa",timezoneSamoa:"Samoa",chooseTimezone:"V\u00e6lg din tidszone"});