// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.8/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/declareExtendsHelper ../../../../core/tsSupport/decorateHelper ../../../../Graphic ../../../../core/Accessor ../../../../core/Collection ../../../../core/Handles ../../../../core/watchUtils ../../../../core/accessorSupport/decorators ../../../../geometry/support/webMercatorUtils ../../../../tasks/support/Query ./constants ./Graphics3DCore ./Graphics3DElevationAlignment ./Graphics3DFrustumVisibility ./Graphics3DHighlights ./Graphics3DScaleVisibility ./Graphics3DSpatialIndex ./Graphics3DVerticalScale ./graphicUtils ../support/attributeUtils".split(" "),
function(F,G,p,d,h,q,r,t,g,c,k,u,v,w,x,y,z,A,B,C,D,l){return function(m){function b(a){a=m.call(this)||this;a._handles=new t;a.highlights=new z;a.suspendResumeExtentMode="computed";a.dataExtent=null;a.suspendResumeExtent=null;return a}p(b,m);Object.defineProperty(b.prototype,"suspended",{get:function(){return this.scaleVisibility&&this.scaleVisibility.suspended||this.frustumVisibility&&this.frustumVisibility.suspended},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"updating",{get:function(){return!!(this.graphicsCore&&
this.graphicsCore.updating||this.frustumVisibility&&this.frustumVisibility.updating||this.scaleVisibility&&this.scaleVisibility.updating)},enumerable:!0,configurable:!0});b.prototype.normalizeCtorArgs=function(a){var b=this,f=null,c,d,e,n;a.queryGraphicUIDsInExtent||!a.scaleVisibilityEnabled&&!a.elevationAlignmentEnabled||(f=new B({spatialReference:a.owner.view.spatialReference}));a.frustumVisibilityEnabled&&(c=new y);a.scaleVisibilityEnabled&&(d=new A);a.elevationAlignmentEnabled&&(e=new x);a.verticalScaleEnabled&&
(n=new C({sourceSpatialReference:a.layer.spatialReference,destSpatialReference:a.owner.view.spatialReference}));var g=function(a,b,E){return f.queryGraphicUIDsInExtent(a,b,E)};return{graphicsCore:new w({owner:a.owner,layer:a.layer,basemapTerrain:a.owner.view.basemapTerrain,elevationFeatureExpressionEnabled:a.elevationFeatureExpressionEnabled,graphicTransformFunc:function(a){return b.verticalScale?b.verticalScale.adjust(a):a}}),frustumVisibility:c,verticalScale:n,scaleVisibility:d,elevationAlignment:e,
spatialIndex:f,updateClippingExtent:a.updateClippingExtent,suspendResumeExtentMode:a.suspendResumeExtentMode,dataExtent:a.dataExtent,queryGraphicUIDsInExtent:a.queryGraphicUIDsInExtent||g}};b.prototype.initialize=function(){var a=this;this.scaleVisibility&&this._handles.add(this.layer.watch(["minScale","maxScale"],function(){return a.scaleVisibility.layerMinMaxScaleChangeHandler()}));this.elevationAlignment&&this._handles.add(this.layer.watch("elevationInfo",function(){return a.graphicsCore.elevationInfoChange()}));
this.graphicsCore&&(this._handles.add(this.layer.watch("labelsVisible",function(){return a.owner.view.labeler.setDirty()})),this._handles.add(this.layer.watch("labelingInfo",function(){return a.graphicsCore.updateLabelingInfo()})));this.idleClients=[this.frustumVisibility,this.scaleVisibility,this.elevationAlignment,this.graphicsCore]};b.prototype.setup=function(){var a=this;this.frustumVisibility&&this.frustumVisibility.setup(this.owner);var b=this.owner.view.basemapTerrain,f=this.owner.view.elevationProvider;
this.scaleVisibility&&this.scaleVisibility.setup(this.owner,this.layer,this.queryGraphicUIDsInExtent,this.graphicsCore,b);this.elevationAlignment&&this.elevationAlignment.setup(this.owner,this.queryGraphicUIDsInExtent,this.graphicsCore,f);this.highlights&&this.highlights.setup(this.graphicsCore);this._set("labeling",this.owner.view.labeler.addGraphicsOwner(this.graphicsCore,this.scaleVisibility,this.spatialIndex));this.graphicsCore.setup({elevationAlignment:this.elevationAlignment,scaleVisibility:this.scaleVisibility,
spatialIndex:this.spatialIndex,labeling:this.labeling,highlights:this.highlights});this._handles.add([this.layer.watch("renderer",function(b){return a.graphicsCore.rendererChange(b)}),this.owner.watch("fullOpacity",function(){return a.graphicsCore.opacityChange()})]);this._handles.add(this.layer.on("graphic-update",function(b){return a.graphicsCore.graphicUpdateHandler(b)}));this.setupSuspendResumeExtent();this.owner.view.resourceController.registerIdleFrameWorker(this,{needsUpdate:this.needsIdleUpdate,
idleFrame:this.idleUpdate});this.updateClippingExtent&&(this._handles.add(this.owner.view.watch("clippingArea",function(){return a._updateClippingExtent()})),this._updateClippingExtent());if(this.graphicsCore.labelsEnabled)return this.graphicsCore.updateLabelingInfo()};b.prototype.destroy=function(){this.owner&&this.owner.view.resourceController.deregisterIdleFrameWorker(this);this._handles&&(this._handles.destroy(),this._handles=null);this.frustumVisibility&&(this.frustumVisibility.destroy(),this._set("frustumVisibility",
null));this.scaleVisibility&&(this.scaleVisibility.destroy(),this._set("scaleVisibility",null));this.elevationAlignment&&(this.elevationAlignment.destroy(),this._set("elevationAlignment",null));this.graphicsCore&&(this.graphicsCore.destroy(),this._set("graphicsCore",null));this.spatialIndex&&(this.spatialIndex.destroy(),this._set("spatialIndex",null));this.highlights&&(this.highlights.destroy(),this._set("highlights",null));this._set("layer",null);this._set("owner",null)};b.prototype.highlight=function(a,
b,f){var c=this;if(a instanceof u){b=this.highlights.acquireSet(b,f);var d=b.set,e=b.handle;this.owner.queryObjectIds(a).then(function(a){return c.highlights.setObjectIds(d,a)});return e}if("number"===typeof a||a instanceof h)return this.highlight([a],b,f);a instanceof r&&(a=a.toArray());if(Array.isArray(a)&&0<a.length){if(a[0]instanceof h)if(e=a,f&&e[0].attributes&&null!==l.attributeLookup(e[0].attributes,f))a=e.map(function(a){return l.attributeLookup(a.attributes,f)});else return a=e.map(function(a){return a.uid}),
e=this.highlights.acquireSet(b,null),b=e.set,e=e.handle,this.highlights.setUids(b,a),e;if("number"===typeof a[0])return e=this.highlights.acquireSet(b,f),b=e.set,e=e.handle,this.highlights.setObjectIds(b,a),e}return{remove:function(){}}};b.prototype.needsIdleUpdate=function(){for(var a=0,b=this.idleClients;a<b.length;a++){var f=b[a];if(f&&f.needsIdleUpdate())return!0}return!1};b.prototype.idleUpdate=function(a){for(var b=0,f=this.idleClients;b<f.length;b++){var c=f[b];c&&c.idleUpdate(a)}};b.prototype._updateClippingExtent=
function(){var a=this.owner.view.clippingArea;this.graphicsCore.setClippingExtent(a,this.owner.view.spatialReference)&&(this.updateClippingExtent(a)||this.graphicsCore.recreateAllGraphics())};b.prototype.setupSuspendResumeExtent=function(){var a=this;(this.frustumVisibility||this.scaleVisibility)&&this._handles.add(g.init(this,"suspendResumeExtentMode",function(b){a._handles.remove("suspendResumeExtentMode");switch(a.suspendResumeExtentMode){case "computed":a._handles.add(g.init(a.graphicsCore,"computedExtent",
function(b){return a.updateSuspendResumeExtent(b)}),"suspendResumeExtentMode");break;case "data":a._handles.add(g.init(a,"dataExtent",function(b){return a.updateSuspendResumeExtent(b)}),"suspendResumeExtentMode")}}))};b.prototype.updateSuspendResumeExtent=function(a){a?this.suspendResumeExtentChanged(this.extentToSuspendResumeRect(a,this.suspendResumeExtent)):this.suspendResumeExtentChanged(null)};b.prototype.extentToSuspendResumeRect=function(a,b){var c=this.owner.view.spatialReference;if(!a.spatialReference.equals(c)){if(!k.canProject(a,
c))return;a=k.project(a,c)}return D.enlargeExtent(a,b,v.SUSPEND_RESUME_EXTENT_OPTIMISM)};b.prototype.suspendResumeExtentChanged=function(a){this.frustumVisibility&&this.frustumVisibility.setExtent(a);this.scaleVisibility&&this.scaleVisibility.setExtent(a)};d([c.property({aliasOf:"graphicsCore.layer"})],b.prototype,"layer",void 0);d([c.property({aliasOf:"graphicsCore.owner"})],b.prototype,"owner",void 0);d([c.property({constructOnly:!0})],b.prototype,"updateClippingExtent",void 0);d([c.property({constructOnly:!0})],
b.prototype,"queryGraphicUIDsInExtent",void 0);d([c.property({constructOnly:!0})],b.prototype,"graphicsCore",void 0);d([c.property({constructOnly:!0})],b.prototype,"verticalScale",void 0);d([c.property({constructOnly:!0})],b.prototype,"spatialIndex",void 0);d([c.property({constructOnly:!0})],b.prototype,"scaleVisibility",void 0);d([c.property({constructOnly:!0})],b.prototype,"elevationAlignment",void 0);d([c.property({constructOnly:!0})],b.prototype,"frustumVisibility",void 0);d([c.property({readOnly:!0})],
b.prototype,"labeling",void 0);d([c.property({readOnly:!0})],b.prototype,"highlights",void 0);d([c.property()],b.prototype,"suspendResumeExtentMode",void 0);d([c.property()],b.prototype,"dataExtent",void 0);d([c.property({readOnly:!0,dependsOn:["scaleVisibility.suspended","frustumVisibility.suspended"]})],b.prototype,"suspended",null);d([c.property({readOnly:!0,dependsOn:["graphicsCore.updating","frustumVisibility.updating","scaleVisibility.updating"]})],b.prototype,"updating",null);return b=d([c.subclass("esri.views.3d.layers.graphics.Graphics3DFeatureLikeLayerView")],
b)}(c.declared(q))});