// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("../../../chunks/tslib.es6 ../../../geometry ../../../core/Accessor ../../../core/Error ../../../core/accessorSupport/decorators/property ../../../core/has ../../../core/Logger ../../../core/RandomLCG ../../../core/accessorSupport/decorators/subclass ../../../geometry/coordinateFormatter ../../../geometry/projection ../../../geometry/support/spatialReferenceUtils ../../../geometry/support/webMercatorUtils ./coordinateConversionUtils ../../../geometry/SpatialReference".split(" "),function(f,
e,t,n,h,x,y,z,u,l,r,v,w,m,p){e=class extends t{constructor(a){super(a);this.coordinateSegments=this.conversionInfo=null;this._currentPattern=void 0;this.viewModel=this.name=this.defaultPattern=null}get currentPattern(){return(this._currentPattern||this.defaultPattern)??""}set currentPattern(a){this._currentPattern=a}get label(){return this.name??""}set label(a){this._overrideIfSome("label",a)}get hasDisplayProperties(){return!(!this.defaultPattern||!this.coordinateSegments)}get spatialReference(){return"basemap"===
this.name?this._viewSpatialReference:this.conversionInfo?.spatialReference??p.WGS84}set spatialReference(a){this._overrideIfSome("spatialReference",a)}get _viewSpatialReference(){return this.viewModel?.view?.spatialReference??p.WGS84}get _additionalCharactersPattern(){var a=this.coordinateSegments;if(!a)return null;a=a.map(b=>b.alias);a=this.currentPattern.replaceAll(new RegExp(`["nsew${a.join()}]`,"gi"),"").replaceAll(" ","");return new RegExp(`[${a}]`,"g")}get test(){return{additionalCharactersPattern:this._additionalCharactersPattern}}async convert(a){if(!m.isValidPoint(a))throw new n("format:invalid-point",
"Could not convert invalid point.",{point:a});const b=this.conversionInfo?.convert;if(b)return Promise.resolve().then(()=>b(a));const c=await this._project(a,this.spatialReference),d=await this._getCoordinate(c);return{location:c,coordinate:d}}getConversionStrategy(){const a=this._viewSpatialReference;return this.conversionInfo?.convert||this.viewModel?.formatterAvailable||"xy"===this.name&&(a.isWebMercator||a.isWGS84)||"basemap"===this.name?"client":"server"}getDisplayCoordinate(a){if(!a)return null;
if(!this.coordinateSegments||!this.currentPattern)return a;let b=this.currentPattern;a=this._getSegmentMatches(a,!1);for(let c=this.coordinateSegments.length-1;0<=c;c--)b=b.replace(this.coordinateSegments[c].alias,a[c]);return b}parseUserInput(a){const {defaultPattern:b,_additionalCharactersPattern:c,coordinateSegments:d}=this;if(!b||!c)return"";let k=b.replace(c,"");a=a.replace(c,"");a=this._getSegmentMatches(a,!0);if(d)for(let g=d.length-1;0<=g;g--)k=k.replace(d[g].alias,a[g]);return k}_getSegmentMatches(a,
b){const c=[],{coordinateSegments:d}=this;if(!d)return c;for(let q=0;q<d.length;q++){var k=d[q],g=a.match(k.searchPattern);g?(g=g[0],a=a.replace(g,"").trim(),k.substitution&&(k=b?k.substitution.input(g):k.substitution.output(g))&&(g=`${k}`),c.push(g)):c.push("")}return c}async reverseConvert(a){const b=this.parseUserInput(a),c=this.conversionInfo?.reverseConvert;let d;if(c)d=c(b);else if("xy"===this.name||"basemap"===this.name)d=m.fromXY(b,this.spatialReference);else if(this.viewModel?.formatterAvailable)switch(this.name){case "dd":case "ddm":case "dms":d=
l.fromLatitudeLongitude(b,this.spatialReference);break;case "mgrs":d=l.fromMgrs(b,this.spatialReference,"automatic");break;case "utm":d=l.fromUtm(b,this.spatialReference,"latitude-band-indicators");break;case "usng":d=l.fromUsng(b,this.spatialReference);break;default:d=null}if(!d)throw new n("format:invalid-input","Could not parse input into point.",{userInput:a});return this._project(d,this._viewSpatialReference)}async _getCoordinate(a){var b=this.viewModel?.view?.scale??0;if(!m.isValidPoint(a))throw new n("format:invalid-point",
"Could not transform invalid point into coordinate.",{point:a});if(this.viewModel?.formatterAvailable||"basemap"===this.name||"xy"===this.name)switch(this.name){case "dd":case "ddm":case "dms":return b=m.getDegreePrecision(b),l.toLatitudeLongitude(a,this.name,b);case "mgrs":return l.toMgrs(a,"automatic",5,!1);case "usng":return l.toUsng(a,5,!1);case "utm":return l.toUtm(a,"latitude-band-indicators",!0)}return m.pointToCoordinate(a,b)}async _project(a,b){return v.equals(a.spatialReference,b)||!b?a:
this.viewModel?.formatterAvailable&&r.isLoaded()?r.project(a,b):this.viewModel?.formatterAvailable||(a=w.project(a,b),null==a)?null:a}};f.__decorate([h.property()],e.prototype,"conversionInfo",void 0);f.__decorate([h.property()],e.prototype,"coordinateSegments",void 0);f.__decorate([h.property()],e.prototype,"currentPattern",null);f.__decorate([h.property()],e.prototype,"_currentPattern",void 0);f.__decorate([h.property()],e.prototype,"label",null);f.__decorate([h.property()],e.prototype,"defaultPattern",
void 0);f.__decorate([h.property({readOnly:!0})],e.prototype,"hasDisplayProperties",null);f.__decorate([h.property()],e.prototype,"name",void 0);f.__decorate([h.property({type:p})],e.prototype,"spatialReference",null);f.__decorate([h.property()],e.prototype,"viewModel",void 0);f.__decorate([h.property({readOnly:!0})],e.prototype,"_viewSpatialReference",null);f.__decorate([h.property({readOnly:!0})],e.prototype,"_additionalCharactersPattern",null);return e=f.__decorate([u.subclass("esri.widgets.CoordinateConversion.support.Format")],
e)});