// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/tslib.es6 ../../../core/Accessor ../../../core/handleUtils ../../../core/maybe ../../../core/reactiveUtils ../../../core/scheduling ../../../core/signal ../../../core/time ../../../core/accessorSupport/decorators/property ../../../core/has ../../../core/Logger ../../../core/RandomLCG ../../../core/accessorSupport/decorators/subclass ./index ./MemoryController ./StreamDataLoader ../../support/Scheduler".split(" "),function(m,b,f,q,g,k,r,t,u,d,z,A,B,n,p,v,w,h){f=class extends f{constructor(){super(...arguments);
this.updating=!1}};b.__decorate([d.property({readOnly:!0})],f.prototype,"updating",void 0);f=b.__decorate([n.subclass("esri.views.3d.support.ResourceControllerMain")],f);let c=class extends f{constructor(){super(...arguments);this._normalTask=this._immediateTask=h.ImmediateTask;this._updatingObjects=t.signal([]);this._frameTask=null}get immediate(){return this._immediateTask}get normal(){return this._normalTask}initialize(){this._scheduler=h.newScheduler();this._memoryController=v.newMemoryController(this.view);
this._streamDataLoader=new w.StreamDataLoader;this._streamDataLoader.setup(p.maxDownloadSlots,p.downloadSlotsPerClient,this._scheduler);this.addHandles([k.watch(()=>this.view.state?.mode,a=>{null!=a&&(this._scheduler.state=a)},k.sync),k.watch(()=>this.view.stationary,()=>this._stationaryChangedHandler())]);this._frameTask=r.addFrameTask({update:a=>this._frame(a)});this._immediateTask=this._scheduler.registerTask(h.TaskPriority.RESOURCE_CONTROLLER_IMMEDIATE);this._normalTask=this._scheduler.registerTask(h.TaskPriority.RESOURCE_CONTROLLER)}destroy(){this._immediateTask.remove();
this._normalTask.remove();this._frameTask=g.removeMaybe(this._frameTask);this._streamDataLoader=g.destroyMaybe(this._streamDataLoader);this._memoryController=g.destroyMaybe(this._memoryController);this._scheduler=g.destroyMaybe(this._scheduler);this.view=null}get updating(){return!!(this._memoryController?.updating||this._streamDataLoader?.updating||this._immediateTask?.updating)||this._updatingObjects?.value.some(a=>a.updating)}get scheduler(){return this._scheduler}get memoryController(){return this._memoryController}createStreamDataRequester(a){const e=
this._streamDataLoader;return{request(l,x,y){return e.request(l,x,a,y)},get busy(){return!e.hasDownloadSlots(a)}}}addUpdatingObject(a){const e=this._updatingObjects;e.value=[...e.value,a];return q.makeHandle(()=>{e.value=e.value.filter(l=>l!==a)})}_frame(a){if(!this.view.suspended){if(this.view.stateManager&&(this.view.stateManager.step(u.secondsFromMilliseconds(a.deltaTime)),!this._scheduler))return;this._memoryController.update();this._scheduler.updateBudget(a)&&this._scheduler.frame()}}_stationaryChangedHandler(){this.memoryController.resetStableQuality()}get test(){return{getQueueStats:a=>
this._streamDataLoader.test.loadQueue.getStatsForType(a)}}};b.__decorate([d.property()],c.prototype,"view",void 0);b.__decorate([d.property()],c.prototype,"_scheduler",void 0);b.__decorate([d.property()],c.prototype,"_memoryController",void 0);b.__decorate([d.property()],c.prototype,"_streamDataLoader",void 0);b.__decorate([d.property()],c.prototype,"_immediateTask",void 0);b.__decorate([d.property()],c.prototype,"_normalTask",void 0);b.__decorate([d.property()],c.prototype,"_updatingObjects",void 0);
b.__decorate([d.property({readOnly:!0})],c.prototype,"updating",null);c=b.__decorate([n.subclass("esri.views.3d.support.ResourceControllerImpl")],c);m.newResourceController=function(a){return new c({view:a})};Object.defineProperty(m,Symbol.toStringTag,{value:"Module"})});