// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.8/esri/copyright.txt for details.
//>>built
define("../lib/Renderer ../lib/SSAOHelperObscurance ../lib/ShadowMap ../lib/NearFarCalc ../lib/Util ../lib/gl-matrix".split(" "),function(x,y,z,A,t,h){var k=h.vec3d,q=h.mat4;return function(l,h,B,u,n){var d=new x(l,h,B,u,n),c=new z(l,n),b=new y(l,u,n),C=new A,p={},v=!1,w=!1,m=!0;this.getCombinedStats=function(){return d.getCombinedStats()};this.dispose=function(){d.dispose();c.getEnableState()&&c.disable();b.getEnableState()&&b.disable()};this.setLightingData=function(a){d.setLightingData(a)};this.getLightingData=
function(){return d.getLightingData()};this.getViewParams=function(a){var f=a||{};if(!a||a.pixelRatio)f.pixelRatio=d.getPixelRatio();return f};this.setViewParams=function(a){null!=a.pixelRatio&&d.setPixelRatio(a.pixelRatio)};this.setRenderParams=function(a){void 0!==a.shadowMapResolution&&!1===c.getEnableState()&&c.setTextureResolution(a.shadowMapResolution);void 0!==a.shadowMap&&a.shadowMap!==c.getEnableState()&&c.setEnableState(a.shadowMap);void 0!==a.shadowMapMaxCascades&&c.setMaxNumCascades(a.shadowMapMaxCascades);
void 0!==a.ssao&&a.ssao!==b.getEnableState()&&b.setEnableState(a.ssao);void 0!==a.ssaoAttenuation&&b.setAttenuation(a.ssaoAttenuation);void 0!==a.ssaoRadius&&b.setRadius(a.ssaoRadius);void 0!==a.ssaoFilterRadius&&b.setFilterRadius(a.ssaoFilterRadius);void 0!==a.ssaoSamples&&b.setSamples(a.ssaoSamples);void 0!==a.debugInstanceThreshold&&d.setThreshold(a.debugInstanceThreshold);void 0!==a.drawShadowMapDebugQuad&&(v=a.drawShadowMapDebugQuad);void 0!==a.drawSSAODebugQuad&&(w=a.drawSSAODebugQuad);m=!0};
this.getRenderParams=function(){var a={};c.getIsSupported()&&(a.shadowMap=c.getEnableState(),a.shadowMapResolution=c.getTextureResolution(),a.shadowMapMaxCascades=c.getMaxNumCascades());b.getIsSupported()&&(a.ssao=b.getEnableState(),a.ssaoAttenuation=b.getAttenuation(),a.ssaoRadius=b.getRadius(),a.ssaoFilterRadius=b.getFilterRadius(),a.ssaoSamples=b.getSamples());return a};this.modify=function(a,f,e,b,c){d.modify(a,f,e,b);e=0;for(b=f.length;e<b;++e)delete p[f[e].uniqueName];e=0;for(b=a.length;e<b;++e)p[a[e].uniqueName]=
a[e]};this.getContent=function(){return p};this.getPickRay=function(a,b,e,c,d,l){k.unproject(k.createFrom(a[0],a[1],0),c,e.projectionMatrix,e.fullViewport,d);k.unproject(k.createFrom(a[0],a[1],1),c,e.projectionMatrix,e.fullViewport,l)};this.getSideIndexForPoint=function(a,b){return 0};this.getProjectionMatrix=function(a,b,c,d,g){b=t.fovx2fovy(b,a[2],a[3]);q.perspective(180*b/Math.PI,a[2]/a[3],c,d,g)};this.setSelectionObject=function(a,b){d.setSelectionObject(a,b)};this.setHighlightObjects=function(a,
b){d.setHighlightObjects(a,b)};this.addExternalRenderer=function(a,b){return d.addExternalRenderer(a,b)};this.removeExternalRenderer=function(a,b){return d.removeExternalRenderer(a,b)};this.getExternalRenderers=function(){return d.getExternalRenderers()};this.resetNeedsRender=function(){m=!1;d.resetNeedsRender()};this.needsRender=function(){return m||d.needsRender()};this.render=function(a,f,e,h){var g=a.viewport,k;if(c.getEnableState()||b.getEnableState())k=C.calculateSceneNearFar(a,p,e);if(c.getEnableState()){c.prepare(a,
f,p,e,k);f=c.getCascades();for(var m=0;m<f.length;++m){var r=f[m];r.camera.setGLViewport(n);d.renderSimple(r.camera,e,"materialDepthShadowMap",r.camera.viewport)}c.finish(h);a.setGLViewport(n)}c.bindAll(l);b.getEnableState()&&(b.prepare0(a),d.renderSimple(a,e,"materialNormal"),b.prepare1(),d.renderSimple(a,e,"materialDepth"),b.finish(a,h,k));b.bindAll(l);d.render(a,e,c,b,h);v&&c.getEnableState()&&(a=q.ortho(g[0],g[2],g[1],g[3],-1,1),c.drawDebugQuad(a));w&&b.getEnableState()&&(a=q.ortho(g[0],g[2],
g[1],g[3],-1,1),b.drawQuad(a))};this._getModule=function(a){if("renderer"===a)return d;t.assert(!1,"Unknown module: "+a)}}});