// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define("require exports ../../../../request ../../../../core/arrayUtils ../../../../core/Error ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/typedArrayUtil ../../../../core/libs/gl-matrix-2/mat4f64 ../../../../core/libs/gl-matrix-2/quat ../../../../core/libs/gl-matrix-2/quatf32 ../../../../core/libs/gl-matrix-2/vec3 ../../../../core/libs/gl-matrix-2/vec3f64 ../../../../core/libs/gl-matrix-2/vec4f64 ../../../../geometry/SpatialReference ../../../../geometry/support/aaBoundingBox ../../../../geometry/support/webMercatorUtils ../../../../tasks/support/Query ./I3SBinaryReader ../support/edgeUtils ../support/symbolColorUtils ../../support/projectionUtils".split(" "),
function(ga,e,N,O,n,w,t,B,P,z,Q,m,R,S,C,T,U,V,W,D,X,u){function A(b){return b&&parseInt(b.substring(b.lastIndexOf("/")+1,b.length),10)}function E(b,a){var c=a[0],f=a[1],d=a[2];a=a[3];var h=b[0]-c,c=c-b[3],e=b[1]-f,f=f-b[4],l=b[2]-d;b=d-b[5];var d=Math.max(h,c,0),x=Math.max(e,f,0),v=Math.max(l,b,0),d=d*d+x*x+v*v;return d>a*a?0:0<d?1:-Math.max(h,c,e,f,l,b)>a?3:2}function G(b,a,c){var f=[],d=c&&c.missingFields;c=c&&c.originalFields;for(var h=0;h<b.length;h++){for(var e=b[h],l=e.toLowerCase(),x=!1,v=
0,g=a;v<g.length;v++){var k=g[v];if(l===k.name.toLowerCase()){f.push(k.name);x=!0;c&&c.push(e);break}}!x&&d&&d.push(e)}return f}function Y(b,a){return b.filter(function(b){return b!==a}).concat([a])}function Z(b,a,c,f){a.sort(function(a,b){return a.attributes[c]-b.attributes[c]});var d=a.map(function(a){return a.attributes[c]}),h=[],e=G(f,b.fields,{originalFields:h});return H(b,d,e).then(function(b){for(var c=0;c<a.length;c++){var d=a[c],f=b[c],l={};if(d.attributes)for(var F in d.attributes)l[F]=
d.attributes[F];for(var g=0;g<h.length;g++)l[h[g]]=f[e[g]];d.attributes=l}return a})}function H(b,a,c){var f=b.capabilities.query.maxRecordCount;if(null!=f&&a.length>f)return f=aa(a,f),t.all(f.map(function(a){return H(b,a,c)})).then(ba);f=new V({objectIds:a,outFields:c,orderByFields:[b.objectIdField]});return b.queryFeatures(f).then(function(b){if(b&&b.features&&b.features.length===a.length)return b.features.map(function(a){return a.attributes});throw new n("scenelayer:feature-not-in-associated-layer",
"Feature not found in associated feature layer");})}function ca(b,a,c,f,d){for(var e=[],g=0;g<a.length;g++){var l=a[g];l&&-1!==d.indexOf(l.name)&&e.push({url:b+"/nodes/"+c.resources.attributes+"/attributes/"+l.key+"/0",storageInfo:l})}return t.eachAlways(e.map(function(a){return N(a.url,{responseType:"array-buffer"}).then(function(b){return W.readBinaryAttribute(a.storageInfo,b.data)})})).then(function(a){for(var b=[],c=0;c<f.length;c++){for(var d=f[c],h={},g=0;g<a.length;g++)null!=a[g].value&&(h[e[g].storageInfo.name]=
I(a[g].value,d));b.push(h)}return b})}function I(b,a){if(!b)return null;a=b[a];return B.isInt16Array(b)?a===da?null:a:B.isInt32Array(b)?a===ea?null:a:a!==a?null:a}function aa(b,a){var c=b.length;a=Math.ceil(c/a);for(var f=[],d=0;d<a;d++)f.push(b.slice(Math.floor(c*d/a),Math.floor(c*(d+1)/a)));return f}function ba(b){for(var a=[],c=0;c<b.length;c++)a=a.concat(b[c]);return a}function J(b){var a=new C(A(b.store.indexCRS||b.store.geographicCRS));return a.equals(b.spatialReference)?b.spatialReference:
a}function K(b){var a=new C(A(b.store.vertexCRS||b.store.projectedCRS));return a.equals(b.spatialReference)?b.spatialReference:a}function y(b,a,c){if(!U.canProject(b,a))throw new n("layerview:spatial-reference-incompatible","The spatial reference of this scene layer is incompatible with the spatial reference of the view",{});if("local"===c&&b.isGeographic)throw new n("layerview:local-gcs-not-supported","Geographic coordinate systems are not supported in local scenes",{});}function L(b,a,c){var f=
J(b);b=K(b);y(f,a,c);y(b,a,c)}Object.defineProperty(e,"__esModule",{value:!0});e.DDS_ENCODING_STRING="image/vnd-ms.dds";e.BROWSER_SUPPORTED_IMAGE_ENCODING_STRINGS=["image/jpeg","image/png"];e.extractWkid=A;e.selectEncoding=function(b,a){if(a)for(a=0;a<b.length;a++)if(b[a].encoding===e.DDS_ENCODING_STRING)return b[a];for(a=0;a<b.length;a++)if(-1<e.BROWSER_SUPPORTED_IMAGE_ENCODING_STRINGS.indexOf(b[a].encoding))return b[a];return null};e.findIntersectingNodes=function(b,a,c,f,d,e){d.traverse(c,function(c){var d=
c.mbs;a!==f&&(d=fa,u.mbsToMbs(c.mbs,f,d,a));d=E(b,d);if(0!==d)return e(c,d),!0})};e.filterInPlace=function(b,a,c){for(var f=0,d=0,e=0;e<a.length&&f<b.length;e++)b[f]===a[e]&&(c(e)&&(b[d]=b[f],d++),f++);b.length=d};var q=T.create();e.getClipAABB=function(b,a){if(0===a.rotationScale[1]&&0===a.rotationScale[2]&&0===a.rotationScale[3]&&0===a.rotationScale[5]&&0===a.rotationScale[6]&&0===a.rotationScale[7])return q[0]=(b[0]-a.position[0])/a.rotationScale[0],q[1]=(b[1]-a.position[1])/a.rotationScale[4],
q[2]=(b[2]-a.position[2])/a.rotationScale[8],q[3]=(b[3]-a.position[0])/a.rotationScale[0],q[4]=(b[4]-a.position[1])/a.rotationScale[4],q[5]=(b[5]-a.position[2])/a.rotationScale[8],q};var fa=S.vec4f64.create();e.intersectBoundingBoxWithMbs=E;e.findFieldsCaseInsensitive=G;e.whenGraphicAttributes=function(b,a,c,f,d,e){!0===(e&&e.populateObjectId)&&(f=Y(f,c));if(0===a.length)return t.resolve(a);e=b.associatedLayer;var g=b.attributeStorageInfo;if(e)return Z(e,a,c,f);if(g){a=d(a);if(!a)return t.reject(new n("scenelayer:features-not-loaded",
"Tried to query attributes for unloaded features"));var h=b.parsedUrl.path;return t.all(a.map(function(a){return ca(h,g,a.node,a.indices,f).then(function(b){for(var c=0;c<a.graphics.length;c++){var d=a.graphics[c],f=b[c];if(d.attributes)for(var e in d.attributes)e in f||(f[e]=d.attributes[e]);d.attributes=f}return a.graphics})})).then(O.flatten)}return t.reject(new n("scenelayer:no-attribute-source","This scene layer does not have a source for attributes available"))};var da=-Math.pow(2,15),ea=-Math.pow(2,
31);e.getCachedAttributeValue=I;e.convertFlatRangesToOffsets=function(b,a,c){a=null!=a?a:b.length/c;for(var f=new Uint32Array(a+1),d=0;d<a;d++){var e=b[d*c];f[d]=3*e;var g=(d-1)*c+1;if(0<=g&&e-1!==b[g])throw new n("Face ranges are not continuous");}f[f.length-1]=3*(b[(a-1)*c+1]+1);return f};e.getIndexCrs=J;e.getVertexCrs=K;e.getCacheKeySuffix=function(b,a){return a===u.SphericalECEFSpatialReference?"@ECEF":b.equals(a)?"":null!=a.wkid?"@"+a.wkid:null};e.checkSpatialReference=y;e.checkSpatialReferences=
L;e.checkSceneLayerValid=function(b){var a;(a=null==b.store||null==b.store.defaultGeometrySchema)||(a=b.store.defaultGeometrySchema,a=!!(null!=a.geometryType&&"triangles"!==a.geometryType||null!=a.topology&&"PerAttributeArray"!==a.topology||null==a.vertexAttributes||null==a.vertexAttributes.position));if(a)throw new n("scenelayer:unsupported-geometry-schema","The geometry schema of this scene layer is not supported.",{url:b.parsedUrl.path});};e.checkSceneLayerCompatibleWithView=function(b,a){L(b,
a.spatialReference,a.viewingMode)};e.checkPointCloudLayerValid=function(b){var a;(a=null==b.store||null==b.store.defaultGeometrySchema)||(b=b.store.defaultGeometrySchema,a=!!(null==b.geometryType||"points"!==b.geometryType||null!=b.topology&&"PerAttributeArray"!==b.topology||null!=b.encoding&&""!==b.encoding&&"lepcc-xyz"!==b.encoding||null==b.vertexAttributes||null==b.vertexAttributes.position));if(a)throw new n("pointcloud:unsupported-geometry-schema","The geometry schema of this point cloud scene layer is not supported.",
{});};e.checkPointCloudLayerCompatibleWithView=function(b,a){y(b.spatialReference,a.spatialReference,a.viewingMode)};e.rendererNeedsTextures=function(b){if(null==b||"simple"!==b.type&&"class-breaks"!==b.type&&"unique-value"!==b.type||("unique-value"===b.type||"class-breaks"===b.type)&&null==b.defaultSymbol)return!0;b=b.getSymbols();if(0===b.length)return!0;for(var a=0;a<b.length;a++){var c=b[a];if("mesh-3d"!==c.type||0===c.symbolLayers.length)return!0;for(var f=0,c=c.symbolLayers.items;f<c.length;f++){var d=
c[f];if("fill"!==d.type||w.isNone(d.material)||w.isNone(d.material.color)||"replace"!==d.material.colorMixMode)return!0}}return!1};e.transparentEdgeMaterial=D.createSolidEdgeMaterial({color:[0,0,0,0],opacity:0});var M=function(){return function(){this.material=this.edgeMaterial=null;this.castShadows=!0}}();e.SymbolInfo=M;e.getSymbolInfo=function(b){var a=new M,c=!1,f=!1,d=0;for(b=b.symbolLayers.items;d<b.length;d++){var e=b[d];if("fill"===e.type&&e.enabled){var g=e.material,k=e.edges;w.isSome(g)&&
!c&&(c=g.color,g=X.parseColorMixMode(g.colorMixMode),w.isSome(c)?a.material={color:[c.r/255,c.g/255,c.b/255],alpha:c.a,colorMixMode:g}:a.material={color:[1,1,1],alpha:1,colorMixMode:1},a.castShadows=e.castShadows,c=!0);w.isSome(k)&&!f&&(a.edgeMaterial=D.createMaterialFromEdges(k,{}),f=!0)}}a.material||(a.material={color:[1,1,1],alpha:1,colorMixMode:1});return a};e.addWraparound=function(b,a){return(b|0)+(a|0)|0};e.transformObb=function(b,a,c,e,d,h){void 0===h&&(h=0);m.vec3.set(c.center,b.center[0],
b.center[1],b.center[2]+h);if(d&&e===u.SphericalECEFSpatialReference&&!a.isGeographic){for(d=0;8>d;d++)m.vec3.set(g,b.halfSize[0]*(1===(d&1)?-1:1),b.halfSize[1]*(2===(d&2)?-1:1),b.halfSize[2]*(4===(d&4)?-1:1)),m.vec3.transformQuat(g,g,b.quaternion),m.vec3.add(g,g,c.center),p[3*d+0]=g[0],p[3*d+1]=g[1],p[3*d+2]=g[2];u.computeLinearTransformation(a,c.center,k,e);d=2*Math.sqrt(1+k[0]+k[5]+k[10]);r[0]=(k[6]-k[9])/d;r[1]=(k[8]-k[2])/d;r[2]=(k[1]-k[4])/d;r[3]=.25*d;z.quat.multiply(c.quaternion,r,b.quaternion);
m.vec3.set(c.center,k[12],k[13],k[14]);u.bufferToBuffer(p,a,0,p,e,0,8);z.quat.conjugate(r,c.quaternion);for(d=e=a=b=0;8>d;d++)m.vec3.set(g,p[3*d+0],p[3*d+1],p[3*d+2]),m.vec3.sub(g,g,c.center),m.vec3.transformQuat(g,g,r),b=Math.max(b,Math.abs(g[0])),a=Math.max(a,Math.abs(g[1])),e=Math.max(e,Math.abs(g[2]));m.vec3.set(c.halfSize,b,a,e)}else u.bufferToBuffer(c.center,a,0,c.center,e,0,1),z.quat.copy(c.quaternion,b.quaternion),m.vec3.copy(c.halfSize,b.halfSize)};var g=R.vec3f64.create(),k=P.mat4f64.create(),
r=Q.quatf32.create(),p=new Float64Array(24)});