// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("exports ../../Viewpoint ../../core/Collection ../../core/unitUtils ../../core/libs/gl-matrix-2/math/common ../../core/libs/gl-matrix-2/math/mat2d ../../core/libs/gl-matrix-2/factories/mat2df64 ../../core/libs/gl-matrix-2/math/vec2 ../../core/libs/gl-matrix-2/factories/vec2f64 ../../geometry/Extent ../../geometry/Geometry ../../geometry/Point ../../geometry/projection ../../geometry/SpatialReference ../../geometry/support/normalizeUtils ../../geometry/support/spatialReferenceUtils".split(" "),
function(k,D,aa,N,E,t,B,g,p,O,ba,P,v,Q,R,x){function F(a,b){return b.type?g.set(a,b.x,b.y):g.copy(a,b)}function y(a,b){return Math.max(a.width/Math.max(1,b[0]),a.height/Math.max(1,b[1]))*S(a.spatialReference)}async function z(a,b,c,d){if(!a||Array.isArray(a)&&!a.length)return null;aa.isCollection(a)&&(a=a.toArray());if(Array.isArray(a)&&a.length&&"object"===typeof a[0]){var e=a.every(n=>"attributes"in n);var f=a.some(n=>!n.geometry),l=a;if(e&&f&&b&&b.allLayerViews){e=new Map;for(var r of a)a=r.layer,
f=e.get(a)||[],l=r.attributes[a.objectIdField],null!=l&&f.push(l),e.set(a,f);const n=[];e.forEach((q,T)=>{const G=b.allLayerViews.find(A=>A.layer.id===T.id);if(G&&"queryFeatures"in G){const A=T.createQuery();A.objectIds=q;A.returnGeometry=!0;n.push(G.queryFeatures(A))}});r=await Promise.all(n);a=[];for(var h of r)if(h&&h.features&&h.features.length)for(var m of h.features)null!=m.geometry&&a.push(m.geometry);l=a}for(const n of l)d=await z(n,b,c,d);return d}if(Array.isArray(a)&&2===a.length&&"number"===
typeof a[0]&&"number"===typeof a[1])e=new P(a);else if(a instanceof ba)e=a;else if("geometry"in a)if(a.geometry)e=a.geometry;else if(a.layer){const n=a.layer;(h=b.allLayerViews.find(q=>q.layer.id===n.id))&&"queryFeatures"in h&&(m=n.createQuery(),m.objectIds=[a.attributes[n.objectIdField]],m.returnGeometry=!0,e=(await h.queryFeatures(m))?.features?.[0]?.geometry)}if(null==e)return null;switch(e.type){case "point":h=new O({xmin:e.x,ymin:e.y,xmax:e.x,ymax:e.y,spatialReference:e.spatialReference});break;
case "extent":case "multipoint":case "polygon":case "polyline":h=R.getDenormalizedExtent(e);break;default:h=e.extent}if(!h)return null;v.isLoaded()||v.canProjectWithoutEngine(h.spatialReference,c)||await v.load();c=v.project(h,c);return c?d=d?d.union(c):c:null}function ca(a){if(a&&(!Array.isArray(a)||"number"!==typeof a[0])&&("object"===typeof a||Array.isArray(a)&&"object"===typeof a[0])){if("layer"in a&&null!=a.layer?.minScale&&null!=a.layer.maxScale){var b=a.layer;return{min:b.minScale,max:b.maxScale}}if(Array.isArray(a)&&
a.length&&a.every(c=>"layer"in c)){let c=b=0;for(const d of a)a=d.layer,a?.minScale&&a.maxScale&&(b=a.minScale<b?a.minScale:b,c=a.maxScale>c?a.maxScale:c);return b&&c?{min:b,max:c}:null}}}function H(a,b){return x.equals(a.wkid?a:a.spatialReference||Q.WGS84,b)?a:v.project(a,b)}function u(a,b){const c=a.targetGeometry,d=b.targetGeometry;c.x=d.x;c.y=d.y;c.spatialReference=d.spatialReference;a.scale=b.scale;a.rotation=b.rotation;return a}function U(a,b,c){return c?g.set(a,.5*(b[0]-c.right+c.left),.5*
(b[1]-c.bottom+c.top)):g.scale(a,b,.5)}function w(a){return a.scale*V(a.targetGeometry?.spatialReference)}function V(a){return null!=a&&x.isValid(a)?1/(39.37*N.getMetersPerUnitForSR(a)*96):1}function S(a){return x.isValid(a)?39.37*N.getMetersPerUnitForSR(a)*96:1}function W(a){return(a=x.getInfo(a))?a.valid[1]-a.valid[0]:0}const da=180/Math.PI,ea=function(){const a=p.create();return function(b,c,d){const e=c.targetGeometry;F(a,e);c=.5*w(c);b.xmin=a[0]-c*d[0];b.ymin=a[1]-c*d[1];b.xmax=a[0]+c*d[0];b.ymax=
a[1]+c*d[1];b.spatialReference=e.spatialReference;return b}}(),I=function(){const a=p.create();return function(b,c,d){return g.sub(b,g.scale(b,c,.5),U(a,c,d))}}(),X=function(){const a=B.create(),b=p.create();return function(c,d,e,f){const l=w(d);d=E.toRadian(d.rotation)||0;g.set(b,l,l);t.fromScaling(a,b);t.rotate(a,a,d);t.translate(a,a,I(b,e,f));t.translate(a,a,[0,f.top-f.bottom]);return g.set(c,a[4],a[5])}}(),J=function(){const a=p.create(),b=p.create(),c=p.create();return function(d,e,f,l,r,h){g.negate(a,
e);g.scale(b,f,.5*h);g.set(c,1/l*h,-1/l*h);t.fromTranslation(d,b);r&&t.rotate(d,d,r);t.scale(d,d,c);t.translate(d,d,a);return d}}(),K=function(){const a=p.create();return function(b,c,d,e){const f=w(c),l=E.toRadian(c.rotation)||0;F(a,c.targetGeometry);return J(b,a,d,f,l,e)}}(),fa=function(){const a=p.create();return function(b,c,d,e){const f=w(c);F(a,c.targetGeometry);return J(b,a,d,f,0,e)}}(),ha=function(){const a=p.create(),b=p.create(),c=[0,0,0];return function(d,e,f){g.subtract(a,d,e);g.normalize(a,
a);g.subtract(b,d,f);g.normalize(b,b);g.cross(c,a,b);d=Math.acos(g.dot(a,b)/(g.length(a)*g.length(b)))*da;0>c[2]&&(d=-d);isNaN(d)&&(d=0);return d}}(),ia=function(){const a=p.create();return function(b,c,d,e){const f=b.targetGeometry;u(b,c);X(a,c,d,e);f.x+=a[0];f.y+=a[1];return b}}(),Y=function(){return function(a,b,c){u(a,b);b=a.targetGeometry;b.x=c.x;b.y=c.y;b.spatialReference=c.spatialReference;return a}}(),ja=function(){const a=p.create();return function(b,c,d,e,f){f||="center";g.sub(a,d,e);g.scale(a,
a,.5);d=a[0];e=a[1];switch(f){case "center":g.set(a,0,0);break;case "left":g.set(a,-d,0);break;case "top":g.set(a,0,e);break;case "right":g.set(a,d,0);break;case "bottom":g.set(a,0,-e);break;case "top-left":g.set(a,-d,e);break;case "bottom-left":g.set(a,-d,-e);break;case "top-right":g.set(a,d,e);break;case "bottom-right":g.set(a,d,-e)}C(b,c,a);return b}}(),ka=function(){const a=p.create();return function(b,c,d,e,f){u(b,c);isNaN(d)||0===d||(L(a,e,c,f),b.scale=c.scale*d,M(a,a,b,f),C(b,b,g.set(a,a[0]-
e[0],e[1]-a[1])));return b}}(),Z=function(){const a=p.create();return function(b,c,d,e,f,l){u(b,c);isNaN(d)||0===d||(L(a,f,c,l),b.scale=c.scale*d,b.rotation+=e,M(a,a,b,l),C(b,b,g.set(a,a[0]-f[0],f[1]-a[1])));return b}}(),la=function(){const a=p.create(),b=p.create();return function(c,d,e,f,l,r,h){I(b,r,h);g.add(a,l,b);return f?Z(c,d,e,f,a,r):ka(c,d,e,a,r)}}(),L=function(){const a=B.create();return function(b,c,d,e){var f=g.transformMat2d;K(a,d,e,1);d=t.invert(a,a);return f.call(g,b,c,d)}}(),M=function(){const a=
B.create();return function(b,c,d,e){return g.transformMat2d(b,c,K(a,d,e,1))}}(),C=function(){const a=p.create(),b=B.create();return function(c,d,e){u(c,d);const f=w(d),l=c.targetGeometry;t.fromRotation(b,E.toRadian(d.rotation)||0);t.scale(b,b,p.fromValues(f,f));g.transformMat2d(a,e,b);l.x+=a[0];l.y+=a[1];return c}}();k.addPadding=ia;k.angleBetween=ha;k.centerAt=Y;k.copy=u;k.create=async function(a,b){if(!a||!b)return new D({targetGeometry:new P,scale:0,rotation:0});let c=b.spatialReference;const {constraints:d,
padding:e,viewpoint:f,size:l}=b,r=[e?l[0]-e.left-e.right:l[0],e?l[1]-e.top-e.bottom:l[1]];let h=null;a instanceof D?h=a:a.viewpoint?h=a.viewpoint:a.target&&"esri.Viewpoint"===a.target.declaredClass&&(h=a.target);let m=null;if(h?.targetGeometry)m=h.targetGeometry;else if(a instanceof O)m=a;else if(a||a&&("center"in a||"extent"in a||"target"in a))m=await z(a.center,b,c)||await z(a.extent,b,c)||await z(a.target,b,c)||await z(a,b,c);!m&&f?.targetGeometry?m=f.targetGeometry:!m&&b.extent&&(m=b.extent);
if(!c){var n=b.spatialReference||b.extent||m;c=n.wkid?n:n.spatialReference||Q.WGS84}v.isLoaded()||x.equals(m.spatialReference,c)||v.canProjectWithoutEngine(m.spatialReference,c)||await v.load();n=H("center"in m?m.center:m,c);!1!==b.pickClosestTarget&&"point"===n.type&&"point"===f.targetGeometry?.type&&(n.x=R.getClosestDenormalizedXToReference(n.x,f.targetGeometry.x,n.spatialReference));var q=0;null!=h?.targetGeometry&&"point"===h.targetGeometry.type?q=h.scale:"scale"in a&&a.scale?q=a.scale:"zoom"in
a&&-1!==a.zoom&&d&&d.effectiveLODs?q=d.zoomToScale(a.zoom):Array.isArray(m)||"point"===m.type||"extent"===m.type&&0===m.width&&0===m.height?(q=H(b.extent,c),q=null!=q?y(q,r):b.extent?y(b.extent,r):f.scale):q=y(H(m.extent,c),r);if(b=ca(a.target??a))b.min&&b.min<q?q=b.min:b.max&&b.max>q&&(q=b.max);b=0;h?b=h.rotation:a.hasOwnProperty("rotation")?b=a.rotation:f&&(b=f.rotation);a=new D({targetGeometry:n,scale:q,rotation:b});d&&(a=d.fit(a),d.constrainByGeometry(a),d.rotationEnabled||(a.rotation=f.rotation));
return a};k.extentToScale=y;k.getAnchor=U;k.getExtent=ea;k.getMatrix=J;k.getPaddingMapTranslation=X;k.getPaddingScreenTranslation=I;k.getResolution=w;k.getResolutionToScaleFactor=S;k.getScaleToResolutionFactor=V;k.getTransform=K;k.getTransformNoRotation=fa;k.getWorldScreenWidth=function(a,b){return Math.round(W(a)/b)};k.getWorldWidth=W;k.padAndScaleAndRotateBy=la;k.resize=ja;k.rotateBy=function(a,b,c){u(a,b);a.rotation+=c;return a};k.rotateTo=function(a,b,c){u(a,b);a.rotation=c;return a};k.scaleAndRotateBy=
Z;k.scaleTo=function(a,b,c){u(a,b);a.scale=c;return a};k.setExtent=function(a,b,c,d,e){Y(a,b,c.center);a.scale=y(c,d);e?.constraints?.constrain(a);return a};k.toMap=L;k.toScreen=M;k.translateBy=C;Object.defineProperty(k,Symbol.toStringTag,{value:"Module"})});