// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/tsSupport/assignHelper ../../../../core/Logger ../../../../core/maybe ../../../../core/screenUtils ../../../../core/libs/gl-matrix-2/vec2 ../../../../core/libs/gl-matrix-2/vec3 ../../../../core/libs/gl-matrix-2/vec3f64 ../../support/geometryUtils ../../support/buffer/BufferView ../lib/ComponentUtils ../lib/geometryDataUtils ../lib/GLMaterial ../lib/Material ../lib/Util ./internal/bufferWriterUtils ./internal/DefaultBufferWriter ./internal/MaterialUtil ./renderers/MergedRenderer ../shaders/NativeLineTechnique".split(" "),
function(G,ca,H,da,N,z,x,O,d,h,b,P,Q,R,S,T,t,U,A,I,V,J){var W=N.getLogger("esri.views.3d.webgl-engine.materials.NativeLineMaterial");G=function(h){function a(c,a){a=h.call(this,a)||this;a.techniqueConfig=new J.NativeLineTechniqueConfiguration;a.params=I.copyParameters(c,X);return a}H(a,h);a.prototype.setParameterValues=function(c){var a=this.params,e;for(e in c)a[e]=c[e];this.parametersChanged()};a.prototype.getParameters=function(){return this.params};a.prototype.getTechniqueConfig=function(c){this.techniqueConfig.output=
c;this.techniqueConfig.slicePlaneEnabled=this.params.slicePlaneEnabled;this.techniqueConfig.vertexColors=this.params.vertexColors;this.techniqueConfig.transparent=1>this.params.color[3]||1>this.params.width;c=z.isSome(this.params.stipplePattern);this.techniqueConfig.stippleEnabled=c;this.techniqueConfig.stippleOffColorEnabled=c&&z.isSome(this.params.stippleOffColor);this.techniqueConfig.stippleIntegerRepeatsEnabled=c&&this.params.stippleIntegerRepeats;this.techniqueConfig.sceneHasOcludees=this.params.sceneHasOcludees;
return this.techniqueConfig};a.prototype.getPassParameters=function(){return this.params};a.prototype.intersect=function(c,a,e,b,d,m,k,g,f){f?I.intersectDrapedRenderLineGeometry(c,b,m,1,k):this.intersectLineGeometry(c,a,e,b,k)};a.prototype.intersectLineGeometry=function(c,a,e,r,h){if(r.options.selectionMode&&!Q.isAllHidden(a.componentVisibilities,c.componentOffsets))if(t.isTranslationMatrix(e)){a=c.data.getVertexAttr().position.data;var m=r.camera,k=Y;O.vec2.copy(k,r.point);d.vec3.set(y[0],k[0]-2,
k[1]+2,0);d.vec3.set(y[1],k[0]+2,k[1]+2,0);d.vec3.set(y[2],k[0]+2,k[1]-2,0);d.vec3.set(y[3],k[0]-2,k[1]-2,0);for(var g=0;4>g;g++)m.unprojectPoint(y[g],q[g]);b.plane.fromPoints(m.eye,q[0],q[1],C);b.plane.fromPoints(m.eye,q[1],q[2],D);b.plane.fromPoints(m.eye,q[2],q[3],E);b.plane.fromPoints(m.eye,q[3],q[0],F);c=Number.MAX_VALUE;for(g=0;g<a.length-5;g+=3)if(l[0]=a[g]+e[12],l[1]=a[g+1]+e[13],l[2]=a[g+2]+e[14],n[0]=a[g+3]+e[12],n[1]=a[g+4]+e[13],n[2]=a[g+5]+e[14],!(0>b.plane.signedDistance(C,l)&&0>b.plane.signedDistance(C,
n)||0>b.plane.signedDistance(D,l)&&0>b.plane.signedDistance(D,n)||0>b.plane.signedDistance(E,l)&&0>b.plane.signedDistance(E,n)||0>b.plane.signedDistance(F,l)&&0>b.plane.signedDistance(F,n))){m.projectPoint(l,u);m.projectPoint(n,v);if(0>u[2]&&0<v[2]){d.vec3.subtract(p,l,n);var f=m.frustum,B=-b.plane.signedDistance(f.planes[4],l),f=B/d.vec3.dot(p,f.planes[4]);d.vec3.scale(p,p,f);d.vec3.add(l,l,p);m.projectPoint(l,u)}else if(0<u[2]&&0>v[2])d.vec3.subtract(p,n,l),f=m.frustum,B=-b.plane.signedDistance(f.planes[4],
n),f=B/d.vec3.dot(p,f.planes[4]),d.vec3.scale(p,p,f),d.vec3.add(n,n,p),m.projectPoint(n,v);else if(0>u[2]&&0>v[2])continue;u[2]=0;v[2]=0;f=b.lineSegment.distance2(b.lineSegment.fromPoints(u,v,K),k);f<c&&(c=f,d.vec3.copy(L,l),d.vec3.copy(M,n))}e=r.rayBeginPoint;r=r.rayEndPoint;4>c&&(c=Number.MAX_VALUE,b.lineSegment.closestLineSegmentPoint(b.lineSegment.fromPoints(L,M,K),b.lineSegment.fromPoints(e,r,Z),w)&&(d.vec3.subtract(w,w,e),c=d.vec3.length(w),d.vec3.scale(w,w,1/c),c/=d.vec3.distance(e,r)),h(c,
w))}else W.error("intersection assumes a translation-only matrix")};a.prototype.computeAttachmentOrigin=function(c,a){c=c.data;return(c="getVertexAttr"in c?c.getVertexAttr():"vertexAttr"in c?c.vertexAttr:null)?R.computeAttachmentOriginLines(c[t.VertexAttrConstants.POSITION],null,a):null};a.prototype.createBufferWriter=function(){var c=this.params.vertexColors?A.PositionColorLayout:A.PositionLayout;return z.isNone(this.params.stipplePattern)?new A.DefaultBufferWriter(c):new aa(c.clone().vec3f(t.VertexAttrConstants.AUXPOS1))};
a.prototype.createRenderer=function(c,a){return new V(c,a,this)};a.prototype.getGLMaterial=function(a){return 0===a.output||4===a.output?new ba(a):void 0};return a}(T.Material);var ba=function(b){function a(a){a=b.call(this,a)||this;a.updateParameters();return a}H(a,b);a.prototype.updateParameters=function(){this.technique=this.techniqueRep.acquireAndReleaseExisting(J.NativeLineTechnique,this.material.getTechniqueConfig(this.output),this.technique)};a.prototype.beginSlot=function(a){return 3===a};
a.prototype._updateOccludeeState=function(a){a.hasOccludees!==this.material.getParameters().sceneHasOcludees&&(this.material.setParameterValues({sceneHasOcludees:a.hasOccludees}),this.updateParameters())};a.prototype.ensureParameters=function(a){0===this.output&&this._updateOccludeeState(a)};a.prototype.bind=function(a,b){a.bindProgram(this.technique.program);this.technique.bindPass(a,this.material.getPassParameters(),b)};a.prototype.getPipelineState=function(a,b){return b?this.technique.opaqueOccludeeState:
this.technique.pipeline};return a}(S.GLMaterial),aa=function(){function b(a){this.vertexBufferLayout=a}b.prototype.allocate=function(a){return this.vertexBufferLayout.createBuffer(a)};b.prototype.elementCount=function(a){return a.indices[t.VertexAttrConstants.POSITION].length};b.prototype.write=function(a,c,b,e){U.writeDefaultAttributes(c,this.vertexBufferLayout,a.transformation,a.invTranspTransformation,b,e);this.writeAuxpos1(a,c,b,e)};b.prototype.writeAuxpos1=function(a,c,b,e){var d=b.getField(t.VertexAttrConstants.AUXPOS1,
P.BufferViewVec3f);b=c.indices[t.VertexAttrConstants.POSITION];c=c.vertexAttr[t.VertexAttrConstants.POSITION].data;a=a.transformation;var h=d.typedBufferStride,d=d.typedBuffer;e*=h;for(var m=0;m<b.length;m+=2)for(var k=3*b[m],g=c[k],f=c[k+1],l=c[k+2],k=a[0]*g+a[4]*f+a[8]*l+a[12],n=a[1]*g+a[5]*f+a[9]*l+a[13],g=a[2]*g+a[6]*f+a[10]*l+a[14],f=0;2>f;++f)d[e]=k,d[e+1]=n,d[e+2]=g,e+=h};return b}(),X={color:[1,1,1,1],vertexColors:!1,slicePlaneEnabled:!1,width:1,stipplePattern:null,stippleIntegerRepeats:!1,
stippleOffColor:null,sceneHasOcludees:!1},l=h.vec3f64.create(),n=h.vec3f64.create(),p=h.vec3f64.create(),w=h.vec3f64.create(),u=x.createRenderScreenPointArray3(),v=x.createRenderScreenPointArray3(),L=h.vec3f64.create(),M=h.vec3f64.create(),K=b.lineSegment.create(),Z=b.lineSegment.create(),Y=h.vec3f64.create(),y=[x.createRenderScreenPointArray3(),x.createRenderScreenPointArray3(),x.createRenderScreenPointArray3(),x.createRenderScreenPointArray3()],q=[h.vec3f64.create(),h.vec3f64.create(),h.vec3f64.create(),
h.vec3f64.create()],C=b.plane.create(),D=b.plane.create(),E=b.plane.create(),F=b.plane.create();return G});