// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.8/esri/copyright.txt for details.
//>>built
define("require exports ../lib/glMatrix ./TerrainConst ../webgl-engine/lib/DefaultVertexAttributeLocations ../webgl-engine/lib/DefaultVertexBufferLayouts ../webgl-engine/lib/glUtil3D ../../vectorTiles/tileRendererHelper3D ../../vectorTiles/VectorTileDisplayObject ../../webgl/BufferObject ../../webgl/FramebufferObject ../../webgl/Texture ../../webgl/Util ../../webgl/VertexArrayObject".split(" "),function(D,E,m,q,w,x,p,y,z,A,B,r,t,C){var u=Array(20),v=[0,0];return function(){function l(c,a,d,b,g){this._backgroundTex=
null;this.tileSize=256;this._context=c;this.tileSize=a;this._resourceCounter=b;this._setNeedsRender=g;c.capabilities.textureFilterAnisotropic&&(this._maxAnisotropy=Math.min(8,c.parameters.maxMaxAnisotropy));a=new Float32Array(20);a[0]=-1;a[1]=-1;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=-1;a[7]=0;a[8]=1;a[9]=0;a[10]=-1;a[11]=1;a[12]=0;a[13]=0;a[14]=1;a[15]=1;a[16]=1;a[17]=0;a[18]=1;a[19]=1;this._vaoQuad=new C(c,w.Default3D,{geometry:x.Pos3Tex},{geometry:A.createVertex(c,35044,a)});this._blendLayersProgram=
d.get("blendLayers")}l.prototype.dispose=function(){this._fbo&&(this._fbo.dispose(),this._fbo=null);this._vaoQuad&&(this._vaoQuad.dispose(),this._vaoQuad=null);this._backgroundTex&&(this._backgroundTex.dispose(),this._backgroundTex=null);this._blendLayersProgram&&(this._blendLayersProgram.dispose(),this._blendLayersProgram=null);this._context&&(this._context=null)};l.prototype.updateTileTexture=function(c){for(var a=q.LayerClass.MAP,d=c.layerInfo[a],b=0;b<d.length;b++)d[b].pendingUpdates&=~q.TileUpdateTypes.UPDATE_TEXTURE;
if(c.renderData){var g,b=c.renderData,f,e=0,k=!0;for(f=0;f<d.length;f++){g=d[f];var h=c.parentSurface.layerViewByIndex(f,a);u[f]=h.fullOpacity;if(g.data||g.upsampleFromTile)if(e++,!h.isTransparent){k=!1;break}}f===d.length&&f--;0===e&&this._backgroundTex?(b.textureReference=this._backgroundTex,m.vec4d.set4(0,0,1,1,b.texOffsetAndScale)):1!==e||k?(this._composeMapLayers(c,d,f,k,u),b.textureReference=null,m.vec4d.set4(0,0,1,1,b.texOffsetAndScale)):(g=d[f],g.data?(a=g,m.vec4d.set4(0,0,1,1,b.texOffsetAndScale)):
(c=g.upsampleFromTile,a=c.tile.layerInfo[a][f],m.vec4d.set4(c.offset[0],c.offset[1],c.scale,c.scale,b.texOffsetAndScale)),a&&(a.data instanceof HTMLImageElement&&(a.data=this._buildTexture(a.data)),b.textureReference=a.data));this._setNeedsRender()}};l.prototype.setBackground=function(c){this._backgroundTex=c instanceof HTMLImageElement?this._buildTexture(c):p.createColorTexture(this._context,c)};l.prototype._buildTexture=function(c){var a={target:3553,pixelFormat:6408,dataType:5121,wrapMode:33071,
samplingMode:9729,maxAnisotropy:this._maxAnisotropy,flipped:!0,hasMipmap:!0},d=this._context,b;if(c instanceof HTMLImageElement)try{b=new r(d,a,c)}catch(g){b=p.createEmptyTexture(d),console.warn("TileRenderer: failed to execute 'texImage2D', cross-origin image may not be loaded.")}else a.width=a.height=this.tileSize,b=new r(d,a);d.bindTexture(b);b.generateMipmap();return b};l.prototype._drawVectorData=function(c,a,d,b,g,f,e,k,h){void 0===h&&(h=1);y(this._context,d,c,a.renderer,a.schemeHelper,d[0],
b,g,0,f,e,k,h)};l.prototype._drawRasterData=function(c,a,d,b){void 0===b&&(b=1);var g=this._context,f=this._blendLayersProgram,e=this._vaoQuad;g.bindProgram(f);g.bindVAO(e);t.assertCompatibleVertexAttributeLocations(e,f);g.bindTexture(c,0);f.setUniform1i("tex",0);f.setUniform1f("scale",a);f.setUniform2f("offset",d[0],d[1]);f.setUniform1f("opacity",b);g.drawArrays(5,0,t.vertexCount(e,"geometry"))};l.prototype._composeMapLayers=function(c,a,d,b,g){var f=q.LayerClass.MAP,e=this._context;c.renderData.texture||
(c.renderData.texture=this._buildTexture());var k=c.renderData.texture,h=this._fbo;h&&h.width===k.descriptor.width&&h.height===k.descriptor.height||(this._fbo=h=B.create(e,{colorTarget:0,depthStencilTarget:1,width:k.descriptor.width,height:k.descriptor.height}));var l=e.gl;e.bindFramebuffer(h);e.setViewport(0,0,this.tileSize,this.tileSize);e.setClearColor(0,0,0,0);e.setClearDepth(1);e.clear(l.COLOR_BUFFER_BIT|l.DEPTH_BUFFER_BIT);e.setDepthTestEnabled(!1);e.setBlendFunctionSeparate(1,771,1,771);e.setBlendEquation(32774);
e.setBlendingEnabled(!0);var m,n,p;for(b&&this._backgroundTex&&this._drawRasterData(this._backgroundTex,1,v);0<=d;d--)if(b=null,h=a[d],h.data?(b=h,m=v,n=1):h.upsampleFromTile&&(n=h.upsampleFromTile,b=n.tile.layerInfo[f][d],p=n.tile.lij[0],m=n.offset,n=n.scale),b){if(b.data instanceof HTMLImageElement||b.data instanceof HTMLCanvasElement)b.data=this._buildTexture(b.data);b.data instanceof z?(h=c.parentSurface.layerViewByIndex(d,f),this._drawVectorData(b.data,h,c.lij,k.descriptor.width,k.descriptor.height,
n,m,p,g[d])):this._drawRasterData(b.data,n,m,g[d])}e.bindTexture(k);l.copyTexImage2D(e.gl.TEXTURE_2D,0,k.descriptor.pixelFormat,0,0,k.descriptor.width,k.descriptor.height,0);k.generateMipmap();e.bindFramebuffer(null);e.setBlendFunctionSeparate(770,771,1,771);e.setBlendingEnabled(!1);this._resourceCounter.incrementNumTileTexturesComposited()};return l}()});