// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/decorateHelper ../../../../core/tsSupport/declareExtendsHelper ../../../../Color ../../../../core/colorUtils ../../../../core/compilerUtils ../../../../core/handleUtils ../../../../core/JSONSupport ../../../../core/watchUtils ../../../../core/accessorSupport/decorators ../../../../core/libs/gl-matrix-2/vec4f64 ../../webgl-engine/materials/lineStippleUtils".split(" "),function(y,d,c,k,g,z,A,u,l,v,b,I,J){function r(b,a){b=b.clone();b.a*=a;return b}
function h(b,a,e,c,d){return v.init(b,a,function(a){e[c]=d?d(a):a})}function n(b){return b}function m(b){return I.vec4f64.fromArray(g.toUnitRGBA(b))}function K(b){if(!b)return null;b=b.split(/[^0-9]/).map(function(a){return parseFloat(a)});return J.createStipplePattern(b)}function w(b,a){a=a&&"foreground"===a.layer;switch(b){case "always":return a?32:16;case "transparent":return a?8:4;case "always-transparent":return 2;default:A.neverReached(b)}return 1}Object.defineProperty(d,"__esModule",{value:!0});
d.colors={main:new g([255,127,0]),selected:new g([255,255,255]),outline:new g([0,0,0,.5]),selectedOutline:new g([255,255,255])};var B=function(f){function a(e){e=f.call(this,e)||this;e.color=d.colors.main;e.height=90;e.coneHeight=40;e.coneWidth=23;e.width=3;e.occludedMode="always";e.enabled="always";return e}k(a,f);Object.defineProperty(a.prototype,"occludedFlag",{get:function(){return w(this.occludedMode)},enumerable:!0,configurable:!0});c([b.property({type:g,nonNullable:!0,json:{write:!0}})],a.prototype,
"color",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:1,max:200,step:1},json:{write:!0}})],a.prototype,"height",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:1,max:60,step:1},json:{write:!0}})],a.prototype,"coneHeight",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:1,max:60,step:1},json:{write:!0}})],a.prototype,"coneWidth",void 0);c([b.property({type:Number,range:{min:0,max:16,step:.5},json:{write:!0}})],a.prototype,"width",void 0);c([b.property({type:["always",
"transparent","always-transparent"],json:{write:!0}})],a.prototype,"occludedMode",void 0);c([b.property({type:["always","not-grab-z"],json:{write:!0},nonNullable:!0})],a.prototype,"enabled",void 0);return a=c([b.subclass("esri.views.3d.interactive.editingTools.settings.ZManipulatorStyle")],a)}(b.declared(l.JSONSupport)),p=function(f){function a(e){e=f.call(this,e)||this;e.size=11;e.outlineSize=1;e.collisionPadding=9;e.color=d.colors.main;e.outlineColor=d.colors.outline;e.occludedMode="always";e.hoverOutlineColor=
d.colors.selectedOutline;return e}k(a,f);Object.defineProperty(a.prototype,"renderOccludedFlag",{get:function(){return w(this.occludedMode)},enumerable:!0,configurable:!0});a.prototype.bindOccludedMode=function(e){var a=this;return v.init(this,"occludedMode",function(){return e.renderOccluded=a.renderOccludedFlag})};a.prototype.bindColorMaterial=function(e,a){return u.handlesGroup([v.init(this,e,function(b){a.setParameterValues({color:m(b),transparent:"color"===e?1>b.a:!0})}),this.bindOccludedMode(a)])};
c([b.property({type:Number,nonNullable:!0,range:{min:1,max:32,step:.5},json:{write:!0}})],a.prototype,"size",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:0,max:32,step:.5},json:{write:!0}})],a.prototype,"outlineSize",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:0,max:32,step:.5},json:{write:!0}})],a.prototype,"collisionPadding",void 0);c([b.property({type:g,nonNullable:!0,json:{write:!0}})],a.prototype,"color",void 0);c([b.property({type:g,nonNullable:!0,json:{write:!0}})],
a.prototype,"outlineColor",void 0);c([b.property({type:["always","transparent"],json:{write:!0}})],a.prototype,"occludedMode",void 0);c([b.property({type:g,nonNullable:!0,json:{write:!0}})],a.prototype,"hoverOutlineColor",void 0);return a=c([b.subclass("esri.views.3d.interactive.editingTools.settings.VertexManipulatorStyle")],a)}(b.declared(l.JSONSupport)),C=function(f){function a(a){a=f.call(this,a)||this;a.vertex=new p({color:d.colors.main,outlineColor:d.colors.outline});var e=r(d.colors.main,2/
3).clone(),b=z.toHSV(e);b.s*=.5;b=z.toRGB(b);e.r=b.r;e.g=b.g;e.b=b.b;a.edge=new p({color:e,outlineColor:r(d.colors.outline,.5),size:8,collisionPadding:8});a.selected=new p({color:d.colors.selected,outlineColor:d.colors.outline});return a}k(a,f);c([b.property({type:p,nonNullable:!0,constructOnly:!0,json:{write:!0}})],a.prototype,"vertex",void 0);c([b.property({type:p,nonNullable:!0,constructOnly:!0,json:{write:!0}})],a.prototype,"edge",void 0);c([b.property({type:p,nonNullable:!0,constructOnly:!0,
json:{write:!0}})],a.prototype,"selected",void 0);return a=c([b.subclass("esri.views.3d.interactive.editingTools.settings.ReshapeManipulators")],a)}(b.declared(l.JSONSupport)),x=function(f){function a(a){a=f.call(this,a)||this;a.color=d.colors.selected;a.width=1.5;a.stipplePattern="5-5";a.stippleOffColor=d.colors.outline;a.falloff=0;a.innerWidth=1.5;a.innerColor=d.colors.selected;a.occludedMode="transparent";return a}k(a,f);a.prototype.bindStyle=function(a){return u.handlesGroup([h(this,"color",a,
"color",m),h(this,"width",a,"width",n),h(this,"stipplePattern",a,"stipplePattern",K),h(this,"stippleOffColor",a,"stippleOffColor",m),h(this,"falloff",a,"falloff",n),h(this,"innerWidth",a,"innerWidth",n),h(this,"innerColor",a,"innerColor",m),h(this,"occludedMode",a,"occludedMode",function(a){return w(a,{layer:"foreground"})})])};c([b.property({type:g,nonNullable:!0,json:{write:!0}})],a.prototype,"color",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:0,max:32,step:.5},json:{write:!0}})],
a.prototype,"width",void 0);c([b.property({type:String,json:{write:!0,default:null}})],a.prototype,"stipplePattern",void 0);c([b.property({type:g,nonNullable:!0,json:{write:!0}})],a.prototype,"stippleOffColor",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:0,max:16,step:.5},json:{write:!0}})],a.prototype,"falloff",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:0,max:16,step:.5},json:{write:!0}})],a.prototype,"innerWidth",void 0);c([b.property({type:g,nonNullable:!0,json:{write:!0}})],
a.prototype,"innerColor",void 0);c([b.property({type:["always","transparent"],json:{write:!0}})],a.prototype,"occludedMode",void 0);return a=c([b.subclass("esri.views.3d.interactive.editingTools.settings.LineStyle")],a)}(b.declared(l.JSONSupport)),D=function(f){function a(a){a=f.call(this,a)||this;a.color=d.colors.selected;a.size=4;a.outlineSize=1;a.outlineColor=d.colors.outline;a.shape="square";return a}k(a,f);a.prototype.bindStyle=function(a){return u.handlesGroup([h(this,"color",a,"color",m),h(this,
"size",a,"size",n),h(this,"outlineSize",a,"outlineSize",n),h(this,"outlineColor",a,"outlineColor",m),h(this,"shape",a,"primitive",n)])};c([b.property({type:g,nonNullable:!0,json:{write:!0}})],a.prototype,"color",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:0,max:32,step:.5},json:{write:!0}})],a.prototype,"size",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:0,max:32,step:.5},json:{write:!0}})],a.prototype,"outlineSize",void 0);c([b.property({type:g,nonNullable:!0,json:{write:!0}})],
a.prototype,"outlineColor",void 0);c([b.property({type:"circle square kite cross x triangle".split(" "),nonNullable:!0,json:{write:!0}})],a.prototype,"shape",void 0);return a=c([b.subclass("esri.views.3d.interactive.editingTools.settings.PointStyle")],a)}(b.declared(l.JSONSupport)),q=function(f){function a(a){a=f.call(this,a)||this;a.innerColor=d.colors.selected;a.innerWidth=1;a.glowColor=d.colors.main;a.glowWidth=8;a.glowFalloff=8;a.globalAlpha=.3;a.globalAlphaContrastBoost=2;a.radius=3;a.heightFillColor=
d.colors.main;return a}k(a,f);a.prototype.bindStyle=function(a){var b=this,e=1,c=function(){var c={glowColor:g.toUnitRGB(b.glowColor),glowFalloff:b.glowFalloff,glowWidth:b.glowWidth,innerColor:g.toUnitRGB(b.innerColor),innerWidth:b.innerWidth,globalAlpha:b.globalAlpha*e,globalAlphaContrastBoost:b.globalAlphaContrastBoost,intersectsLineRadius:b.radius,heightPlaneFillColor:g.toUnitRGBA(b.heightFillColor)};"style"in a?a.style=c:a.laserlineStyle=c};c();var d=this.watch(this.keys(),c);return{updateGlobalAlpha:function(a){a!==
e&&(e=a,c())},remove:function(){d.remove()}}};c([b.property({type:g,nonNullable:!0,json:{write:!0}})],a.prototype,"innerColor",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:0,max:16,step:.5},json:{write:!0}})],a.prototype,"innerWidth",void 0);c([b.property({type:g,nonNullable:!0,json:{write:!0}})],a.prototype,"glowColor",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:0,max:16,step:.5},json:{write:!0}})],a.prototype,"glowWidth",void 0);c([b.property({type:Number,nonNullable:!0,
range:{min:0,max:16,step:.5},json:{write:!0}})],a.prototype,"glowFalloff",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:0,max:1,step:.01},json:{write:!0}})],a.prototype,"globalAlpha",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:0,max:10,step:.25},json:{write:!0}})],a.prototype,"globalAlphaContrastBoost",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:0,max:16,step:.05},json:{write:!0}})],a.prototype,"radius",void 0);c([b.property({type:g,nonNullable:!0,
json:{write:!0}})],a.prototype,"heightFillColor",void 0);return a=c([b.subclass("esri.views.3d.interactive.editingTools.settings.LaserlineStyle")],a)}(b.declared(l.JSONSupport)),E=function(f){function a(a){a=f.call(this,a)||this;a.outline=new x({color:d.colors.selected,occludedMode:"transparent",stippleOffColor:d.colors.outline,stipplePattern:"5-5",width:1.5});a.outlineEnabled=!0;a.shadowStyle=new q({globalAlpha:.3,glowColor:d.colors.main,glowFalloff:8,glowWidth:8,innerColor:d.colors.selected,innerWidth:1});
a.shadowEnabled="always";return a}k(a,f);c([b.property({type:x,constructOnly:!0,nonNullable:!0,json:{write:!0}})],a.prototype,"outline",void 0);c([b.property({type:Boolean,nonNullable:!0,json:{write:!0}})],a.prototype,"outlineEnabled",void 0);c([b.property({type:q,json:{write:!0}})],a.prototype,"shadowStyle",void 0);c([b.property({type:["never","always","grab-xy"],nonNullable:!0,json:{write:!0}})],a.prototype,"shadowEnabled",void 0);return a=c([b.subclass("esri.views.3d.interactive.editingTools.settings.LineGraphics")],
a)}(b.declared(l.JSONSupport)),F=function(f){function a(a){a=f.call(this,a)||this;a.outline=new D({color:d.colors.selected,outlineColor:d.colors.outline,outlineSize:1,shape:"circle",size:4});a.outlineEnabled=!0;a.shadowStyle=new q({globalAlpha:.3,glowColor:d.colors.main,glowFalloff:1.5,glowWidth:6,innerColor:d.colors.selected,innerWidth:1,radius:2});a.shadowEnabled="always";return a}k(a,f);c([b.property({type:D,constructOnly:!0,nonNullable:!0,json:{write:!0}})],a.prototype,"outline",void 0);c([b.property({type:Boolean,
nonNullable:!0,json:{write:!0}})],a.prototype,"outlineEnabled",void 0);c([b.property({type:q,json:{write:!0}})],a.prototype,"shadowStyle",void 0);c([b.property({type:["never","always","grab-xy"],nonNullable:!0,json:{write:!0}})],a.prototype,"shadowEnabled",void 0);return a=c([b.subclass("esri.views.3d.interactive.editingTools.settings.PointGraphics")],a)}(b.declared(l.JSONSupport)),t=function(d){function a(a){a=d.call(this,a)||this;a.enabled="always";return a}k(a,d);c([b.property({type:["never","always",
"grab-z"],nonNullable:!0,json:{write:!0}})],a.prototype,"enabled",void 0);return a=c([b.subclass("esri.views.3d.interactive.editingTools.settings.HeightPlane")],a)}(b.declared(q)),G=function(d){function a(a){a=d.call(this,a)||this;a.enabled="always";a.infinite="ground";return a}k(a,d);Object.defineProperty(a.prototype,"infiniteType",{get:function(){switch(this.infinite){case "single":return 1;case "double":return 2;case "ground":return 3;default:return A.neverReached(this.infinite),1}},enumerable:!0,
configurable:!0});c([b.property({type:["never","always","grab-z","grab-xy","grab"],nonNullable:!0,json:{write:!0}})],a.prototype,"enabled",void 0);c([b.property({type:["single","double","ground"],nonNullable:!0,json:{write:!0}})],a.prototype,"infinite",void 0);return a=c([b.subclass("esri.views.3d.interactive.editingTools.settings.ZVerticalLine")],a)}(b.declared(x)),H=function(f){function a(a){a=f.call(this,a)||this;a.lineGraphics=new E;a.pointGraphics=new F;a.heightPlane=new t({globalAlpha:.3,glowColor:d.colors.main,
glowFalloff:8,glowWidth:8,innerColor:d.colors.selected,innerWidth:1});a.heightBox=new t({globalAlpha:.3,glowColor:d.colors.main,glowFalloff:8,glowWidth:8,innerColor:d.colors.selected,innerWidth:0,heightFillColor:d.colors.main});a.zVerticalLine=new G({color:r(d.colors.main,.5),falloff:2,innerColor:r(d.colors.selected,0),occludedMode:"transparent",stipplePattern:null,width:5,infinite:"ground"});a.laserlineAlphaMultiplier=1.5;a.heightPlaneAngleCutoff=20;return a}k(a,f);c([b.property({type:E,constructOnly:!0,
nonNullable:!0,json:{write:!0}})],a.prototype,"lineGraphics",void 0);c([b.property({type:F,constructOnly:!0,nonNullable:!0,json:{write:!0}})],a.prototype,"pointGraphics",void 0);c([b.property({type:t,constructOnly:!0,nonNullable:!0,json:{write:!0}})],a.prototype,"heightPlane",void 0);c([b.property({type:t,constructOnly:!0,nonNullable:!0,json:{write:!0}})],a.prototype,"heightBox",void 0);c([b.property({type:G,constructOnly:!0,nonNullable:!0,json:{write:!0}})],a.prototype,"zVerticalLine",void 0);c([b.property({type:Number,
nonNullable:!0,range:{min:1,max:2,step:.1},json:{write:!0}})],a.prototype,"laserlineAlphaMultiplier",void 0);c([b.property({type:Number,nonNullable:!0,range:{min:0,max:45,step:1},json:{write:!0}})],a.prototype,"heightPlaneAngleCutoff",void 0);return a=c([b.subclass("esri.views.3d.interactive.editingTools.settings.VisualElements")],a)}(b.declared(l.JSONSupport));y=function(d){function a(a){a=d.call(this,a)||this;a.visualElements=new H;a.reshapeManipulators=new C;a.zManipulator=new B;return a}k(a,d);
a.prototype.colorToVec4=function(a){return m(a)};c([b.property({type:H,constructOnly:!0,nonNullable:!0,json:{write:!0}})],a.prototype,"visualElements",void 0);c([b.property({type:C,constructOnly:!0,nonNullable:!0,json:{write:!0}})],a.prototype,"reshapeManipulators",void 0);c([b.property({type:B,constructOnly:!0,nonNullable:!0,json:{write:!0}})],a.prototype,"zManipulator",void 0);return a=c([b.subclass("esri.views.3d.interactive.editingTools.settings.Settings")],a)}(b.declared(l.JSONSupport));d.settings=
new y});