// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("../../chunks/tslib.es6 ../../request ../../core/Collection ../../core/Error ../../core/lang ../../core/Loadable ../../core/accessorSupport/decorators/property ../../core/has ../../core/Logger ../../core/accessorSupport/decorators/subclass ../../intl/date ../../intl/locale ../../portal/Portal ../../rest/geoprocessor/execute ../../rest/geoprocessor/GPOptions ../../config ../../geometry/Polygon ../../geometry/Polyline ../../geometry/support/normalizeUtilsCommon ../../geometry/support/spatialReferenceUtils ../../geometry/SpatialReference ../../geometry/support/Ellipsoid ../../geometry ../../geometry/Extent ../../geometry/Geometry ../../geometry/Multipoint ../../geometry/Point ../../kernel ../../core/urlUtils ../../layers/support/Field ../../layers/support/MapImage ../../rest/support/DataFile ../../rest/support/FeatureSet ../../rest/support/LinearUnit ../../rest/support/ParameterValue ../../rest/support/RasterData ../../rest/support/JobInfo ../../rest/print ../../rest/support/fileFormat ../../rest/support/layoutTemplate ../../rest/support/PrintParameters ../../rest/support/PrintTemplate ./CustomTemplate".split(" "),
function(h,B,f,r,C,D,k,O,P,E,u,F,v,G,Q,R,S,T,U,V,W,X,Y,Z,aa,ba,ca,da,ea,fa,ha,ia,ja,ka,la,ma,na,H,w,t,I,J,x){function K(a){a.layoutOptions??(a.layoutOptions={});var b;(b=a.layoutOptions).customTextElements??(b.customTextElements=[]);a.layoutOptions.customTextElements.find(e=>"date"in e)||({customTextElements:a}=a.layoutOptions,b=u.formatDate(Date.now(),u.convertDateFormatToIntlOptions("short-date")),"ar"===F.getLanguage()&&(b="\u200f"+b),a.push({date:b}))}const y=f.ofType(x);f=class extends D{constructor(a){super(a);
this._serviceTemplateCustomTextElements=null;this.allowedLayouts=this.allowedFormats="all";this.defaultTemplates=new y;this.extraParameters=null;this.includeDefaultTemplates=!0;this.error=null;this.portal=v.getDefault();this.printServiceUrl=null;this.printTimeout=12E4;this.templatesInfo=null;this.updateDelay=1E3;this.templateCustomTextElements=this.view=null;this.print=this.print.bind(this)}destroy(){this.view=null}get effectivePrintServiceUrl(){return this.printServiceUrl??null}get effectiveTemplateCustomTextElements(){if(!this._serviceTemplateCustomTextElements)return{};
const a=C.clone(this._serviceTemplateCustomTextElements);this.templateCustomTextElements&&Object.keys(this.templateCustomTextElements).forEach(b=>{const e=a[b];if(e){const g=this.templateCustomTextElements?.[b];e.forEach(d=>{const [c]=Object.entries(d)[0];g?.forEach(n=>{const [l,p]=Object.entries(n)[0];c===l&&(d[c]=p)})})}});return Object.freeze(a)}get state(){return"loading"===this.loadStatus?"initializing":this.error||"failed"===this.loadStatus?"error":this.view?.ready&&"loaded"===this.loadStatus?
"ready":"disabled"}async load(a){this.addResolvingPromise(this._loadResources(a).catch(b=>this.error=b));return this}async print(a){const {view:b,extraParameters:e,updateDelay:g}=this;if(!b)throw new r("print:view-required","view is not set");K(a);a=new I({view:b,template:a,extraParameters:e,updateDelay:g});try{return await H.execute(this.effectivePrintServiceUrl,a,{timeout:this.printTimeout})}catch(d){throw new r("print:export-error","An error occurred while exporting the web map.",{error:d});}}toPrintTemplate({attributionEnabled:a,
author:b,copyright:e,customTextElements:g,dpi:d,forceFeatureAttributes:c,format:n,height:l,includeTables:p,layout:m,legendEnabled:q,northArrowEnabled:z,scale:L,scaleEnabled:M,title:N,width:A}){a=new J({attributionVisible:a,forceFeatureAttributes:c,format:n,includeTables:p,layout:m,layoutOptions:{authorText:b||"",copyrightText:e||"",customTextElements:g,titleText:N||""},outScale:L??0,scalePreserved:M});A&&(a.exportOptions.width=A);l&&(a.exportOptions.height=l);d&&(a.exportOptions.dpi=d);!q&&a.layoutOptions&&
(a.layoutOptions.legendLayers=[]);(d=this.templateToNorthArrowInfo[m])&&d.visible!==z&&a.layoutOptions&&(a.layoutOptions.elementOverrides={[d.name]:{visible:z}});return a}async _loadResources(a){let b=[];var {printServiceUrl:e}=this;if(!e){if(this.destroyed)return;({portal:e}=this);try{await e.load(a)}catch(g){throw new r("print:could-not-load-portal","Cannot load print resource information from portal",{url:this.effectivePrintServiceUrl});}if(e=e.helperServices?.printTask)this._set("effectivePrintServiceUrl",
e.url),b=(e?.templates??[]).map(g=>x.fromJSON(g))}0<b.length&&this.defaultTemplates.addMany(b);if(-1===(this.effectivePrintServiceUrl?.toLowerCase().split("/")?.indexOf("gpserver")??-1))throw new r("print:invalid-print-service-url","Can't fetch print templates information from provided URL",{url:this.effectivePrintServiceUrl});this._processLayoutTemplateInfos(await this._getLayoutTemplatesInfo(a));await this._loadServiceDescription(a)}async _loadServiceDescription(a){a=await this._getPrintTemplatesFromService(a);
this._set("templatesInfo",a)}async _getLayoutTemplatesInfo(a){let b=[];const e=async g=>{g=this.effectivePrintServiceUrl.replace(/(\/GPServer\/).+/i,`$1${encodeURI(g)}`);return(await G.execute(g,null,null,a)).results[0].value};try{b=await e("Get Layout Templates Info Task")}catch(g){}if(!b||1>b.length)try{b=await e("Get Layout Templates Info")}catch(g){}return b}_processLayoutTemplateInfos(a){const b={},e={};a.forEach(({layoutTemplate:g,layoutOptions:{customTextElements:d,mapSurroundInfos:c}})=>{g=
t.fromJSON(g);b[g]=d;c&&(e[g]=c.find(n=>"CIMMarkerNorthArrow"===n.type))});this._serviceTemplateCustomTextElements=Object.freeze(b);this.templateToNorthArrowInfo=e}async _getPrintTemplatesFromService(a){return B(this.effectivePrintServiceUrl,{...a,query:{f:"json"},timeout:this.printTimeout}).then(b=>{let e=null,g=null;(b?.data?.parameters).forEach(d=>{var c=d.choiceList?.slice(),n=-1;c?.length&&d.defaultValue&&(n=c.indexOf(d.defaultValue));-1<n&&(c.splice(n,1),c.unshift(d.defaultValue));n=(l,p)=>
{const m="all"===p?l:l.filter(q=>p.includes(q));return 0===m.length?l:m};if("Format"===d.name)c=n(c.map(w.fromJSON),this.allowedFormats),d=w.fromJSON(d.defaultValue),e={defaultValue:c.includes(d)?d:c[0],choiceList:c};else if("Layout_Template"===d.name){c=c.filter(m=>"map_only"!==m.toLowerCase());let l=-1,p;c.some((m,q)=>{m=m.toLowerCase();if(m.includes("letter")&&m.includes("landscape"))return l=q,!0;m.includes("a4")&&m.includes("landscape")&&(l=q);return!1});0<l&&(p=c[l],c.splice(l,1),c.unshift(p));
c=n(c.map(t.fromJSON),this.allowedLayouts);d=t.fromJSON(d.defaultValue);g={defaultValue:c.includes(d)?d:c[0],choiceList:c}}});this.error=null;return{format:e,layout:g}}).catch(b=>{throw new r("print:unavailable-service-info","Can't fetch templates info from service",{error:b});})}};h.__decorate([k.property()],f.prototype,"_serviceTemplateCustomTextElements",void 0);h.__decorate([k.property()],f.prototype,"allowedFormats",void 0);h.__decorate([k.property()],f.prototype,"allowedLayouts",void 0);h.__decorate([k.property({type:y})],
f.prototype,"defaultTemplates",void 0);h.__decorate([k.property()],f.prototype,"extraParameters",void 0);h.__decorate([k.property()],f.prototype,"includeDefaultTemplates",void 0);h.__decorate([k.property({readOnly:!0})],f.prototype,"effectivePrintServiceUrl",null);h.__decorate([k.property()],f.prototype,"effectiveTemplateCustomTextElements",null);h.__decorate([k.property()],f.prototype,"error",void 0);h.__decorate([k.property({type:v})],f.prototype,"portal",void 0);h.__decorate([k.property()],f.prototype,
"printServiceUrl",void 0);h.__decorate([k.property()],f.prototype,"printTimeout",void 0);h.__decorate([k.property({readOnly:!0})],f.prototype,"state",null);h.__decorate([k.property({readOnly:!0})],f.prototype,"templatesInfo",void 0);h.__decorate([k.property()],f.prototype,"updateDelay",void 0);h.__decorate([k.property()],f.prototype,"view",void 0);h.__decorate([k.property()],f.prototype,"templateCustomTextElements",void 0);h.__decorate([k.property()],f.prototype,"templateToNorthArrowInfo",void 0);
return f=h.__decorate([E.subclass("esri.widgets.Print.PrintViewModel")],f)});