// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("../../chunks/tslib.es6 ../../core/Accessor ../../core/asyncUtils ../../core/Collection ../../core/Error ../../core/promiseUtils ../../core/reactiveUtils ../../core/time ../../core/accessorSupport/decorators/property ../../core/has ../../core/Logger ../../core/RandomLCG ../../core/accessorSupport/decorators/subclass ../../webdoc/Widgets ../../webdoc/widgets/FloorFilter ../support/GoTo".split(" "),function(h,g,I,B,J,K,x,L,k,Q,R,S,M,N,O,P){function y(a){return"esri.WebMap"===a.declaredClass}
g=class extends P.GoToMixin(g){constructor(a){super(a);this.filterMenuOpen=!1;this.filterMenuType="site";this.filterMode="base-floors";this.levelsExpanded=!0;this._viewWidthBreakpoint=this._viewHeightBreakpoint=this._updateFloorFilterTask=this.view=this.searchTerm=null}initialize(){this.addHandles([x.watch(()=>this.view?.map,a=>{null!=this._updateFloorFilterTask&&(this._updateFloorFilterTask.abort(),this._updateFloorFilterTask=null);this._updateFloorFilterTask=I.createTask(async c=>{await this._updateFloorFilterFromMap(a);
K.throwIfAborted(c);this._setInitialViewState(a)})},x.initial),x.watch(()=>this.view,(a,c)=>{this._unregisterWidget(c);this._registerWidget(a);this._watchSearchResults(a)},x.syncAndInitial),x.watch(()=>this.view?.widthBreakpoint??null,a=>{this._viewWidthBreakpoint=a}),x.watch(()=>this.view?.heightBreakpoint??null,a=>{this._viewHeightBreakpoint=a})])}destroy(){this._unregisterWidget(this.view);this.view=null;null!=this._updateFloorFilterTask&&(this._updateFloorFilterTask.abort(),this._updateFloorFilterTask=
null)}set enabled(a){this._callOverride("enabled",a)}set facility(a){if(a&&this._isOverridden("facility")){const c=this.getFacility(a);this.hasMultipleSites&&(this.site=c?.siteId||null)}this._callOverride("facility",a)}set filterFeatures(a){this._callOverride("filterFeatures",a)}set filterLayers(a){this._callOverride("filterLayers",a)}get hasFacilities(){return null!=this.filterLayers?.facilityLayer&&0<this.filterFeatures?.facilities?.facilitiesInfo?.length}get hasLevels(){return null!=this.filterLayers?.levelLayer&&
0<this.filterFeatures?.levels?.levelsInfo?.length}get hasMultipleSites(){return null!=this.filterLayers?.siteLayer&&1<this.filterFeatures?.sites?.sitesInfo?.length}get isNormalMode(){let a=!0;const c=this._viewWidthBreakpoint;if("xsmall"===this._viewHeightBreakpoint||"xsmall"===c)a=!1;return a}set level(a){if(a){var c=null,b=null;c=a?.split("--");1<c?.length&&"all"===c[0]?(b=c[1],c={id:a,facilityId:b,shortName:null,longName:null,levelNumber:null,verticalOrder:null}):(c=this.getLevel(a),b=c?.facilityId??
null);this.level!==a||this.isNormalMode||this.levelsExpanded?(c&&this.hasFacilities&&this.hasLevels?(this.facility=b,this.hasMultipleSites&&(this.site=this.getFacility(b)?.siteId||null),this.setFloors(c)):this._isOverridden("level")&&(this.site=this.facility=null,this.hasMultipleSites&&(this.filterMenuType="site"),this.setFloors(null)),this._callOverride("level",a)):1<this.getFacilityLevels(b)?.length&&(this.levelsExpanded=!0)}else this._callOverride("level",a),this.site=this.facility=null,this.setFloors(null)}set longNames(a){this._callOverride("longNames",
a)}set minimized(a){this._callOverride("minimized",a)}set pinnedLevels(a){this._callOverride("pinnedLevels",a)}set site(a){this._callOverride("site",a)}get state(){return this.view&&this.filterFeatures&&this.hasFacilities&&this.hasLevels?"ready":this.view&&!this.filterFeatures?"loading":"disabled"}filterFacilities(a){let c=a;this.searchTerm&&(this.searchTerm=this.searchTerm.trim(),c=a.filter(b=>{({name:b}=b);return b.toLowerCase().includes(this.searchTerm?.toLowerCase())}));this.site&&(c=c.filter(b=>
b.siteId===this.site));return c.sort((b,d)=>b.name.localeCompare(d.name,void 0,{sensitivity:"base"}))}filterSites(a){let c=a;this.searchTerm&&(this.searchTerm=this.searchTerm.trim(),c=a.filter(b=>{({name:b}=b);return b.toLowerCase().includes(this.searchTerm?.toLowerCase())}));return c.sort((b,d)=>b.name.localeCompare(d.name,void 0,{sensitivity:"base"}))}getBaseLevel(a){const c=this.filterFeatures?.levels?.levelsInfo;let b=null;if(a){const {id:d}=a;if(c&&0<c.length&&(c.forEach(e=>{0===e.verticalOrder&&
e.facilityId===d&&(b=e)}),!b)){let e=null;c.forEach(f=>{f.facilityId===d&&(e?0<=(f.verticalOrder??0)?null!=e.verticalOrder&&(0>e.verticalOrder||(f.verticalOrder??0)<e.verticalOrder)&&(e=f):null!=e.verticalOrder&&null!=f.verticalOrder&&0>e.verticalOrder&&f.verticalOrder>e.verticalOrder&&(e=f):e=f)});e&&(b=e)}}return b}getFacility(a){return this.filterFeatures?.facilities?.facilitiesInfo?.find(c=>c.id===a)??null}getFacilityLevels(a){return a&&this.filterFeatures?.levels?.levelsInfo?this.filterFeatures.levels.levelsInfo.filter(c=>
c.facilityId===a).sort((c,b)=>{c=c.verticalOrder??0;b=b.verticalOrder??0;return c>b?-1:c===b?0:1}):[]}getLevel(a){return this.filterFeatures?.levels?.levelsInfo?.find(c=>c.id===a)??null}getSite(a){return this.filterFeatures?.sites?.sitesInfo?.find(c=>c.id===a)??null}goTo(a){const {view:c}=this;c&&a&&({geometry:a}=a,a&&a.extent&&this.callGoTo({target:a.extent,options:{duration:L.Milliseconds(1E3),easing:"in-out-quad"}}))}setFloors(a){const {view:c}=this;c&&(c?.map?.allLayers?.forEach(b=>{"feature"===
b.type&&this._computeViewAllModeFloors(b)}),c.floors=new B(this._computeFloors(a)))}updateWebDocument(a){if(y(a)){const c=new O({enabled:this.enabled,longNames:this.longNames,minimized:this.minimized,pinnedLevels:this.pinnedLevels,site:this.site??null,facility:this.facility??null,level:this.level??null});a.widgets?a.widgets.floorFilter=c:a.widgets=new N({floorFilter:c})}}_computeFloors(a){if("single-floor"===this.filterMode)this._computeSingleFloor(a);else if("base-floors"===this.filterMode)return"3d"===
this.view?.type?this._computeBaseFloors3D(a):this._computeBaseFloors(a);return this._computeEmptyFloors()}_computeSingleFloor(a){if(!a)return this._computeEmptyFloors();const c=[];"all"===a?.id?this.getFacilityLevels(a.facilityId).forEach(b=>{b.id&&c.push(b.id)}):a&&c.push(a.id);return c}_computeBaseFloors(a){const c=this.filterFeatures?.levels?.levelsInfo;if(!c?.length)return this._computeEmptyFloors();const b=[];"all"===a?.id?this.getFacilityLevels(a.facilityId).forEach(e=>{e.id&&b.push(e.id)}):
a&&b.push(a.id);const d=a?.facilityId;c.forEach(e=>{const {id:f,facilityId:l,verticalOrder:p}=e;d||0!==p||b.includes(f)?l===d||0!==p||b.includes(f)||b.push(f):b.push(f)});return b}_computeBaseFloors3D(a){const c=this.filterFeatures?.levels?.levelsInfo;if(!c?.length)return this._computeEmptyFloors();const b=[],d=a?.id.split("--")??[];1<d?.length&&"all"===d[0]?this.getFacilityLevels(a?.facilityId).forEach(f=>{f.id&&b.push(f.id)}):a&&b.push(a.id);const e=a?.facilityId;c.forEach(f=>{const {id:l,facilityId:p}=
f;e||b.includes(l)?p===e||b.includes(l)||b.push(l):b.push(l)});return b}_computeEmptyFloors(){return[]}async _setFilterLayers(){var {view:a}=this;if(a&&!this._isOverridden("filterLayers"))if(y(a.map)||"esri.WebScene"===a.map.declaredClass){const b=a.map;var c=b?.allLayers;if(0<c?.items?.length){const d={siteLayer:null,facilityLayer:null,levelLayer:null},e=b.floorInfo?.siteLayer?.layerId,f=b.floorInfo?.facilityLayer?.layerId,l=b.floorInfo?.levelLayer?.layerId,p=b.floorInfo?.siteLayer?.sublayerId||
b.floorInfo?.facilityLayer?.sublayerId||b.floorInfo?.levelLayer?.sublayerId;if(f&&l){a=c.items.filter(m=>"feature"===m.type||"scene"===m.type);c=c.items.filter(m=>"map-image"===m.type);if(0<c?.length&&p){await Promise.all(c.map(n=>n.load()));const m=b.floorInfo?.siteLayer?.sublayerId,r=b.floorInfo?.facilityLayer?.sublayerId,u=b.floorInfo?.levelLayer?.sublayerId;c.forEach(n=>{const q=n.id;n=n?.allSublayers;(q===e||q===f||q===l)&&0<n?.items?.length&&n.items.forEach(t=>{const v=t.id;q===e&&v===m?d.siteLayer=
t:v===r?d.facilityLayer=t:v===u&&(d.levelLayer=t)})})}0<a?.length&&a.forEach(m=>{const r=m.id;r===e?d.siteLayer=m:r===f?d.facilityLayer=m:r===l&&(d.levelLayer=m)});this.filterLayers=d}}}else throw new J("Map must be a webmap or webscene");}async _getFilterFeatures(){if(this._isOverridden("filterFeatures"))return this.filterFeatures;const [a,c,b]=await Promise.all([this._getSites(),this._getFacilities(),this._getLevels()]);return{sites:a,facilities:c,levels:b}}async _getSites(){const a={sitesInfo:[]},
{filterLayers:c,view:b}=this;var d=b?.map;const {siteLayer:e}=c;if(!e||!d?.floorInfo?.siteLayer)return a;const f=e.createQuery();f.returnGeometry=!0;f.outFields=["*"];f.returnZ=!0;"type"in e&&"scene"===e.type&&(f.multipatchOption="xyFootprint");const {siteIdField:l,nameField:p}=d.floorInfo.siteLayer;d=await e.queryFeatures(f);if(0<d?.features?.length){d=d.features;const m=e?.fieldsIndex.get(l)?.name||l,r=e?.fieldsIndex.get(p)?.name||p;null!=m&&null!=r&&d.forEach(u=>{var n=u.attributes;u=u.geometry;
const q=n[m];n=n[r];q&&n&&a.sitesInfo.push({id:q,name:n,geometry:u})})}return a}async _getFacilities(){const {filterLayers:a,view:c}=this;var b=c?.map;const {facilityLayer:d}=a,e={facilitiesInfo:[]};if(!d||!b?.floorInfo?.facilityLayer)return e;const f=d.createQuery();f.returnGeometry=!0;f.outFields=["*"];f.returnZ=!0;"type"in d&&"scene"===d.type&&(f.multipatchOption="xyFootprint");const {facilityIdField:l,siteIdField:p,nameField:m}=b.floorInfo.facilityLayer;b=await d.queryFeatures(f);if(0<b?.features?.length){b=
b.features;const r=d?.fieldsIndex.get(l)?.name||l,u=d?.fieldsIndex.get(p)?.name||p,n=d?.fieldsIndex.get(m)?.name||m;r&&u&&n&&b.forEach(q=>{var t=q.attributes;q=q.geometry;const v=t[r],z=t[u];t=t[n];v&&t&&e.facilitiesInfo.push({id:v,siteId:z,name:t,geometry:q})})}return e}async _getLevels(){const {filterLayers:a,view:c}=this;var b=c?.map;const {levelLayer:d}=a,e={levelsInfo:[]};if(!d||!b?.floorInfo?.levelLayer)return e;const f=d.createQuery();f.returnGeometry=!0;f.outFields=["*"];f.returnZ=!0;const {levelIdField:l,
facilityIdField:p,longNameField:m,shortNameField:r,levelNumberField:u,verticalOrderField:n}=b.floorInfo.levelLayer;b=await d.queryFeatures(f);if(0<b?.features?.length){b=b.features;const q=d?.fieldsIndex.get(l)?.name||l,t=d?.fieldsIndex.get(p)?.name||p,v=d?.fieldsIndex.get(m)?.name||m,z=d?.fieldsIndex.get(r)?.name||r,C=d?.fieldsIndex.get(u)?.name||u,D=d?.fieldsIndex.get(n)?.name||n;q&&t&&v&&z&&C&&D&&b.forEach(A=>{var w=A.attributes;A=w[q];const E=w[t],F=w[v],G=w[z],H=w[C];w=w[D];A&&E&&F&&G&&"number"===
typeof H&&"number"===typeof w&&e.levelsInfo.push({id:A,facilityId:E,longName:F,shortName:G,levelNumber:H,verticalOrder:w})})}return e}_registerWidget(a){a?.persistableViewModels.includes(this)||a?.persistableViewModels.add(this)}_unregisterWidget(a){a?.persistableViewModels.remove(this)}_watchSearchResults(a){a?.on("select-result-floor",c=>{const b=this.getLevel(c);b&&this.level!==c&&(this.level=c,this.setFloors(b))})}async _setInitialViewState(a){if(this.view)try{await this.view.when();await this._setFilterLayers();
const c=await this._getFilterFeatures();if(c)if(this.filterFeatures=c,this.hasFacilities&&this.hasLevels)if(this.hasMultipleSites||(this.filterMenuType="facility"),this.facility&&this.level){this.filterMenuType="facility";const b=this.getFacility(this.facility),d=this.getLevel(this.level);this.site||(this.site=b?.siteId||void 0);this.setFloors(d)}else if(this.facility&&!this.level){this.filterMenuType="facility";const b=this.getFacility(this.facility),d=this.getBaseLevel(b);this.site||(this.site=
b?.siteId||void 0);this.level=d?.id||void 0;this.setFloors(d)}else if(!this.facility&&this.level){this.filterMenuType="facility";const b=this.getLevel(this.level),d=this.getFacility(b?.facilityId);this.facility=d?.id||void 0;this.site||(this.site=d?.siteId||void 0);this.setFloors(b)}else{if(!this.site||this.facility||this.level){if(!a||!y(a)){this.setFloors(null);return}a=a?.widgets?.floorFilter;if(!a){this.setFloors(null);return}a.site&&!this.site&&(this.site=a.site,this.filterMenuType="facility")}else this.filterMenuType=
"site";this.setFloors(null)}else console.error("Facilities and Levels are required for the Floor Filter widget")}catch(c){console.error("Couldn't retrieve sites, facilities, and levels",c)}}_callOverride(a,c){this._override(a,c)}async _updateFloorFilterFromMap(a){a&&y(a)&&(a=a?.widgets?.floorFilter)&&(this._isOverridden("enabled")||(this.enabled=a.enabled),this._isOverridden("longNames")||(this.longNames=a.longNames),this._isOverridden("minimized")||(this.minimized=a.minimized),this._isOverridden("pinnedLevels")||
(this.pinnedLevels=a.pinnedLevels),this._isOverridden("site")||(this.site=a.site),this._isOverridden("facility")||(this.facility=a.facility),this._isOverridden("level")||(this.level=a.level))}_computeViewAllModeFloors(a){const {filterFeatures:c}=this;if(a.floorInfo?.viewAllMode&&this.hasLevels&&this.hasFacilities&&"base-floors"===this.filterMode){const {level:b,facility:d}=this,e=[];c.levels.levelsInfo.forEach(f=>{const {id:l,facilityId:p}=f;d&&p===d?b&&l===b&&e.push(l):e.push(l)});a.floorInfo.viewAllLevelIds=
new B(e)}}};h.__decorate([k.property({value:!1})],g.prototype,"enabled",null);h.__decorate([k.property({value:void 0})],g.prototype,"facility",null);h.__decorate([k.property({value:null})],g.prototype,"filterFeatures",null);h.__decorate([k.property({value:null})],g.prototype,"filterLayers",null);h.__decorate([k.property()],g.prototype,"filterMenuOpen",void 0);h.__decorate([k.property()],g.prototype,"filterMenuType",void 0);h.__decorate([k.property()],g.prototype,"filterMode",void 0);h.__decorate([k.property()],
g.prototype,"hasFacilities",null);h.__decorate([k.property()],g.prototype,"hasLevels",null);h.__decorate([k.property()],g.prototype,"hasMultipleSites",null);h.__decorate([k.property({readOnly:!0})],g.prototype,"isNormalMode",null);h.__decorate([k.property({value:void 0})],g.prototype,"level",null);h.__decorate([k.property({value:!1})],g.prototype,"longNames",null);h.__decorate([k.property()],g.prototype,"levelsExpanded",void 0);h.__decorate([k.property({value:!1})],g.prototype,"minimized",null);h.__decorate([k.property({value:!1})],
g.prototype,"pinnedLevels",null);h.__decorate([k.property()],g.prototype,"searchTerm",void 0);h.__decorate([k.property({value:void 0})],g.prototype,"site",null);h.__decorate([k.property({readOnly:!0})],g.prototype,"state",null);h.__decorate([k.property()],g.prototype,"view",void 0);h.__decorate([k.property()],g.prototype,"_viewHeightBreakpoint",void 0);h.__decorate([k.property()],g.prototype,"_viewWidthBreakpoint",void 0);h.__decorate([k.property()],g.prototype,"updateWebDocument",null);return g=
h.__decorate([M.subclass("esri/widgets/FloorFilter/FloorFilterViewModel")],g)});