// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/tsSupport/paramHelper ../core/tsSupport/generatorHelper ../core/tsSupport/awaiterHelper ../core/Error ../core/lang ../core/Logger ../core/promiseUtils ../core/accessorSupport/decorators ../core/libs/gl-matrix-2/vec3f64 ../core/libs/gl-matrix-2/vec4f64 ./Extent ./Geometry ./Point ./Polygon ./support/MeshComponent ./support/MeshVertexAttributes ./support/triangulationUtils ./support/meshUtils/centerAt ./support/meshUtils/merge ./support/meshUtils/offset ./support/meshUtils/primitives ./support/meshUtils/rotate ./support/meshUtils/scale".split(" "),
function(G,v,H,l,R,z,A,B,I,J,C,f,h,w,x,K,r,L,t,D,M,N,O,P,m,n,Q){var p=J.getLogger("esri.geometry.Mesh");v=function(h){function b(a){a=h.call(this,a)||this;a.components=null;a.hasZ=!0;a.hasM=!1;a.vertexAttributes=new D.MeshVertexAttributes;a.type="mesh";return a}H(b,h);k=b;Object.defineProperty(b.prototype,"extent",{get:function(){var a=this.spatialReference,c=this.vertexAttributes&&this.vertexAttributes.position;if(!c||0===c.length||this.components&&0===this.components.length)return new x({xmin:0,
ymin:0,zmin:0,xmax:0,ymax:0,zmax:0,spatialReference:a});a={xmin:Infinity,xmax:-Infinity,ymin:Infinity,ymax:-Infinity,zmin:Infinity,zmax:-Infinity,spatialReference:a};if(!this.components)return new x(this.extendExtent(a,c,null));for(var b=0,d=this.components;b<d.length;b++){var e=d[b];if(e.faces)this.extendExtent(a,c,e.faces);else{this.extendExtent(a,c,null);break}}return new x(a)},enumerable:!0,configurable:!0});b.prototype.addComponent=function(a){this.components||(this.components=[]);this.components.push(t.from(a));
this.clearCache()};b.prototype.removeComponent=function(a){if(this.components&&(a=this.components.indexOf(a),-1!==a)){this.components=this.components.splice(a,1);return}p.error("removeComponent()","Provided component is not part of the list of components")};b.prototype.rotate=function(a,c,b,d){n.axisAngleFrom(y.x,a/180*Math.PI,q);n.axisAngleFrom(y.y,c/180*Math.PI,E);n.axisAngleFrom(y.z,b/180*Math.PI,F);n.axisAngleMultiply(q,E,q);n.axisAngleMultiply(q,F,q);n.rotate(this,q,d);return this};b.prototype.offset=
function(a,c,b,d){u[0]=a;u[1]=c;u[2]=b;P.offset(this,u,d);return this};b.prototype.scale=function(a,c){Q.scale(this,a,c);return this};b.prototype.centerAt=function(a,c){N.centerAt(this,a,c);return this};b.prototype.clone=function(){var a=this.components?new Map:null,c=this.components?new Map:null,b=this.components?this.components.map(function(b){return b.cloneWithDeduplication(a,c)}):null;return new k({components:b,spatialReference:this.spatialReference,vertexAttributes:I.clone(this.vertexAttributes)})};
b.prototype.vertexAttributesChanged=function(){this.clearCache()};b.prototype.toJSON=function(a){return this.write(null,a)};b.prototype.forEachVertex=function(a,c,b){if(c)for(e=0;e<c.length;e++){var d=3*c[e];b(a[d+0],a[d+1],a[d+2])}else for(var e=0;e<a.length;e+=3)b(a[e+0],a[e+1],a[e+2])};b.prototype.extendExtent=function(a,c,b){this.forEachVertex(c,b,function(c,b,k){a.xmin=Math.min(a.xmin,c);a.xmax=Math.max(a.xmax,c);a.ymin=Math.min(a.ymin,b);a.ymax=Math.max(a.ymax,b);a.zmin=Math.min(a.zmin,k);a.zmax=
Math.max(a.zmax,k)});return a};b.createBox=function(a,c){if(!(a instanceof r))return p.error(".createBox()","expected location to be a Point instance"),null;a=new k(m.convertUnitGeometry(m.createUnitSizeBox(),a,c));if(c&&c.imageFace&&"all"!==c.imageFace){var b=a.components[0],d=b.faces,e=m.boxFaceOrder[c.imageFace],f=6*e;c=new Uint32Array(6);for(var l=new Uint32Array(d.length-6),h=0,n=0,g=0;g<d.length;g++)g>=f&&g<f+6?c[h++]=d[g]:l[n++]=d[g];d=new Float32Array(a.vertexAttributes.uv);e*=8;f=[0,1,1,
1,1,0,0,0];for(g=0;g<f.length;g++)d[e+g]=f[g];a.vertexAttributes.uv=d;a.components=[new t({faces:c,material:b.material}),new t({faces:l})]}return a};b.createSphere=function(a,b){return a instanceof r?new k(m.convertUnitGeometry(m.createUnitSizeSphere(b&&b.densificationFactor||0),a,b)):(p.error(".createSphere()","expected location to be a Point instance"),null)};b.createCylinder=function(a,b){return a instanceof r?new k(m.convertUnitGeometry(m.createUnitSizeCylinder(b&&b.densificationFactor||0),a,
b)):(p.error(".createCylinder()","expected location to be a Point instance"),null)};b.createPlane=function(a,b){return a instanceof r?new k(m.convertUnitGeometry(m.createUnitSizePlane(b&&b.facing||"up"),a,b)):(p.error(".createPlane()","expected location to be a Point instance"),null)};b.createFromPolygon=function(a,b){if(!(a instanceof L))return p.error(".createFromPolygon()","expected polygon to be a Polygon instance"),null;var c=M.triangulate(a);return new k({vertexAttributes:{position:c.position},
components:[{faces:c.faces,shading:"flat",material:b&&b.material||null}],spatialReference:a.spatialReference})};b.createFromGLTF=function(a,b,f){return A(this,void 0,void 0,function(){var c=this;return z(this,function(d){if(!(a instanceof r))throw p.error(".createfromGLTF()","expected location to be a Point instance"),new B("invalid-input","Expected location to be a Point instance");return[2,C.create(function(d,e){G(["./support/loadGLTFMesh"],function(l){return A(c,void 0,void 0,function(){var c,
g;return z(this,function(h){switch(h.label){case 0:return h.trys.push([0,2,,3]),C.throwIfAborted(f),[4,l.loadGLTFMesh(a,b,f)];case 1:return c=h.sent(),d(new k(O.merge(c.map(function(a){return new k(a)}),{reuseMaterials:!0}))),[3,3];case 2:return g=h.sent(),e(new B("gltf-loader-error","Failed to load glTF.","["+g.name+"] "+g.message)),[3,3];case 3:return[2]}})})})})]})})};var k;l([f.property({dependsOn:["vertexAttributes","vertexAttributes.position","components"],json:{read:!1}})],b.prototype,"cache",
void 0);l([f.property({type:[t]})],b.prototype,"components",void 0);l([f.property({dependsOn:["cache"],readOnly:!0,json:{read:!1}})],b.prototype,"extent",null);l([f.property({readOnly:!0,json:{read:!1,write:!1}})],b.prototype,"hasZ",void 0);l([f.property({readOnly:!0,json:{read:!1,write:!1}})],b.prototype,"hasM",void 0);l([f.property({type:D.MeshVertexAttributes,nonNullable:!0,json:{write:!0}})],b.prototype,"vertexAttributes",void 0);return b=k=l([f.subclass("esri.geometry.Mesh")],b)}(f.declared(K));
v.prototype.toJSON.isDefaultToJSON=!0;var y={x:h.vec3f64.fromValues(1,0,0),y:h.vec3f64.fromValues(0,1,0),z:h.vec3f64.fromValues(0,0,1)},u=h.vec3f64.create(),q=w.vec4f64.create(),E=w.vec4f64.create(),F=w.vec4f64.create();return v});