// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("exports ../request ./featureSetCollection ../chunks/languageUtils ./featureset/actions/AttributeFilter ./featureset/actions/GroupBy ./featureset/actions/OrderBy ./featureset/actions/SpatialFilter ./featureset/actions/Top ./featureset/sources/FeatureLayerDynamic ./featureset/sources/FeatureLayerMemory ./featureset/sources/FeatureLayerRelated ./featureset/support/cache ./featureset/support/errorsupport ./featureset/support/FeatureSet ./featureset/support/shared ../core/sql/WhereClause ../layers/FeatureLayer ../portal/PortalItem".split(" "),
function(q,u,x,t,E,F,G,H,I,J,K,L,g,y,M,z,A,m,N){async function v(a,e){if(g.applicationCache){var b=g.applicationCache.getLayerInfo(a);if(b)return b=await b,new m({url:a,outFields:e,sourceJSON:b});const d=new m({url:a,outFields:e});e=(async()=>{await d.load();return d.sourceJSON})();if(g.applicationCache){g.applicationCache.setLayerInfo(a,e);try{return await e,d}catch(c){throw g.applicationCache.clearLayerInfo(a),c;}}await e;return d}return new m({url:a,outFields:e})}async function w(a,e,b,d,c,f=null){a=
await v(a,["*"]);return l(a,e,b,d,c,f)}function l(a,e=null,b=null,d=!0,c=null,f=null){if(a instanceof m||t.isSubtypeGrouplayer(a))return e={layer:a,spatialReference:e,outFields:b,includeGeometry:d,lrucache:c,interceptor:f},!0===!(a.url||!a.source)?new K(e):new J(e);e=l(a.parent,e,b,d,c,f);return e.filter(A.WhereClause.create(a.parent.subtypeField+"\x3d"+a.subtypeCode.toString(),a.parent.fieldsIndex,e.dateFieldsTimeZoneDefaultUTC))}async function O(a){if(null!==g.applicationCache){var e=g.applicationCache.getLayerInfo(a);
if(null!==e)return e}e=(async()=>{const b=await u(a,{responseType:"json",query:{f:"json"}});return b.data?b.data:null})();if(null!==g.applicationCache){g.applicationCache.setLayerInfo(a,e);try{return await e}catch(b){throw g.applicationCache.clearLayerInfo(a),b;}}return e}async function P(a,e){const b="QUERYDATAELEMTS:"+e.toString()+":"+a;if(null!==g.applicationCache){var d=g.applicationCache.getLayerInfo(b);if(null!==d)return d}d=(async()=>{var c=await u(a+"/queryDataElements",{method:"post",responseType:"json",
query:{layers:JSON.stringify([e.toString()]),f:"json"}});if(c.data&&(c=c.data,c.layerDataElements?.[0]))return c.layerDataElements[0];throw new y.FeatureSetError(y.FeatureSetErrorCodes.DataElementsNotFound);})();if(null!==g.applicationCache){g.applicationCache.setLayerInfo(b,d);try{return await d}catch(c){throw g.applicationCache.clearLayerInfo(b),c;}}return d}async function B(a){if(null!==g.applicationCache){var e=g.applicationCache.getLayerInfo(a);if(null!==e)return e}e=(async()=>{var b=await u(a,
{responseType:"json",query:{f:"json"}});return b.data?(b=b.data,b.layers||(b.layers=[]),b.tables||(b.tables=[]),b):{layers:[],tables:[]}})();if(null!==g.applicationCache){g.applicationCache.setLayerInfo(a,e);try{return await e}catch(b){throw g.applicationCache.clearLayerInfo(a),b;}}return e}E.registerAction();F.registerAction();G.registerAction();H.registerAction();I.registerAction();class Q extends x{constructor(a,e=null,b=null,d=null){super();this._map=a;this._overridespref=e;this._lrucache=b;this._interceptor=
d;this._instantLayers=[]}_makeAndAddFeatureSet(a,e=!0,b=null){const d=l(a,this._overridespref,null===b?["*"]:b,e,this._lrucache,this._interceptor);this._instantLayers.push({featureset:d,opitem:a,includeGeometry:e,outFields:JSON.stringify(b)});return d}async featureSetByName(a,e=!0,b=null){if(void 0!==this._map.loaded&&void 0!==this._map.load&&!1===this._map.loaded)return await this._map.load(),this.featureSetByName(a,e,b);null===b&&(b=["*"]);b=b.slice(0);b=b.sort();var d=JSON.stringify(b);for(let c=
0;c<this._instantLayers.length;c++){const f=this._instantLayers[c];if(f.opitem.title===a&&f.includeGeometry===e&&f.outFields===d)return this._instantLayers[c].featureset}if(d=this._map.allLayers.find(c=>{if(c instanceof m){if(c.title===a)return!0}else if(t.isSubtypeGrouplayer(c)&&c.title===a)return!0;return!1}))return this._makeAndAddFeatureSet(d,e,b);if(this._map.tables&&(d=this._map.tables.find(c=>c.title&&c.title===a||c.title&&c.title===a?!0:!1))){if(d instanceof m)return this._makeAndAddFeatureSet(d,
e,b);d._materializedTable||(d._materializedTable=new m(d.outFields?d:{...d,outFields:["*"]}));await d._materializedTable.load();return this._makeAndAddFeatureSet(d._materializedTable,e,b)}return null}async featureSetById(a,e=!0,b=["*"]){if(void 0!==this._map.loaded&&void 0!==this._map.load&&!1===this._map.loaded)return await this._map.load(),this.featureSetById(a,e,b);null===b&&(b=["*"]);b=b.slice(0);b=b.sort();var d=JSON.stringify(b);for(let c=0;c<this._instantLayers.length;c++){const f=this._instantLayers[c];
if(f.opitem.id===a&&f.includeGeometry===e&&f.outFields===d)return this._instantLayers[c].featureset}if(d=this._map.allLayers.find(c=>{if(c instanceof m){if(c.id===a)return!0}else if(t.isSubtypeGrouplayer(c)&&c.id===a)return!0;return!1}))return this._makeAndAddFeatureSet(d,e,b);if(this._map.tables&&(d=this._map.tables.find(c=>c.id===a?!0:!1))){if(d instanceof m)return this._makeAndAddFeatureSet(d,e,b);d._materializedTable||(d._materializedTable=new m({...d,outFields:["*"]}));await d._materializedTable.load();
return this._makeAndAddFeatureSet(d._materializedTable,e,b)}return null}}class C extends x{constructor(a,e=null,b=null,d=null){super();this._url=a;this._overridespref=e;this._lrucache=b;this._interceptor=d;this.metadata=null;this._instantLayers=[]}get url(){return this._url}_makeAndAddFeatureSet(a,e=!0,b=null){const d=l(a,this._overridespref,null===b?["*"]:b,e,this._lrucache);this._instantLayers.push({featureset:d,opitem:a,includeGeometry:e,outFields:JSON.stringify(b)});return d}async _loadMetaData(){const a=
await B(this._url);return this.metadata=a}load(){return this._loadMetaData()}clone(){return new C(this._url,this._overridespref,this._lrucache,this._interceptor)}async featureSetByName(a,e=!0,b=null){null===b&&(b=["*"]);b=b.slice(0);b=b.sort();var d=JSON.stringify(b);for(var c=0;c<this._instantLayers.length;c++){const f=this._instantLayers[c];if(f.opitem.title===a&&f.includeGeometry===e&&f.outFields===d)return this._instantLayers[c].featureset}d=await this._loadMetaData();c=null;for(const f of d.layers??
[])f.name===a&&(c=f);if(!c)for(const f of d.tables??[])f.name===a&&(c=f);return c?(a=await v(this._url+"/"+c.id,["*"]),this._makeAndAddFeatureSet(a,e,b)):null}async featureSetById(a,e=!0,b=["*"]){null===b&&(b=["*"]);b=b.slice(0);b=b.sort();var d=JSON.stringify(b);a=null!==a&&void 0!==a?a.toString():"";for(var c=0;c<this._instantLayers.length;c++){const f=this._instantLayers[c];if(f.opitem.id===a&&f.includeGeometry===e&&f.outFields===d)return this._instantLayers[c].featureset}d=await this._loadMetaData();
c=null;for(const f of d.layers??[])null!==f.id&&void 0!==f.id&&f.id.toString()===a&&(c=f);if(!c)for(const f of d.tables??[])null!==f.id&&void 0!==f.id&&f.id.toString()===a&&(c=f);return c?(a=await v(this._url+"/"+c.id,["*"]),this._makeAndAddFeatureSet(a,e,b)):null}}q.constructAssociationMetaDataFeatureSetFromUrl=async function(a,e){var b=3,d=[],c=null,f={},k=null;k=await B(a);if(void 0!==k.controllerDatasetLayers?.utilityNetworkLayerId&&null!==k.controllerDatasetLayers.utilityNetworkLayerId){if(k.layers)for(var n of k.layers)f[n.id]=
n.name;if(k.tables)for(var h of k.tables)f[h.id]=h.name;n=k.controllerDatasetLayers.utilityNetworkLayerId;if(k=await P(a,n)){c=k;c?.dataElement&&void 0!==c.dataElement.schemaGeneration&&(b=c.dataElement.schemaGeneration);k={};c.dataElement.domainNetworks||(c.dataElement.domainNetworks=[]);for(var r of c.dataElement.domainNetworks){for(const p of r.edgeSources??[])h={layerId:p.layerId,sourceId:p.sourceId,className:f[p.layerId]??null},h.className&&(k[h.className]=h);for(const p of r.junctionSources??
[])h={layerId:p.layerId,sourceId:p.sourceId,className:f[p.layerId]??null},h.className&&(k[h.className]=h)}if(c.dataElement.terminalConfigurations)for(const p of c.dataElement.terminalConfigurations)for(const D of p.terminals)d.push({terminalId:D.terminalId,terminalName:D.terminalName});f=await O(a+"/"+n);if(void 0!==f.systemLayers?.associationsTableId&&null!==f.systemLayers.associationsTableId)return r=[],4<=b&&(r.push("STATUS"),r.push("PERCENTALONG")),a=await w(a+"/"+f.systemLayers.associationsTableId.toString(),
e,["OBJECTID","FROMNETWORKSOURCEID","TONETWORKSOURCEID","FROMGLOBALID","TOGLOBALID","TOTERMINALID","FROMTERMINALID","ASSOCIATIONTYPE","ISCONTENTVISIBLE","GLOBALID",...r],!1,null,null),await a.load(),4<=b&&(a=a.filter(A.WhereClause.create("STATUS NOT IN (1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 33, 34, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 49, 50, 51, 52, 53, 54, 55, 57, 58, 59, 60, 61, 62, 63)",a.getFieldsIndex(),a.dateFieldsTimeZoneDefaultUTC)),
await a.load()),{lkp:k,associations:a,unVersion:b,terminals:d}}}return{associations:null,unVersion:b,lkp:null,terminals:[]}};q.constructFeatureSet=l;q.constructFeatureSetFromPortalItem=async function(a,e,b,d,c,f,k,n=null){if(g.applicationCache){var h=g.applicationCache.getLayerInfo(a+":"+f.url);if(h)return a=await h,e=new m({url:z.extractServiceUrl(a.url)+"/"+e,outFields:["*"]}),l(e,b,d,c,k,n)}h=(new N({id:a,portal:f})).load();g.applicationCache&&g.applicationCache.setLayerInfo(a+":"+f.url,h);try{const r=
await h,p=new m({url:z.extractServiceUrl(r.url??"")+"/"+e,outFields:["*"]});return l(p,b,d,c,k,n)}catch(r){throw g.applicationCache&&g.applicationCache.clearLayerInfo(a+":"+f.url),r;}};q.constructFeatureSetFromRelationship=async function(a,e,b,d=null,c=null,f=!0,k=null,n=null){var h=a.serviceUrl();if(!h)return null;h="/"===h.charAt(h.length-1)?h+e.relatedTableId.toString():h+"/"+e.relatedTableId.toString();h=await w(h,d,c,f,k,n);return new L({layer:a,relatedLayer:h,relationship:e,objectId:b,spatialReference:d,
outFields:c,includeGeometry:f,lrucache:k,interceptor:n})};q.constructFeatureSetFromUrl=w;q.convertToFeatureSet=function(a,e,b,d,c){if(null===a)return null;if(a instanceof m){switch(e){case "datasource":return l(a,c,a.outFields,!0,b,d).getDataSourceFeatureSet();case "parent":return l(a,c,a.outFields,!0,b,d);case "root":return l(a,c,a.outFields,!0,b,d)}return null}if(t.isSubtypeGrouplayer(a)){switch(e){case "datasource":return l(a,c,a.outFields,!0,b,d).getDataSourceFeatureSet();case "parent":return l(a,
c,a.outFields,!0,b,d);case "root":return l(a,c,a.outFields,!0,b,d)}return null}if(t.isSubtypeSublayer(a)){switch(e){case "datasource":return l(a.parent,c,a.parent.outFields,!0,b,d).getDataSourceFeatureSet();case "parent":return l(a,c,a.parent.outFields,!0,b,d);case "root":return l(a,c,a.parent.outFields,!0,b,d)}return null}if(a instanceof M)switch(e){case "datasource":return a.getDataSourceFeatureSet();case "parent":return a;case "root":return a.getRootFeatureSet()}return null};q.createFeatureSetCollectionFromMap=
function(a,e,b=null,d=null){return new Q(a,e,b,d)};q.createFeatureSetCollectionFromService=function(a,e,b=null,d=null){return new C(a,e,b,d)};q.initialiseMetaDataCache=function(){null===g.applicationCache&&(g.applicationCache=new g)};Object.defineProperty(q,Symbol.toStringTag,{value:"Module"})});