// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define("exports ../../../../../core/handleUtils ../../../../../core/time ../../../../../geometry/support/meshUtils/exporters/gltf/imageutils ../../../../../symbols/cim/enums ../grouping".split(" "),function(k,z,g,A,l,B){function r(a){return g.Milliseconds(a.frameDurations.reduce((b,c)=>b+c,0))}function t(a){const {width:b,height:c}=a,f=a.frameDurations.reverse();return{frameCount:a.frameCount,duration:a.duration,frameDurations:f,getFrame:d=>a.getFrame(a.frameDurations.length-1-d),width:b,height:c}}
function u(a,b){const {width:c,height:f,getFrame:d}=a,e=b/a.duration;b=a.frameDurations.map(h=>g.Milliseconds(h*e));return{frameCount:a.frameCount,duration:a.duration,frameDurations:b,getFrame:d,width:c,height:f}}function v(a,b){const {width:c,height:f,getFrame:d}=a,e=a.frameDurations.slice(),h=e.shift();e.unshift(g.Milliseconds(h+b));return{frameCount:a.frameCount,duration:a.duration+b,frameDurations:e,getFrame:d,width:c,height:f}}function p(a,b){const {width:c,height:f,getFrame:d}=a,e=a.frameDurations.slice(),
h=e.pop();e.push(g.Milliseconds(h+b));return{frameCount:a.frameCount,duration:a.duration+b,frameDurations:e,getFrame:d,width:c,height:f}}function w(a,b,c,f){let {repeatType:d}=b;null==d&&(d=l.AnimatedSymbolRepeatType.Loop);!0===b.reverseAnimation&&(a=t(a));null!=b.duration&&(a=u(a,g.Milliseconds(1E3*b.duration)));if(null!=b.repeatDelay){const e=1E3*b.repeatDelay;d===l.AnimatedSymbolRepeatType.Loop?a=p(a,g.Milliseconds(e)):d===l.AnimatedSymbolRepeatType.Oscillate&&(a=v(p(a,g.Milliseconds(e/2)),g.Milliseconds(e/
2)))}null!=b.startTimeOffset?b=g.Milliseconds(1E3*b.startTimeOffset):null!=b.randomizeStartTime?(b=B.getRandomValue(c,null!=b.randomizeStartSeed?b.randomizeStartSeed:82749913),b=g.Milliseconds(b*r(a))):b=g.Milliseconds(0);return new x(a,b,d,f)}class x{constructor(a,b,c,f){this._animation=a;this._repeatType=c;this._onFrameData=f;this._direction=1;this._currentFrame=0;this.timeToFrame=this._animation.frameDurations[this._currentFrame];for(a=0;b>a;)a+=this.timeToFrame,this.nextFrame();b=this._animation.getFrame(this._currentFrame);
this._onFrameData(b)}nextFrame(){this._currentFrame+=this._direction;if(0<this._direction){if(this._currentFrame===this._animation.frameDurations.length)switch(this._repeatType){case l.AnimatedSymbolRepeatType.None:this._currentFrame-=this._direction;break;case l.AnimatedSymbolRepeatType.Loop:this._currentFrame=0;break;case l.AnimatedSymbolRepeatType.Oscillate:this._currentFrame-=this._direction,this._direction=-1}}else if(-1===this._currentFrame)switch(this._repeatType){case l.AnimatedSymbolRepeatType.None:this._currentFrame-=
this._direction;break;case l.AnimatedSymbolRepeatType.Loop:this._currentFrame=this._animation.frameDurations.length-1;break;case l.AnimatedSymbolRepeatType.Oscillate:this._currentFrame-=this._direction,this._direction=1}this.timeToFrame=this._animation.frameDurations[this._currentFrame];const a=this._animation.getFrame(this._currentFrame);this._onFrameData(a)}}let q,y;k.Player=x;k.adjustDuration=u;k.appendDelay=p;k.createPlayer=w;k.getDuration=r;k.play=function(a,b,c,f){function d(){n=e?setTimeout(()=>
{h.nextFrame();m=h.timeToFrame;d()},m):void 0}const e=null!=b.playAnimation?b.playAnimation:!0,h=w(a,b,c,f);let m=h.timeToFrame,n;d();return z.makeHandle(()=>e&&clearTimeout(n))};k.prependDelay=v;k.resize=function(a,b,c){q??=document.createElement("canvas");y??=q.getContext("2d");const {canvas:f,ctx:d}={canvas:q,ctx:y};f.width=b;f.height=c;const e=[],h=a.frameDurations.length;for(let m=0;m<h;m++){const n=a.getFrame(m);d.clearRect(0,0,b,c);n instanceof ImageData?d.drawImage(A.imageTypeToCanvas(n),
0,0,b,c):d.drawImage(n,0,0,b,c);e.push(d.getImageData(0,0,b,c))}return{width:b,height:c,frameDurations:a.frameDurations,getFrame:m=>e[m],frameCount:a.frameCount,duration:a.duration}};k.reverse=t;Object.defineProperty(k,Symbol.toStringTag,{value:"Module"})});