// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
define(["exports","./debounce"],function(n,m){function t(a){if("string"==typeof a)return a;if(u(a)){for(var b=-1,d=null==a?0:a.length,e=Array(d);++b<d;)e[b]=t(a[b],b,a);return e+""}if(m.isSymbol(a))return v?v.call(a):"";b=a+"";return"0"==b&&1/a==-A?"-0":b}function B(a){return a}function w(a){return"number"==typeof a&&-1<a&&0==a%1&&9007199254740991>=a}function x(a){return m.isObjectLike(a)&&"[object Arguments]"==m.baseGetTag(a)}function C(){return!1}function D(a){return m.isObjectLike(a)&&w(a.length)&&
!!c[m.baseGetTag(a)]}function E(a){return function(b){return a(b)}}function F(a){var b;if(b=null!=a&&w(a.length))m.isObject(a)?(b=m.baseGetTag(a),b="[object Function]"==b||"[object GeneratorFunction]"==b||"[object AsyncFunction]"==b||"[object Proxy]"==b):b=!1,b=!b;if(b){b=u(a);var d=!b&&G(a),e=!b&&!d&&H(a),k=!b&&!d&&!e&&I(a);if(b=b||d||e||k){d=a.length;for(var p=String,g=-1,h=Array(d);++g<d;)h[g]=p(g);d=h}else d=[];p=d.length;for(f in a)(a=b)&&!(a="length"==f||e&&("offset"==f||"parent"==f)||k&&("buffer"==
f||"byteLength"==f||"byteOffset"==f))&&(a=f,g=p,h=typeof a,g=null==g?9007199254740991:g,a=!!g&&("number"==h||"symbol"!=h&&J.test(a))&&-1<a&&0==a%1&&a<g),a||d.push(f);var f=d}else if(m.isObject(a)){f=a&&a.constructor;f=a===("function"==typeof f&&f.prototype||K);k=[];for(e in a)("constructor"!=e||!f&&L.call(a,e))&&k.push(e);f=k}else if(f=[],null!=a)for(k in Object(a))f.push(k);return f}function M(a){return(a=null==a?"":t(a))&&N.test(a)?a.replace(y,"\\$\x26"):a}function O(a,b){return null==a?a:P(a,"function"==
typeof b?b:B,F)}var u=Array.isArray,A=1/0,l=m.Symbol?m.Symbol.prototype:void 0,v=l?l.toString:void 0,J=/^(?:0|[1-9]\d*)$/,K=Object.prototype;l=Object.prototype;var Q=l.hasOwnProperty,R=l.propertyIsEnumerable,G=x(function(){return arguments}())?x:function(a){return m.isObjectLike(a)&&Q.call(a,"callee")&&!R.call(a,"callee")},z=(l="object"==typeof n&&n&&!n.nodeType&&n)&&"object"==typeof module&&module&&!module.nodeType&&module,H=((l=z&&z.exports===l?m.root.Buffer:void 0)?l.isBuffer:void 0)||C,c={};c["[object Float32Array]"]=
c["[object Float64Array]"]=c["[object Int8Array]"]=c["[object Int16Array]"]=c["[object Int32Array]"]=c["[object Uint8Array]"]=c["[object Uint8ClampedArray]"]=c["[object Uint16Array]"]=c["[object Uint32Array]"]=!0;c["[object Arguments]"]=c["[object Array]"]=c["[object ArrayBuffer]"]=c["[object Boolean]"]=c["[object DataView]"]=c["[object Date]"]=c["[object Error]"]=c["[object Function]"]=c["[object Map]"]=c["[object Number]"]=c["[object Object]"]=c["[object RegExp]"]=c["[object Set]"]=c["[object String]"]=
c["[object WeakMap]"]=!1;var q=(l="object"==typeof n&&n&&!n.nodeType&&n)&&"object"==typeof module&&module&&!module.nodeType&&module,r=q&&q.exports===l&&m.freeGlobal.process,I=(l=(l=function(){try{var a=q&&q.require&&q.require("util").types;return a?a:r&&r.binding&&r.binding("util")}catch(b){}}())&&l.isTypedArray)?E(l):D,L=Object.prototype.hasOwnProperty,P=function(a){return function(b,d,e){var k=-1,p=Object(b);e=e(b);for(var g=e.length;g--;){var h=e[a?g:++k];if(!1===d(p[h],h,p))break}return b}}(),
y=/[\\^$.*+?()[\]{}|]/g,N=RegExp(y.source);n.filter=(a,b)=>{b=M(b);const d=new RegExp(b,"i");0===a.length&&console.warn("No data was passed to the filter function.\n    The data argument should be an array of objects");const e=(k,p)=>{if(k?.constant||k?.filterDisabled)return!0;let g=!1;O(k,h=>{"function"!==typeof h&&null!=h&&(Array.isArray(h)||"object"===typeof h&&null!==h?e(h,p)&&(g=!0):p.test(h)&&(g=!0))});return g};return a.filter(k=>e(k,d))}});